### PR TITLE
[REVIEW]Define and implement new copying APIs `slice` and `split`

### LINKED ISSUE #2211: [FEA] Add `split` and `slice` functions that return zero-copy, non-owning views of columns
In Spark when we shuffle data between machines we will partition the data and then serialize out each partition separately, because each partition is likely to go to a different machine.   As a part of the serialization we would like to capture the null count for each partition, but there is no way to currently do that efficiently.

We could do it on the receiving end where we take all of the data and concatenate it back together, and then call gdf_count_nonzero_mask on it, but that is a legacy operation that I would rather not rely on.  Also if I can get the null count early I can potentially avoid sending unnecessary validity buffers across the wire.

### LINKED ISSUE #3148: [BUG]device_column_view bit mask validation doesn't account the offset
**Describe the bug**
libcudf `device_column_view` bit mask validation doesn't account the offset of that view

https://github.com/rapidsai/cudf/blob/7cff6cc27d81fca843bac20ab4aec51a1c97dc57/cpp/include/cudf/column/column_device_view.cuh#L164

**Expected behavior**
Should be `return bit_is_set(_null_mask, _offset + element_index);`

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: Source

**Additional context**
I will create a PR for this bug

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
Code changes for `split` and `slice` which are defined under copying.

All the test cases have been added

close #3148
close #2211

### CODE REVIEW

File: cpp/include/cudf/column/column_view.hpp [hunk 1]
```diff
@@ -294,6 +294,26 @@ class column_view : public detail::column_view_base {
...
+   * As the views can have offsets, so actual start would be offset of `input` +
+   * offset requested.
+   *
+   * @param slice_offset The offset from which the new column_view should start.
+   * @param slice_size The size of the column_view requested from the offset.
+   *
+   * @return unique_ptr<column_view> The unique pointer to the column view
+   * constrcuted as per the offset and size requested.
+   *---------------------------------------------------------------------------**/
+  std::unique_ptr<column_view> slice (size_type slice_offset,
```
Comment (jrhemstad) [inline cpp/include/cudf/column/column_view.hpp]: Since a `column_view` is non-owning, it can just be returned as a stack object. No need to use a `unique_ptr`.
```suggestion
column_view slice (size_type slice_offset,
```

File: cpp/include/cudf/copying.hpp [hunk 2]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * splits: {2, 5, 9}
+ * output:  {{10, 12}, {14, 16, 18}, {20, 22, 24, 26}, {28}}
+ *
+ * @throws `cudf::logic_error` if `splits` has end index > size of `input`.
+ *
+ * @param input Immutable view of input column for spliting
+ * @param indices A vector indices that are used to split the `input`
+ * @return vector<std::unique_ptr<column_view>> A vector of `column_view` unique_ptr each of which may have a different number of rows. 
+ */
+std::vector<std::unique_ptr<column_view>> split(column_view const& input,
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]:
```suggestion
std::vector<column_view> split(column_view const& input,
```

File: cpp/include/cudf/copying.hpp [hunk 3]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * output:  {{12, 14}, {20, 22, 24, 26}, {14, 16}, {}}
+ *
+ * @throws `cudf::logic_error` if `indices` size is not even.
+ *
+ * @param input Immutable view of input column for slicing
+ * @param indices A vector indices that are used to take 'slices' of the `input`.
+ * @return vector<std::unique_ptr<column_view>> A vector of `column_view` unique_ptr each of which may have a different number of rows. 
+ */
+
+std::vector<std::unique_ptr<column_view>> slice(column_view const& input,
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]:
```suggestion
std::vector<column_view> slice(column_view const& input,
```

File: cpp/include/cudf/column/column_view.hpp (hunk 1 above)
Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: Does this need to be a member function? Can't it just be a free function?

Comment (rgsl888prabhu) [reply cpp/include/cudf/column/column_view.hpp]: It would be easier to access children and it will ensure no changes will be made to calling object.

Apart from that not much of difference.

Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: I think I'd like to make this a free function if there's not a strong reason against doing so.

File: cpp/include/cudf/column/column_view.hpp [hunk 4]
```diff
@@ -493,4 +473,26 @@ class mutable_column_view : public detail::column_view_base {
...
+ *
+ * @param input Immutable view of input column to emulate
+ * @param slice_offset The offset from which the new column_view should start.
+ * @param slice_size The size of the column_view requested from the offset.
+ *
+ * @return unique_ptr<column_view> The unique pointer to the column view
+ * constrcuted as per the offset and size requested.
+ *---------------------------------------------------------------------------**/
+column_view slice(column_view const& input,
+                  size_type slice_offset,
```
Comment (jrhemstad) [inline cpp/include/cudf/column/column_view.hpp]: Can we do this as a `begin/end` index instead? That would be more idiomatic with the rest of libcudf functions and C++ in general.

**Comment by rgsl888prabhu** [comment]
@jrhemstad

File: cpp/include/cudf/copying.hpp [hunk 5]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
  */
 std::unique_ptr<table> empty_like(table_view input_table);
 
+/**
+ * @brief Slices a column_view (including null values) into a set of column_views
+ * according to a set of indices.
+ *
+ * The `slice` function creates `column_view`s from `input` with multiple intervals
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Here's a start on cleaning up and simplifying this documentation. 

```suggestion
 * The returned view's of `input` are constructed from an even number indices where
 * the `i`th returned `column_view` will view the elements in `input` indicated by the range
 * `[indices[i], indices[i+1])`.
 * 
 * For all `i` it is expected `indices[i] <= input.size()`
 * For all `i%2==0`, it is expected that `indices[i] <= indices[i+1]`
```

File: cpp/include/cudf/copying.hpp [hunk 6]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * of rows using the `indices` values. Regarding the interval of indices, a pair of 
+ * values are taken from the indices vector in a consecutive manner.
+ * The pair of indices are left-closed and right-open.
+ *
+ * The pairs of indices in the vector are required to comply with the following
+ * conditions:
+ * a, b belongs to Range[0, input column size]
+ * a <= b, where the position of a is less or equal to the position of b.
+ *
+ * Exceptional cases for the indices array are:
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Use the `@throws` syntax.

File: cpp/include/cudf/copying.hpp [hunk 7]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * When the values in the pair are equal, the function returns an empty `column_view`.
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: This isn't an exception.

File: cpp/include/cudf/copying.hpp [hunk 8]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * When the values in the pair are 'strictly decreasing', the outcome is
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Is it undefined? Won't it throw an exception if `indices[i] > indices[i+1]`?

File: cpp/include/cudf/copying.hpp [hunk 9]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * undefined.
+ * When any of the values in the pair don't belong to the range[0, input column
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: It's not undefined, it throws an exception, does it not?

File: cpp/include/cudf/copying.hpp [hunk 10]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * size), the outcome is undefined.
+ * When the indices vector is empty, an empty vector of `column_view` unique_ptr is returned.
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Not an exception. 
```suggestion
```

File: cpp/include/cudf/copying.hpp [hunk 11]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ *
+ * @example:
+ * input:   {10, 12, 14, 16, 18, 20, 22, 24, 26, 28}
+ * indices: {1, 3, 5, 9, 2, 4, 8, 8}
+ * output:  {{12, 14}, {20, 22, 24, 26}, {14, 16}, {}}
+ *
+ * @throws `cudf::logic_error` if `indices` size is not even.
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Add the other exceptions here.

File: cpp/include/cudf/copying.hpp [hunk 12]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ *
+ * @param input Immutable view of input column for slicing
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @param input View of column to slice 
```

File: cpp/include/cudf/copying.hpp [hunk 13]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * @param indices A vector indices that are used to take 'slices' of the `input`.
+ * @return vector<std::unique_ptr<column_view>> A vector of `column_view` unique_ptr each of which may have a different number of rows.
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @return The set of requested views of `input` indicated by the ranges in `indices`. 
```

File: cpp/include/cudf/copying.hpp [hunk 14]
```diff
@@ -79,5 +79,78 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * @param input Immutable view of input column for slicing
+ * @param indices A vector indices that are used to take 'slices' of the `input`.
+ * @return vector<std::unique_ptr<column_view>> A vector of `column_view` unique_ptr each of which may have a different number of rows. 
+ */
+
+std::vector<column_view> slice(column_view const& input,
+                               std::vector<size_type> const& indices);
+
+/**
+ * @brief Splits a `column_view` (including null values) into a set of `column_view`s
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Update the `split` documentation in the same way I suggested for `slice`.

File: cpp/src/copying/slice.cpp [hunk 15]
```diff
@@ -0,0 +1,65 @@
...
+#include <cudf/copying.hpp>
+#include <algorithm>
+
+namespace cudf {
+
+namespace experimental {
+
+namespace detail {
+
+std::vector<cudf::column_view> slice(cudf::column_view const& input,
```
Comment (jrhemstad) [inline cpp/src/copying/slice.cpp]: This doesn't need a `detail` API because it doesn't allocate any memory nor execute any kernels, which means it doesn't need a stream.

File: cpp/src/copying/slice.cpp [hunk 16]
```diff
@@ -0,0 +1,65 @@
...
+    if(indices.size() == 0 or input.size() == 0) {
+        return result;
+    }
+
+    std::vector<std::pair<size_type, size_type>> indices_tuple{};
+
+    auto it_start = indices.begin();
+    auto it_end = indices.begin() + 1;
+
+    for(;it_start != indices.end(); std::advance(it_start, 2), std::advance(it_end, 2)) {
```
Comment (jrhemstad) [inline cpp/src/copying/slice.cpp]: This is off by one. I think you want this:
```suggestion
    for(;it_end != indices.end(); std::advance(it_start, 2), std::advance(it_end, 2)) { 
```

File: cpp/src/copying/slice.cpp [hunk 17]
```diff
@@ -0,0 +1,65 @@
+/*
+ * Copyright 2019 BlazingDB, Inc.
```
Comment (jrhemstad) [inline cpp/src/copying/slice.cpp]: Update the license since the implementation is new.

File: cpp/src/copying/split.cpp [hunk 18]
```diff
@@ -0,0 +1,57 @@
+/*
+ * Copyright 2019 BlazingDB, Inc.
```
Comment (jrhemstad) [inline cpp/src/copying/split.cpp]: Update license.

File: cpp/src/copying/split.cpp [hunk 19]
```diff
@@ -0,0 +1,57 @@
...
+        return result;
+    }
+
+    CUDF_EXPECTS(splits.back() <= input.size(), "splits can't exceed size of the column");
+
+    //If the size is not zero, the split will always start at `0`
+    std::vector<size_type> indices{0};
+    std::for_each(splits.begin(), splits.end(), 
+            [&indices](auto split) {
+                indices.push_back(split); // This for end
```
Comment (jrhemstad) [inline cpp/src/copying/split.cpp]: This doesn't look right.

Given the example splits `{2, 5, 9}` this will generate indices`{2,2,5,5,9,9}` which will generate 3 empty views. 

What you really want is `{0,2,2,5,5,9,9,input.size()}`

Comment (rgsl888prabhu) [reply cpp/src/copying/split.cpp]: Because of this code `std::vector<size_type> indices{0};` zero will be added to start and ```if (splits.back() != input.size()) {
        indices.push_back(input.size()); // This to include rest of the elements
    } else {
        indices.pop_back(); // Not required as it is extra 
    }```

will take care of the end value.

File: cpp/include/cudf/column/column_view.hpp [hunk 20]
```diff
@@ -474,23 +475,50 @@ class mutable_column_view : public detail::column_view_base {
...
  * @return unique_ptr<column_view> The unique pointer to the column view
  * constrcuted as per the offset and size requested.
  *---------------------------------------------------------------------------**/
-column_view slice(column_view const& input,
-                  size_type begin,
-                  size_type end);
-
-}  // namespace cudf
+template <typename ColumnView>
+ColumnView slice(ColumnView const& input,
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/column/column_view.hpp]: But what if you expect mutable_column view in return ?

File: cpp/src/copying/split.cpp (hunk 19 above)
Comment (jrhemstad) [reply cpp/src/copying/split.cpp]: Aha, now it makes sense. Thanks for explaining it to me.

File: cpp/include/cudf/column/column_view.hpp [hunk 21]
```diff
@@ -473,4 +474,51 @@ class mutable_column_view : public detail::column_view_base {
...
+                    std::is_same<ColumnView, cudf::mutable_column_view>::value,
+                "slice can be performed only on column_view and mutable_column_view");
+   cudf::size_type expecetd_size = input.offset() + end;
+   CUDF_EXPECTS(begin >= 0, "begin should be non negative value");
+   CUDF_EXPECTS(end >= 0, "end should be non negative value");
+   CUDF_EXPECTS(expecetd_size <= input.size(), "Expected slice exceeds the size of the column_view");
+
+   // If an empty `column_view` is created, it will not have null_mask. So this will help in
+   // comparing in such situation.
+   auto tmp_null_mask = (end-begin > 0)? input.null_mask() : nullptr;
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/column/column_view.hpp]: It would be a problem while testing

File: cpp/include/cudf/column/column_view.hpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: Hm, great point.

In that case, if a public API is going to be a template, it needs to be explicitly instantiated in the source file for `column_view` and `mutable_column_view`.

File: cpp/include/cudf/column/column_view.hpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: I'm not following. Why would it matter when testing?

File: cpp/include/cudf/column/column_view.hpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/column/column_view.hpp]: For `slice` and `split` currently I am expecting them to be column_view, but the `slice` defined column_view.hpp, I am letting it be a template so that others can use it for both `immutable and mutable`.

[the remark this answers is not in the document]
Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: Okay, that's reasonable. In that case, the template `slice` should be put in the `detail` namespace.

[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/column/column_view.hpp]: As of now, I am expecting only to be used by libcudf users.

File: cpp/src/copying/slice.cpp (hunk 15 above)
Comment (rgsl888prabhu) [reply cpp/src/copying/slice.cpp]: Wouldn't it be good to have them in detail and having stream if we are planning any changes in future which might require these changes.

File: cpp/include/cudf/copying.hpp (hunk 8 above)
Comment (rgsl888prabhu) [reply cpp/include/cudf/copying.hpp]: It should have been updated, my bad.

File: cpp/include/cudf/column/column_view.hpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (jrhemstad) [reply cpp/include/cudf/column/column_view.hpp]: In that case, put it in the `detail` namespace.

File: cpp/src/copying/slice.cpp (hunk 16 above)
Comment (jrhemstad) [reply cpp/src/copying/slice.cpp]: Also, I think this may be a case where a raw for loop is actually better than an algorithm given the tools available to use in C++14:
```c++
for(size_t i = 0; i < indices.size(); i+=2){
   result.emplace_back(slice(input, indices[i], indices[i+1]);
}
```

This could be done with a `transform` using a `strided_iterator` for the input, but that's not currently available in C++14 without implementing ourselves.

Comment (rgsl888prabhu) [reply cpp/src/copying/slice.cpp]: Yes, I was trying to get an iterator to do that, but couldn't find one.

File: cpp/src/copying/split.cpp (hunk 18 above)
Comment (rgsl888prabhu) [reply cpp/src/copying/split.cpp]: Should I change this  to Nvidia?

Comment (kkraus14) [reply cpp/src/copying/split.cpp]: No, there can be multiple copyrights if multiple parties worked on the file. We should put a shorthand NVIDIA copyright below the Blazing copyright.

Comment (rgsl888prabhu) [reply cpp/src/copying/split.cpp]: But, this was overwritten/completely new code. Should we still need to add Blazing ?

Comment (jrhemstad) [reply cpp/src/copying/split.cpp]: Blazing doesn't need to be in the license anymore because the implementation is completely new.

File: cpp/src/copying/slice.cpp (hunk 15 above)
Comment (jrhemstad) [reply cpp/src/copying/slice.cpp]: I think it would be better if such changes were necessary to add these APIs at that time. Otherwise it could cause confusion as to why the detail API needs to exist.

File: cpp/include/cudf/copying.hpp [hunk 22]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
  */
 std::unique_ptr<table> empty_like(table_view input_table);
 
+/**
+ * @brief Slices a `column_view` into a set of `column_view`s according to a set of indices.
+ * The returned view's of `input` are constructed from an even number indices where
+ * the `i`th returned `column_view` will view the elements in `input` indicated by the range
+ * `[indices[i], indices[i+1])`.
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: I realize I made a mistake in my earlier suggestion.
```suggestion
 * `[indices[2*i], indices[(2*i)+1])`.
```

File: cpp/src/copying/slice.cpp [hunk 23]
```diff
@@ -1,7 +1,5 @@
 /*
- * Copyright 2019 BlazingDB, Inc.
- *     Copyright 2019 Christian Noboa Mardini <christian@blazingdb.com>
- *     Copyright 2019 William Scott Malpica <william@blazingdb.com>
+ * Copyright (c) 2019, NVIDIA CORPORATION.
```
Comment (kkraus14) [inline cpp/src/copying/slice.cpp]: Put this below the BlazingDB copyrights, don't delete theirs.

Comment (jrhemstad) [reply cpp/src/copying/slice.cpp]: It's an entirely new implementation and file. Not a single line of source was preserved, as such, I don't see a reason to keep the Blazing license.

File: cpp/src/copying/slice.cpp [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+
+    for(size_t i = 0; i < indices.size(); i+=2){
+        result.emplace_back(slice(input, indices[i], indices[i+1]));
+    }
+
+    const auto slicer = [&input] (auto indices) {
+             return slice(input, indices.first, indices.second);
+    }; 
+
+    std::transform(indices_tuple.begin(), indices_tuple.end(), std::back_inserter(result),
```
Comment (jrhemstad) [inline cpp/src/copying/slice.cpp]: This can be removed now?

File: cpp/include/cudf/column/column_view.hpp [hunk 25]
```diff
@@ -473,4 +474,47 @@ class mutable_column_view : public detail::column_view_base {
...
\ No newline at end of file
+namespace detail {
+/**---------------------------------------------------------------------------*
+ * @brief Constructs a zero-copy `column_view`/`mutable_column_view` of the
+ * elements in the range `[begin,end)` in `input`.
+ *
+ * @note It is the caller's responsibility to ensure that the returned view
+ * does not outlive the viewed device memory.
+ *
+ * @throws `cudf::logic_error` if `begin` with `end` goes beyond
```
Comment (harrism) [inline cpp/include/cudf/column/column_view.hpp]: Do you mean `begin` *or* `end`? "with" doesn't make much sense here.

Maybe replace this all with a single line:

```suggestion
 * @throws `cudf::logic_error` if `begin < 0`, `end < begin` or `end > input.size()`.
```

File: cpp/include/cudf/column/column_view.hpp [hunk 26]
```diff
@@ -473,4 +474,47 @@ class mutable_column_view : public detail::column_view_base {
...
+ * the size of the `input`.
+ * @throws `cudf::logic_error` if `begin` < 0.
+ * @throws `cudf::logic_error` if `end` < 0.
+ *
+ * @param input View of input column to emulate
```
Comment (harrism) [inline cpp/include/cudf/column/column_view.hpp]:
```suggestion
 * @param input View of input column to slice.
```

File: cpp/include/cudf/copying.hpp [hunk 27]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
  */
 std::unique_ptr<table> empty_like(table_view input_table);
 
+/**
+ * @brief Slices a `column_view` into a set of `column_view`s according to a set of indices.
+ * The returned view's of `input` are constructed from an even number indices where
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * The returned views of `input` are constructed from an even number of indices where
```

File: cpp/include/cudf/copying.hpp [hunk 28]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * the `i`th returned `column_view` will view the elements in `input` indicated by the range
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * the `i`th returned `column_view` views the elements in `input` indicated by the range
```

File: cpp/include/cudf/copying.hpp [hunk 29]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * @note It is the caller's responsibility to ensure that the returned view
+ * does not outlive the viewed device memory.
+ *
+ * @example:
+ * input:   {10, 12, 14, 16, 18, 20, 22, 24, 26, 28}
+ * indices: {1, 3, 5, 9, 2, 4, 8, 8}
+ * output:  {{12, 14}, {20, 22, 24, 26}, {14, 16}, {}}
+ *
+ * @throws `cudf::logic_error` if `indices` size is not even.
+ * @throws `cudf::logic_error` When the values in the pair are 'strictly decreasing'.
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @throws `cudf::logic_error` When the values in the pair are strictly decreasing.
```

File: cpp/include/cudf/copying.hpp [hunk 30]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * @throws `cudf::logic_error` When any of the values in the pair don't belong to
+ * the range [0, input.size()).
+ *
+ * @param input View of column to slice
+ * @param indices A vector indices that are used to take 'slices' of the `input`.
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @param indices A vector of indices used to take slices of `input`.
```

File: cpp/include/cudf/copying.hpp [hunk 31]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * @return The set of requested views of `input` indicated by the ranges in `indices`.
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @return Vector of views of `input` indicated by the ranges in `indices`.
```

File: cpp/include/cudf/copying.hpp [hunk 32]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ */
+
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
```

File: cpp/include/cudf/copying.hpp [hunk 33]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+std::vector<column_view> slice(column_view const& input,
+                               std::vector<size_type> const& indices);
+
+/**
+ * @brief Splits a `column_view` into a set of `column_view`s according to a set of indices
+ * derived from expected splits.
+ * The returned view's of `input` are constructed from vector of splits, which indicates
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 *
 * The returned views of `input` are constructed from a vector of indices that indicate
```

File: cpp/include/cudf/copying.hpp [hunk 34]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * indices where the split should occur. For `i`th returned `column_view`, the view would be
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * where the split should occur. The `i`th returned `column_view` is sliced as
```

File: cpp/include/cudf/copying.hpp [hunk 35]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * sliced as [0, splits[i]) if i=0, else [splits[i], input.size()) if `i` is last view and
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * `[0, splits[i])` if `i`=0, else `[splits[i], input.size())` if `i` is the last view and
```

File: cpp/include/cudf/copying.hpp [hunk 36]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * splits[i] != input.size(), [splits[i-1], splits[i]] for other.
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * `splits[i] != input.size()`, or `[splits[i-1], splits[i]]` otherwise.
```

File: cpp/include/cudf/copying.hpp [hunk 37]
```diff
@@ -79,5 +79,64 @@ std::unique_ptr<column> allocate_like(column_view input, size_type size,
...
+ * Example:
+ * input:   {10, 12, 14, 16, 18, 20, 22, 24, 26, 28}
+ * splits:  {2, 5, 9}
+ * output:  {{10, 12}, {14, 16, 18}, {20, 22, 24, 26}, {28}}
+ *
+ * @throws `cudf::logic_error` if `splits` has end index > size of `input`.
+ * @throws `cudf::logic_error` When the value in `splits` is not in the range [0, input.size()).
+ * @throws `cudf::logic_error` When the values in the `splits` are 'strictly decreasing'.
+ *
+ * @param input View of column to slice
```
Comment (harrism) [inline cpp/include/cudf/copying.hpp]:
```suggestion
 * @param input View of column to split
```
