### PR TITLE
[REVIEW] Disabling `column_view` iterators for non fixed-width types

### LINKED ISSUE #3355: [BUG] Disable `column_view` iterators for non fixed-width types
**Describe the bug**

`column_view` provides host-callable [`begin/end`](https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/include/cudf/column/column_view.hpp#L88) methods to return "iterators" (really, raw pointers) to the elements of the column. They require the caller to explicitly specify the type (since the columns are type erased). 

Example:
```c++
mutable_column_view c{...};
thrust::sort(c.begin<int32_t>(), c.end<int32_t>());
```

This is fine for fixed-width types that don't have children, but would be problematic for any type with children (e.g., strings). Bad things would happen (likely fail to compile with inscrutable compiler error) if someone tried:
```c++
column_view c{...};
auto begin = c.begin<string_view>();
```

First, this would require a specialization of `begin`. Even if that was done, it would be impossible to do correctly because in order for the returned iterator to work correctly, it would require the children to live in device memory (i.e., it requires a `column_device_view).

We should more explicitly disable these methods for non-compound, non-fixed-width types.

**Note:** `column_device_view::begin<string_view>()` _is_ possible because the children live in device memory. See https://github.com/rapidsai/cudf/pull/3298

**Expected behavior**

We can disable these at compile time in a few different ways.

1.) 
```c++
  template <typename T = void>
  std::enable_if_t<is_fixed_width<T>(), T const*>
  begin() const noexcept {
    return data<T>();
  }
```

2.)
```
  template <typename T>
  T const* begin() const noexcept {
    static_assert(is_fixed_width<T>(), "column_view::begin only supports fixed-width types");
    return data<T>();
  }
```

The second option is probably better because it will produce more readable compiler errors than the first.

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
Disabling `column_view` iterators for non fixed-width types.

close #3355

### CODE REVIEW

File: cpp/include/cudf/column/column_view.hpp [hunk 1]
```diff
@@ -98,6 +100,7 @@ class column_view_base {
    *---------------------------------------------------------------------------**/
   template <typename T>
   T const* end() const noexcept {
+    static_assert(is_fixed_width<T>(), "column_view::begin only supports fixed-width types");
```
Comment (jrhemstad) [inline cpp/include/cudf/column/column_view.hpp]:
```suggestion
    static_assert(is_fixed_width<T>(), "column_view::end only supports fixed-width types");
```

File: cpp/include/cudf/column/column_view.hpp [hunk 2]
```diff
@@ -407,6 +410,7 @@ class mutable_column_view : public detail::column_view_base {
    *---------------------------------------------------------------------------**/
   template <typename T>
   T* begin() const noexcept {
+    static_assert(is_fixed_width<T>(), "column_view::begin only supports fixed-width types");
```
Comment (jrhemstad) [inline cpp/include/cudf/column/column_view.hpp]:
```suggestion
    static_assert(is_fixed_width<T>(), "mutable_column_view::begin only supports fixed-width types");
```

File: cpp/include/cudf/column/column_view.hpp [hunk 3]
```diff
@@ -419,6 +423,7 @@ class mutable_column_view : public detail::column_view_base {
    *---------------------------------------------------------------------------**/
   template <typename T>
   T* end() const noexcept {
+    static_assert(is_fixed_width<T>(), "column_view::begin only supports fixed-width types");
```
Comment (jrhemstad) [inline cpp/include/cudf/column/column_view.hpp]:
```suggestion
    static_assert(is_fixed_width<T>(), "mutable_column_view::end only supports fixed-width types");
```

**Comment by jrhemstad** [comment]
rerun tests

**Comment by harrism** [comment]
Why is this WIP? is it not finished?

**Comment by rgsl888prabhu** [comment]
> Why is this WIP? is it not finished?

I have changed it
