### PR TITLE
Fix join match context tests

### LINKED ISSUE #20445: [BUG] Hash join match context fails in debug build of libcudf
**Describe the bug**
The `cudf::hash_join` `match_context` functions are producing incorrect results per gtests in a libcudf debug build.

```
inner_join_match_context
left_join_match_context
full_join_match_context
```

```
[ RUN      ] JoinTest.HashJoinInnerMatchContext
/cudf/cpp/tests/join/join_tests.cpp:2021: Failure
Expected equality of these values:
  h_match_counts
    Which is: { 29, 0, 2, 1, 2 }
  expected_counts
    Which is: { 1, 0, 1, 0, 0 }

/cudf/cpp/tests/join/join_tests.cpp:2053: Failure
Expected equality of these values:
  h_match_counts
    Which is: { 29, 0, 2, 1, 2 }
  expected_counts
    Which is: { 1, 0, 0, 0, 0 }

[  FAILED  ] JoinTest.HashJoinInnerMatchContext (1 ms)
[ RUN      ] JoinTest.HashJoinLeftMatchContext
/cudf/cpp/tests/join/join_tests.cpp:2111: Failure
Expected equality of these values:
  h_match_counts
    Which is: { 29, 1, 2, 1, 2 }
  expected_counts
    Which is: { 1, 1, 1, 1, 1 }

/cudf/cpp/tests/join/join_tests.cpp:2127: Failure
Expected equality of these values:
  h_match_counts
    Which is: { 29, 1, 1, 1, 1 }
  expected_counts
    Which is: { 1, 1, 1, 1, 1 }

[  FAILED  ] JoinTest.HashJoinLeftMatchContext (0 ms)
[ RUN      ] JoinTest.HashJoinFullMatchContext
/cudf/cpp/tests/join/join_tests.cpp:2179: Failure
Expected equality of these values:
  h_match_counts
    Which is: { 29, 1, 2, 1, 2 }
  expected_counts
    Which is: { 1, 1, 1, 1, 1 }

[  FAILED  ] JoinTest.HashJoinFullMatchContext (0 ms)
```

**Steps/Code to reproduce bug**
Build libcudf with debug using `-DCMAKE_BUILD_TYPE=Debug` or `build.sh libcudf -g`
Also, there are instructions for just building specific files here: https://github.com/rapidsai/cudf/blob/main/CONTRIBUTING.md#device-debug-symbols
Though I don't know which files are involved in this issue.

Next run the individual test using either `ctest -R JOIN_TEST --output-on-failure` or 
`LD_PRELOAD=libcudf_identify_stream_usage_mode_cudf.so gtests/JOIN_TEST --gtest_filter=JoinTest.HashJoin*MatchContext`

Running without the `LD_PRELOAD` does not seem to fail the test so it may be stream related.

The `*` wildcard in the `gtest_filter` parameter runs all three tests.

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
Closes #20445

This PR refactors the hash join match context tests. Previously, the tests used the synchronous `cudaMemcpy` API, which caused incorrect results when building and running in debug mode. The update replaces these calls with existing test APIs that copy data between host and device using the provided stream, resolving the async issue when non-default streams are used.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/tests/join/join_tests.cpp [hunk 1]
```diff
@@ -43,6 +45,19 @@ constexpr cudf::size_type NoneValue =
...
+                               std::vector<cudf::size_type> const& expected_counts,
+                               rmm::cuda_stream_view stream)
+{
+  auto const host_actual_counts = cudf::detail::make_host_vector_async(actual_counts, stream);
+  stream.synchronize();
+
+  ASSERT_EQ(host_actual_counts.size(), expected_counts.size());
+  for (size_t i = 0; i < expected_counts.size(); ++i) {
+    EXPECT_EQ(host_actual_counts[i], expected_counts[i]) << "Mismatch at index " << i;
+  }
```
Comment (mhaseeb123) [inline cpp/tests/join/join_tests.cpp]:
```suggestion
  EXPECT_EQ(std::equal(host_actual_counts.begin(), host_actual_counts.end(), expected_counts.begin()), "Error message");
```

Comment (PointKernel) [reply cpp/tests/join/join_tests.cpp]: Love the suggestion. Thanks @mhaseeb123 !
