### PR TITLE
[REVIEW] Align parquet page data allocation size to 4 bytes

### LINKED ISSUE #2820: [BUG] cuda-memcheck reports invalid readings when opening some parquet files
**Describe the bug**
The script below reports some errors when executed with cuda-memcheck.

**Steps/Code to reproduce bug**
Minimal script:
```
import cudf
customer_file = '/path/to/customer_0_0.parquet'
gdf = cudf.read_parquet(customer_file)
print(gdf)
```
**File attachment**
https://drive.google.com/file/d/1iLDzKgM6D3TubzQ0wpWl1HWoRXrazScJ/view?usp=sharing

**Traceback:**
```
========= CUDA-MEMCHECK
========= Invalid __global__ read of size 4
=========     at 0x000030d0 in gpuDecodePageData
=========     by thread (43,0,0) in block (5,0,0)
=========     Address 0x7f132361d694 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so (cuLaunchKernel + 0x2cd) [0x2486ed]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 [0x168fd]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 [0x16987]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 (cudaLaunchKernel + 0x225) [0x448c5]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_Z98__device_stub__ZN4cudf2io7parquet3gpu17gpuDecodePageDataEPNS2_8PageInfoEPNS2_15ColumnChunkDescEmmiPN4cudf2io7parquet3gpu8PageInfoEPNS2_15ColumnChunkDescEmmi + 0x122) [0xa424f2]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet3gpu14DecodePageDataEPNS2_8PageInfoEiPNS2_15ColumnChunkDescEimmP11CUstream_st + 0x6e) [0xa4257e]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl16decode_page_dataERK17hostdevice_vectorINS1_3gpu15ColumnChunkDescEERKS4_INS5_8PageInfoEERKSt6vectorIP11gdf_column_SaISG_EEmm + 0x1ce) [0xa451ee]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl4readEiii + 0x1d1f) [0xa4709f]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader8read_allEv + 0x2b) [0xa47bfb]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x251ba]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x26f23]
=========     Host Frame:python (_PyMethodDef_RawFastCallKeywords + 0x254) [0x164744]
=========     Host Frame:python (_PyCFunction_FastCallKeywords + 0x21) [0x164861]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x47a4) [0x1cfb94]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x163f57]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4b39) [0x1cff29]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x115424]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x11544c]
=========     Host Frame:python [0x22ab74]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x234eb1]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x2350a3]
=========     Host Frame:python [0x236195]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x2362bc]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1db062]
=========
========= Invalid __global__ read of size 4
=========     at 0x00002378 in gpuDecodePageData
=========     by thread (43,0,0) in block (0,0,0)
=========     Address 0x7f132360755c is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so (cuLaunchKernel + 0x2cd) [0x2486ed]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 [0x168fd]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 [0x16987]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 (cudaLaunchKernel + 0x225) [0x448c5]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_Z98__device_stub__ZN4cudf2io7parquet3gpu17gpuDecodePageDataEPNS2_8PageInfoEPNS2_15ColumnChunkDescEmmiPN4cudf2io7parquet3gpu8PageInfoEPNS2_15ColumnChunkDescEmmi + 0x122) [0xa424f2]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet3gpu14DecodePageDataEPNS2_8PageInfoEiPNS2_15ColumnChunkDescEimmP11CUstream_st + 0x6e) [0xa4257e]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl16decode_page_dataERK17hostdevice_vectorINS1_3gpu15ColumnChunkDescEERKS4_INS5_8PageInfoEERKSt6vectorIP11gdf_column_SaISG_EEmm + 0x1ce) [0xa451ee]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl4readEiii + 0x1d1f) [0xa4709f]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader8read_allEv + 0x2b) [0xa47bfb]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x251ba]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x26f23]
=========     Host Frame:python (_PyMethodDef_RawFastCallKeywords + 0x254) [0x164744]
=========     Host Frame:python (_PyCFunction_FastCallKeywords + 0x21) [0x164861]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x47a4) [0x1cfb94]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x163f57]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4b39) [0x1cff29]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x115424]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x11544c]
=========     Host Frame:python [0x22ab74]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x234eb1]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x2350a3]
=========     Host Frame:python [0x236195]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x2362bc]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1db062]
=========
========= Program hit cudaErrorLaunchFailure (error 4) due to "unspecified launch failure" on CUDA API call to cudaStreamSynchronize. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so [0x3451c3]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 (cudaStreamSynchronize + 0x15e) [0x44aee]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl16decode_page_dataERK17hostdevice_vectorINS1_3gpu15ColumnChunkDescEERKS4_INS5_8PageInfoEERKSt6vectorIP11gdf_column_SaISG_EEmm + 0x20d) [0xa4522d]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl4readEiii + 0x1d1f) [0xa4709f]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader8read_allEv + 0x2b) [0xa47bfb]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x251ba]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x26f23]
=========     Host Frame:python (_PyMethodDef_RawFastCallKeywords + 0x254) [0x164744]
=========     Host Frame:python (_PyCFunction_FastCallKeywords + 0x21) [0x164861]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x47a4) [0x1cfb94]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x163f57]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4b39) [0x1cff29]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x115424]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x11544c]
=========     Host Frame:python [0x22ab74]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x234eb1]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x2350a3]
=========     Host Frame:python [0x236195]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x2362bc]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1db062]
=========
========= Program hit cudaErrorLaunchFailure (error 4) due to "unspecified launch failure" on CUDA API call to cudaFree. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so [0x3451c3]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/./libcudart.so.9.2 (cudaFree + 0x186) [0x3f3e6]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so [0xa42df0]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader4Impl4readEiii + 0x1e8e) [0xa4720e]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/../../../../libcudf.so (_ZN4cudf2io7parquet6reader8read_allEv + 0x2b) [0xa47bfb]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x251ba]
=========     Host Frame:/home/rommel/miniconda3/envs/cudf-0.9/lib/python3.7/site-packages/cudf/bindings/parquet.cpython-37m-x86_64-linux-gnu.so [0x26f23]
=========     Host Frame:python (_PyMethodDef_RawFastCallKeywords + 0x254) [0x164744]
=========     Host Frame:python (_PyCFunction_FastCallKeywords + 0x21) [0x164861]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x47a4) [0x1cfb94]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x163f57]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4b39) [0x1cff29]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x114539]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x115424]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x11544c]
=========     Host Frame:python [0x22ab74]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x234eb1]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x2350a3]
=========     Host Frame:python [0x236195]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x2362bc]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1db062]
(continues) … 
```

**Expected behavior**
The parquet file should be read without memory issues. Since the same file read using pyarrow parquet reader works as expected.
```
import pyarrow.parquet as parquet
customer_file = '/path/to/customer_0_0.parquet'
df = parquet.read_pandas(customer_file).to_pandas()
print(df.head())
```

**Environment overview**
 - Environment location: Bare-metal
 - Method of cuDF install: conda
```
conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults \
    cudf=0.9 python=3.7.4 cudatoolkit=9.2
```

**Environment details**
***OS Information***
```
Ubuntu 16.04.6 LTS
Linux mastermind 4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

***GPU Information***
```
     Tue Sep 17 11:33:40 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
     |  0%   37C    P0    N/A /  90W |      0MiB /  4040MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
```

***CPU***
```
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Model name:            Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
```
         
***nvcc***
```
     //usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Tue_Jun_12_23:07:04_CDT_2018
     Cuda compilation tools, release 9.2, V9.2.148
```

***Python***
```
     /home/rommel/miniconda3/envs/cudf-0.9/bin/python
     Python 3.7.4
```
  
***conda packages***
```
     /home/rommel/miniconda3/bin/conda
     # packages in environment at /home/rommel/miniconda3/envs/cudf-0.9:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     arrow-cpp                 0.14.1           py37hb2cae1d_2    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_1    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.9.11            hecc5488_0    conda-forge
     certifi                   2019.9.11                py37_0    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     cudatoolkit               9.2                           0
     cudf                      0.9.0                    py37_0    rapidsai
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     dlpack                    0.2                  he1b5a44_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     fastavro                  0.22.4           py37h516909a_0    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libcudf                   0.9.0                 cuda9.2_0    rapidsai
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     liblapack                 3.8.0               12_openblas    conda-forge
     libnvstrings              0.9.0                 cuda9.2_0    rapidsai
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.9.0                 cuda9.2_0    rapidsai
     libstdcxx-ng              9.1.0                hdf63c60_0
     llvmlite                  0.29.0           py37hf484d3e_0    numba
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     numba                     0.45.1          np116py37hf484d3e_0    numba
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     nvstrings                 0.9.0                    py37_0    rapidsai
     openssl                   1.1.1c               h516909a_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pyarrow                   0.14.1           py37h8b68381_1    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     python                    3.7.4                h265db76_1
     python-dateutil           2.8.0                      py_0    conda-forge
     pytz                      2019.2                     py_0    conda-forge
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  7.0               hf8c457e_1001    conda-forge
     rmm                       0.9.0                    py37_0    rapidsai
     setuptools                41.2.0                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sqlite                    3.29.0               h7b6447c_0
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

**Additional context**
The ‘customer’ parquet file was generated with Apache Drill 1.12.0 directly from their CLI that underneath uses Apache Parquet java package version 1.8.1-drill-r0.

Here we are creating the parquet file using cudf.to_parquet reader from the data frame read by pyarrow.
```
import cudf
import numpy as np
import shutil
import os

import cudf
import pyarrow.parquet as parquet
import pyarrow as pa

customer_file = '/home/aocsa/tpch/100MB2Part/customer_0_0.parquet'
df = parquet.read_pandas(customer_file).to_pandas()

out_df = cudf.from_pandas(df)

out_df.to_parquet('temp')
r_fi = ['temp/' + x for x in os.listdir('temp/') if x.endswith(".parquet")]

print("\nDataFrame Metadata (rows, row-groups, columns):")
print(cudf.io.read_parquet_metadata(r_fi[0]))
filepath = r_fi[0]
    
with open(filepath, "rb") as f:
    chunk = cudf.read_parquet(f)
    print(chunk.head())
    del chunk
```
running `cuda-memcheck python parquet_test.py` works with zero issues. That means that files created with Apache Parquet Hadoop cause this kind of issues.

### PR DESCRIPTION
**Pull request by OlivierNV**
Stops cuda memcheck from complaining, which resolves #2820

### CODE REVIEW

**Comment by OlivierNV** [comment]
rerun tests

**Comment by OlivierNV** [comment]
rerun tests

File: cpp/src/io/parquet/parquet_reader_impl.hpp [hunk 1]
```diff
@@ -66,6 +66,16 @@ class reader::Impl {
...
  private:
+  /**
+   * @brief Align a size such that aligned loads within a memory block
+   * won't read bytes beyond the unaligned cuda-memcheck limit
+   *
+   * @param[in] size in bytes
+   *
+   * @return size_t Aligned size
+   **/
+  size_t align_size(size_t v) const { return v + (3 & -static_cast<int>(v)); }
```
Comment (harrism) [inline cpp/src/io/parquet/parquet_reader_impl.hpp]: The arithmetic here looks a little bit magical. I'm not sure exactly how it works. Can you explain it?  You could write the `3` as `0x11` just to make it clear that it's a mask of the lower two bits.

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: > The arithmetic here looks a little bit magical. I'm not sure exactly how it works. Can you explain it? You could write the `3` as `0x11` just to make it clear that it's a mask of the lower two bits.

The value we're adding to get to the next 4B-aligned boundary is
"(4 - size % 4) % 4", or (4 - (size & 3)) & 3, or just (-size & 3)
The static_cast is only here so that an overzealous compiler doesn't complain about the use of a negate operand on an unsigned type (I now prefer this over the '(size+3)&~3).
I don't think using 0b11 makes it clearer (perhaps I should expand to comment to make it clear that it's aligning the size to a 4B boundary and not say 8 or 64, but the '3' in the expression along with the name of the function 'align_size' isn't exactly obscure about what the function is doing).

Comment (harrism) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: The compiler will do all of these optimizations. (compilers know to replace `%4` with `&3`, and they distribute operators), so I think the hand optimization obfuscates the code unnecessarily. I recommend just leaving it as `(4 - size % 4) % 4`, or at least `(-static_cast<int>(v) % 4)`.

All that said, a clearer thing to do would be to use cudf's existing safe rounding code, which eliminates potential overflows when rounding up. https://github.com/rapidsai/cudf/blob/d164d44200a7cae0852b18c2302c4842f13342fe/cpp/src/utilities/integer_utils.hpp#L33

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: In general, I find it actually painful to use modulo power of 2, and also find that using modulo actually obfuscate the intent here, since it's fundamentally a logical masking out of bits that we want.

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: Perhaps you would be more comfortable with (v + 3) & ~3 ?

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: In the interest of not wasting any more time, I tried to use util::round_up_safe<size_t>(v, 4), which resulted in a "internal compiler error (codegen)", perhaps due to the mix of constexpr and std::throw ? It's got to be the most inefficient function to round up I have ever seen (though I suppose there is no limit to how inefficient something might be), and the sole reason for the existence of this function is the questionable design decision to use int as gdf_size_type, so I gave it my best shot, but I will respectfully stick to my original implementation.

Comment (jrhemstad) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: I agree the implementation that is here is unnecessarily obfuscated. 

> the questionable design decision to use int as gdf_size_type

Straight from the Arrow spec:
```
Array lengths
Any array has a known and fixed length, stored as a 32-bit signed integer, so a maximum of 2^31 - 1 elements. We choose a signed int32 for a couple reasons:

Enhance compatibility with Java and client languages which may have varying quality of support for unsigned integers.
To encourage developers to compose smaller arrays (each of which contains contiguous memory in its leaf nodes) to create larger array structures possibly exceeding 2^31 - 1 elements, as opposed to allocating very large contiguous memory blocks.
```

If perhaps you believe we should use an unsigned type, then the Google Style Guide has a good explanation on why we don't do this: https://google.github.io/styleguide/cppguide.html#Integer_Types

> perhaps due to the mix of constexpr and std::throw

You're allowed to `throw` in a `constexpr` so long as there exists arguments to the function that allow it to be evaluated at compile time without throwing: https://stackoverflow.com/questions/34280729/throw-in-constexpr-function


>  It's got to be the most inefficient function to round up I have ever seen

That's because it guards against overflow.

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: It doesn't prevent uoverflow, it just throws an exception (and again overflow only likely because of the int32_t size type, which has nothing to do with what happens in this PR that uses size_t)
Back to the PR, using cudf::util::round_up_safe(v, 4) results in compile error because there is no template for <size_t, int> and using round_up_safe<size_t>(v, 4) results in internal compiler error (codegen), I suppose util::round_up_safe(v, static_cast<size_t>(4)) will work, but seriously ? As opposed to (v+3)&~3 or v+(3 & -v) ? Are people really that unfamiliar with 2's complement these days ?

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: Regarding round_up_safe() the throw condition can't be evaluated at compile time unless both arguments to the function are also constexpr (v is not a constexpr in this PR).

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: So far, I have been given 3 different suggestions that sound good but don't work to replace something that is literally 2-3 arithmetic instructions. Can I use that as grounds to dismiss a review and merge this trivial change that doesn't even change any functionality to begin with ?
(I get the feeling we're gonna have very long discussions for more serious PRs like the orc writer that are full of 2's complement stuff)

Comment (OlivierNV) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: Speaking of arrow, from bit_util.h:
constexpr uint64_t RoundUpToPowerOf2(uint64_t value, uint64_t factor) {
  // DCHECK(IsPowerOf2(factor));
  return (value + (factor - 1)) & ~(factor - 1);
}

**Comment by kkraus14** [comment]
Removed the "Ready to Merge" label as there still seemed to be ongoing discussion, will wait for @harrism or @jrhemstad to review / merge.

**Comment by OlivierNV** [comment]
Okay. New, more traditional implementation of align_bytes() that hopefully is more likely to pass the review stage ?

File: cpp/src/io/parquet/parquet_reader_impl.hpp (hunk 1 above)
Comment (harrism) [reply cpp/src/io/parquet/parquet_reader_impl.hpp]: It has nothing to do with familiarity with the code or not. I just cringe at undocumented magic numbers in any context. I like clear and well-documented code. I like not duplicating functionality we have in our library in utility functions already. 

I agree that the rounding utilities in libcudf aren't great. But the solution is to fix them, not to avoid them. I would prefer that PRs contribute to improving the utilities rather than adding another one.

As for questionable design decisions, as Jake pointed out the use of int32 is a well-documented Arrow design decision. It surprised me at first, too, but we are sticking with it for Arrow compatibility.

**Comment by harrism** [comment]
@OlivierNV I respectfully request that you contribute to improving libcudf's integer utilities rather than complaining about them and adding new ones.

**Comment by OlivierNV** [comment]
> @OlivierNV I respectfully request that you contribute to improving libcudf's integer utilities rather than complaining about them and adding new ones.

The latest version no longer has any "magic" numbers.

**Comment by harrism** [comment]
What I mean is to improve our rounding functions so that you can use them directly rather than adding additional general-purpose utilities that are not in the utility namespace.

**Comment by OlivierNV** [comment]
> What I mean is to improve our rounding functions so that you can use them directly rather than adding additional general-purpose utilities that are not in the utility namespace.

Can I add a
cudf_align_up(size_t a, size_t b) { return (a + (b - 1)) & ~(b - 1); } ?

Or are you suggesting that I use the slow function that checks for overflow (after fixing it such that it at least compiles), even though the overflow check is not useful here since we're dealing with a size_t type, and I can safely assume powers of 2 alignment ?

**Comment by OlivierNV** [comment]
Okay, if that last commit doesn't pass mharris pr-review, maybe I need to think about going in a different field...

**Comment by harrism** [comment]
BTW, just discovered that the `constexpr` issue was known -- in fact reported by its author: #1438

**Comment by OlivierNV** [comment]
Okay, can we merge this PR now ?

**Comment by harrism** [comment]
It hasn't passed CUDA 10.1 CI. I'm waiting for help from our Python experts on this issue that is affecting multiple PRs.

While you wait, are you interested in contributing a faster rounding utility for cases that are known to be safe from overflow?

**Comment by OlivierNV** [comment]
> While you wait, are you interested in contributing a faster rounding utility for cases that are known to be safe from overflow?

For such cases, I would just use (v + r) & ~r in the code, as in my original pr, and not go through a utility function, in the same way that I would not add a cudf::util::detail::multiply_accumulate "utility" for (a * b) + c. My general rule of thumb is that if it takes more code to type the function name than its implementation, it's probably not useful.

**Comment by jrhemstad** [comment]
> My general rule of thumb is that if it takes more code to type the function name than its implementation, it's probably not useful.

It is far from obvious that `(v + r) & ~r` means "round up to a multiple of `r`" no matter how skilled of a programmer you are.

Furthermore, it's bug prone to type this all over your code. What if one day you accidentally type `(v + r) && ~r`---you've now silently introduced a bug. This is the whole point of DRY (Don't Repeat Yourself) is to avoid things like this. 

Finally, using functions convey intent and meaning. Writing good code is like telling a story---it should be comprehensible and easy to follow.  By using a function called `round_up`, there is zero cognitive overhead for anyone reading your code to understand what you are doing.

**Comment by OlivierNV** [comment]
> It is far from obvious that `(v + r) & ~r` means "round up to a multiple of `r`" no matter how skilled of a programmer you are.
I means round up to a multiple of (r+1), r being a power of 2 minus 1. Maybe it's only obvious if you've used it a lot like in areas where you do need to frequently align stuff (video, simd, or block-level cuda development). When I see the code, I know what it's doing. To know what a function does, you actually have to look it up, names are often misleading, like "round_up_safe" for example.

> What if one day you accidentally type (v + r) && ~r---you've now silently introduced a bug.
By the same reasoning, we should use an 'assign' utility function instead of a = b, because what if one day you accidentally type == instead of = , is that what you're saying ?

**Comment by mjsamoht** [comment]
I think this has a lot to do with personal experience and preference.  Having worked on low-level code for decades I know right away what `(v + r) & ~r` does.  But probably less obvious to others.

Reminds me about he MISRA rules for automotive safety where they say you can't write `if (x) { ...}` because it's not clear, and instead you should write `if (x != 0) { ...}`.  To me the former is more intuitive and I don't need to think.

But now that Olivier has agreed to change the code to use `util::round_up_safe()` is there anything left to approve the PR?  @jrhemstad? @harrism?

**Comment by harrism** [comment]
I'm repeating myself now. I was hoping Olivier would be willing to use `round_up_unsafe` since this call site can't possibly overflow. And I was hoping he would be willing to improve round_up_unsafe if he found it less efficient than his code. If wishes were horses...

It doesn't matter if I approve this PR right now (which I am), because CI hasn't passed for CUDA 10.1.  I've asked for help on this unrelated CI problem but have gotten no response.

**Comment by harrism** [comment]
I find it ... ironic? ... that you disparage using a utility function to round up a size, but you do exactly that in this PR. Yours just happen to be called `align_size` instead of `round_up`, and it is duplicated  in every file reader, rather than just calling `round_up` directly.

**Comment by OlivierNV** [comment]
> I was hoping Olivier would be willing to use `round_up_unsafe` since this call site can't possibly overflow.

Heh. "round_up_unsafe". Good one. I'm hoping that people involved in this thread will from now on recognize immediately the expression "(x + 3) & ~3" as a round up to the next modulo 4. That's how you learn coding: looking at code, not function names.

**Comment by kkraus14** [comment]
@harrism @OlivierNV @mjsamoht Just wanted to chime in and say that the CUDA 10.1 CI issues are completely unrelated to the code here and are due to an outdated version of CuPy being pulled erroneously (Not sure why the conda solver isn't rejecting the package even). We should hopefully have it fixed very shortly.
