### PR TITLE
Document undefined behavior in div_rounding_up_safe

### LINKED ISSUE #17539: [DOC] clarify safety of integer utils
**Describe the bug**

Noticed while implementing saturating addition for rolling window work.

This is a minor thing, and I think all the usages in libcudf are safe anyway, but...

In `integer_utils.hpp` we have (for signed integers).

```c++
template <typename I>
constexpr I div_rounding_up_safe(std::integral_constant<bool, true>, I dividend, I divisor) noexcept
{
  auto quotient  = dividend / divisor;
  auto remainder = dividend % divisor;
  return quotient + (remainder != 0);
}
```

This doesn't work for `divisor == 0` (OK, fine). It also overflows for `divisor == -1` since `INT_MIN / -1` is undefined.

I think all the usages in libcudf are for dividing two positive integers, in which case it's probably fine.

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Adds more description to the `div_rounding_up_safe` utility identifying undefined behavior.
Closes #17539 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by pmattione-nvidia — APPROVED** [review]

**Review by wence- — APPROVED** [review]
Thanks David!

File: cpp/include/cudf/detail/utilities/integer_utils.hpp [hunk 1]
```diff
@@ -134,16 +134,20 @@ constexpr I div_rounding_up_safe(std::integral_constant<bool, true>, I dividend,
 }  // namespace detail
 
 /**
- * Divides the left-hand-side by the right-hand-side, rounding up
+ * @brief Divides the left-hand-side by the right-hand-side, rounding up
  * to an integral multiple of the right-hand-side, e.g. (9,5) -> 2 , (10,5) -> 2, (11,5) -> 3.
  *
+ * The result is undefined if `divisor==0` or
+ * if `divisor==-1` and `dividend==min<I>()`.
```
Comment (ttnghia) [inline cpp/include/cudf/detail/utilities/integer_utils.hpp:141]:
```suggestion
 * The result is undefined if `divisor == 0` or
 * if `divisor == -1` and `dividend == min<I>()`.
```

**Review by ttnghia — APPROVED** [review]
