### PR TITLE
Fix cudaErrorIllegalAddress in concatenate_list_elements when inner list has 0 rows

### LINKED ISSUE #22146: [Bug] flattenLists() crashes with cudaErrorIllegalAddress when inner list column has 0 rows
## Summary

`ColumnView.flattenLists()` (which routes to `cudf::lists::concatenate_list_elements`) triggers `cudaErrorIllegalAddress` (CUDA error 700) when the input is a `list<list<T>>` column whose inner `list<T>` child has **0 rows** — i.e., the outer list row is a valid-but-empty list (`[]`).

The CUDA error is asynchronous and deferred: `flattenLists()` returns without throwing, but the next GPU operation that forces a stream sync (allocation, copy, etc.) surfaces the fatal error.

## Environment

- cuDF version: 26.06.00
- spark-rapids-jni: 26.06.0-SNAPSHOT (bundles cuDF)
- GPU: NVIDIA RTX PRO 4500 Blackwell Server Edition
- CUDA driver: 590.44.01
- Java: OpenJDK 17.0.18

## Reproducer

```java
import ai.rapids.cudf.*;
import java.util.*;

public class FlattenReproducer {
    public static void main(String[] args) throws Exception {
        HostColumnVector.ListType intType =
            new HostColumnVector.ListType(true, new HostColumnVector.BasicType(true, DType.INT32));
        HostColumnVector.ListType listOfListsType =
            new HostColumnVector.ListType(true, intType);

        // PASS: normal non-empty case
        try (ColumnVector input = ColumnVector.fromLists(listOfListsType,
                 Arrays.asList(Arrays.asList(1, 2), Arrays.asList(3)));
             ColumnVector result = input.flattenLists()) {
            Cuda.deviceSynchronize(); // OK
            System.out.println("flatten([[1,2],[3]]): OK, rows=" + result.getRowCount());
        }

        // PASS: null inner list
        try (ColumnVector input = ColumnVector.fromLists(listOfListsType,
                 Arrays.asList((List<Integer>) null));
             ColumnVector result = input.flattenLists()) {
            Cuda.deviceSynchronize(); // OK
            System.out.println("flatten([null]): OK, rows=" + result.getRowCount());
        }

        // CRASH: outer list is a valid-but-empty list — inner column has 0 rows
        try (ColumnVector input = ColumnVector.fromLists(listOfListsType,
                 Collections.emptyList());        // 1 row: []
             ColumnVector result = input.flattenLists()) {
            Cuda.deviceSynchronize(); // <-- cudaErrorIllegalAddress 700 here
            System.out.println("flatten([]): OK");
        }
    }
}
```

## Actual output

```
flatten([[1,2],[3]]): OK, rows=1
flatten([null]): OK, rows=1
Testing flatten([]) ... [fromLists OK] [flattenLists returned] FAILED at deviceSynchronize after flattenLists:
Fatal CUDA error encountered at: ../../thirdparty/cudf/java/src/main/native/src/CudaJni.cpp:456:
700 cudaErrorIllegalAddress an illegal memory access was encountered
```

## Expected output

```
flatten([]): OK, rows=1   (result should be a 1-row column containing an empty list)
```

## Root cause analysis

The only guard in `cudf::lists::concatenate_list_elements` (`concatenate_list_elements.cu`) is:

```cpp
if (input.size() == 0) { return cudf::empty_like(input); }
```

This guards against a **zero-row outer column** but not against the case where the outer column has rows yet the **inner `list<T>` child column has 0 rows** (all outer rows are empty lists).

When the inner column has 0 rows, `concatenate_lists_ignore_null` proceeds to access device memory via `d_list_offsets` (derived from the inner column's offsets child). For a 0-row list column, this offsets buffer may be uninitialized or zero-length, causing the illegal memory access in the kernel.

The existing Java test `ColumnVectorTest::testFlattenLists` does not cover any empty-inner-list case.

## Workaround

In `spark-rapids`, `GpuFlattenArray.doColumnar` now guards against this before calling `flattenLists()`:

```scala
val needsEmptyGuard = withResource(inputBase.getChildColumnView(0)) { inner =>
  inner.getRowCount == 0L || { ... }
}
if (!needsEmptyGuard) inputBase.flattenLists
else /* build empty-list column directly */
```

See: https://github.com/NVIDIA/spark-rapids/pull/14610

## Suggested fix

Add a guard in `cudf::lists::concatenate_list_elements` (or `concatenate_lists_ignore_null`) for the case `lists_column_view(input).child().size() == 0`, returning `cudf::empty_like(input)` (with outer null mask preserved). Also extend `ColumnVectorTest::testFlattenLists` to cover `[]`, `[[]]`, and `[[],[]]` inputs.

### PR DESCRIPTION
**Pull request by wjxiz1992**
## Summary

Fixes #22146

When `flatten` (i.e. `cudf::lists::concatenate_list_elements`) is called on a column whose **inner (child) list column has 0 rows** — for example a single valid-but-empty `list<list<T>>` row — the existing code dereferences the inner column's offsets buffer through a raw device pointer. For a 0-row list column that buffer may be **unallocated (zero bytes)**, causing `cudaErrorIllegalAddress` (CUDA error 700). Because CUDA kernel errors are asynchronous, the illegal access is not caught immediately; it surfaces at the next `deviceSynchronize` or GPU memory allocation, potentially corrupting subsequent GPU operations in the same stream.

**Root cause**: `concatenate_list_elements` had an early-exit guard for `input.size() == 0` but not for `child.size() == 0`.

**Fix**: add a second early-exit guard immediately after the existing one. When `child.size() == 0`, every outer row is either null or a valid-but-empty list, so we can build the result directly without touching any device buffer:
- All-zero offsets column (`thrust::fill`)
- A copy of the 0-row grandchild column (preserves element type and nested structure)
- The outer null mask, copied verbatim

`null_policy` need not be consulted because `child.size() == 0` implies `child.has_nulls() == false`.

## Files changed

- `cpp/src/lists/combine/concatenate_list_elements.cu` — guard + `#include <thrust/fill.h>`
- `java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java` — 4 new test cases in `testFlattenLists()` covering `flatten([])`, `flatten(null, [])`, `flatten([[]])`, `flatten([[],[],[]])`

## C++ test validation

Existing C++ test suite `ConcatenateListElements*` (87 tests) all PASSED after the fix. The crash cases were also verified manually with a Java reproducer before the fix.

## Checklist

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/tests/lists/combine/concatenate_list_elements_tests.cpp [hunk 1]
```diff
@@ -796,3 +796,65 @@ TEST_F(ConcatenateListElementsTest, ListsOfListsOfStructsHavingListsWithNulls)
     CUDF_TEST_EXPECT_COLUMNS_EQUAL(*expected, *results, verbosity);
   }
 }
+
+// Tests for the child.size()==0 early-exit guard added to fix rapidsai/cudf#22146.
+// When the inner list column has 0 rows, the offsets buffer may be unallocated;
+// the guard must build the result without dereferencing that buffer.
+
+// Subcase A: child.size()==1 (guard does NOT fire) — baseline check.
+TEST_F(ConcatenateListElementsTest, EmptyInnerListColumnChildSizeOne)
```
Comment (pmattione-nvidia) [inline cpp/tests/lists/combine/concatenate_list_elements_tests.cpp:805]: I would add a test for list<struct<int, int>> since structs also have child columns

File: cpp/src/lists/combine/concatenate_list_elements.cu [hunk 2]
```diff
@@ -245,6 +246,36 @@ std::unique_ptr<column> concatenate_list_elements(column_view const& input,
...
+    auto [null_mask, null_count] = input.has_nulls()
+                                     ? std::pair(cudf::detail::copy_bitmask(input, stream, mr),
+                                                 input.null_count())
+                                     : std::pair(rmm::device_buffer{}, cudf::size_type{0});
+    return make_lists_column(num_rows,
+                             std::move(out_offsets),
+                             std::move(out_entries),
+                             null_count,
+                             std::move(null_mask));
+  }
```
[the remark this answers is not in the document]
Comment (wjxiz1992) [reply cpp/src/lists/combine/concatenate_list_elements.cu:274]: Addressed in commit `df709cd`: added three subcases (`EmptyInnerListColumnChildSizeOne`, `EmptyInnerListColumnChildSizeZero`, `EmptyInnerListColumnWithNullRow`) in `concatenate_list_elements_tests.cpp` covering the `child.size()==0` guard path.

File: java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java [hunk 3]
```diff
@@ -2738,6 +2738,48 @@ void testFlattenLists() {
...
+           (List<List<Integer>>) null,    // row 0: null outer row
+           Collections.emptyList());      // row 1: [] valid-but-empty outer row
+         ColumnVector result = input.flattenLists();
+         ColumnVector expected = ColumnVector.fromLists(listType,
+           null,                          // row 0: null preserved
+           Collections.emptyList())) {    // row 1: []
+      assertColumnsAreEqual(expected, result);
+    }
+
+    // Regression: flatten([[]]]) and flatten([[],[],[]]) do NOT crash in isolation
```
[the remark this answers is not in the document]
Comment (wjxiz1992) [reply java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java]: Fixed in commit `df709cd` — the extra `]` in the comment has been removed.

File: cpp/tests/lists/combine/concatenate_list_elements_tests.cpp (hunk 1 above)
Comment (wjxiz1992) [reply cpp/tests/lists/combine/concatenate_list_elements_tests.cpp:805]: Done — added `EmptyInnerListColumnChildSizeZeroWithStructGrandchild` in commit `4027aa1`. The test creates a `list<list<struct<int32,int32>>>` where `child.size() == 0` and verifies the guard correctly copies the struct grandchild (preserving its two int32 field columns) without dereferencing the child offsets buffer. All 4 `EmptyInnerListColumn*` tests pass locally.

**Review by pmattione-nvidia — APPROVED** [review]

File: java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java [hunk 4]
```diff
@@ -2738,6 +2738,48 @@ void testFlattenLists() {
         assertColumnsAreEqual(expected, result);
       }
     }
+
+    // Edge cases: empty/null outer rows — inner column has 0 rows (rapidsai/cudf#22146).
```
Comment (firestarman) [inline java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java:2742]: LGTM, However better to have c++ test suties instead of Java tests for cu code.

**Review by res-life — APPROVED** [review]
LGTM

File: cpp/src/lists/combine/concatenate_list_elements.cu [hunk 5]
```diff
@@ -245,6 +246,33 @@ std::unique_ptr<column> concatenate_list_elements(column_view const& input,
...
+  // so both policies would dispatch to concatenate_lists_ignore_null with build_null_mask=false,
+  // which simply copies the outer null mask — exactly what we do below.
+  if (child.size() == 0) {
+    auto const num_rows = input.size();
+    auto out_offsets    = make_numeric_column(
+      data_type{type_to_id<size_type>()}, num_rows + 1, mask_state::UNALLOCATED, stream, mr);
+    thrust::fill(rmm::exec_policy_nosync(stream, cudf::get_current_device_resource_ref()),
+                 out_offsets->mutable_view().begin<size_type>(),
+                 out_offsets->mutable_view().end<size_type>(),
+                 size_type{0});
```
Comment (davidwendt) [inline cpp/src/lists/combine/concatenate_list_elements.cu:265]:
```suggestion
    auto out_offsets = cudf::make_column_from_scalar( cudf::numeric_scalar<cudf::size_type>(0,true,stream,mr), num_rows + 1);
```
No need for thrust here.

File: cpp/src/lists/combine/concatenate_list_elements.cu [hunk 6]
```diff
@@ -245,6 +246,33 @@ std::unique_ptr<column> concatenate_list_elements(column_view const& input,
...
+    // Copy the 0-row grandchild to preserve the element type (and any nested structure).
+    auto out_entries = std::make_unique<column>(lists_column_view(child).child(), stream, mr);
```
Comment (davidwendt) [inline cpp/src/lists/combine/concatenate_list_elements.cu:267]:
```suggestion
    auto out_entries = cudf::empty_like(child);
```
This is probably more efficient.

File: cpp/src/lists/combine/concatenate_list_elements.cu [hunk 7]
```diff
@@ -245,6 +246,33 @@ std::unique_ptr<column> concatenate_list_elements(column_view const& input,
...
+    auto [null_mask, null_count] =
+      input.has_nulls()
+        ? std::pair(cudf::detail::copy_bitmask(input, stream, mr), input.null_count())
+        : std::pair(rmm::device_buffer{}, cudf::size_type{0});
+    return make_lists_column(
+      num_rows, std::move(out_offsets), std::move(out_entries), null_count, std::move(null_mask));
```
Comment (davidwendt) [inline cpp/src/lists/combine/concatenate_list_elements.cu:273]:
```suggestion
    return make_lists_column( num_rows, std::move(out_offsets), std::move(out_entries), input.null_count(), cudf::detail::copy_bitmask(input, stream, mr));
```
The `copy_bitmask` has the correct behavior for input nulls.

**Review by davidwendt — CHANGES_REQUESTED** [review]

File: java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java (hunk 4 above)
Comment (wjxiz1992) [reply java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java:2791]: Agreed. The C++ guard path is now covered by four dedicated tests in `cpp/tests/lists/combine/concatenate_list_elements_tests.cpp` — `EmptyInnerListColumnChildSizeOne`, `EmptyInnerListColumnChildSizeZero`, `EmptyInnerListColumnWithNullRow`, and `EmptyInnerListColumnChildSizeZeroWithStructGrandchild` — added in commits `df709cd` and `4027aa1`. The Java tests are kept as they cover the JNI binding path specifically.

File: cpp/src/lists/combine/concatenate_list_elements.cu (hunk 5 above)
Comment (wjxiz1992) [reply cpp/src/lists/combine/concatenate_list_elements.cu]: Done in `ba16364` — replaced `make_numeric_column` + `thrust::fill` with `make_column_from_scalar`, and dropped the now-unused `#include <thrust/fill.h>`.

File: cpp/src/lists/combine/concatenate_list_elements.cu (hunk 6 above)
Comment (wjxiz1992) [reply cpp/src/lists/combine/concatenate_list_elements.cu]: One concern here: `child` is the inner `list<T>` column (from `lists_column_view(input).child()`), so `empty_like(child)` would produce an empty `list<T>` column. Using that as `out_entries` in `make_lists_column` would make the output type `list<list<T>>` rather than the intended `list<T>`. The current code uses `lists_column_view(child).child()` (the grandchild) to get an empty `T` column — did you mean `empty_like(lists_column_view(child).child())`? Happy to switch once we align on the intent.

File: cpp/src/lists/combine/concatenate_list_elements.cu (hunk 7 above)
Comment (wjxiz1992) [reply cpp/src/lists/combine/concatenate_list_elements.cu]: Done.

File: cpp/src/lists/combine/concatenate_list_elements.cu (hunk 6 above)
Comment (davidwendt) [reply cpp/src/lists/combine/concatenate_list_elements.cu]: Yes, sorry. I did not inspect this close enough. Just wanted to point out `cudf::empty_like` as a candidate replacement.

Comment (wjxiz1992) [reply cpp/src/lists/combine/concatenate_list_elements.cu]: Updated in commit `dce7569` — switched to `cudf::empty_like(lists_column_view(child).child())` (applying it to the grandchild, not `child`, so `out_entries` is type `T` not `list<T>`). `empty_like` recurses through children, so struct grandchildren retain their field columns. Verified locally: 4/4 `EmptyInnerListColumn*` tests pass, full 13/13 `ConcatenateListElementsTest` pass. Could you dismiss the changes-requested when you get a chance?

**Review by davidwendt — APPROVED** [review]

**Comment by wjxiz1992** [comment]
CI status note: of the 4 failing checks, all appear to be pre-existing infrastructure issues unrelated to this PR:

- `check-nightly-ci` — reports that `test.yaml` on `main` has had 0 successful runs in the last 30 days.
- `spark-rapids-jni / spark-rapids-jni-build` — nvcc internal compiler error (`pop_object_lifetime_full: useful lifetime is unbound`, gcc-toolset-14 `type_traits`) while compiling `shuffle_split.cu`, which is not touched by this PR.
- `third-party-integration-tests-cudf-pandas / build` — fails with `Artifacts directory not found`, a cascading failure from the above.
- `pr-builder / run` — rollup of the above.

The same `check-nightly-ci` + `spark-rapids-jni-build` failures are currently reproducing on other open PRs (#22263, #22261, #22260), which suggests they are repo-wide and not caused by the changes here.

All code-relevant checks pass on this PR: `conda-cpp-build` / `conda-cpp-tests` (V100, L4, A100, H100, RTX Pro 6000), `conda-java-tests` (covers the new `testFlattenLists()` cases), `wheel-build-libcudf` / `wheel-build-cudf` / `wheel-tests-cudf`, `conda-python-cudf-tests`, `cpp-linters`, and `streams-*`.

**Comment by davidwendt** [comment]
The `spark-rapids-jni` build is non-blocking for merging.

**Comment by wjxiz1992** [comment]
/ok to test https://github.com/rapidsai/cudf/pull/22147/commits/a09b0d966a85bdf867504bfa2e58018e76d2f1d3

**Comment by wjxiz1992** [comment]
CI status update (re-run on 2026-04-28):

The earlier nvcc / gcc-toolset-14 internal compiler error and the `rmm/mr/device_memory_resource.hpp` not-found error are gone after NVIDIA/spark-rapids-jni#4468 merged. `check-nightly-ci` and `third-party-integration-tests-cudf-pandas` are now green again.

The remaining failures are all pre-existing main-branch breakage unrelated to this PR's diff:

- `spark-rapids-jni / spark-rapids-jni-build` — new failure, different root cause: `fatal error: cuco/hash_functions.cuh: No such file or directory` while compiling JNI hash sources. Tracked in NVIDIA/spark-rapids-jni#4498; introduced by #22263, which routes cudf's installed `murmurhash3_x86_32.cuh` through cuco headers that aren't on the JNI build's include path.
- `wheel-tests-cudf-polars-with-rapidsmpf` (h100, rtxpro6000) and `cudf-polars-polars-tests` (h100, rtxpro6000) — `ImportError: librapidsmpf.so: cannot open shared object file` from `cudf_polars/tests/conftest.py::_skip_unless_spmd`. The rapidsmpf shared lib isn't loadable in the polars test env; not touched by this PR.
- `pr-builder / run` — rollup of the above.

This PR only edits `cpp/src/lists/combine/concatenate_list_elements.cu` and adds a gtest, so none of the remaining failures are caused by it. Could a maintainer admin-merge once the above downstream/infra issues are sorted, or advise on the right path forward?

**Comment by ttnghia** [comment]
/ok to test https://github.com/rapidsai/cudf/pull/22147/commits/2f3a5e0f86a9cd65d22ac059a5b3ad88dbfac6c7
