### PR TITLE
Fix RMM JNI pinned_fallback_host_memory_resource for CCCL 3.1.0

### LINKED ISSUE #20159: [BUG] JNI pinned_fallback_host_memory_resource broken by CCCL 3.1.0
**Describe the bug**

The Java file `RmmJni.cpp` appears to have been broken by the update to CCCL 3.1.0 (https://github.com/rapidsai/build-planning/issues/217). This was not caught in testing. It seems like the `conda-java-tests` job doesn't obey the rapids-cmake branch overrides in `cmake/rapids_config.cmake`.

The compile errors look like this:
```
FAILED: [code=1] CMakeFiles/cudfjni.dir/src/RmmJni.cpp.o 
/opt/conda/envs/test/bin/x86_64-conda-linux-gnu-c++ -DCCCL_DISABLE_PDL -DCUB_DISABLE_NAMESPACE_MAGIC -DCUB_IGNORE_NAMESPACE_MAGIC_ERROR -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DRMM_LOG_ACTIVE_LEVEL=RAPIDS_LOGGER_LOG_LEVEL_INFO -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -Dcudfjni_EXPORTS -I/__w/cudf/cudf/java/target/cmake-build/include -I/__w/cudf/cudf/java/src/main/native/include -I/__w/cudf/cudf/java/src/main/native/src -I/opt/conda/envs/test/include/linux -I/__w/cudf/cudf/java/target/cmake-build/_deps/arrow-src/cpp/src -I/__w/cudf/cudf/java/target/cmake-build/_deps/arrow-src/cpp/src/generated -I/__w/cudf/cudf/java/target/cmake-build/_deps/arrow-src/cpp/thirdparty/hadoop/include -I/__w/cudf/cudf/java/target/cmake-build/_deps/arrow-src/cpp/thirdparty/flatbuffers/include -I/opt/conda/envs/test/include/rapids -isystem /opt/conda/envs/test/targets/x86_64-linux/include -isystem /opt/conda/envs/test/targets/x86_64-linux/include/cccl -O3 -DNDEBUG -std=gnu++20 -fPIC -Wall -Werror -Wno-unknown-pragmas -Wno-error=deprecated-declarations -Wno-deprecated-declarations -MD -MT CMakeFiles/cudfjni.dir/src/RmmJni.cpp.o -MF CMakeFiles/cudfjni.dir/src/RmmJni.cpp.o.d -fmodules-ts -fmodule-mapper=CMakeFiles/cudfjni.dir/src/RmmJni.cpp.o.modmap -MD -fdeps-format=p1689r5 -x c++ -o CMakeFiles/cudfjni.dir/src/RmmJni.cpp.o -c /__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:583:25: error: 'async_resource_with' is not a member of 'cuda::mr'; did you mean 'rmm::detail::polyfill::async_resource_with<Resource, Properties ...>'?
  583 | static_assert(cuda::mr::async_resource_with<pinned_fallback_host_memory_resource,
      |                         ^~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/test/include/rmm/detail/cccl_adaptors.hpp:19,
                 from /opt/conda/envs/test/include/rmm/mr/device/device_memory_resource.hpp:20,
                 from /opt/conda/envs/test/include/rmm/mr/device/cuda_memory_resource.hpp:21,
                 from /opt/conda/envs/test/include/rmm/mr/device/per_device_resource.hpp:21,
                 from /opt/conda/envs/test/include/rmm/device_buffer.hpp:22,
                 from /opt/conda/envs/test/include/cudf/utilities/span.hpp:22,
                 from /opt/conda/envs/test/include/cudf/column/column_view.hpp:21,
                 from /opt/conda/envs/test/include/cudf/column/column.hpp:18,
                 from /opt/conda/envs/test/include/cudf/table/table.hpp:18,
                 from /opt/conda/envs/test/include/cudf/contiguous_split.hpp:19,
                 from /__w/cudf/cudf/java/src/main/native/src/cudf_jni_apis.hpp:21,
                 from /__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:17:
/opt/conda/envs/test/include/rmm/detail/cuda_memory_resource.hpp:39:23: note: 'rmm::detail::polyfill::async_resource_with<Resource, Properties ...>' declared here
   39 | inline constexpr bool async_resource_with = cuda::mr::resource_with<Resource, Properties...>;
      |                       ^~~~~~~~~~~~~~~~~~~
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:583:81: error: expected primary-expression before ',' token
  583 | static_assert(cuda::mr::async_resource_with<pinned_fallback_host_memory_resource,
      |                                                                                 ^
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:584:45: error: 'static_assert' with non-string message only available with '-std=c++2c' or '-std=gnu++2c' [-Werror=c++26-extensions]
  584 |                                             cuda::mr::device_accessible,
      |                                             ^~~~
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:584:72: error: expected primary-expression before ',' token
  584 |                                             cuda::mr::device_accessible,
      |                                                                        ^
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:584:72: error: expected ')' before ',' token
  584 |                                             cuda::mr::device_accessible,
      |                                                                        ^
      |                                                                        )
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:583:14: note: to match this '('
  583 | static_assert(cuda::mr::async_resource_with<pinned_fallback_host_memory_resource,
      |              ^
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp: In function 'void Java_ai_rapids_cudf_Rmm_setCudfPinnedPoolMemoryResource(JNIEnv*, jclass, jlong)':
/__w/cudf/cudf/java/src/main/native/src/RmmJni.cpp:1066:63: error: could not convert '{anonymous}::pinned_fallback_mr.std::unique_ptr<{anonymous}::pinned_fallback_host_memory_resource>::operator*()' from '{anonymous}::pinned_fallback_host_memory_resource' to 'rmm::host_device_async_resource_ref' {aka 'rmm::detail::cccl_async_resource_ref<cuda::mr::__4::basic_resource_ref<cuda::mr::__4::_AllocType::_Default, cuda::mr::__4::host_accessible, cuda::mr::__4::device_accessible> >'}
 1066 |     prior_cudf_pinned_mr() = cudf::set_pinned_memory_resource(*pinned_fallback_mr);
      |                                                               ^~~~~~~~~~~~~~~~~~~
      |                                                               |
      |                                                               {anonymous}::pinned_fallback_host_memory_resource
cc1plus: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #20159.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: java/src/main/native/src/RmmJni.cpp
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp:659]:
```suggestion
static_assert(cuda::mr::resource_with<pinned_fallback_host_memory_resource,
                                      cuda::mr::device_accessible,
                                      cuda::mr::host_accessible>);
```

File: java/src/main/native/src/RmmJni.cpp [hunk 1]
```diff
@@ -577,6 +577,80 @@ class pinned_fallback_host_memory_resource {
...
+   * CUDA out of memory error.
+   * @throws rmm::bad_alloc if the requested allocation could not be fulfilled due to any other
+   * error.
+   *
+   * @param stream CUDA stream on which to perform the allocation (ignored).
+   * @param bytes The size, in bytes, of the allocation.
+   * @param alignment Alignment in bytes.
+   * @return Pointer to the newly allocated memory.
+   */
+  static void* allocate(cuda_stream_view stream, std::size_t bytes, std::size_t alignment)
```
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  static void* allocate(rmm::cuda_stream_view stream, std::size_t bytes, std::size_t alignment)
```

File: java/src/main/native/src/RmmJni.cpp [hunk 2]
```diff
@@ -577,6 +577,80 @@ class pinned_fallback_host_memory_resource {
...
+   * alignment bytes.
+   *
+   * @note Stream argument is ignored and behavior is identical to deallocate.
+   *
+   * @param stream CUDA stream on which to perform the deallocation (ignored).
+   * @param ptr Pointer to be deallocated.
+   * @param bytes Size of the allocation.
+   * @param alignment Alignment in bytes.
+   */
+  static void deallocate(cuda_stream_view stream,
```
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  static void deallocate(rmm::cuda_stream_view stream,
```

File: java/src/main/native/src/RmmJni.cpp [hunk 3]
```diff
@@ -577,6 +578,80 @@ class pinned_fallback_host_memory_resource {
...
+   * CUDA out of memory error.
+   * @throws rmm::bad_alloc if the requested allocation could not be fulfilled due to any other
+   * reason.
+   *
+   * @param bytes The size, in bytes, of the allocation.
+   * @param alignment Alignment in bytes. Default alignment is used if unspecified.
+   *
+   * @return Pointer to the newly allocated memory.
+   */
+  static void* allocate_sync(std::size_t bytes, std::size_t alignment)
```
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp]: All the newly added functions here cannot be `static` as they are calling to the existing non-static functions.
```suggestion
  void* allocate_sync(std::size_t bytes, std::size_t alignment)
```

File: java/src/main/native/src/RmmJni.cpp [hunk 4]
```diff
@@ -577,6 +578,80 @@ class pinned_fallback_host_memory_resource {
                            cuda::mr::host_accessible) noexcept
   {
   }
+
+#if CCCL_MAJOR_VERSION > 3 || (CCCL_MAJOR_VERSION == 3 && CCCL_MINOR_VERSION >= 1)
```
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp:548]: Please also move this `#if...#endif` up, after line 548 so they can stay closer to the similar functions.

File: java/src/main/native/src/RmmJni.cpp
Comment (ttnghia) [reply java/src/main/native/src/RmmJni.cpp:659]: Ref: https://github.com/NVIDIA/cccl/pull/5313

Comment (bdice) [reply java/src/main/native/src/RmmJni.cpp:659]: Addressed in 24f366b.

File: java/src/main/native/src/RmmJni.cpp (hunk 3 above)
Comment (bdice) [reply java/src/main/native/src/RmmJni.cpp]: Addressed in 24f366b.

File: java/src/main/native/src/RmmJni.cpp (hunk 4 above)
Comment (bdice) [reply java/src/main/native/src/RmmJni.cpp:548]: Addressed in 24f366b.

**Review by ttnghia — APPROVED** [review]

File: java/src/main/native/src/RmmJni.cpp [hunk 5]
```diff
@@ -547,6 +545,74 @@ class pinned_fallback_host_memory_resource {
...
+  }
+
+  /**
+   * @brief Deallocate memory pointed to by \p ptr of size \p bytes bytes.
+   *
+   * @param ptr Pointer to be deallocated.
+   * @param bytes Size of the allocation.
+   * @param alignment Alignment in bytes. Default alignment is used if unspecified.
+   */
+  void deallocate_sync(void* ptr, std::size_t bytes, std::size_t alignment)
```
Comment (bdice) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  void deallocate_sync(void* ptr, std::size_t bytes, std::size_t alignment) noexcept
```

File: java/src/main/native/src/RmmJni.cpp [hunk 6]
```diff
@@ -547,6 +545,74 @@ class pinned_fallback_host_memory_resource {
...
+   * alignment bytes.
+   *
+   * @note Stream argument is ignored and behavior is identical to deallocate.
+   *
+   * @param stream CUDA stream on which to perform the deallocation (ignored).
+   * @param ptr Pointer to be deallocated.
+   * @param bytes Size of the allocation.
+   * @param alignment Alignment in bytes.
+   */
+  void deallocate(rmm::cuda_stream_view stream, void* ptr, std::size_t bytes, std::size_t alignment)
```
Comment (bdice) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  void deallocate(rmm::cuda_stream_view stream, void* ptr, std::size_t bytes, std::size_t alignment) noexcept
```

Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  void deallocate(rmm::cuda_stream_view stream, void* ptr, std::size_t bytes, std::size_t alignment) noexcept
```

File: java/src/main/native/src/RmmJni.cpp (hunk 5 above)
Comment (ttnghia) [inline java/src/main/native/src/RmmJni.cpp]:
```suggestion
  void deallocate_sync(void* ptr, std::size_t bytes, std::size_t alignment) noexcept
```

**Comment by ttnghia** [comment]
`spark-rapids-jni` fails due to missing `fmt`, which should be fixed by https://github.com/NVIDIA/spark-rapids-jni/pull/3805. That failure is not blocking this to merge.

**Review by ttnghia — APPROVED** [review]
