### PR TITLE
[REVIEW] Fix groupby multiple aggregations same column

### LINKED ISSUE #2460: [BUG] Error in groupby with multiple aggregations on the same column
**Describe the bug**
Calling
```c++
table keys{columnA};
table values{columnB, columnB};
std::vector<operators> ops{SUM, MEAN};
Options options{false};

cudf::groupby::hash::groupby(keys, values, ops, options);
```
throws an error `"SUM request missing."`
This is caused because here ⬇️ when processing the first SUM operation it gets deleted but it's still needed for the calculation of the AVG operation
https://github.com/rapidsai/cudf/blob/320adf2f199f134d573f4a4383cdfdba4c034441/cpp/src/groupby/hash/aggregation_requests.cpp#L116-L146

**Expected behavior**
The above code should't throw any error and terminate successfully

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #2460  #2331

### CODE REVIEW

**Comment by jrhemstad** [comment]
This works, but it relies on the fact that `MEAN` just happens to be last in the `operations` enum, which isn't quite robust.

A more robust solution, which also solves https://github.com/rapidsai/cudf/issues/2331, would be to associate a `count` with every simple request in `compound_to_simple`, and decrement the count during `compute_original_requests`. Only once the `count` reaches zero should it be erased. This should be able to handle duplicate requests for the same aggregation (see https://github.com/rapidsai/cudf/issues/2331) by simply making a copy of the corresponding column from `simple_outputs`.

**Comment by jeanp413** [comment]
Needed to keep de processing order to avoid doing unnecessary copies when processing simple requests.

**Comment by jrhemstad** [comment]
> When a PR is fixing a bug, you should include a new test that exercises the bug to ensure it is fixed. Can you please add a gtest or update existing tests?

To be fair to @jeanp413, all of the hash groupby tests are single column tests, and this bug only appears for multi-column tests. It's more involved to add _proper_ multi-column tests.

@jeanp413, I think it'd be appropriate to just add a one-off multi-column test in a separate test file.

File: cpp/src/groupby/hash/aggregation_requests.cpp [hunk 1]
```diff
@@ -57,13 +58,15 @@ std::vector<AggRequestType> compound_to_simple(
...
     auto col = p.first;
-    std::set<operators>& ops = p.second;
+    std::multiset<operators>& ops = p.second;
     while (not ops.empty()) {
-      simple_requests.emplace_back(col, *ops.begin());
-      ops.erase(ops.begin());
+      auto op = *ops.begin();
+      simple_requests.emplace_back(std::make_pair(col, op),
+                                   static_cast<gdf_size_type>(ops.count(op)));
+      ops.erase(op);
```
Comment (jrhemstad) [inline cpp/src/groupby/hash/aggregation_requests.cpp]: This logic will end up with duplicates in `simple_requests` and end up redundantly computing the same aggregation during the groupby computation. Instead, it would be more efficient to compute the aggregation _once_, and then simply make copies of the result to satisfy the original requests. 

This is because by using a `multiset`, it will end up with duplicate entries for the same key, and `ops.erase(op)` erases a _single_ instance of that key, rather than all occurrences of that key.  `emplace_back` will then end up being called multiple times for the same request. 

This should be changed to either:
1. Use a `std::set` and increase the count when inserting
2. Erase all of the matching keys from the `multiset`

File: cpp/src/groupby/hash/aggregation_requests.cpp [hunk 2]
```diff
@@ -96,64 +99,92 @@ gdf_column* compute_average(gdf_column sum, gdf_column count,
...
-        simple_outputs.get_column(i);
+    simple_requests_to_outputs[simple_requests[i].first] = {
+        simple_outputs.get_column(i), simple_requests[i].second};
   }
 
-  std::vector<gdf_column*> final_value_columns;
+  // Calculate processing order so that the compound operators are
+  // processed first
+  std::vector<gdf_size_type> processing_order(original_requests.size());
+  std::iota(processing_order.begin(), processing_order.end(), 0);
```
Comment (jrhemstad) [inline cpp/src/groupby/hash/aggregation_requests.cpp]: I see what you mean about still needing to sort the requests to avoid unnecessary copies. 

How about instead of relying on the enum ordering for the sort, we do a 2 pass approach? 

Do a first pass through the `original_requests` and compute the compound requests (decrementing the counts of the associated `simple_requests` as necessary without making any copies).

Then do a second pass, of which only simple requests should remain. For each simple request, make copies and decrement the count until the `count == 1`, at which point, no copy is made, just use the computed result. Then remove the request.

File: cpp/src/groupby/hash/aggregation_requests.cpp (hunk 1 above)
Comment (jeanp413) [reply cpp/src/groupby/hash/aggregation_requests.cpp]: From https://en.cppreference.com/w/cpp/container/multiset/erase
> size_type erase( const key_type& key ); (3)
> 3) Removes all elements with the key equivalent to key.

Comment (jrhemstad) [reply cpp/src/groupby/hash/aggregation_requests.cpp]: Oh, duh. I confused (1) and (3) :)

File: cpp/src/groupby/hash/aggregation_requests.cpp (hunk 2 above)
Comment (jeanp413) [reply cpp/src/groupby/hash/aggregation_requests.cpp]: done

**Comment by jrhemstad** [comment]
@jeanp413 you just need to add a CHANGELOG entry and then we'll be good to go.
