### PR TITLE
Support fixed point types in Parquet predicate pushdown

### LINKED ISSUE #21584: [BUG] Parquet stats filters perform incorrect decoding for decimal128 stats
**Describe the bug**
cuDF decimal pushdown fails in both stats filtering (JIT/AST) and row‑level evaluation for DECIMAL64/DECIMAL128. Stats filtering prunes all row groups (`afterStats=0`, `outputRows=0`) for cases
that should match, and row‑eval returns incorrect boolean values and/or null propagation for range and IN‑list filters. The repro uses DECIMAL64 stored as INT64 and DECIMAL128 stored as
FIXED_LEN_BYTE_ARRAY (big‑endian per Parquet spec).

**Steps/Code to reproduce bug**
Minimal cuDF‑only repro is attached as `cudf-decimal-pushdown-repro.zip` ([cudf-decimal-pushdown-repro.zip](https://github.com/user-attachments/files/25588636/cudf-decimal-pushdown-repro.zip)). It includes a Docker build/run script.

All failing cases are described in one file: `cudf-decimal-pushdown-repro/src/decimal_pushdown_repro.cpp` in included zip. Everything else is to aid in reproduction and keeping repro environment consistent. 

*Docker (recommended):*
1. Unzip `cudf-decimal-pushdown-repro.zip`.
2. From the repo root, run: `./cudf-decimal-pushdown-repro/build_and_run.sh --run`
   (or build only: `./cudf-decimal-pushdown-repro/build_and_run.sh`)
3. Observe legend + matrix output: multiple FAILs in both JIT and AST modes.

*Manual Docker (alternative):*
1. `docker build -t cudf-decimal-repro -f cudf-decimal-pushdown-repro/Dockerfile .`
2. `docker run --rm --gpus all cudf-decimal-repro`
(Verbose output: `docker run --rm --gpus all cudf-decimal-repro --verbose`)

*Local build (alternative):*
1. `cmake -S cudf-decimal-pushdown-repro -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_ARCHITECTURES=<arch>`
2. `cmake --build build -j`
3. `./build/decimal_pushdown_repro`

**Expected behavior**
All tests PASS.
- Stats filter should keep correct row groups and output row counts for DECIMAL64/DECIMAL128 in both JIT and AST modes.
- Row‑level evaluation should return correct boolean values and null propagation for range and IN‑list filters in both JIT and AST modes.

**Environment overview (please complete the following information)**
- Environment location: Docker
- Method of cuDF install: from source (FetchContent in repro)
  - cuDF built in Docker environment, Docker commands used:
    - `./cudf-decimal-pushdown-repro/build_and_run.sh --run`
    - (manual) `docker build -t cudf-decimal-repro -f cudf-decimal-pushdown-repro/Dockerfile .`
    - (manual) `docker run --rm --gpus all cudf-decimal-repro`

**Environment details**
See dockerfile for full description of env.

**Additional context**

There are many tests failing. 

Repro is in `cudf-decimal-pushdown-repro/src/decimal_pushdown_repro.cpp`. It defines numbered tests and prints a legend + matrix:
- Stats filter cases: positive range, negative range, non‑pruning, and IN‑list. One case verifies Parquet physical types (`c0` INT64, `c1` FIXED_LEN_BYTE_ARRAY) to exercise the big‑endian decimal
 decode path.
- Row‑eval cases: range and IN‑list with nulls for DECIMAL64/DECIMAL128, including a large DECIMAL128 value.
- cuDF commit pinned in repro: `e6ba1feee8f056ce2e245f771403cfa5f598d813` (Velox‑pinned).
Observed failures: stats pruning collapses to 0 row groups/rows; row‑eval mismatches in both JIT and AST for DECIMAL64/DECIMAL128.
- There was a reasonable effort to flush out all issues with decimals in these code-paths, but there could remain related issues missed by this bug report. Consider verifying by adding more test coverage.

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description

Closes #21584

This PR enables proper support for fixed point (specifically decimal128) types in Parquet / Hybrid scan predicate pushdown

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/io/parquet/stats_filter_helpers.hpp [hunk 1]
```diff
@@ -38,8 +39,17 @@ constexpr size_t initial_chars_capacity = 1024;
  */
 class stats_caster_base {
  protected:
+  static inline numeric::decimal128::rep decode_flba_decimal128(uint8_t const* stats_val)
+  {
+    using RepType  = numeric::decimal128::rep;
+    auto value_rep = std::bit_cast<std::array<std::byte, sizeof(RepType)>>(
+      *reinterpret_cast<RepType const*>(stats_val));
+    std::ranges::reverse(value_rep);
```
Comment (wence-) [inline cpp/src/io/parquet/stats_filter_helpers.hpp]: Just to note, this becomes incorrect if we ever start running on host systems with a native big-endian byte order.

Comment (mhaseeb123) [reply cpp/src/io/parquet/stats_filter_helpers.hpp]: Added a fix

File: cpp/tests/io/parquet_reader_test.cpp [hunk 2]
```diff
@@ -2963,18 +2957,17 @@ void filter_typed_test()
...
-        return cudf::string_scalar("000010000");  // i (0-20,000)
+        return cudf::string_scalar("000010000");  // i ∈ [0-20,000)
+      } else if constexpr (cudf::is_fixed_point<T>()) {
+        return cudf::fixed_point_scalar<T>(typename T::rep{0},
+                                           numeric::scale_type{0});  // i ∈ [-10,000, 10,000)
       } else {
-        // table[0] < 0 or 100u
         return cudf::numeric_scalar<T>(
-          (100 - 100 * std::is_signed_v<T>));  // i/100 (-100-100/ 0-200)
+          (100 - 100 * std::is_signed_v<T>));  // i/100 ∈ [-100, -100) or [0, 200)
```
Comment (ttnghia) [inline cpp/tests/io/parquet_reader_test.cpp]:
```suggestion
          (100 - 100 * std::is_signed_v<T>));  // i/100 ∈ [-100, 100) or [0, 200)
```

File: cpp/src/io/parquet/stats_filter_helpers.hpp [hunk 3]
```diff
@@ -38,8 +39,21 @@ constexpr size_t initial_chars_capacity = 1024;
...
 class stats_caster_base {
  protected:
+  static inline numeric::decimal128::rep decode_flba_decimal128(uint8_t const* stats_val)
+  {
+    auto constexpr endianness = std::endian::native;
+    static_assert(endianness == std::endian::little or endianness == std::endian::big,
+                  "Encountered unsupported endianness while decoding decimal128 from FLBA");
+    using RepType  = numeric::decimal128::rep;
+    auto value_rep = std::bit_cast<std::array<std::byte, sizeof(RepType)>>(
+      *reinterpret_cast<RepType const*>(stats_val));
```
Comment (ttnghia) [inline cpp/src/io/parquet/stats_filter_helpers.hpp]: `stats_val` may not have the required alignment for casting into `RepType`. Consider creating a local `RepType` variable and do a memcpy into it.

Comment (wence-) [reply cpp/src/io/parquet/stats_filter_helpers.hpp]: good point. That's true broadly of all the reinterpret_casts in the stats decoding I thinn

File: cpp/tests/io/parquet_reader_test.cpp (hunk 2 above)
Comment (mhaseeb123) [reply cpp/tests/io/parquet_reader_test.cpp]: Thanks for the catch

File: cpp/src/io/parquet/stats_filter_helpers.hpp (hunk 3 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/stats_filter_helpers.hpp]: Good point. `stats_val` points to `std::vector<uint8_t>::data()` so it's surprising that this has never complained. Fixed in f01e6fb

File: cpp/tests/io/parquet_reader_test.cpp [hunk 4]
```diff
@@ -3353,18 +3348,17 @@ void filter_unary_operation_typed_test()
...
```
Comment (mhaseeb123) [inline cpp/tests/io/parquet_reader_test.cpp]:
```suggestion
          (100 - 100 * std::is_signed_v<T>));  // i/100 ∈ [-100, 100) or [0, 200)
```
