### PR TITLE
Setting a threshold for KvikIO IO

### LINKED ISSUE #12780: [BUG] Writing ORC files with KvikIO is 5x slower
**Describe the bug**
When running the `orc_write_io_compression` libcudf benchmarks, using `LIBCUDF_CUFILE_POLICY=KVIKIO` causes the benchmarks to run 5x slower.

When set to `OFF` or `GDS` the runtimes are 500-700 ms, however when set to `KVIKIO` the runtimes are >2.5 s.

```
LIBCUDF_CUFILE_POLICY										OFF	GDS	KVIKIO
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=0 run_length=1]	708	712	5529
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=1000 run_length=1]	749	731	2713
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=0 run_length=32]	517	534	2468
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=1000 run_length=32]	519	516	2519
```

**Steps/Code to reproduce bug**
Build from source (`./build.sh libcudf benchmarks`) and run:

```
export WORKSPACE=/raid && export CUDF_BENCHMARK_DROP_CACHE=1 && export LIBCUDF_CUFILE_POLICY=KVIKIO && ./ORC_WRITER_NVBENCH --benchmark 1 --devices 0 --profile --axis io=FILEPATH --axis compression=NONE

export WORKSPACE=/raid && export CUDF_BENCHMARK_DROP_CACHE=1 && export LIBCUDF_CUFILE_POLICY=GDS && ./ORC_WRITER_NVBENCH --benchmark 1 --devices 0 --profile --axis io=FILEPATH --axis compression=NONE

export WORKSPACE=/raid && export CUDF_BENCHMARK_DROP_CACHE=1 && export LIBCUDF_CUFILE_POLICY=OFF && ./ORC_WRITER_NVBENCH --benchmark 1 --devices 0 --profile --axis io=FILEPATH --axis compression=NONE

```

**Expected behavior**
I expect KVIKIO to be similar or better performance than the libcudf default data sink.

**Environment overview (please complete the following information)**
I collected these numbers with `3c39be5a9` and docker image `0022659d9d65` from [rapidsai-dev-nightly](https://hub.docker.com/r/rapidsai/rapidsai-dev-nightly/tags?page=1&name=23.02)

**Additional context**
The extra time is spent in the write step. The encoding kernels are not impacted.

`KVIKIO`
image

`OFF`
image

I also tried using the tuning parameters `KVIKIO_TASK_SIZE`, `KVIKIO_NTHREADS` and `KVIKIO_COMPAT_MODE` but could not recover performance completely. Increasing the number of threads showed a positive impact.

```
LIBCUDF_CUFILE_POLICY										OFF	GDS	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO	KVIKIO
KVIKIO_NTHREADS														1	16	64					16	16
KVIKIO_TASK_SIZE															4194304	16777216 67108864			67108864
KVIKIO_COMPAT_MODE																			ON	ON	ON
												
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=0 run_length=1]	708	712	5529	5453	3946	3913	5566	5482	5496	2650	1052	965
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=1000 run_length=1]	749	731	2713	2741	1043	958	2727	2723	2728	2736	1022	1005
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=0 run_length=32]	517	534	2468	2455	727	647	2476	2475	2474	2448	709	728
orc_write_io_compression [Device=0 io=FILEPATH compression=NONE cardinality=1000 run_length=32]	519	516	2519	2543	712	627	2532	2541	2534	2521	733	707

```

### PR DESCRIPTION
**Pull request by madsbk**
### Description
For small reads and writes the overhead of using cuFile and/or KvikIO becomes significant. This PR introduces the threshold already used by the `GDS` to the `KVIKIO` backend as well. 

Closes #12780

### Future work
Let's optimize KvikIO for small reads and writes so we don't need this threshold. 
Tracking here: https://github.com/rapidsai/kvikio/issues/178

### Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

cc. @GregoryKimball, @vuule

### CODE REVIEW

**Comment by madsbk** [comment]
@GregoryKimball or @vuule, can I get one of you to confirm that it fixes #12841?

**Comment by GregoryKimball** [comment]
Thank you Mads for sharing this solution! One of us will take a look and get back to you soon.
😄

**Review by vuule — APPROVED** [review]
Ran benchmarks locally (no GDS support); big gains on the ORC writer side, no significant impact on the Parquet reader (I assume ORC reader would behave the same way). Performance might look different on a GDS-enabled system.
Looks like a good change to merge.

File: cpp/src/io/utilities/datasource.cpp [hunk 1]
```diff
@@ -98,6 +98,8 @@ class file_source : public datasource {
  private:
   std::unique_ptr<detail::cufile_input_impl> _cufile_in;
   kvikio::FileHandle _kvikio_file;
+  // The read size above which GDS is faster then posix-read + h2d-copy
+  static constexpr size_t _gds_io_preferred_threshold = 128 << 10;
```
Comment (ttnghia) [inline cpp/src/io/utilities/datasource.cpp:102]: This is bad. You have the same constant defined in two separate places without sync.

Please define it in one place and use it in both.

File: cpp/src/io/utilities/data_sink.cpp [hunk 2]
```diff
@@ -96,6 +96,8 @@ class file_sink : public data_sink {
   size_t _bytes_written = 0;
   std::unique_ptr<detail::cufile_output_impl> _cufile_out;
   kvikio::FileHandle _kvikio_file;
+  // The write size above which GDS is faster then d2h-copy + posix-write
+  static constexpr size_t _gds_io_preferred_threshold = 128 << 10;
```
[the remark this answers is not in the document]
Comment (vuule) [reply cpp/src/io/utilities/data_sink.cpp:100]: IMO 128 << 10 is clearer as 128KB

File: cpp/src/io/utilities/datasource.cpp (hunk 1 above)
Comment (vuule) [reply cpp/src/io/utilities/datasource.cpp:102]: These don't really represent the same value. We could potentially use different thresholds for reads and writes.

Comment (ttnghia) [reply cpp/src/io/utilities/datasource.cpp:102]: Then please use different names. Using exactly the same name will cause confusion.

Comment (ttnghia) [reply cpp/src/io/utilities/datasource.cpp:102]: Also:
```suggestion
  static constexpr size_t _gds_io_preferred_threshold = 128 << 10; // 128KB
```

**Comment by madsbk** [comment]
@ttnghia, thanks for the review. I have renamed `_gds_io_preferred_threshold` to:
```c++
_gds_read_preferred_threshold
_gds_write_preferred_threshold
```

**Review by ttnghia — APPROVED** [review]
