### PR TITLE
[REVIEW] Fix merging dataframes when names differ

### LINKED ISSUE #2299: [BUG] Merge fills in values in the other key that should be NaN/null when left_on and right_on differ
Calling merge on columns with partial overlap does not produce NaNs/nulls in the resultant dataframe. Instead, the "missing values" from the key column are filled with the key value from the other key column.

cuDF:
```python
import cudf
import pandas as pd
​
df1 = cudf.DataFrame({'a':[0,1,2.0,3,4,5, 9]})
df2 = cudf.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
​
res = df1.merge(df2, how='left', left_on=['a'], right_on=['b'])
print(res)
     a    b  c
0  3.0  3.0  2
1  5.0  5.0  1
2  9.0  9.0  3
3  0.0  0.0   
4  1.0  1.0   
5  2.0  2.0   
6  4.0  4.0   
7  5.0  5.0  4
```

pandas:
```python
import cudf
import pandas as pd
​
df1 = pd.DataFrame({'a':[0,1,2.0,3,4,5, 9]})
df2 = pd.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
​
res = df1.merge(df2, how='left', left_on=['a'], right_on=['b'])
print(res)
     a    b    c
0  0.0  NaN  NaN
1  1.0  NaN  NaN
2  2.0  NaN  NaN
3  3.0  3.0  2.0
4  4.0  NaN  NaN
5  5.0  5.0  1.0
6  5.0  5.0  4.0
7  9.0  9.0  3.0
```

```
commit 28492c82d39aca7f9ee64c7d74138158914965bb
Merge: 78116de 6eb5861
Author: Keith Kraus <kkraus@nvidia.com>
Date:   Mon Jul 15 11:14:58 2019 -0400
```

### LINKED ISSUE #2504: [BUG] joins can return success without initializing dtypes
**Describe the bug**
If you do a join that is going to return an empty table GDF_SUCCESS is returned before the output dtypes are initialized. Which means the caller has to initialize the dtypes themselves before passing in the output which is not needed in any other case.
```
  GDF_REQUIRE(0 != num_cols_to_join, GDF_SUCCESS);
...

  // If the inputs are empty, immediately return
  if ((0 == left_col_size) && (0 == right_col_size)) {
    return GDF_SUCCESS;
  }

  // If left join and the left table is empty, return immediately
  if ((JoinType::LEFT_JOIN == join_type) && (0 == left_col_size)) {
    return GDF_SUCCESS;
  }

  // If Inner Join and either table is empty, return immediately
  if ((JoinType::INNER_JOIN == join_type) &&
      ((0 == left_col_size) || (0 == right_col_size))) {
    return GDF_SUCCESS;
  }
```

**Steps/Code to reproduce bug**
Inner join where either table is empty.

**Expected behavior**
Get a valid set of empty columns back.

### LINKED ISSUE #2594: [BUG] dataframe labels after merge
**Describe the bug**
When the same column names are used but in a different order, the merge function doesn't label the output as expected.  I would expect either the columns to be labeled as the left data frame or expect both columns (as pandas).  See the example below.

**Steps/Code to reproduce bug**
The following code demonstrates the behavior:
```
a = cudf.DataFrame()
b = cudf.DataFrame()

a['src'] = [ 0, 0 ]
a['dst'] = [ 1, 2 ]
a['name'] = 'a'

b['src'] = [ 1, 2 ]
b['dst'] = [ 0, 0 ]
b['name'] = 'b'

print('a')
print(a.to_pandas())
print('a merge b')
print(a.merge(b, left_on=['src', 'dst'], right_on=['dst', 'src']).to_pandas())
```

**Expected behavior**
The current code provides the following result:
```
a
   src  dst name
0    0    1    a
1    0    2    a
a merge b
   src  dst name_x name_y
0    1    0      a      b
1    2    0      a      b
```
Note that the src and dest columns are labeled as in data frame b even though we started from a and did a left inner join.  I would expect - if we only keep one set of src/dst columns that it would be the columns from a, since that is both the object of the operation and the fact that we are doing a left join and a is on the left.  It might be better, in this case, to use the suffix method as pandas does.

Pandas (with the same code) provides the following output:
```
a
   src  dst name
0    0    1    a
1    0    2    a
a merge b
   src_x  dst_x name_x  src_y  dst_y name_y
0      0      1      a      1      0      b
1      0      2      a      2      0      b
```
Which preserves both values for src/dst by adding the suffixes to the key columns when their names match.  A little experimenting with different variations of selecting columns whose names match in same and different orderings suggest that the criteria for using the suffix is something like:
 - if we're comparing a key column from both data frames and the names match use this name in the output
 - if we're comparing a key column from both data frames and the names don't match then append the suffix if that column name appears as a column in the other data frame
 - Already have rules in place for handling if a non-key column name is duplicated, leave those in place.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
[cudf-environment.txt](https://github.com/rapidsai/cudf/files/3506146/cudf-environment.txt)

**Additional context**

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
[REVIEW]
The code changes contain solution for issue #2299 and the APIs have been modified to accept cuff::table rather than array of gdf_column.

Additional test case has been added to take care of the #2299 

close #2299
close #2504 
close #2594

### CODE REVIEW

File: cpp/include/cudf/join.hpp [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+ * list at same index in join list.  
+ * @param[in] r_common_name_join_ind Indices of right dataframe in join list which have same name as one on left dataframe join 
+ * list at same index in join list.  
+ * @param[in] join_context The context to use to control how the join is performed,e.g.,
+ * sort vs hash based implementation
+ * 
+ * @returns If Success, pair of left and right table which are merged 
+ * 
+ */
+std::pair<cudf::table, cudf::table> gdf_inner_join(
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]:
```suggestion
std::pair<cudf::table, cudf::table> inner_join(
```

`gdf_` prefix is defunct.

File: cpp/include/cudf/join.hpp [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+                         cudf::table & left_cols,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: In libcudf, we never pass by a non-const reference. For inputs, always pass by `const&`. This needs to be changed throughout.

File: cpp/include/cudf/join.hpp [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+                         std::vector <int> left_join_cols,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: Pass non-trivially copied inputs by `const&`
```suggestion
                         std::vector<int> const& left_join_cols,
```

Comment (jrhemstad) [reply cpp/include/cudf/join.hpp]: Instead of passing the indices of the "on" columns, we should instead pass another `table` containing pointers to the "on" columns from the left and right columns respectively.

File: cpp/include/cudf/join.hpp [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+                         cudf::table & right_cols,
+                         std::vector <int> right_join_cols,
+                         gdf_column * left_indices,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: I do not think there is any need to return the joined indices anymore. This can be removed.

File: cpp/include/cudf/join.hpp [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+ * @param[in] left_join_cols The column indices of columns from the left dataframe
+ * to join on
+ * @param[in] right_cols The table of right dataframe
+ * @param[in] right_join_cols The column indices of columns from the right dataframe
+ * to join on
+ * @param[out] gdf_column * left_indices If not nullptr, indices of rows from the left table that match rows in the right table
+ * @param[out] gdf_column * right_indices If not nullptr, indices of rows from the right table that match rows in the left table
+ * @param[in] l_common_name_join_ind Indices of left dataframe in join list which have same name as one on right dataframe join 
+ * list at same index in join list.  
+ * @param[in] r_common_name_join_ind Indices of right dataframe in join list which have same name as one on left dataframe join
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: This naming and description is confusing. I don't quite understand what it means.

Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: I am returning a vector which will have the indices of the column which have same name and are present in left_on and right_on set at same position.

example :

left_on ['a', 'b', 'c'] right_on['a', 'd','c']

the vectors will have [0, 2] and [0,2] as a and c are the common name at same position in both the join list, this will help to determine which have common name and requires only one column to be sent in result. 

I will try to name it in better way with better explanation.

File: cpp/include/cudf/join.hpp (hunk 4 above)
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: These indices might be required in C++ test cases where we don't know the order of the result we have got back from the join call.

File: cpp/src/join/joining.cu [hunk 6]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector<int> r_common_name_join_ind (num_merging_join_cols);
+
+    if (num_cols_to_join > 0)
+    {
+        CUDA_TRY (cudaMemcpy(left_j_cols.data(), join_cols.get_column(0)->data, 
+                             cudf::size_of(join_cols.get_column(0)->dtype)*num_cols_to_join , cudaMemcpyDeviceToHost));
+    }
+    if (num_merging_join_cols > 0)
+    {
+        CUDA_TRY (cudaMemcpy(l_common_name_join_ind.data(), merging_join_cols.get_column(0)->data,
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Something is wrong here. The memory for `l_common_name_join_ind` is of size `sizeof(int) * num_merging_join_cols`. But this `cudaMemcpy is copying based on the `cudf::sizeof()` of the column's dtype.  What if the dtype is larger than int? We will get a CUDA error. I don't understand why you are copying rows of a column into a vector of indices.

Comment (harrism) [reply cpp/src/join/joining.cu]: Same goes for all 3 of these `cudaMemcpy` calls.

File: cpp/src/join/joining.cu [hunk 7]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-        CUDA_TRY( cudaMemset(result_cols[i]->valid, 0, sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size)) );
-        CHECK_STREAM(0);
+    cudf::table result_left(join_size, cudf::column_dtypes(left_cols), cudf::column_dtype_infos(left_cols), true);
+    cudf::table result_right(join_size, rdtypes, rdtype_infos, true);
+    
+    std::vector<gdf_column*> result_lnonjoincol;
+    std::vector<gdf_column*> result_rnonjoincol;
+    std::vector<gdf_column*> result_joincol;
+
+    for (int lindex = 0; lindex < num_left_cols; ++lindex)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: This is another `set_difference`.

File: cpp/src/join/joining.cu [hunk 8]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
     }
-    for (int i = right_table_begin; i < result_num_cols; ++i) {
-        gdf_column_view(result_cols[i], nullptr, nullptr, join_size, rnonjoincol[i - right_table_begin]->dtype);
-        int col_width = cudf::byte_width(*(result_cols[i]));
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->data), col_width * join_size, 0) ); // TODO: non-default stream?
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->valid), sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size), 0) );
-        CUDA_TRY( cudaMemset(result_cols[i]->valid, 0, sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size)) );
-        CHECK_STREAM(0);
+        
+    // Accumalate the join-col
```
Comment (harrism) [inline cpp/src/join/joining.cu]:
```suggestion
    // Gather the join-col 
```

File: cpp/src/join/joining.cu [hunk 9]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+            == l_common_name_join_ind.end()) {
+            lnonjoincol.push_back(const_cast<gdf_column*>(left_cols.get_column(i)));
         }
     }
     for (int i = 0; i < num_right_cols; ++i) {
-        if (r_join_indices.find(i) == r_join_indices.end()) {
-            rnonjoincol.push_back(right_cols[i]);
+        if (std::find(r_common_name_join_ind.begin(), r_common_name_join_ind.end(), i) 
+            == r_common_name_join_ind.end()) {
+            rnonjoincol.push_back(const_cast<gdf_column*>(right_cols.get_column(i)));
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Same as above: set difference followed by gathering up the columns, types, and dtype_infos.

File: cpp/src/join/joining.cu [hunk 10]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-    for (int join_index = 0; join_index < num_cols_to_join; ++join_index) {
-        int i = left_table_end + join_index;
-        gdf_column_view(result_cols[i], nullptr, nullptr, join_size, left_cols[left_join_cols[join_index]]->dtype);
-        int col_width = cudf::byte_width(*(result_cols[i]));
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->data), col_width * join_size, 0) ); // TODO: non-default stream?
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->valid), sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size), 0) );
-        CUDA_TRY( cudaMemset(result_cols[i]->valid, 0, sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size)) );
-        CHECK_STREAM(0);
+    
+    // Accumalate the right non-join col
```
Comment (harrism) [inline cpp/src/join/joining.cu]:
```suggestion
    // Gather the right non-join col
```

File: cpp/src/join/joining.cu [hunk 11]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
 
       cudf::detail::gather(&left_source_table,
                            static_cast<index_type const *>(left_indices->data),
                            &left_destination_table, check_bounds);
+
       CHECK_STREAM(0);
       gdf_error update_err = nvcategory_gather_table(left_source_table,left_destination_table);
       CHECK_STREAM(0);
-      GDF_REQUIRE(update_err == GDF_SUCCESS,update_err);
+      CUDF_EXPECTS(update_err == GDF_SUCCESS, "nvcategory_gather_table throwing a GDF error");
```
Comment (harrism) [inline cpp/src/join/joining.cu]:
```suggestion
      CUDF_EXPECTS(update_err == GDF_SUCCESS, "nvcategory_gather_table error");
```

File: cpp/src/join/joining.cu [hunk 12]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
     }
-
+
```
Comment (harrism) [inline cpp/src/join/joining.cu]:
```suggestion

```

File: cpp/src/join/joining.cu [hunk 13]
```diff
@@ -242,149 +210,175 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
     // Construct the joined columns
-    if (0 != ljoincol.size()) {
-      cudf::table join_source_table(ljoincol.data(), ljoincol.size());
-      cudf::table join_destination_table(result_cols + left_table_end,
-                                         num_cols_to_join);
+    if (0 != ljoincols.num_columns() && num_merging_join_cols > 0) {
+
+      std::vector <gdf_column *> l_join;
+      std::vector <gdf_column *> r_join;
+      for (int join_ind = 0; join_ind < num_merging_join_cols; ++join_ind)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: I think this is a `set_intersection` followed by a gather...

File: cpp/src/join/joining.cu [hunk 14]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
-  GDF_REQUIRE(0 != num_cols_to_join, GDF_SUCCESS);
-  GDF_REQUIRE(nullptr != left_join_cols, GDF_DATASET_EMPTY);
-  GDF_REQUIRE(nullptr != right_join_cols, GDF_DATASET_EMPTY);
-  GDF_REQUIRE(nullptr != join_context, GDF_INVALID_API_CALL);
 
-  for(int column_index = 0; column_index  < num_left_cols; column_index++){
-    GDF_REQUIRE(left_cols[column_index]->dtype != GDF_invalid,GDF_UNSUPPORTED_DTYPE);
+  int num_left_cols = left_cols.num_columns();
+  int num_right_cols = right_cols.num_columns();
+  int num_cols_to_join = (join_cols.num_columns() > 0 ? join_cols.get_column(0)->size: 0);
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Here again you are assigning a number of rows to something called `num_cols`. Doesn't make sense.

File: cpp/src/join/joining.cu [hunk 15]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+  int num_merging_join_cols = (merging_join_cols.num_columns() > 0 ? merging_join_cols.get_column(0)->size: 0);
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Here too.

File: cpp/src/join/joining.cu [hunk 16]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+
+  std::vector<int> left_join_cols (num_cols_to_join);
+  std::vector<int> right_join_cols (num_cols_to_join);
+  std::vector<int> l_common_name_join_ind (num_merging_join_cols);
+  std::vector<int> r_common_name_join_ind (num_merging_join_cols);
+
+  if (num_cols_to_join > 0)
+  {
+      CUDA_TRY (cudaMemcpy((void *)left_join_cols.data(), (void *)join_cols.get_column(0)->data,
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Here again copying something that might have a larger size than the allocated size of the target vector.

File: cpp/src/join/joining.cu [hunk 17]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+      CUDA_TRY (cudaMemcpy((void *)left_join_cols.data(), (void *)join_cols.get_column(0)->data, 
+                           cudf::size_of(join_cols.get_column(0)->dtype)*num_cols_to_join, cudaMemcpyDeviceToHost));
+      CUDA_TRY (cudaMemcpy((void *)right_join_cols.data(), (void *)join_cols.get_column(1)->data, 
+                           cudf::size_of(join_cols.get_column(1)->dtype)*num_cols_to_join, cudaMemcpyDeviceToHost));
   }
-  for(int column_index = 0; column_index  < num_right_cols; column_index++){
-    GDF_REQUIRE(right_cols[column_index]->dtype != GDF_invalid,GDF_UNSUPPORTED_DTYPE);
+  if (num_merging_join_cols > 0)
+  {
+      CUDA_TRY (cudaMemcpy(l_common_name_join_ind.data(), merging_join_cols.get_column(0)->data,
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Also here (mismatched copy size).

File: cpp/src/join/joining.cu [hunk 18]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
-  // constructed output dataframe, or both
-  bool const construct_output_dataframe{nullptr != result_cols};
-  bool const return_output_indices{(nullptr != left_indices) and
-                                   (nullptr != right_indices)};
+  std::vector <gdf_column*> tmp_left_cols;
+  std::vector <gdf_column*> tmp_right_cols;
 
-  GDF_REQUIRE(construct_output_dataframe or return_output_indices,
-              GDF_INVALID_API_CALL);
+  for (int i=0; i < num_left_cols; ++i)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Why are you using a loop to do what a copy constructor does?
```suggestion
  std::vector <gdf_column*> tmp_left_cols(left_cols);
```

File: cpp/src/join/joining.cu [hunk 19]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+  {
+      tmp_left_cols.push_back(const_cast<gdf_column *> (left_cols.get_column(i)));
+  }
+
+  for (int i=0; i < num_right_cols; ++i)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: set_difference

File: cpp/src/join/joining.cu [hunk 20]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
-  auto const left_col_size = left_cols[0]->size;
-  auto const right_col_size = right_cols[0]->size;
+  cudf::table tmp_left_table = (tmp_left_cols.size()>0)? cudf::table (tmp_left_cols) : cudf::table{};
+  cudf::table tmp_right_table = (tmp_right_cols.size()>0)? cudf::table (tmp_right_cols) : cudf::table{};
+
+  CUDF_EXPECTS (0 != num_left_cols, "Left table is empty");
+  CUDF_EXPECTS (0 != num_right_cols, "Right table is empty");
+  CUDF_EXPECTS (nullptr != join_context, "Join context is invalid");
+
+  if (0 == num_cols_to_join)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Move this up to where you first compute num_cols_to_join. If it's zero, skip all those loops above and just return.

File: cpp/src/join/joining.cu [hunk 21]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+  {
+      return std::pair <cudf::table, cudf::table>(cudf::empty_like(tmp_left_table), cudf::empty_like(tmp_right_table));
+  }
+
+  for(int column_index = 0; column_index  < num_left_cols; column_index++){
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Replace these loops with one-liners:

```suggestion
  GDF_EXPECTS(std::none_of(cbegin(left_cols), cend(left_cols), [](auto col) { return col == GDF_invalid; }), "Unsupported left column dtype");
```

File: cpp/src/join/joining.cu [hunk 22]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
   if ((JoinType::INNER_JOIN == join_type) &&
       ((0 == left_col_size) || (0 == right_col_size))) {
-    return GDF_SUCCESS;
+      return std::pair <cudf::table, cudf::table>(cudf::empty_like(tmp_left_table), cudf::empty_like(tmp_right_table));
   }
 
 
   //if the inputs are nvcategory we need to make the dictionaries comparable
   bool at_least_one_category_column = false;
   for(int join_column_index = 0; join_column_index < num_cols_to_join; join_column_index++){
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Replace this with a one-liner using `bool at_least_one_category_column == std::any_of(...)`.

File: cpp/src/join/joining.cu [hunk 23]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
-    at_least_one_category_column |= left_cols[left_join_cols[join_column_index]]->dtype == GDF_STRING_CATEGORY;
+    at_least_one_category_column |= left_cols.get_column(left_join_cols[join_column_index])->dtype == GDF_STRING_CATEGORY;
   }
 
-  std::vector<gdf_column*> new_left_cols(left_cols, left_cols + num_left_cols);
-  std::vector<gdf_column*> new_right_cols(right_cols, right_cols + num_right_cols);
+  std::vector<gdf_column*> new_left_cols;
+  std::vector<gdf_column*> new_right_cols;
+
+  for (int i = 0; i < num_left_cols; i++)
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Use a copy constructor!

File: cpp/src/join/joining.cu (hunk 6 above)
Comment (harrism) [reply cpp/src/join/joining.cu]: Also, why are we copying column data back to host anyway? Is there some of this processing we could just do in a kernel?

File: cpp/src/join/joining.cu [hunk 24]
```diff
@@ -399,83 +393,121 @@ gdf_error construct_join_output_df(
...
+  }
+  for(int column_index = 0; column_index  < num_right_cols; column_index++){
+    CUDF_EXPECTS(right_cols.get_column(column_index)->dtype != GDF_invalid, "Unsupported Dtype in right column");
+  }
+
+  auto const left_col_size = left_cols.get_column(0)->size;
+  auto const right_col_size = right_cols.get_column(0)->size;
 
   // If the inputs are empty, immediately return
   if ((0 == left_col_size) && (0 == right_col_size)) {
```
Comment (harrism) [inline cpp/src/join/joining.cu]: I think these "immediate" returns should move earlier in the function...

File: cpp/src/join/joining.cu [hunk 25]
```diff
@@ -548,46 +574,48 @@ gdf_error join_call_compute_df(
...
         construct_join_output_df<join_type, index_type>(
-            ljoincol, rjoincol,
-            left_cols, num_left_cols, left_join_cols,
-            right_cols, num_right_cols, right_join_cols,
-            num_cols_to_join, result_num_cols, result_cols,
+            ljoin_cols, rjoin_cols,
+            updated_left_cols, updated_right_cols, 
+            join_cols, merging_join_cols, 
             left_index_out, right_index_out);
     CHECK_STREAM(0);
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Just check the stream once at the end.
```suggestion
```

File: cpp/src/join/joining.cu [hunk 26]
```diff
@@ -604,91 +632,55 @@ gdf_error join_call_compute_df(
     }
 
     CHECK_STREAM(0);
-
-
-    return df_err;
+
```
Comment (harrism) [inline cpp/src/join/joining.cu]: Can't comment on them since they are collapsed, but can you eliminate some of the unnecessary repeated blank lines above?

File: cpp/include/cudf/join.hpp [hunk 27]
```diff
@@ -0,0 +1,126 @@
...
+ * @param[out] gdf_column * left_indices If not nullptr, indices of rows from the left table that match rows in the right table
+ * @param[out] gdf_column * right_indices If not nullptr, indices of rows from the right table that match rows in the left table
+ * @param[in] l_common_name_join_ind Indices of left dataframe in join list which have same name as one on right dataframe join 
+ * list at same index in join list.  
+ * @param[in] r_common_name_join_ind Indices of right dataframe in join list which have same name as one on left dataframe join 
+ * list at same index in join list.  
+ * @param[in] join_context The context to use to control how the join is performed,e.g.,
+ * sort vs hash based implementation
+ * 
+ * @returns If Success, pair of left and right table which are merged
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: When you have two column with same name, they end-up being only one column  in the result like,
      TableA    a   b
                      1  2

      TableB     a   c
                      1   3
 when joined with respect to column a, the resulting table would be

       Result  a   b  c
                    1  2  3

File: cpp/include/cudf/join.hpp [hunk 28]
```diff
@@ -0,0 +1,101 @@
...
+ * specified columns of two dataframes (left, right)
+ * If join_context->flag_method is set to GDF_SORT then the null_count of the
+ * columns must be set to 0 otherwise a GDF_VALIDITY_UNSUPPORTED error is
+ * returned.
+ *
+ * @param[in] left_cols The table of left dataframe
+ * @param[in] right_cols The table of right dataframe
+ * @param[in] join_cols The table containing indices of left and right join columns
+ * respectively
+ * @param[in] merging_join_cols The table containing indices of left and right
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: Yes, two columns with each column containing indices provided in left_on and right_on for join_cols and for mergin_join_cols with same name.

File: cpp/src/copying/copy.cpp [hunk 29]
```diff
@@ -95,6 +95,8 @@ gdf_column copy(gdf_column const& input, cudaStream_t stream)
 }
 
 table empty_like(table const& t) {
+  if (t.num_columns() == 0)
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/copying/copy.cpp]: I think so, else it might crash.

File: cpp/src/join/joining.cu [hunk 30]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
 }
 
 /* --------------------------------------------------------------------------*/
 /** 
  * @brief  Computes the join operation between two sets of columns
  * 
  * @param[in] num_cols The number of columns to join
- * @param[in] leftcol The left set of columns to join
- * @param[in] rightcol The right set of columns to join
+ * @param[in] leftcols  cudf table of left columns to join
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: Yes, I have to update it.

File: cpp/src/join/joining.cu [hunk 31]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
  *                         whether to perform a hash or sort based join
  * @tparam join_type The type of join to be performed
  * 
- * @returns GDF_SUCCESS upon succesfull compute, otherwise returns appropriate error code
+ * @returns void
  */
 /* ----------------------------------------------------------------------------*/
 template <JoinType join_type>
-gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
+void join_call( int num_cols, cudf::table const& leftcols, cudf::table const& rightcols,
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: My bad, I will update

File: cpp/src/join/joining.cu [hunk 32]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
                      gdf_column *left_result, gdf_column *right_result,
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: As we are not continuing with the gdf_errors, I thought it would be better to update the functions in earlier stage.

**Comment by kkraus14** [comment]
Moved to 0.10.

File: cpp/include/cudf/join.hpp [hunk 33]
```diff
@@ -0,0 +1,101 @@
...
+ * columns must be set to 0 otherwise a GDF_VALIDITY_UNSUPPORTED error is
+ * returned.
+ * 
+ * @param[in] left_cols The table of left dataframe
+ * @param[in] right_cols The table of right dataframe
+ * @param[in] join_cols The table containing indices of left and right join columns
+ * respectively
+ * @param[in] merging_join_cols The table containing indices of left and right
+ * join columns which have same name respectively and which will merge into a single column
+ * @param[out] out_indices The table containing joined indices of left and right table
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: It is not being used in python side and eventually planning to remove it, so it currently kept as an optional parameter.

File: cpp/src/join/joining.cu [hunk 34]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
                      gdf_context *join_context)
 {
-  GDF_REQUIRE( 0 != num_cols, GDF_DATASET_EMPTY);
-  GDF_REQUIRE( nullptr != leftcol, GDF_DATASET_EMPTY);
-  GDF_REQUIRE( nullptr != rightcol, GDF_DATASET_EMPTY);
-  GDF_REQUIRE( nullptr != join_context, GDF_INVALID_API_CALL);
+  CUDF_EXPECTS( 0 != num_cols, "Dataset is empty");
+  CUDF_EXPECTS( 0 != leftcols.num_columns(), "Left Dataset is empty");
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: This will just compute indices for the joined columns and nothing else.

So, if the there were empty input, it would be returned earlier in the function call. 

This check is just to ensure that there will not be any coding issues in the main function.

File: cpp/src/join/joining.cu (hunk 32 above)
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: Did you mean pair of tables ?

File: cpp/src/join/joining.cu [hunk 35]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
-  GDF_REQUIRE( left_col_size < MAX_JOIN_SIZE, GDF_COLUMN_SIZE_TOO_BIG);
-  GDF_REQUIRE( right_col_size < MAX_JOIN_SIZE, GDF_COLUMN_SIZE_TOO_BIG);
+  CUDF_EXPECTS( left_col_size < MAX_JOIN_SIZE, "left column size is too big");
+  CUDF_EXPECTS( right_col_size < MAX_JOIN_SIZE, "right column size is too big");
 
 
   // If both frames are empty, return immediately
   if((0 == left_col_size ) && (0 == right_col_size)) {
-    return GDF_SUCCESS;
+    return;
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: The index are only the parameters that are getting updated, and there are already updated with basic gdf_column values, so don't have to update anything.

File: cpp/src/join/joining.cu [hunk 36]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
   }
 
   // If left join and the left table is empty, return immediately
   if( (JoinType::LEFT_JOIN == join_type) && (0 == left_col_size)){
-    return GDF_SUCCESS;
+    return;
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: The index are only the parameters that are getting updated, and there are already updated with basic gdf_column values, so don't have to update anything.

File: cpp/src/join/joining.cu [hunk 37]
```diff
@@ -153,87 +126,82 @@ gdf_error trivial_full_join(
...
   }
 
   // If Inner Join and either table is empty, return immediately
   if( (JoinType::INNER_JOIN == join_type) && 
       ((0 == left_col_size) || (0 == right_col_size)) ){
-    return GDF_SUCCESS;
+    return;
```
[the remark this answers is not in the document]
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: The index are only the parameters that are getting updated, and there are already updated with basic gdf_column values, so don't have to update anything.

File: cpp/src/join/joining.cu (hunk 13 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: The indices of left and right indices are kind of pairs and need not be in order, so set_intersection will not work.

File: cpp/src/join/joining.cu (hunk 23 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: Can't use a copy constructor as the the table is of type const and vector is variable.

File: cpp/src/join/joining.cu (hunk 6 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: As we need them for looping and other stuff throughout the function, using kernel will not be efficient.

**Comment by rgsl888prabhu** [comment]
@jrhemstad @harrism

File: cpp/src/join/joining.cu (hunk 32 above)
[the remark this answers is not in the document]
Comment (harrism) [reply cpp/src/join/joining.cu]: I mean this function is void rather than returning its results, like the public API does.

File: cpp/include/cudf/join.hpp [hunk 38]
```diff
@@ -0,0 +1,131 @@
...
+
+namespace cudf {
+// joins
+
+/** 
+ * @brief  Performs an inner join on the specified columns of two
+ * dataframes (left, right)
+ *
+ * If join_context->flag_method is set to GDF_SORT then the null_count of the
+ * columns must be set to 0 otherwise @throws GDF Validity is unsupported by sort_join.
```
Comment (harrism) [inline cpp/include/cudf/join.hpp]: I think @throws should appear on its own line, and should give the typename of the exception thrown.

File: cpp/include/cudf/join.hpp (hunk 27 above)
[the remark this answers is not in the document]
Comment (harrism) [reply cpp/include/cudf/join.hpp]: Sorry to ask you a rhetorical question. My point is that the documentation should be unambiguous. I think here "merged" means "joined". So I think you shouldn't introduce new terms without definition.

File: cpp/include/cudf/join.hpp [hunk 39]
```diff
@@ -0,0 +1,131 @@
...
+ * @brief  Performs a left join (also known as left outer join) on the
+ * specified columns of two dataframes (left, right)
+ *
+ * If join_context->flag_method is set to GDF_SORT then the null_count of the
+ * columns must be set to 0 otherwise @throws GDF Validity is unsupported by sort_join.
+ * 
+ * @example TableA a:{0,1,2}
+ *          TableB b:{1,2,3}, c:{4,5,6} And TableB joins TableA 
+ *          on column 'a' with column 'b'.
+ * The result would be Table-res a:{0, 1, 2}, b:{nan, 1, 2}, c:{nan, 4, 5}
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: NaN and NULL are not the same thing. 
```suggestion
 * The result would be Table-res a:{0, 1, 2}, b:{NULL, 1, 2}, c:{NULL, 4, 5}
```

File: cpp/include/cudf/join.hpp [hunk 40]
```diff
@@ -0,0 +1,131 @@
...
+ * joined indices of left and right table 
+ * @param[in] join_context The context to use to control how 
+ * the join is performed,e.g., sort vs hash based implementation
+ * 
+ * @returns If Success, pair of left and right table which are merged 
+ */
+std::pair<cudf::table, cudf::table> inner_join(
+                         cudf::table const& left_table,
+                         cudf::table const& right_table,
+                         cudf::table const& join_ind_table,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: This should accept separate tables for the "key" columns of the left and right tables. There's also no need to include "table" in the name, that's already well-known from the type. 

```
std::pair<cudf::table, cudf::table> inner_join(
                         cudf::table const& left,
                         cudf::table const& left_on,
                         cudf::table const& right,
                         cudf::table const& right_on,
```

File: cpp/include/cudf/join.hpp [hunk 41]
```diff
@@ -0,0 +1,131 @@
...
+                         cudf::table const& merging_join_ind_table,
+                         cudf::table const& out_index_table,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: `out_index` is not an input, so it should not be passed by `const&`. Please refer to https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/docs/TRANSITIONGUIDE.md for how output parameters should be passed.

File: cpp/include/cudf/join.hpp [hunk 42]
```diff
@@ -0,0 +1,131 @@
...
+ *          on column 'a' with column 'b'.
+ * The result would be Table-res a:{1, 2}, b:{1, 2}, c:{4, 5}
+ * Result is intersection of column 'a' and column 'b'
+ *
+ * @param[in] left_table The left dataframe
+ * @param[in] right_table The right dataframe
+ * @param[in] join_ind_table The table containing two columns,
+ * first column - indices of left table provided for join
+ * second column - indices of right table provided for join
+ * @param[in] merging_join_ind_table Similar to join_ind_table,
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: This still isn't clear. Perhaps it needs an example.

Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: This will also contain the left and right indices in two columns, should I also split it in two tables ?

Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: And for example of what it has,

`
import cudf
import pandas as pd

df1 = cudf.DataFrame({'a':[0,1,2.0,3,4,5, 9], 'c':[0,2,3,5,7,8,9], 'd':range(7)})
df2 = cudf.DataFrame({'a':[12,5.0,3,9,5], 'c':range(5), 'e':range(5)})

res = df1.merge(df2, how='left', left_on=['a', 'd'], right_on=['a', 'e'])
print(res)
`

In this case, this table will have two columns [0], [0], which indicate the series with name 'a' in both dataframe and are being referenced to join at same index in 'on', and they will end up being single column in result.

Comment (jrhemstad) [reply cpp/include/cudf/join.hpp]: Okay, this definitely should not be a `table`.

It should be a `std::vector<std::pair>` that contains the column indices from `left_on` and `right_on` that are the same and will only materialize a single result column.

Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: ok

Comment (jrhemstad) [reply cpp/include/cudf/join.hpp]: That's much less intuitive and it decouples information that should be linked. We want to group together the relevant information of a column index from the `left_on` and `right_on` tables that are the same. This is what a `vector` of index `pair`s  does this. A `pair` of `vector`s requires accessing the same element from from disjoint vectors, and the information is no longer coupled.

File: CHANGELOG.md [hunk 43]
```diff
@@ -7,6 +7,7 @@
 ## Improvements
 
 ## Bug Fixes
+- PR #2496 Fix improper merge of two dataframes when names differ
```
Comment (kkraus14) [inline CHANGELOG.md]: One blank line between headers and changelog entries
```suggestion

- PR #2496 Fix improper merge of two dataframes when names differ
```

File: python/cudf/cudf/bindings/join.pyx [hunk 44]
```diff
@@ -229,11 +200,10 @@ cpdef join(col_lhs, col_rhs, left_on, right_on, how, method):
                 valids.append(None)
```
Comment (kkraus14) [inline python/cudf/cudf/bindings/join.pyx]: @rgsl888prabhu do you mind cleaning up this section of the code while we're changing things? We have helper functions to convert gdf_column or cudf::table objects into cudf Python objects that should be used here.

File: cpp/include/cudf/join.hpp [hunk 45]
```diff
@@ -0,0 +1,144 @@
...
+ * The result would be Table-res a:{1, 2}, b:{1, 2}
+ * Result is intersection of column 'a' from A and column 'a' from B
+ *
+ * @throws cudf::logic_error 
+ * "GDF Validity is unsupported" by sort_join, if join_context->flag_method = GDF_SORT
+ * and null_count is not set to 0.
+ *
+ * @param[in] left The left dataframe
+ * @param[in] right The right dataframe
+ * @param[in] left_on The column indices from left dataframe
```
[the remark this answers is not in the document]
Comment (harrism) [reply cpp/include/cudf/join.hpp]: No apostrophe in columns. :)

File: cpp/src/join/joining.cu (hunk 11 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: Oh, I had missed it.

**Comment by rgsl888prabhu** [comment]
@jrhemstad

**Comment by rgsl888prabhu** [comment]
@jrhemstad

File: cpp/src/join/joining.cu [hunk 46]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+ * If either `left_indices[i]` or `right_indices[i]` is negative, then the i
+ * contributions from `left` or `right` will be NULL.
+ *
+ * @throws cudf::logic_error
+ * If call to nvcategory_gather_table fails
+ * 
+ * @param[in] left   The left table
+ * @param[in] right  the right table
+ * @param[in] columns_in_common is a vector of pairs of column indices
+ * from tables `left` and `right` respectively, which are supposed to be joined onto,
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
 * from tables `left` and `right` respectively, 
```

File: cpp/src/join/joining.cu [hunk 47]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+ * that are "in common". For "common" columns, only a single output column will
+ * be produced. Depending on type of join, the values will be gathered.
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
 * be produced. For an inner or left join, the result will be gathered from the column in `left. For a full join, the result will be gathered from both common columns in `left` and `right`.
```

File: cpp/src/join/joining.cu [hunk 48]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+ * @param[in] left_indices Row indices from `left` to gather. If any row index
+ * is out of bounds, the contribution in the output `table` will be NULL.
+ * @param[in] right_indicess  Row indices from `right` to gather. If any row
+ * index is out of bounds, the contribution in the output `table` will be NULL.
+ * 
+ * @returns Result of joining `left` and `right` tables as per `left_indices` and
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
 * @returns table` containing the concatenation of rows from `left` and `right` specified by `left_indices` and `right_indices`, respectively. For any columns indicated by `columns_in_common`, only the corresponding column in `left` will be included in the result. 
```

File: cpp/src/table/legacy/table.cpp [hunk 49]
```diff
@@ -27,14 +27,17 @@
...
 table::table(std::vector<gdf_column*> const& cols) : _columns{cols} {
-  CUDF_EXPECTS(nullptr != cols[0], "Null input column");
-  gdf_size_type num_rows = cols[0]->size;
-
-  std::for_each(_columns.begin(), _columns.end(),
-                [this, num_rows](gdf_column* col) {
-                  CUDF_EXPECTS(nullptr != col, "Null input column");
-                  CUDF_EXPECTS(num_rows == col->size, "Column size mismatch");
-                });
+  if (cols.size() != 0)
```
Comment (jrhemstad) [inline cpp/src/table/legacy/table.cpp]: You'll want to update your PR with the latest 0.10 branch which added throwing an exception if you try and construct a table with 0 columns.

File: cpp/include/cudf/join.hpp [hunk 50]
```diff
@@ -0,0 +1,166 @@
...
+ * @param[in] columns_in_common is a vector of pairs of column indices into
+ * `left_on` and `right_on`, respectively, that are "in common". For "common"
+ * columns, only a single output column will be produced, which is gathered
+ * from `left_on` columns. Else, for every column in `left_on` and `right_on`,
+ * an output column will be produced.
+ *
+ * @param[out] * @returns joined_indices Optional, if not `nullptr`, on return, will
+ * contain two non-nullable, `GDF_INT32` columns containing the indices of
+ * matching rows between `left_on` and `right_on`. The first column corresponds to
+ * rows in `left_on`, and the second to `right_on`. A value of `-1` in the second column
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: It's not possible to have non-matches in an inner join.
```suggestion
 * rows in `left_on`, and the second to `right_on`. 
```

File: cpp/include/cudf/join.hpp [hunk 51]
```diff
@@ -0,0 +1,166 @@
...
+ * indicates that the corresponding row in `left_on` has no match. It is the caller's
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]:
```suggestion
 *  It is the caller's
```

File: cpp/include/cudf/join.hpp [hunk 52]
```diff
@@ -0,0 +1,166 @@
...
+ * responsibility to free these columns.
+ * @param[in] join_context The context to use to control how
+ * the join is performed,e.g., sort vs hash based implementation
+ *
+ * @returns Result of joining `left` and `right` tables on the columns
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: The order of the resulting columns isn't clear. There are 3 kinds of columns:

- "on" columns
- columns in common
- non-"on" columns

It's not clear to me what the order of these will be. Is the original order of left and right preserved (excluding any "columns in common" which will be absent from right)?

File: cpp/include/cudf/join.hpp [hunk 53]
```diff
@@ -0,0 +1,166 @@
...
+                         gdf_context *join_context);
+
+/** 
+ * @brief  Performs a full join (also known as full outer join) on the
+ * specified columns of two tables (left, right)
+ * 
+ * @example TableA a:{0,1,2}
+ *          TableB b:{1,2,3}, a:{1,2,5} And column 'a' of TableB joins
+ *          column 'a' of TableA.
+ * The result would be Table-res a:{0, 1, 2, 5}, b:{NULL, 1, 2, 3}
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: Modify the example to show that NULL values can occur in both the left/right columns.

File: cpp/include/cudf/join.hpp [hunk 54]
```diff
@@ -0,0 +1,166 @@
...
+ * @param[in] columns_in_common is a vector of pairs of column indices into
+ * `left_on` and `right_on`, respectively, that are "in common". For "common"
+ * columns, only a single output column will be produced, which is gathered
+ * from respective columns in `left_on` and `right_on`. Else, for every column in
+ * `left_on` and `right_on`, an output column will be produced.
+ *
+ * @param[out] * @returns joined_indices Optional, if not `nullptr`, on return, will
+ * contain two non-nullable, `GDF_INT32` columns containing the indices of
+ * matching rows between `left_on` and `right_on`. The first column corresponds to
+ * rows in `left_on`, and the second to `right_on`. A value of `-1` in the second column
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: For a full join, -1 values can appear in the indices corresponding to both the left and right table, indicating non-matches.

File: cpp/src/join/joining.cu [hunk 55]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-    for (int i = 0; i < num_left_cols; ++i) {
-        if (l_join_indices.find(i) == l_join_indices.end()) {
-            lnonjoincol.push_back(left_cols[i]);
-        }
-    }
-    for (int i = 0; i < num_right_cols; ++i) {
-        if (r_join_indices.find(i) == r_join_indices.end()) {
-            rnonjoincol.push_back(right_cols[i]);
-        }
+    std::vector<gdf_size_type> left_column_indices(left.num_columns());
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: It's easier to understand code when you declare variables immediately before they are used. When they are bunched together like this, it's more difficult to see when and how they are used.

File: cpp/src/join/joining.cu [hunk 56]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector<gdf_size_type> right_column_indices(right.num_columns());
+    std::vector<gdf_size_type> left_columns_in_common (columns_in_common.size());
+    std::vector<gdf_size_type> right_columns_in_common (columns_in_common.size());
+    std::vector<gdf_size_type> left_nonjoin_indices (left.num_columns() - left_columns_in_common.size());
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: Referring to these as "nonjoin_indices" doesn't seem to match with how they are being used. Instead it seems to be the indices of all non-common columns.

File: cpp/src/join/joining.cu [hunk 57]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-        gdf_column* col = left_cols[left_join_cols[join_index]];
-        gdf_column_view_augmented(result_cols[i], nullptr, nullptr, join_size,
-                                  col->dtype, 0, col->dtype_info, col->col_name);
-        int col_width = cudf::byte_width(*(result_cols[i]));
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->data), col_width * join_size, 0) ); // TODO: non-default stream?
-        RMM_TRY( RMM_ALLOC((void**)&(result_cols[i]->valid), sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size), 0) );
-        CUDA_TRY( cudaMemset(result_cols[i]->valid, 0, sizeof(gdf_valid_type)*gdf_valid_allocation_size(join_size)) );
-        CHECK_STREAM(0);
+    // Update first set of type and type infos from left
+    std::vector <gdf_dtype> rdtypes = cudf::column_dtypes(left);
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: Ambiguous abbreviation. Don't put spaces between a type and it's template arguments. 
```suggestion
    std::vector<gdf_dtype> result_dtypes = cudf::column_dtypes(left);
```

File: cpp/src/join/joining.cu [hunk 58]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector <gdf_dtype_extra_info> rdtype_infos = cudf::column_dtype_infos(left);
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
    std::vector<gdf_dtype_extra_info> result_dtype_infos = cudf::column_dtype_infos(left);
```

File: cpp/src/join/joining.cu (hunk 56 above)
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: There's a lot of redundancy here that could be eliminated by a function:
```
auto non_common_column_indices(
    gdf_size_type num_columns,
    std::vector<gdf_size_type> const& common_column_indices) {
  CUDF_EXPECTS(common_column_indices.size() <= num_columns,
               "Too many columns in common");
  std::vector<gdf_size_type> all_column_indices(num_columns);
  std::iota(std::begin(all_column_indices), std::end(all_column_indices), 0);
  std::vector<gdf_size_type> sorted_common_column_indices{
      common_column_indices};
  std::sort(std::begin(sorted_common_column_indices),
            std::end(sorted_common_column_indices));
  std::vector<gdf_size_type> non_common_indices(num_columns -
                                                common_column_indices.size());
  std::set_difference(std::cbegin(all_column_indices),
                      std::cend(all_column_indices),
                      std::cbegin(sorted_common_column_indices),
                      std::cend(sorted_common_column_indices), std::begin(non_common_column_indices));
   return non_common_indices;
}
```

File: cpp/src/join/joining.cu [hunk 59]
```diff
@@ -253,260 +220,345 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector<gdf_column*> left_nonjoin_column(left_nonjoin_indices.size());
+    std::vector<gdf_column*> right_nonjoin_column;
+
+    // Gathering all the left table columns not in joining indices 
+    std::transform(std::cbegin(left_nonjoin_indices), std::cend(left_nonjoin_indices),
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: A function in `table` to return a table of only the specified columns would also eliminate a lot of redundancy:
```
/**---------------------------------------------------------------------------*
 * @brief Returns a new `table` containing the set of specified columns.
 * 
 * @param column_indices Indices of the desired columns
 * @return table New table containing only the desired columns
*---------------------------------------------------------------------------**/
table table::select(std::vector<gdf_size_type> const& column_indices){
    CUDF_EXPECTS(column_indices.size() < num_columns(), "Requested too many columns.");
    std::vector<gdf_column*> desired_columns;
    for(auto index : column_indices){
        desired_columns.push_back(get_column(index));
    }
    return table{desired_columns};
}
```

File: cpp/include/cudf/join.hpp (hunk 52 above)
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: Yes

File: cpp/src/join/joining.cu (hunk 59 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: @jrhemstad is this already available or should I introduce? I couldn't find it in latest 0.10

Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: Should I also introduce an offset variable which can offset the index ?

File: cpp/include/cudf/join.hpp (hunk 52 above)
Comment (jrhemstad) [reply cpp/include/cudf/join.hpp]: Can you update the documentation to say that?

File: cpp/src/join/joining.cu (hunk 59 above)
Comment (jrhemstad) [reply cpp/src/join/joining.cu]: `table::select` doesn't exist, I just prototyped it for the review.

>Should I also introduce an offset variable which can offset the index ?

Is this necessary? Seems to complicate an otherwise simple function. I'd think the user should be able to easily construct the `column_indices` with the desired columns.

File: cpp/include/cudf/join.hpp (hunk 52 above)
Comment (rgsl888prabhu) [reply cpp/include/cudf/join.hpp]: ok

File: cpp/src/join/joining.cu (hunk 59 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: In my case for the `result` table, the right table will have a shist in index due to concatinattion, so I have to update the column indices by that offset to use this function, else do it using transform. If we have an offset, we can use offset to provide this information. So I was just curious whether it will have any additional benefits.

Comment (jrhemstad) [reply cpp/src/join/joining.cu]: I think its more appropriate to update the indices via a `transform` before passing them into `select` rather than adding an `offset`.

Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: ok

File: cpp/src/table/legacy/table.cpp [hunk 60]
```diff
@@ -97,6 +97,24 @@ void table::destroy(void) {
...
+        desired_columns.push_back(get_column(index));
+    }
+    return table{desired_columns};
+}
+
+table table::select(std::vector<gdf_size_type> const& column_indices) const {
+    CUDF_EXPECTS(column_indices.size() <= num_columns(), "Requested too many columns.");
+    std::vector<gdf_column*> desired_columns;
+    for(auto index : column_indices){
+        desired_columns.push_back(const_cast<gdf_column*>(get_column(index)));
```
Comment (jrhemstad) [inline cpp/src/table/legacy/table.cpp]: I realize if we just access `_columns` directly, then there's no need for a `const_cast`. Furthermore, there's no need for a `const` and `non-const` version of `select`, we can just have the single `const` version.

File: cpp/include/cudf/legacy/table.hpp [hunk 61]
```diff
@@ -180,6 +197,16 @@ std::vector<gdf_dtype_extra_info> column_dtype_infos(cudf::table const& table);
...
 
+/**---------------------------------------------------------------------------*
+ * @brief `table1` and `table2` are concatenated to return single table
+ *
+ * @param table1 The table to be concatenated with `table2`
+ * @param table2 The table to be concatenated with `table1`
+ * @return A single table having all the columns from `table1` and `table2`
+ * respectively in the same order.
+ *---------------------------------------------------------------------------**/
+table concat_tables(cudf::table const& table1, cudf::table const&table2);
```
Comment (jrhemstad) [inline cpp/include/cudf/legacy/table.hpp]:
```suggestion
table concat(cudf::table const& lhs, cudf::table const& rhs);
```

File: cpp/src/table/legacy/table.cpp [hunk 62]
```diff
@@ -116,4 +137,22 @@ bool has_nulls(cudf::table const& table) {
   });
 }
 
+table concat_tables(cudf::table const& table1, cudf::table const&table2) {
+    if ((table1.num_columns() == 0) and (table2.num_columns() == 0))
```
Comment (jrhemstad) [inline cpp/src/table/legacy/table.cpp]: I don't think these explicit `if` checks are necessary. With the way you construct the vector below, you'll automatically get the same result.

File: cpp/src/join/joining.cu [hunk 63]
```diff
@@ -253,260 +220,317 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector<gdf_size_type> left_columns_in_common (columns_in_common.size());
+    std::vector<gdf_size_type> right_columns_in_common (columns_in_common.size());
+
+    for (unsigned int i = 0; i < columns_in_common.size(); ++i)
+    {
+        left_columns_in_common[i] = columns_in_common[i].first;
+        right_columns_in_common[i] = columns_in_common[i].second;
     }
-    //TODO : Invalid api
+    std::vector <gdf_size_type> tmp_left_join_indices = left_columns_in_common;
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]: These don't look like they're used anymore. 
```suggestion
```

File: cpp/src/join/joining.cu [hunk 64]
```diff
@@ -253,260 +220,317 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+    std::vector <gdf_size_type> tmp_right_join_indices = right_columns_in_common;
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
```

File: cpp/src/join/joining.cu [hunk 65]
```diff
@@ -253,260 +220,317 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-    // -1, requiring bounds checking when gathering the result table
+    cudf::table result(join_size, result_dtypes, result_dtype_infos, true);
     bool const check_bounds{ join_type != JoinType::INNER_JOIN };
 
     // Construct the left columns
-    if (0 != lnonjoincol.size()) {
-      cudf::table left_source_table(lnonjoincol.data(), lnonjoincol.size());
-      cudf::table left_destination_table(result_cols,
-                                         num_left_cols - num_cols_to_join);
+    if (0 != left_non_common_indices.size()) {
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
    if (not left_non_common_indices.empty()) {
```

File: cpp/src/join/joining.cu [hunk 66]
```diff
@@ -253,260 +220,317 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-      GDF_REQUIRE(update_err == GDF_SUCCESS,update_err);
+      CUDF_EXPECTS(update_err == GDF_SUCCESS, "nvcategory_gather_table error");
     }
 
     // Construct the right columns
-    if (0 != rnonjoincol.size()) {
-      cudf::table right_source_table(rnonjoincol.data(), rnonjoincol.size());
-      cudf::table right_destination_table(result_cols + right_table_begin,
-                                          num_right_cols - num_cols_to_join);
+    if (0 != right_non_common_indices.size()) {
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
    if (not right_non_common_indices.empty()) {
```

File: cpp/src/join/joining.cu [hunk 67]
```diff
@@ -253,260 +220,317 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-      GDF_REQUIRE(update_err == GDF_SUCCESS,update_err);
+      CUDF_EXPECTS(update_err == GDF_SUCCESS, "nvcategory_gather_table error");
     }
 
     // Construct the joined columns
-    if (0 != ljoincol.size()) {
-      cudf::table join_source_table(ljoincol.data(), ljoincol.size());
-      cudf::table join_destination_table(result_cols + left_table_end,
-                                         num_cols_to_join);
+    if (columns_in_common.size() > 0) {
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
    if (not columns_in_common.empty()) {
```

File: cpp/src/table/legacy/table.cpp (hunk 62 above)
Comment (rgsl888prabhu) [reply cpp/src/table/legacy/table.cpp]: This will help me not to come across that exception in table constructor and will also reduce couple of function calls.

Comment (jrhemstad) [reply cpp/src/table/legacy/table.cpp]: I'm not concerned about the overhead of a function call. It would greatly simplify the function to remove these. 

I think we should fix the table constructor.

Comment (rgsl888prabhu) [reply cpp/src/table/legacy/table.cpp]: ok, I will modify the constructor in the next push.

File: cpp/src/table/legacy/table.cpp [hunk 68]
```diff
@@ -27,12 +27,12 @@
 namespace cudf {
 
 table::table(std::vector<gdf_column*> const& cols) : _columns{cols} {
-  CUDF_EXPECTS(_columns.size() != 0, "Cannot construct table with zero columns");
-  std::for_each(_columns.begin(), _columns.end(),
-                [this](gdf_column* col) {
-                  CUDF_EXPECTS(nullptr != col, "Null input column");
-                  CUDF_EXPECTS(_columns.front()->size == col->size, "Column size mismatch");
-                });
+  if (not cols.empty())
```
Comment (jrhemstad) [inline cpp/src/table/legacy/table.cpp]: The way the `for_each` is written, there's no need for this check. It will automatically handle empty vectors.

File: cpp/include/cudf/join.hpp [hunk 69]
```diff
@@ -0,0 +1,160 @@
...
+namespace cudf {
+// joins
+
+/** 
+ * @brief  Performs an inner join on the specified columns of two
+ * tables (left, right)
+ *
+ * @example TableA a:{0,1,2}
+ *          TableB b:{1,2,3}, a:{1,2,5} And column 'a' from TableB
+ *          joins column 'a' from TableA.
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]:
```suggestion
 *          columns_in_common: { {0, 0} }
```

File: cpp/include/cudf/join.hpp [hunk 70]
```diff
@@ -0,0 +1,160 @@
...
+
+namespace cudf {
+// joins
+
+/** 
+ * @brief  Performs an inner join on the specified columns of two
+ * tables (left, right)
+ *
+ * @example TableA a:{0,1,2}
+ *          TableB b:{1,2,3}, a:{1,2,5} And column 'a' from TableB
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: It's best to give examples as concretely as possible using the syntax of the API. Use this example to update the other Join documentation. 
```suggestion
 *          TableB b:{1,2,3}, a:{1,2,5} 
 *          left_on: {0}
 *          right_on: {1}
```

File: cpp/include/cudf/join.hpp [hunk 71]
```diff
@@ -0,0 +1,160 @@
...
+ *          joins column 'a' from TableA.
+ * The result would be Table-res a:{1, 2}, b:{1, 2}
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]:
```suggestion
 * Result: { a: {1, 2}, b: {1, 2} }
```

File: cpp/include/cudf/join.hpp [hunk 72]
```diff
@@ -0,0 +1,160 @@
...
+ * Result is intersection of column 'a' from A and column 'a' from B
```
Comment (jrhemstad) [inline cpp/include/cudf/join.hpp]: It's not really an intersection since a value will be repeated in the result for every match. 
```suggestion
```

File: cpp/include/cudf/join.hpp (hunk 69 above)
Comment (jrhemstad) [reply cpp/include/cudf/join.hpp]: It would probably be good to also show what the result would be if `columns_in_common` were empty.

File: cpp/include/cudf/legacy/table.hpp [hunk 73]
```diff
@@ -180,6 +188,16 @@ std::vector<gdf_dtype_extra_info> column_dtype_infos(cudf::table const& table);
...
 
+/**---------------------------------------------------------------------------*
+ * @brief `table1` and `table2` are concatenated to return single table
+ *
+ * @param table1 The table to be concatenated with `table2`
+ * @param table2 The table to be concatenated with `table1`
+ * @return A single table having all the columns from `table1` and `table2`
+ * respectively in the same order.
+ *---------------------------------------------------------------------------**/
+table concat(cudf::table const& table1, cudf::table const&table2);
```
Comment (jrhemstad) [inline cpp/include/cudf/legacy/table.hpp]: Needs tests.

File: cpp/include/cudf/legacy/table.hpp [hunk 74]
```diff
@@ -137,12 +137,20 @@ struct table {
...
     return 0;
   }
 
+  /**---------------------------------------------------------------------------*
+   * @brief Returns a new `table` containing the set of specified columns.
+   *
+   * @param column_indices Indices of the desired columns
+   * @return table New table containing only the desired columns
+   *---------------------------------------------------------------------------**/
+  table select(std::vector<gdf_size_type> const& column_indices) const;
```
Comment (jrhemstad) [inline cpp/include/cudf/legacy/table.hpp]: Needs tests.

File: cpp/src/table/legacy/table.cpp [hunk 75]
```diff
@@ -92,6 +92,16 @@ void table::destroy(void) {
   }
 }
 
+table table::select(std::vector<gdf_size_type> const& column_indices) const {
+    CUDF_EXPECTS(column_indices.size() <= num_columns(), "Requested too many columns.");
+
+    std::vector<gdf_column*> desired_columns;
+    for(auto index : column_indices){
+        desired_columns.push_back(_columns[index]);
```
Comment (jrhemstad) [inline cpp/src/table/legacy/table.cpp]: Let's add some bounds checking here. Make sure to update the documentation to indicate that it throws `std::out_of_range` if an index is out of range. 
```suggestion
        desired_columns.push_back(_columns.at(index));
```

File: cpp/src/join/joining.cu [hunk 76]
```diff
@@ -253,260 +220,315 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
-
   //if the inputs are nvcategory we need to make the dictionaries comparable
-  bool at_least_one_category_column = false;
-  for(int join_column_index = 0; join_column_index < num_cols_to_join; join_column_index++){
-    at_least_one_category_column |= left_cols[left_join_cols[join_column_index]]->dtype == GDF_STRING_CATEGORY;
-  }
+  bool at_least_one_category_column = std::any_of (cbegin(left_on), cend(left_on),
+                                                  [&](auto index) {  return (left.get_column(index)->dtype == GDF_STRING_CATEGORY);});
+  
+  std::vector<gdf_column*> new_left_cols(left.num_columns());
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
  std::vector<gdf_column*> new_left_cols(left.begin(), left.end());
```

File: cpp/src/join/joining.cu [hunk 77]
```diff
@@ -253,260 +220,315 @@ gdf_error join_call( int num_cols, gdf_column **leftcol, gdf_column **rightcol,
...
+  std::vector<gdf_column*> new_right_cols(right.num_columns());
```
Comment (jrhemstad) [inline cpp/src/join/joining.cu]:
```suggestion
  std::vector<gdf_column*> new_right_cols(right.begin(), right.end());
```

File: cpp/src/join/joining.cu (hunk 76 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: as `left` and `right` are `const`s, we can't pass begin and end to update the vector which is just `gdf_column*`

File: cpp/src/join/joining.cu (hunk 77 above)
Comment (rgsl888prabhu) [reply cpp/src/join/joining.cu]: as `left` and `right` are `const`s, we can't pass begin and end to update the vector which is just `gdf_column*`

**Comment by rgsl888prabhu** [comment]
@jrhemstad
