### PR TITLE
[REVIEW] Fix csv writer handling embedded comma delimiter

### LINKED ISSUE #6641: [BUG] to_csv displays strange behaviour when a string column contains the ',' character
**Describe the bug**
If I include a comma ',' in a string column I see invalid characters in the output and no string encapsulation.

**Steps/Code to reproduce bug**
```
import cudf
df = cudf.DataFrame({"a":[0,1,2,3,4],"b":["a,a is not valid","b","c","d","e"]})
df.to_csv()

outputs:
',a,b\n0,0,a,a is not valid\x00\x00\n1,1,b\n2,2,c\n3,3,d\n4,4,e\n'
```

**Expected behavior**
I wold expect strings to be encapsulated so that we can have commas in the actual text.
I would also expect it not to add these \x00\x00 nulls to the rows where strings contain commas.

**Environment overview (please complete the following information)**
cudf                      0.17.0a201101   cuda_11.0_py38_g54f3c0e26c_139    rapidsai-nightly
dask-cudf                 0.17.0a201101   py38_g54f3c0e26c_139    rapidsai-nightly
libcudf                   0.17.0a201101   cuda11.0_g54f3c0e26c_139    rapidsai-nightly

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #6641 

The csv [writer_impl](https://github.com/rapidsai/cudf/blob/e01ab96d1d90300b8eb32473de2b222ebef54e0c/cpp/src/io/csv/writer_impl.cu#L272) logic is checking for the ',' delimiter using already freed temporary device memory.

The ctor for `predicate_special_chars` accepts a `string_scalar` object but is passed a `std::string`.
The implicit conversion creates a temporary `string_scalar` correctly.
The ctor then sets a `string_view`  of the `string_scalar` data as a member variable. This is just a view and does not make a copy of the data inside of `string_scalar`.
This means that once the ctor returns, the temporary `string_scalar` is destroyed and the `string_view` is now pointing to freed memory.

The PR creates a `string_scalar` before the ctor and then passes a `string_view` instance to the `predicate_special_chars` ctor instead. This also removes the need to pass a stream parameter to the ctor. Now the `string_scalar` object has the same lifespan as the `predicate_special_chars` instance.

### CODE REVIEW

File: cpp/tests/io/csv_test.cpp [hunk 1]
```diff
@@ -203,10 +203,9 @@ void check_string_column(cudf::column_view const& col_lhs,
                    } else {
                      str_repl = str_row;
                    }
-
                    return need_surround ? quotes + str_repl + quotes : str_row;
                  });
-
+  for (auto h : h_rhs) printf("%s\n", h.c_str());
```
Comment (devavret) [inline cpp/tests/io/csv_test.cpp:208]: debug prints?

File: cpp/src/io/csv/writer_impl.cu [hunk 2]
```diff
@@ -268,8 +265,8 @@ struct column_to_strings_fn {
     // where modify() = duplicate the double quotes, if any; add 2bl quotes prefix/suffix;
     //}
     //
-    std::string delimiter{options_.get_inter_column_delimiter()};
-    predicate_special_chars pred{delimiter, stream_};
+    string_scalar delimiter{std::string{options_.get_inter_column_delimiter()}};
```
Comment (devavret) [inline cpp/src/io/csv/writer_impl.cu:268]: As an additional benefit, the string scalar can now be constructed with a stream.

**Review by devavret — CHANGES_REQUESTED** [review]

**Review by vuule — APPROVED** [review]

**Review by harrism — APPROVED** [review]
Good fix.
