### PR TITLE
[REVIEW] Parquet writer list statistics

### LINKED ISSUE #6362: [BUG] Insufficient test coverage of ORC and Parquet statistics
Please see comment: 
https://github.com/rapidsai/cudf/pull/6293#issuecomment-701109873

* Parquet statistics are never enabled in tests;
* ORC has statistics enabled by default, but the tests look like they only test the resulting data frame content;

- [ ] ORC coverage (Vukasin)
- [ ] Parquet coverage (Devavret)

### LINKED ISSUE #6683: [BUG] Bug in parquet writer corrupts subsequent unrelated cudf calls
**Describe the bug**

The parquet writer will throw an exception on some list writes (empty lists, maybe others). More devilishly, subsequent previously-working IO calls will fail (which makes it tough to diagnose), wedging the overall session, with no clear recourse beyond killing the Python process, all its users, and starting over.

**Steps/Code to reproduce bug**

```python
import cudf, pandas as pd, pyarrow as pa
{'c': cudf.__version__, 'pd': pd.__version__, 'pa': pa.__version__}
#{'c': '0.16.0', 'pd': '1.1.3', 'pa': '1.0.1'}

# Works the first time!
pd.DataFrame({'x': [ 1 ]}).to_json('good.json', orient='records')
good_gdf = cudf.read_json('good.json', orient='records')
good_gdf.dtypes
# x int64

# Incorrectly throws an exn + corrupts cudf internals
pd.DataFrame({'x': [ [] ]}).to_json('bad.json', orient='records')
bad_gdf = cudf.read_json('bad.json', orient='records')
try:
    bad_gdf.to_parquet('bad.parquet', compression='snappy')
except Exception as e:
    print('exn', e)
# CUDA error encountered at: /opt/conda/envs/rapids/conda-bld/libcudf_1603299758139/work/cpp/src/io/parquet/writer_impl.cu:467: 700 cudaErrorIllegalAddress an illegal memory access was encountered
bad_gdf.dtypes
# x    list

# Fails the second time!
cudf.read_json('good.json', orient='records')
```

=>

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-6-eb87c1f8567a> in <module>
----> 1 cudf.read_json('good.json', orient='records')

/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/json.py in read_json(path_or_buf, engine, dtype, lines, compression, byte_range, *args, **kwargs)
     62                 **kwargs,
     63             )
---> 64         df = cudf.from_pandas(pd_value)
     65 
     66     return df

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py in from_pandas(obj, nan_as_null)
   7182     """
   7183     if isinstance(obj, pd.DataFrame):
-> 7184         return DataFrame.from_pandas(obj, nan_as_null=nan_as_null)
   7185     elif isinstance(obj, pd.Series):
   7186         return Series.from_pandas(obj, nan_as_null=nan_as_null)

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py in from_pandas(cls, dataframe, nan_as_null)
   4913             if len(col_value.shape) == 1:
   4914                 df[col_name] = column.as_column(
-> 4915                     col_value.array, nan_as_null=nan_as_null
   4916                 )
   4917             else:

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1748                     from_pandas=True if nan_as_null is None else nan_as_null,
   1749                 ),
-> 1750                 nan_as_null=nan_as_null,
   1751             )
   1752         if dtype is not None:

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1573 
   1574     elif isinstance(arbitrary, (pa.Array, pa.ChunkedArray)):
-> 1575         col = ColumnBase.from_arrow(arbitrary)
   1576         if isinstance(arbitrary, pa.NullArray):
   1577             if type(dtype) == str and dtype == "empty":

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py in from_arrow(cls, array)
    395             return cudf.core.column.StructColumn.from_arrow(array)
    396 
--> 397         return libcudf.interop.from_arrow(data, data.column_names)._data[
    398             "None"
    399         ]

cudf/_lib/interop.pyx in cudf._lib.interop.from_arrow()

MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorIllegalAddress an illegal memory access was encountered
```

**Expected behavior**

* parquet writer should handle empty lists
* even if it doesn't, an exception here shouldn't break previously-working calls

**Environment overview (please complete the following information)**

v100 / 10.2 / ubuntu 18 => docker => conda rapids 0.16 / py3.7

### PR DESCRIPTION
**Pull request by devavret**
Fixes #6683 

Adds support for list writing statistics for list columns in parquet writer.
Also adds pytests for checking the statistics written by cudf for non-list as well as list columns.
Thereby closes #6362 

(Unverified) Modifies ORC to accommodate for the changes made to statistics calculation. Need ORC statistics tests to confirm.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by kkraus14 — APPROVED** [review]
Pytest lgtm

**Review by galipremsagar — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

File: cpp/src/io/statistics/column_stats.h [hunk 1]
```diff
@@ -36,8 +36,10 @@ enum statistics_dtype {
 };
 
 struct stats_column_desc {
-  statistics_dtype stats_dtype;    //!< physical data type of column
-  uint32_t num_rows;               //!< number of rows in column
+  statistics_dtype stats_dtype;  //!< physical data type of column
```
Comment (rgsl888prabhu) [inline cpp/src/io/statistics/column_stats.h:39]: Have to update header from 2019 -> 2019-2020

File: cpp/src/io/statistics/column_stats.h [hunk 2]
```diff
@@ -36,8 +36,10 @@ enum statistics_dtype {
...
+  uint32_t num_rows;             //!< number of rows in column
+  uint32_t num_values;  //!< Number of data values in column. Different from num_rows in case of
```
Comment (rgsl888prabhu) [inline cpp/src/io/statistics/column_stats.h:41]: Where `num_values` is being updated for Parquet ?

File: cpp/src/io/orc/writer_impl.cu [hunk 3]
```diff
@@ -737,6 +737,7 @@ std::vector<std::vector<uint8_t>> writer::impl::gather_statistic_blobs(
       default: desc->stats_dtype = dtype_none; break;
     }
     desc->num_rows         = columns[i].data_count();
+    desc->num_values       = columns[i].data_count();
```
Comment (rgsl888prabhu) [inline cpp/src/io/orc/writer_impl.cu:740]: `num_rows` and `num_values` both are getting assigned from `columns[i].data_count();`, how this would hold in case of nested types

File: cpp/src/io/orc/stats_enc.cu [hunk 4]
```diff
@@ -378,7 +378,7 @@ __global__ void __launch_bounds__(encode_threads_per_block)
         //  optional sint64 maximumUtc = 4;
         // }
         if (s->chunk.has_minmax) {
-          cur[0] = 7 * 8 + PB_TYPE_FIXEDLEN;
+          cur[0] = 9 * 8 + PB_TYPE_FIXEDLEN;
```
Comment (vuule) [inline cpp/src/io/orc/stats_enc.cu:381]: What are 7 and 9 here?

File: cpp/src/io/orc/writer_impl.cu (hunk 3 above)
Comment (devavret) [reply cpp/src/io/orc/writer_impl.cu:740]: The actual number of values is different from number of rows for list columns. But it is the same in case of non-list columns. In parquet writer the distinction has been made at the time of adding list column support and the values are set differently. In case of ORC, currently they are the same. Line 739 would need to be updated when list column support is added.

File: cpp/src/io/statistics/column_stats.h (hunk 2 above)
Comment (devavret) [reply cpp/src/io/statistics/column_stats.h:41]: https://github.com/rapidsai/cudf/blob/ff022e6c1e3fbb75974c0b34a56129b04fffef13/cpp%2Fsrc%2Fio%2Fparquet%2Fpage_enc.cu#L161-L169

File: cpp/src/io/orc/stats_enc.cu (hunk 4 above)
Comment (devavret) [reply cpp/src/io/orc/stats_enc.cu:381]: This is the protobuf field number as described in the comment just above this:
https://github.com/rapidsai/cudf/blob/ff022e6c1e3fbb75974c0b34a56129b04fffef13/cpp%2Fsrc%2Fio%2Forc%2Fstats_enc.cu#L351-L359
It was wrong for this field. should've been 9 (timestampStatistics) but was 7 (dateStatistics)

Similar comments describe the protobuf field number for other fields:
https://github.com/rapidsai/cudf/blob/ff022e6c1e3fbb75974c0b34a56129b04fffef13/cpp%2Fsrc%2Fio%2Forc%2Fstats_enc.cu#L314-L319
https://github.com/rapidsai/cudf/blob/ff022e6c1e3fbb75974c0b34a56129b04fffef13/cpp%2Fsrc%2Fio%2Forc%2Fstats_enc.cu#L278-L285

Magic numbers are bad so this should be addressed in another PR.

**Review by vuule — APPROVED** [review]

**Review by rgsl888prabhu — APPROVED** [review]

**Comment by kkraus14** [comment]
Don't rerun, will admin merge once a100 test is done.
