### PR TITLE
[REVIEW] CSV Reader: Fix memory leaks on read_csv() failure

### LINKED ISSUE #1256: [BUG] cudf does not recover properly after out-of-memory in read_csv
**Steps/Code to reproduce bug**
```
$ ls -lh /tmp/Performance*
[...] 1.6G Mar 20 16:52 /tmp/Performance_2001Q1.txt
[...] 191G Mar 20 16:15 /tmp/Performance.txt
```
`Performance.txt` is the concatenation of all `Performance` files from the full Mortgage dataset. I'm not expecting the 191GB file to be parsed successfully, but on error I expect all resources to be released:
```
>>> import cudf
>>> cudf.read_csv("/tmp/Performance.txt", delimiter='|')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf-0.6.0.dev0+1721.g04fac703.dirty-py3.6-linux-x86_64.egg/cudf/io/csv.py", line 337, in read_csv
    libgdf.read_csv(csv_reader)
  File "/conda/envs/rapids/lib/python3.6/site-packages/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: GDF_MEMORYMANAGER_ERROR
>>> cudf.read_csv("/tmp/Performance_2001Q1.txt", delimiter='|')
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory
Aborted (core dumped)
```
Whereas if I just load the smaller file, it works fine:
```
>>> import cudf
>>> print(cudf.read_csv("/tmp/Performance_2001Q1.txt", delimiter='|'))
    100005072756              02/01/2001                NULL  8.0          Unnamed: 4   2.0  358.0 ...  NULL.3
```

**Environment details (please complete the following information):**
Docker container `rapidsai/rapidsai-nightly@sha256:6ac57168a4cbcf6d3ff7fb3d0aec94a831ae5cac107d1a6cf5a1c166523cc9c3`
with cudf rebuilt manually from commit 04fac703a4e654e20bc02fa524bb03bbb42f5cac
```
# conda list | grep -E 'cudf|rmm'
cudf                      0.6.0.dev0+1721.g04fac703.dirty          pypi_0    pypi
dask-cudf                 0.0.0.dev0               pypi_0    pypi
librmm-cffi               0.6.0                    pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by vuule**
Fixes #1256

* Move the local raw_csv_t object to stack (no longer a pointer).
* Use RAII to own memory allocated within the read_csv call.
* Add rmm_device_buffer class to allow easier memory management of RMM buffers.

### CODE REVIEW

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 1]
```diff
@@ -146,3 +146,39 @@ struct rmm_deleter {
...
 using device_ptr = std::unique_ptr<T, rmm_deleter<T>>;
+
+// DOXY
+template <typename T>
+class rmm_device_buffer {
+	T* d_data = nullptr;
+
+public:
+	rmm_device_buffer() noexcept = default;
+	rmm_device_buffer(size_t cnt) {
```
Comment (jrhemstad) [inline cpp/src/io/utilities/wrapper_utils.hpp]: This should accept a stream that defaults to 0.

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 2]
```diff
@@ -146,3 +146,39 @@ struct rmm_deleter {
 };
 template <typename T>
 using device_ptr = std::unique_ptr<T, rmm_deleter<T>>;
+
+// DOXY
+template <typename T>
```
Comment (jrhemstad) [inline cpp/src/io/utilities/wrapper_utils.hpp]: I'd prefer to see this be untyped and just work on raw bytes.

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 3]
```diff
@@ -146,3 +146,39 @@ struct rmm_deleter {
...
+	T* data() const noexcept {return d_data;}
+
+	void resize(size_t cnt) {
+		const auto error = RMM_REALLOC(&d_data, cnt*sizeof(T), 0);
+		if(error != RMM_SUCCESS) {
+			cudf::detail::throw_cuda_error(cudaErrorMemoryAllocation, __FILE__, __LINE__);
+		}
+	}
+	// TODO: do we want to enable copy assignment?
+	rmm_device_buffer& operator=(rmm_device_buffer& ) = delete;
```
Comment (jrhemstad) [inline cpp/src/io/utilities/wrapper_utils.hpp]: I would delete the copy constructor as well.

Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: The copy constructor is implicitly deleted because the destructor is declared.
I'll delete it explicitly to make the intent clear.

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 2 above)
Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: hm, in that case the constructor would have to take the number of bytes?

What is the reason for your preference? I like the templated version a lot more because it makes the constructor call much cleaner (no need for sizeof) and also I get the corrent pointer type when getting the raw pointer. With viod*, many calls to data() would require a cast. Overall, I think it's less error prove to keep the type info in the wrapper type.

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 1 above)
Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: I'll make that change.
Do you also propose we use the same stream when calling rmm_free? I have a concern about using a stream there, because we don't have a guarantee that the stream will still exist when the object is destroyed. What are you thoughts on that?

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 3 above)
Comment (jrhemstad) [reply cpp/src/io/utilities/wrapper_utils.hpp]: Not quite that simple. You are correct that the implicit copy constructor here is deleted, but that's because you have a user-defined move constructor.

See:
https://wandbox.org/permlink/4Aww7zewZMSf69qF
https://en.cppreference.com/w/cpp/language/copy_constructor#Deleted_implicitly-declared_copy_constructor

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 1 above)
Comment (jrhemstad) [reply cpp/src/io/utilities/wrapper_utils.hpp]: Yeah, the `rmm::device_buffer` should maintain state for the stream it was allocated with, and use the same stream for `free`ing.

If a user destroys a stream out from under a `rmm::device_buffer`, I'd file that one under "Undefined Behavior".

With the direction I'd like to go in cuDF, we'll maintain a global set pool of streams, and the streams in that pool wouldn't be destroyed until the end of the program. 

We could also consider passing in the stream as a `shared_ptr` so the device buffer takes shared ownership to ensure it's not destroyed until the device buffer is done using it.

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 3 above)
Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: Darn, mixed up the rules. Illustrates why it's important to delete the special functions explicitly :)

File: cpp/src/io/csv/csv_reader.cu [hunk 4]
```diff
@@ -577,53 +579,61 @@ gdf_error read_csv(csv_read_arg *args)
...
 			return error;
 		}
-		const int h_num_cols = raw_csv->col_names.size();
+		const int h_num_cols = raw_csv.col_names.size();
 
 		// Allocating a boolean array that will use to state if a column needs to read or filtered.
-		raw_csv->h_parseCol = (bool*)malloc(sizeof(bool) * (h_num_cols));
-		RMM_TRY( RMM_ALLOC((void**)&raw_csv->d_parseCol,(sizeof(bool) * (h_num_cols)),0 ) );
+		raw_csv.h_parseCol = std::make_unique<bool[]>(h_num_cols);
+		raw_csv.d_parseCol = device_buffer<bool>(h_num_cols);
```
Comment (j-ieong) [inline cpp/src/io/csv/csv_reader.cu]: I'd prefer using `thrust::host_vector` and `rmm::device_vector` for `h_parseCol` and `d_parseCol`, respectively, since we are using it like a vector in the code.

We can simply assign `d_parseCol = h_parseCol` and not require explicit device_buffer<bool> upfront here.

File: cpp/src/io/csv/csv_reader.cu [hunk 5]
```diff
@@ -577,53 +579,61 @@ gdf_error read_csv(csv_read_arg *args)
...
 		for (int i = 0; i<h_num_cols; i++)
-			raw_csv->h_parseCol[i]=true;
+			raw_csv.h_parseCol[i]=true;
```
Comment (j-ieong) [inline cpp/src/io/csv/csv_reader.cu]: By having `h_parseCol` be a vector, you can pass `true` as the initial value and remove this loop.

**Comment by vuule** [comment]
@j-ieong can you please review?

File: cpp/src/io/csv/csv_reader.cu [hunk 6]
```diff
@@ -805,50 +808,49 @@ gdf_error read_csv(csv_read_arg *args)
...
-  for (int i = 0; i < raw_csv->num_active_cols; ++i) {
-    args->data[i] = columns[i].release();
 
-    if (args->data[i]->dtype == GDF_STRING) {
-      auto str_list = static_cast<string_pair *>(args->data[i]->data);
-      auto str_data = NVStrings::create_from_index(str_list, args->data[i]->size);
-      RMM_TRY(RMM_FREE(std::exchange(args->data[i]->data, str_data), 0));
+  for (int i = 0; i < raw_csv.num_active_cols; ++i) {
+    if (columns[i]->dtype == GDF_STRING) {
+      std::unique_ptr<NVStrings, decltype(&NVStrings::destroy)> str_data(
```
Comment (j-ieong) [inline cpp/src/io/csv/csv_reader.cu]: :+1: Pretty cool

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 7]
```diff
@@ -146,3 +146,53 @@ struct rmm_deleter {
 };
 template <typename T>
 using device_ptr = std::unique_ptr<T, rmm_deleter<T>>;
+
+/**
+ * @brief A helper class that ownes a resizable device memory buffer.
```
Comment (j-ieong) [inline cpp/src/io/utilities/wrapper_utils.hpp]:
```suggestion
 * @brief A helper class that owns a resizable device memory buffer.
```

File: cpp/src/io/csv/csv_reader.cu (hunk 4 above)
Comment (vuule) [reply cpp/src/io/csv/csv_reader.cu]: I agree, just forgot due to inertia. I'll make this change.

Comment (vuule) [reply cpp/src/io/csv/csv_reader.cu]: Done. Pretty happy with the effect.

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 8]
```diff
@@ -146,3 +146,53 @@ struct rmm_deleter {
...
+    stream_(stream), count_(cnt){
+    resize(count_);
+  }
+
+  T* data() const noexcept {return d_data_;}
+  size_t size() const noexcept {return count_;}
+
+  void resize(size_t cnt) {
+    count_ = cnt;
+    const auto error = RMM_REALLOC(&d_data_, count_*sizeof(T), stream_);
```
Comment (harrism) [inline cpp/src/io/utilities/wrapper_utils.hpp]: I don't think you should use RMM_REALLOC currently, it's broken (doesn't copy the data). (since the underlying allocator doesn't support it, it's hard to implement.)

Comment (harrism) [reply cpp/src/io/utilities/wrapper_utils.hpp]: I also don't think it works if you call it before calling RMM_ALLOC. Is that intended to work with other allocators?

Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: @harrism 
In the current use cases, we don't need the data to be copied. I'll modify to include the copy, to make the class more generally applicable.

realloc is defined to behave the same as (m)alloc when the input pointer points to null. I check both cudaRealloc() specs and the rmm::realloc code.
Another edge case I checked for is passing zero size to realloc. rmm::realloc sets the pointer to null, which is exactly what I need here.

Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: @harrism replace the realloc with malloc+copy, please review.

Comment (harrism) [reply cpp/src/io/utilities/wrapper_utils.hpp]: That's better. How did you check `cudaRealloc()` specs? There's no such thing as `cudaRealloc`.

Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: Turns out I checked the C++ realloc for reference on what to expect from realloc behavior in general, before digging into the rmm code. Apologies for the confusion (I'll blame it on the late hours).

File: cpp/src/io/utilities/wrapper_utils.hpp [hunk 9]
```diff
@@ -146,3 +146,70 @@ struct rmm_deleter {
 };
 template <typename T>
 using device_ptr = std::unique_ptr<T, rmm_deleter<T>>;
+
+/**
+ * @brief A helper class that owns a resizable device memory buffer.
```
Comment (jrhemstad) [inline cpp/src/io/utilities/wrapper_utils.hpp]: I'd make it clear in the documentation that the buffer is uninitialized.

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 2 above)
Comment (jrhemstad) [reply cpp/src/io/utilities/wrapper_utils.hpp]: Yeah, you're right.

I was thinking about this as if it were an allocator. One of the biggest mistakes in C++ is making `std::allocator` typed. 

But this isn't an allocator, it's a buffer object. So it makes sense for it to be typed.

File: cpp/src/io/utilities/wrapper_utils.hpp (hunk 9 above)
Comment (vuule) [reply cpp/src/io/utilities/wrapper_utils.hpp]: @jrhemstad added the info below. 
The PR should be ready for merge now. Please update your review if you don't have any other suggestions.
