### PR TITLE
Fix the host-device tdigest offsets by using cuda::std::span

### LINKED ISSUE #20203: [BUG] tdigest_aggregation.cu appears to violate __host__ and __device__ constraints
**Describe the bug**
tdigest_aggregation.cu appears to violate __host__ and __device__ constraints.

1. cumulative_centroid_weight has a field `cudf::device_span tdigest_offsets`.
2. `cudf::device_span::operator[]` is typed `__device__`
3. `cumulative_centroid_weight::operator()` calls `tdigest_offsets[]` (the above operator)
4. But `cumulative_centroid_weight::operator()` is typed `__host__ __device__`
5. So it cannot call the `operator[]`

In practice this violation can only occur at runtime in generate_cluster_limits if num_cpu_groups > 0. I do not currently have the skills to figure out whether the test suite hits that.

**Steps/Code to reproduce bug**
Does not compile in clang, which is strict about attributes.

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
Closes #20203

`cumulative_centroid_weight::tdigest_offsets` was declared as `cudf::device_span<size_type const>`, which is incorrect because the offsets can reside in either host pinned memory or device memory. This PR resolves the issue by using the appropriate `cuda::std::span` instead.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/include/cudf_test/stream_checking_resource_adaptor.hpp [hunk 1]
```diff
@@ -94,7 +94,7 @@ class stream_checking_resource_adaptor final : public rmm::mr::device_memory_res
    * @param bytes Size of the allocation
    * @param stream Stream on which to perform the deallocation
    */
-  void do_deallocate(void* ptr, std::size_t bytes, rmm::cuda_stream_view stream) override
+  void do_deallocate(void* ptr, std::size_t bytes, rmm::cuda_stream_view stream) noexcept override
```
Comment (PointKernel) [inline cpp/include/cudf_test/stream_checking_resource_adaptor.hpp:97]: this change is unrelated but to unblock local build before https://github.com/rapidsai/cudf/pull/20219 gets in.

Comment (bdice) [reply cpp/include/cudf_test/stream_checking_resource_adaptor.hpp:97]: #20218 is now merged in, and has the essential fix. You can pull the upstream.

File: cpp/src/quantiles/tdigest/tdigest_aggregation.cu [hunk 2]
```diff
@@ -270,7 +271,7 @@ struct cumulative_centroid_weight {
   double const* cumulative_weights;  // cumulative weights of non-empty clusters
   GroupLabelsIter group_labels;      // group labels for each tdigest including empty ones
   GroupOffsetsIter group_offsets;    // groups
-  cudf::device_span<size_type const> tdigest_offsets;  // tdigests with a group
+  cuda::std::span<size_type const> tdigest_offsets;  // tdigests with a group
```
Comment (mhaseeb123) [inline cpp/src/quantiles/tdigest/tdigest_aggregation.cu:275]: Since `cuda::std::span` isn't used elsewhere in libcudf (I couldn't find any instance), I think it would be nice to add a comment here explaining its use to span a pinned vector.
