### PR TITLE
Compute whole column variance using numerically stable approach

### LINKED ISSUE #16444: [BUG] whole-column variance calculation uses numerically unstable algorithm
**Describe the bug**

(from a review of https://github.com/rapidsai/cudf/pull/16367)

The calculation of whole-column variance in libcudf uses the "textbook" approach. For some set of measurements $X := \\{x_i\\}_{i=1}^N$ (assuming, wlog, `ddof=1`):

$$
\text{var}{X} = \frac\{\sum_i x_i^2\}\{N - 1\} - \left(\frac{\sum_i x_i}{N}\right)^2 \frac{N}{N-1}.
$$

This is known to be numerically inaccurate, especially when the variance is small compared to the values and both terms are large and of similar magnitude.

The usual fix to this is to compute via a two-pass or stable online approach. The former is then (having computed the mean $\bar{x}$):

$$
\text{var}{X} = \frac\{\sum_i (x_i - \bar{x})^2\}\{N - 1\}
$$

This is the approach used in groupby variance calculation. An online version (Welford's algorithm) is used in rolling variance calculation.

We can see the differences in accuracy:

```python
import cudf

y = cudf.Series([1577836800000000000, 1609372800000000000], dtype="int64").astype("float64")
print("%.32e" % y.var(ddof=1))
print("%.32e" % y.rolling(2, min_periods=0).var().values[1].item())
print("%.32e" % y.groupby(cudf.Series([0, 0])).var().values[0].item())
print("%.32e" % y.values.get().astype("float128").var(ddof=1))
# 4.97259647999910330416731839791104e+32
#               ^^^^ about 1000ulp
# 4.97259647999999970063715022143488e+32
# 4.97259647999999970063715022143488e+32
# 4.97259647999999970063715022143488e+32
```

We should implement a numerically stable approach for the whole column calculation of the variance.

### PR DESCRIPTION
**Pull request by wence-**
## Description
We use the pairwise approach of Chan, Golub, and LeVeque (1983).

- Closes #16444

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: java/src/test/java/ai/rapids/cudf/ReductionTest.java [hunk 1]
```diff
@@ -612,7 +612,7 @@ void testWithSetOutputType() {
       assertEquals(expected, result);
     }
 
-    try (Scalar expected = Scalar.fromFloat(1.666667f);
+    try (Scalar expected = Scalar.fromFloat(1.666666f);
```
Comment (wence-) [inline java/src/test/java/ai/rapids/cudf/ReductionTest.java:615]: The new result is now the closest float to the exact value of $\frac{5}{3}$.

File: cpp/tests/reductions/reduction_tests.cpp [hunk 2]
```diff
@@ -2501,15 +2479,13 @@ TYPED_TEST(DictionaryReductionTest, DISABLED_VarStd)
...
   double std_nulls = std::sqrt(var_nulls);
 
-  EXPECT_EQ(this->template reduction_test<double>(col_nulls, *var_agg, output_type).first,
-            var_nulls);
-  EXPECT_EQ(this->template reduction_test<double>(col_nulls, *std_agg, output_type).first,
-            std_nulls);
+  EXPECT_DOUBLE_EQ(this->template reduction_test<double>(col_nulls, *var_agg, output_type).first,
+                   var_nulls);
+  EXPECT_DOUBLE_EQ(this->template reduction_test<double>(col_nulls, *std_agg, output_type).first,
+                   std_nulls);
```
Comment (wence-) [inline cpp/tests/reductions/reduction_tests.cpp:2488]: I think we were just lucky before that the result we obtained was exactly the same. Now the host-side calculation does the two-pass algorithm:

$$
\frac{1}{n - \text{ddof}}\sum_{i=1}^{n} (x_i - \bar{x})^2
$$

So this has some ulp differences to the one-pass algorithm on the device side. `EXPECT_DOUBLE_EQ` allows for up to 4ULP difference.

**Comment by wence-** [comment]
Back into draft while I figure out some edges cases around NAs.

File: cpp/src/reductions/compound.cuh [hunk 3]
```diff
@@ -54,35 +54,36 @@ std::unique_ptr<scalar> compound_reduction(column_view const& col,
 {
   auto const valid_count = col.size() - col.null_count();
 
+  // ddof is allowed to be negative, hence need to check for all nulls
```
Comment (wence-) [inline cpp/src/reductions/compound.cuh:57]: *question*: pandas at least doesn't raise for negative ddof, but it is mathematically nonsensical, so arguably libcudf should `CUDF_EXPECTS(ddof >= 0, ...)` in the public API.

File: java/src/test/java/ai/rapids/cudf/ReductionTest.java [hunk 4]
```diff
@@ -612,7 +612,7 @@ void testWithSetOutputType() {
       assertEquals(expected, result);
     }
 
-    try (Scalar expected = Scalar.fromFloat(1.666667f);
+    try (Scalar expected = Scalar.fromFloat(1.6666666f);
```
Comment (wence-) [inline java/src/test/java/ai/rapids/cudf/ReductionTest.java:615]: This is the closest float to the exact value of $\frac{5}{3}$, which we now obtain.

File: cpp/src/reductions/compound.cuh (hunk 3 above)
Comment (wence-) [reply cpp/src/reductions/compound.cuh]: Did this.

File: cpp/src/reductions/compound.cuh [hunk 5]
```diff
@@ -53,35 +57,39 @@ std::unique_ptr<scalar> compound_reduction(column_view const& col,
 {
   auto const valid_count = col.size() - col.null_count();
 
+  // All null input produces all null output
+  if (valid_count == 0 ||
+      // Don't care about ddof argument of mean. For variance and
+      // standard deviation must have more valid entries than ddof.
```
Comment (bdice) [inline cpp/src/reductions/compound.cuh:63]: We could add more compound reductions here. Can we check "is var or std" rather than "not mean"?

**Review by bdice — APPROVED** [review]
One suggestion, otherwise LGTM. Thank you for the attention to details throughout this PR!

File: java/src/test/java/ai/rapids/cudf/ReductionTest.java [hunk 6]
```diff
@@ -612,13 +612,13 @@ void testWithSetOutputType() {
...
          ColumnVector cv = ColumnVector.fromBytes(new byte[]{1, 2, 3, 4});
          Scalar result = cv.variance(DType.FLOAT32)) {
       assertEquals(expected, result);
     }
 
-    try (Scalar expected = Scalar.fromFloat(1.2909945f);
+    try (Scalar expected = Scalar.fromFloat(1.2909944f);
```
Comment (wence-) [inline java/src/test/java/ai/rapids/cudf/ReductionTest.java:621]: This now the closest float32 to sqrt(5/3)

File: cpp/src/reductions/compound.cuh [hunk 7]
```diff
@@ -53,35 +58,39 @@ std::unique_ptr<scalar> compound_reduction(column_view const& col,
 {
   auto const valid_count = col.size() - col.null_count();
 
+  // All null input produces all null output
+  if (valid_count == 0 ||
+      // Only care about ddof for standard deviation and variance right now
+      valid_count <= ddof && (std::is_same_v<Op, cudf::reduction::detail::op::standard_deviation> ||
+                              std::is_same_v<Op, cudf::reduction::detail::op::variance>)) {
```
Comment (wence-) [inline cpp/src/reductions/compound.cuh:65]: @bdice Done. I reordered the condition purely because clang-format does a bad for:

```
(std::is_same_v<...> || std::is_same_v<...>) && ...
```
it sticks the `&&` to the paren.

File: cpp/tests/reductions/reduction_tests.cpp [hunk 8]
```diff
@@ -765,6 +769,25 @@ TYPED_TEST(MultiStepReductionTest, Mean)
             expected_value_nulls);
 }
 
+template <typename T>
+double calc_var(std::vector<T> const& v, int ddof, std::vector<bool> const& mask = {})
+{
+  auto const values = [&]() {
+    if (mask.empty()) { return v; }
+    std::vector<T> masked{};
+    thrust::copy_if(
```
Comment (davidwendt) [inline cpp/tests/reductions/reduction_tests.cpp:778]:
```suggestion
    std::copy_if(
```
Prefer using the STL for host containers when possible.

File: cpp/src/reductions/compound.cuh [hunk 9]
```diff
@@ -137,6 +146,7 @@ struct element_type_dispatcher {
                                      rmm::cuda_stream_view stream,
                                      rmm::device_async_resource_ref mr)
   {
+    CUDF_EXPECTS(ddof >= 0, "ddof must be non-negative", std::domain_error);
```
Comment (davidwendt) [inline cpp/src/reductions/compound.cuh:149]: TIL about `std::domain_error`. Nicely done.

**Review by bdice — APPROVED** [review]
Re-approving latest changes.

File: cpp/tests/reductions/reduction_tests.cpp (hunk 8 above)
Comment (davidwendt) [reply cpp/tests/reductions/reduction_tests.cpp]: Looks like `std::copy_if` does not have transform pattern like `thrust::copy_if`. 
Sorry about that. Looks like it will be easier to just change this back.

File: cpp/tests/reductions/reduction_tests.cpp (hunk 2 above)
Comment (mythrocks) [reply cpp/tests/reductions/reduction_tests.cpp:2484]: I had no idea that Github markdown supported this sort of notation.

File: cpp/src/reductions/compound.cuh (hunk 7 above)
Comment (ttnghia) [reply cpp/src/reductions/compound.cuh:65]: `std::is_same_v` is `constexpr`. So you maybe this is better:
```
if constexpr(std::is_same_v<...> || std::is_same_v<...>) {
  if(valid_count == 0 || ...) {
    ...
  }
}
```

Comment (wence-) [reply cpp/src/reductions/compound.cuh:65]: I am perhaps naive in that I hope that any decent compiler will optimise `if (x && true)` to `if (x)`.

Comment (wence-) [reply cpp/src/reductions/compound.cuh:65]: Ah, that's not the right transformation, because the `valid_count == 0` branch should be taken for any `Op`.

File: cpp/tests/reductions/reduction_tests.cpp (hunk 8 above)
Comment (wence-) [reply cpp/tests/reductions/reduction_tests.cpp:778]: Reverted.

File: cpp/src/reductions/compound.cuh (hunk 7 above)
Comment (davidwendt) [reply cpp/src/reductions/compound.cuh:65]: I've found the compiler is pretty good at this sort of thing without our help anyway.

File: cpp/include/cudf/reduction/detail/reduction_operators.cuh [hunk 10]
```diff
@@ -31,17 +31,41 @@ namespace detail {
...
+    auto const n = rhs.count;
+    // Avoid division by zero.
+    if (m == 0) { return rhs; }
+    if (n == 0) { return *this; }
+    auto const tm   = this->running_sum;
+    auto const tn   = rhs.running_sum;
+    auto const sm   = this->running_square_deviations;
+    auto const sn   = rhs.running_square_deviations;
+    auto const tmn  = tm + tn;
+    auto const diff = (static_cast<ResultType>(n) / m) * tm - tn;
```
Comment (nvdbaranec) [inline cpp/include/cudf/reduction/detail/reduction_operators.cuh:65]: The nittiest of nitpicks. Subtraction weirds me out and I am very pro-parentheses :) 
```suggestion
    auto const diff = ((static_cast<ResultType>(n) / m) * tm) - tn;
```

File: cpp/tests/reductions/reduction_tests.cpp [hunk 11]
```diff
@@ -765,6 +769,25 @@ TYPED_TEST(MultiStepReductionTest, Mean)
             expected_value_nulls);
 }
 
+template <typename T>
+double calc_var(std::vector<T> const& v, int ddof, std::vector<bool> const& mask = {})
```
Comment (nvdbaranec) [inline cpp/tests/reductions/reduction_tests.cpp:773]:
```suggestion
double calc_var(cudf::host_span<T const> v, int ddof, cudf::host_span<bool const> mask = {})
```

Comment (wence-) [reply cpp/tests/reductions/reduction_tests.cpp]: This bit broke template argument deduction, so will revert since it's just in a test.
