### PR TITLE
Eagerly load nvCOMP library in `cudf::initialize()`

### LINKED ISSUE #19850: [BUG] nvcompErrorInvalidValue when running NDSH_Q01_NVBENCH with scale_factor=10
**Describe the bug**
The following error occurs running NDSH_Q01_NVBENCH with scale_factor=10 on branch-25.10
```
Unexpected error: CUDF failure at: /cudf/cpp/src/io/comp/nvcomp_adapter.cpp:512: nvCOMP error: nvcompErrorInvalidValue
```

**Steps/Code to reproduce bug**
Run the following benchmark:
```
benchmarks/NDSH_Q01_NVBENCH -d 0 --axis scale_factor=10 --profile
```

### PR DESCRIPTION
**Pull request by vuule**
## Description
issue https://github.com/rapidsai/cudf/issues/19850

Lazy loading of nvCOMP library on first use can lead to OOM errors when cuDF uses a large memory pool.

This PR adds eager loading of the library to the `cudf::initialize()` API and a call to `initialize` in the benchmarks fixture, before the pool is created. 

Verified locally that this fixes #19850.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vuule** [comment]
pre-commit.ci autofix

File: cpp/src/io/comp/nvcomp_adapter.cpp [hunk 1]
```diff
@@ -1065,4 +1066,33 @@ std::optional<size_t> compress_max_allowed_chunk_size(compression_type compressi
...
+    hd_inputs[0] = d_input;
+    hd_inputs.host_to_device_async(stream);
+    cudf::detail::hostdevice_vector<device_span<uint8_t>> hd_outputs(1, stream);
+    hd_outputs[0] = d_compressed;
+    hd_outputs.host_to_device_async(stream);
+    cudf::detail::hostdevice_vector<codec_exec_result> hd_results(1, stream);
+    hd_results[0] = codec_exec_result{0, codec_status::FAILURE};
+    hd_results.host_to_device_async(stream);
+
+    // Perform compression - this will execute an nvCOMP kernel
```
Comment (bdice) [inline cpp/src/io/comp/nvcomp_adapter.cpp:1093]: Is launching a kernel the best solution?

Do we think this is caused by lazy loading? The [CUDA docs on lazy loading](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading) indicate there may be other ways to trigger loading without having to execute a kernel, such as calling the runtime API `cudaFuncGetAttributes()`.

Can you verify whether `CUDA_MODULE_LOADING` or `CUDA_MODULE_DATA_LOADING` are being set or if they're enabled by default?

Comment (vuule) [reply cpp/src/io/comp/nvcomp_adapter.cpp:1093]: From what I could find, launching a kernel is the safest way to make sure everything was loaded. As in, turning off lazy loading might load the library but not JITed (if that's the right term here) code. I can check the repro with something like `cudaFuncGetAttributes`.

I intentionally didn't change the loading behavior, so this early loading can be opt-in. I'm not sure if we want to load nvCOMP on launch by default.

Comment (vuule) [reply cpp/src/io/comp/nvcomp_adapter.cpp:1093]: Looked into this again. `cudaFuncGetAttributes` does not work because the nvCOMP kernels are not exposed directly. Overall could not find a better option to do this.
Modified the `initialize` API to make it more flexible and to keep the default behavior; nvCOMP is now loaded only in benchmarks.

File: cpp/include/cudf/context.hpp [hunk 2]
```diff
@@ -18,11 +18,42 @@
...
+/// @brief Check if a flag is set
+/// @param flags The flags to check against
+/// @param flag The specific flag to check for
+/// @return true if all bits in `flag` are set in `flags`, false otherwise
+constexpr bool has_flag(init_flags flags, init_flags flag) noexcept
+{
+  return (flags | flag) == flags;
+}
+
 /// @brief initialize the cudf global context
```
Comment (lamarrr) [inline cpp/include/cudf/context.hpp]:
```suggestion
/// @brief Initialize the cudf global context
```

**Review by lamarrr — APPROVED** [review]

**Comment by davidwendt** [comment]
The `initialize/deinitialize` APIs also help get around errors thrown in a debug build which seems to have more stringent checks.
If possible, could you try this PR with a libcudf debug build?

**Comment by vuule** [comment]
> The `initialize/deinitialize` APIs also help get around errors thrown in a debug build which seems to have more stringent checks. If possible, could you try this PR with a libcudf debug build?

I was not able to make a debug build, compilation got stuck.

**Comment by davidwendt** [comment]
> > The `initialize/deinitialize` APIs also help get around errors thrown in a debug build which seems to have more stringent checks. If possible, could you try this PR with a libcudf debug build?
> 
> I was not able to make a debug build, compilation got stuck.

I was able to test this PR successfully with a local debug build.

File: cpp/benchmarks/fixture/nvbench_fixture.hpp [hunk 3]
```diff
@@ -15,6 +15,8 @@
  */
 #pragma once
 
+#include "cudf/context.hpp"
```
Comment (bdice) [inline cpp/benchmarks/fixture/nvbench_fixture.hpp]:
```suggestion
#include <cudf/context.hpp>
```

File: cpp/include/cudf/context.hpp [hunk 4]
```diff
@@ -18,11 +18,42 @@
...
+/// @param flags The flags to check against
+/// @param flag The specific flag to check for
+/// @return true if all bits in `flag` are set in `flags`, false otherwise
+constexpr bool has_flag(init_flags flags, init_flags flag) noexcept
+{
+  return (flags | flag) == flags;
+}
+
+/// @brief Initialize the cudf global context
+/// @param flags Optional flags to control which initialization steps to perform.
```
Comment (bdice) [inline cpp/include/cudf/context.hpp:56]: Can you initialize some parts later? Like only init the JIT cache, and then later init the nvcomp load?

File: cpp/src/runtime/context.hpp [hunk 5]
```diff
@@ -19,10 +19,13 @@
 #include <cudf/context.hpp>
 #include <cudf/utilities/export.hpp>
 
+#include <cstdint>
 #include <memory>
 
 namespace cudf {
 
+enum class init_flags : std::uint32_t;
```
Comment (bdice) [inline cpp/src/runtime/context.hpp]: Is this being forward-declared? Why?

File: cpp/include/cudf/context.hpp (hunk 4 above)
Comment (vuule) [reply cpp/include/cudf/context.hpp:56]: as in, call initialize multiple times with different flags?

File: cpp/src/runtime/context.hpp (hunk 5 above)
Comment (vuule) [reply cpp/src/runtime/context.hpp]: no reason, removing

File: cpp/include/cudf/context.hpp (hunk 4 above)
Comment (vuule) [reply cpp/include/cudf/context.hpp:56]: assuming yes - no, not with the current implementation. `initialize` works by instantiating the singleton, so it fails when called the second time (I just realized this). I can rework the implementation to enable initialization in stages and to stop throwing on repeated calls. Let me know if you think this should be in this or in a separate PR.

Comment (bdice) [reply cpp/include/cudf/context.hpp:56]: Document the behavior clearly for now, and file an issue for partially-delayed initialization. We need initialization to be idempotent at a per-flag level.

Comment (vuule) [reply cpp/include/cudf/context.hpp:56]: Now I see that it's already documented in the next line :)
opened https://github.com/rapidsai/cudf/issues/20022

File: cpp/include/cudf/context.hpp [hunk 6]
```diff
@@ -18,11 +18,42 @@
...
+  ALL = LOAD_NVCOMP | INIT_JIT_CACHE
+};
+
+/// @brief Bitwise OR operator for init_flags
+/// @param lhs The left-hand side of the operator
+/// @param rhs The right-hand side of the operator
+/// @return The result of the bitwise OR operation
+constexpr init_flags operator|(init_flags lhs, init_flags rhs) noexcept
+{
+  return static_cast<init_flags>(static_cast<std::uint32_t>(lhs) | static_cast<std::uint32_t>(rhs));
```
Comment (vyasr) [inline cpp/include/cudf/context.hpp]: Maybe use `std::underlying_type_t` to avoid repeating the type here?

File: cpp/include/cudf/context.hpp [hunk 7]
```diff
@@ -18,11 +18,42 @@
...
+  INIT_JIT_CACHE = 1 << 1,
+  /// @brief All initialization steps (default behavior)
+  ALL = LOAD_NVCOMP | INIT_JIT_CACHE
+};
+
+/// @brief Bitwise OR operator for init_flags
+/// @param lhs The left-hand side of the operator
+/// @param rhs The right-hand side of the operator
+/// @return The result of the bitwise OR operation
+constexpr init_flags operator|(init_flags lhs, init_flags rhs) noexcept
```
Comment (vyasr) [inline cpp/include/cudf/context.hpp:40]: Worth making the args const?

File: cpp/src/runtime/context.hpp [hunk 8]
```diff
@@ -19,6 +19,7 @@
 #include <cudf/context.hpp>
 #include <cudf/utilities/export.hpp>
 
+#include <cstdint>
```
Comment (vyasr) [inline cpp/src/runtime/context.hpp]: Is this include needed?

File: cpp/src/runtime/context.cpp [hunk 9]
```diff
@@ -26,13 +27,23 @@
...
+  if (has_flag(flags, init_flags::LOAD_NVCOMP)) { io::detail::nvcomp::load_nvcomp_library(); }
+
   auto dump_codegen_flag = getenv_or("LIBCUDF_JIT_DUMP_CODEGEN", std::string{"OFF"});
   _dump_codegen          = (dump_codegen_flag == "ON" || dump_codegen_flag == "1");
 }
 
-jit::program_cache& context::program_cache() { return *_program_cache; }
+jit::program_cache& context::program_cache()
+{
+  CUDF_EXPECTS(_program_cache != nullptr, "JIT cache not initialized", std::runtime_error);
```
Comment (vyasr) [inline cpp/src/runtime/context.cpp:44]: Just validating: in practice this is unreachable because we only construct a single context object as a singleton via `get_context`, right? In order to hit this the our jit::get_program_cache function would have to be modified to use a different context?

**Review by vyasr — APPROVED** [review]
Some small questions and suggestions but I won't need to review again. Thanks!

File: cpp/include/cudf/context.hpp (hunk 7 above)
Comment (vuule) [reply cpp/include/cudf/context.hpp:40]: IMO, no. These are passed by value, so const does not affect the caller in any way.

File: cpp/src/runtime/context.cpp (hunk 9 above)
Comment (vuule) [reply cpp/src/runtime/context.cpp:44]: this is here for the case when the singleton is initialized without the INIT_JIT_CACHE flag.

File: cpp/src/runtime/context.hpp (hunk 8 above)
Comment (vuule) [reply cpp/src/runtime/context.hpp]: good catch. I think it was added because of the code that got removed since.
