### PR TITLE
Propagate exceptions thrown in async IO operations

### LINKED ISSUE #19586: [BUG]: Cudf Parquet reader ignored the exception thrown from DataSource and produces unrelated errors by misinterpreting the bytes
cudf parquet reader doesn't handle the exceptions delivered to the caller of `cuda::datasource::device_read_async` using the std::future, instead it assumes the bytes have been read and tried to interprete the bytes which leads to parsing errors

**Steps/Code to reproduce bug**
```

#include <algorithm>
#include <cstdint>

#include <gtest/gtest.h>

#include <cudf/column/column.hpp>
#include <cudf/column/column_factories.hpp>
#include <cudf/io/datasource.hpp>
#include <cudf/io/parquet.hpp>
#include <cudf/io/types.hpp>
#include <cudf/table/table.hpp>
#include <cudf/table/table_view.hpp>

#include <array>
#include <future>

namespace theseus::test {

std::unique_ptr<cudf::table> CreateSampleTable() {
  std::vector<int32_t> int_data{1, 2, 3, 4, 5};
  std::vector<double> double_data{1.1, 2.2, 3.3, 4.4, 5.5};

  // Copy to device
  rmm::device_uvector<int32_t> d_int_data(int_data.size(), rmm::cuda_stream_default);
  cudaMemcpy(d_int_data.data(), int_data.data(), int_data.size() * sizeof(int32_t),
             cudaMemcpyHostToDevice);

  rmm::device_uvector<double> d_double_data(double_data.size(), rmm::cuda_stream_default);
  cudaMemcpy(d_double_data.data(), double_data.data(),
             double_data.size() * sizeof(double), cudaMemcpyHostToDevice);

  // Create columns
  auto int_col =
      cudf::make_numeric_column(cudf::data_type(cudf::type_id::INT32), int_data.size());
  cudaMemcpy(int_col->mutable_view().data<int32_t>(), d_int_data.data(),
             int_data.size() * sizeof(int32_t), cudaMemcpyDeviceToDevice);

  auto double_col = cudf::make_numeric_column(cudf::data_type(cudf::type_id::FLOAT64),
                                              double_data.size());
  cudaMemcpy(double_col->mutable_view().data<double>(), d_double_data.data(),
             double_data.size() * sizeof(double), cudaMemcpyDeviceToDevice);

  // Create table from columns
  std::vector<std::unique_ptr<cudf::column>> columns;
  columns.push_back(std::move(int_col));
  columns.push_back(std::move(double_col));

  return std::make_unique<cudf::table>(std::move(columns));
}

class OomThrowingDatasource : public cudf::io::datasource {
 public:
  explicit OomThrowingDatasource(std::unique_ptr<cudf::io::datasource> wrapped_source,
                                 bool throw_oom = true)
      : data_source_(std::move(wrapped_source)), throw_oom_(throw_oom) {}

  [[nodiscard]] size_t size() const override { return data_source_->size(); }

  [[nodiscard]] bool supports_device_read() const override {
    return data_source_->supports_device_read();
  }

  [[nodiscard]] bool is_device_read_preferred(size_t size) const override {
    return data_source_->is_device_read_preferred(size);
  }

  [[nodiscard]] size_t device_read(size_t offset, size_t size, uint8_t* dst,
                                   rmm::cuda_stream_view stream) override {
    if (throw_oom_) {
      throw rmm::out_of_memory("Simulated OOM error");
    }
    return data_source_->device_read(offset, size, dst, stream);
  }

  std::future<size_t> device_read_async(size_t offset, size_t size, uint8_t* dst,
                                        rmm::cuda_stream_view stream) override {
    return std::async(std::launch::deferred, [this, offset, size, dst, stream]() {
      if (throw_oom_) {
        throw rmm::out_of_memory("Simulated OOM error");
      }

      return data_source_->device_read_async(offset, size, dst, stream).get();
    });
  }

  [[nodiscard]] std::unique_ptr<cudf::io::datasource::buffer> host_read(
      size_t offset, size_t size) override {
    return data_source_->host_read(offset, size);
  }

  [[nodiscard]] size_t host_read(size_t offset, size_t size, uint8_t* dst) override {
    return data_source_->host_read(offset, size, dst);
  }

 private:
  std::unique_ptr<cudf::io::datasource> data_source_;
  bool throw_oom_{true};  // Flag to control OOM simulation
};

/// this tests checks if cudf reader can handle exceptions thrown by the datasource
TEST(ExceptionHiddenByCudf, OomException) {
  auto expected = CreateSampleTable();

  auto filepath = "SimpleParquet.parquet";
  cudf::io::parquet_writer_options args =
      cudf::io::parquet_writer_options::builder(cudf::io::sink_info{filepath}, *expected);
  cudf::io::write_parquet(args);

  auto file_source = cudf::io::datasource::create(filepath);
  auto custom_source =
      std::make_unique<OomThrowingDatasource>(std::move(file_source), true);

  cudf::io::source_info source{custom_source.get()};
  auto read_opts = cudf::io::parquet_reader_options::builder(source).build();

  try {
    auto result = cudf::io::read_parquet(read_opts);
  } catch (const rmm::out_of_memory& e) {
    EXPECT_EQ(std::string(e.what()), "Simulated OOM error");
  } catch (const std::exception& e) {
    FAIL() << "Expected rmm::out_of_memory "
              "exception, but got: "
           << e.what();
  }
}

}  // namespace theseus::test
```

**Expected behavior**
the exception from datasource should be handled gracefully, and only in the absence of an exception, the parser should proceed. 

if the datasource throws an `rmm::out_of_memory` exception or any other exceptions, the exception should be delivered to the caller, so proper error handling would be possible.

--- 
this test fails with: 
Expected rmm::out_of_memory exception, but got: CUDF failure at:/home/runner/output/bld/rattler-build_libcudf/work/cpp/src/io/parquet/reader_impl_preprocess.cu:315: Parquet header parsing failed with code(s) while counting page headers 0x1

**Additional context**
I've only tested in with the parquet reader, but it could very well be a wide-spread issue across entire repository.

### PR DESCRIPTION
**Pull request by vuule**
## Description
closes #19586

In some places in libcudf, `std::future::wait()` is called to wait on asynchronous IO operations. The issue with this is that wait does not propagate any exceptions that may be thrown.

This PR replaces the `wait()` calls with `get()` and adds readers and writers tests to make sure exceptions are re-thrown.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Review by aminaramoon — APPROVED** [review]
thanks for addressing this!

**Review by mhaseeb123 — APPROVED** [review]

File: cpp/tests/io/parquet_reader_test.cpp [hunk 1]
```diff
@@ -3165,3 +3167,56 @@ TEST_F(ParquetReaderTest, RowBoundsAndFilter)
...
+
+  // The write_parquet call should either succeed or throw AsyncException.
+  try {
+    cudf::io::write_parquet(write_args);
+    // Test passes if no exception is thrown
+  } catch (const cudf::test::AsyncException&) {
+    // Test passes if AsyncException is thrown (expected test exception)
+  } catch (const std::exception& e) {
+    // Test fails if any other exception is thrown
+    FAIL() << "Unexpected exception thrown: " << e.what();
```
Comment (mhaseeb123) [inline cpp/tests/io/parquet_reader_test.cpp:3220]: Better to use `EXPECT_THROW`, `EXPECT_ANY_THROW` and `EXPECT_NO_THROW` here and above as well.

**Review by ttnghia — APPROVED** [review]
Wow, I didn't know that `wait` doesn't throw!

File: cpp/tests/io/parquet_reader_test.cpp (hunk 1 above)
Comment (vuule) [reply cpp/tests/io/parquet_reader_test.cpp:3220]: there's no good way to check if a specific type is thrown, or none.

**Comment by vuule** [comment]
> Wow, I didn't know that `wait` doesn't throw!

Same :D
