### PR TITLE
Fix ast return_type_functor to handle decimal types with non-zero scale

### LINKED ISSUE #21980: [BUG] Nested decimal evaluation in `compute_column()` and `compute_column_jit()` erasing scale
**Describe the bug**

`compute_column` and `compute_column_jit` reject valid nested fixed-point AST expressions with `"An AST expression was provided non-matching operand types"`. The AST `expression_parser` loses scale information when computing the return type of intermediate operations.

In `cpp/src/ast/operators.cpp`, the `return_type_functor` computes intermediate result types via:

```cpp
using Out = cuda::std::invoke_result_t<OperatorFunctor, LHS, RHS>;
result = cudf::data_type{cudf::type_to_id<Out>()};
```

For fixed-point types, `type_to_id<decimal64>()` produces `cudf::data_type{DECIMAL64}` with **scale=0**, discarding the original scale. When the parser then processes an outer operation (e.g., MUL), it compares:
- Operand A: `DECIMAL64(scale=-2)` (from a column reference)
- Operand B: `DECIMAL64(scale=0)` (computed return type of inner SUB — scale lost)

These don't match, triggering the validation at `expression_parser.cpp:233`.

Single-level decimal operations (e.g., `MUL(col0, col1)`) work fine. Only nested expressions fail.

**Steps/Code to reproduce bug**

```cpp
#include <cudf/ast/expressions.hpp>
#include <cudf/column/column_factories.hpp>
#include <cudf/fixed_point/fixed_point.hpp>
#include <cudf/transform.hpp>
#include <cudf/types.hpp>
#include <rmm/cuda_stream_view.hpp>
#include <rmm/resource_ref.hpp>
#include <cuda_runtime.h>
#include <cstdio>
#include <memory>
#include <vector>

int main()
{
  auto stream = cudf::get_default_stream();
  auto mr     = cudf::get_current_device_resource_ref();

  constexpr int N      = 100;
  constexpr auto scale = numeric::scale_type{-2};
  auto const decimal_dt = cudf::data_type{cudf::type_id::DECIMAL64, scale};

  std::vector<int64_t> col0_host(N, 1000);  // 10.00
  std::vector<int64_t> col1_host(N, 5);     // 0.05

  auto col0 = cudf::make_fixed_point_column(decimal_dt, N, cudf::mask_state::UNALLOCATED, stream, mr);
  auto col1 = cudf::make_fixed_point_column(decimal_dt, N, cudf::mask_state::UNALLOCATED, stream, mr);
  cudaMemcpy(col0->mutable_view().data<int64_t>(), col0_host.data(), sizeof(int64_t) * N, cudaMemcpyHostToDevice);
  cudaMemcpy(col1->mutable_view().data<int64_t>(), col1_host.data(), sizeof(int64_t) * N, cudaMemcpyHostToDevice);

  std::vector<std::unique_ptr<cudf::column>> cols;
  cols.push_back(std::move(col0));
  cols.push_back(std::move(col1));
  auto table = std::make_unique<cudf::table>(std::move(cols));

  // AST: col0 * (literal - col1)
  // This is the TPC-H Q14 pattern: l_extendedprice * (1.00 - l_discount)
  cudf::ast::tree tree;
  auto ref0   = tree.emplace<cudf::ast::column_reference>(0);
  auto scalar = std::make_unique<cudf::fixed_point_scalar<numeric::decimal64>>(
    int64_t{100}, scale, true, stream, mr);  // 1.00
  auto lit    = tree.emplace<cudf::ast::literal>(*scalar);
  auto ref1   = tree.emplace<cudf::ast::column_reference>(1);
  auto sub_op = tree.emplace<cudf::ast::operation>(cudf::ast::ast_operator::SUB, lit, ref1);
  auto mul_op = tree.emplace<cudf::ast::operation>(cudf::ast::ast_operator::MUL, ref0, sub_op);

  try {
    auto result = cudf::compute_column(table->view(), mul_op, stream, mr);
    printf("PASS: %d rows\n", result->size());
  } catch (std::exception const& e) {
    printf("FAIL: %s\n", e.what());
  }

  return 0;
}
```

Output:

```
FAIL: CUDF failure at: .../ast/expression_parser.cpp:233: An AST expression was provided non-matching operand types.
```

**Expected behavior**

`compute_column` should successfully evaluate nested fixed-point expressions. `SUB(decimal64_scale-2, decimal64_scale-2)` returns `decimal64_scale-2` (per the `fixed_point` operator- implementation), so the operand types of the outer MUL should match. The `return_type_functor` should preserve scale when computing intermediate result types for fixed-point operations.

**Environment overview (please complete the following information)**
- Environment location: Bare-metal
- Method of cuDF install: conda (via pixi)

**Environment details**
- libcudf 26.02.00 (stable, `rapidsai` channel) — affected
- libcudf 26.04.00a452 (nightly, `rapidsai-nightly` channel) — also affected
- CUDA 13, GCC 14, RTX 4070 Ti
- Linux x86_64

**Additional context**

This blocks using `compute_column` / `compute_column_jit` for any expression tree containing nested fixed-point arithmetic, which is common in SQL workloads (e.g., TPC-H Q14: `l_extendedprice * (1 - l_discount)`).

Suggested fix: `return_type_functor` in `cpp/src/ast/operators.cpp` needs to preserve scale when computing fixed-point return types. For ADD/SUB the result scale should be `min(lhs.scale(), rhs.scale())`. For MUL it should be `lhs.scale() + rhs.scale()`. The operand `data_type` objects already carry scale — the functor just needs to propagate it to the result `data_type` instead of using the default (scale=0).

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Adds support the AST internal `return_type_functor` to handle decimal types with non-zero scale values.
This requires passing in operand type(s) to properly compute the appropriate output scale.
The output scale is also operator-specific and so static functions to compute the scale are added to the appropriate operator classes.

Code for supporting decimal results was actually missing. This PR adds specialization logic for `decimal32` and `decimal64` to the `resolve_output` utility to retrieve the `rep` component value and store it in the output column. The `decimal128` support is deferred since the maximum intermediate-value type size is `int64`.

Closes #21980

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/ast/operators.cpp [hunk 1]
```diff
@@ -244,13 +259,18 @@ cudf::data_type ast_operator_return_type(ast_operator op,
 {
   cudf::data_type result{cudf::type_id::EMPTY};
   switch (operand_types.size()) {
-    case 1:
-      unary_operator_dispatcher(op, operand_types[0], detail::return_type_functor{}, result);
+    case 1: {
+      auto const op_type = operand_types[0];
+      unary_operator_dispatcher(op, op_type, detail::return_type_functor{op_type}, result);
```
Comment (bdice) [inline cpp/src/ast/operators.cpp]: What if we passed through operand_types as a span? (Thinking about how to avoid arity-dependence.)

Comment (davidwendt) [reply cpp/src/ast/operators.cpp]: Ok

File: cpp/src/ast/operators.cpp [hunk 2]
```diff
@@ -244,13 +261,16 @@ cudf::data_type ast_operator_return_type(ast_operator op,
...
+    case 1: {
+      unary_operator_dispatcher(
+        op, operand_types, detail::return_type_functor{operand_types}, result);
       break;
-    case 2:
+    }
+    case 2: {
       binary_operator_dispatcher(
-        op, operand_types[0], operand_types[1], detail::return_type_functor{}, result);
+        op, operand_types, detail::return_type_functor{operand_types}, result);
```
Comment (bdice) [inline cpp/src/ast/operators.cpp:271]: Ah, I really only meant to suggest using `span` for `return_type_functor` since that's seemingly arity-independent unlike `binary_operator_dispatcher` (for which taking two separate arguments makes a lot of sense), but it's fine either way with me.

**Review by bdice — APPROVED** [review]
