### PR TITLE
[REVIEW] Fix regex infinite loop while parsing invalid quantifier pattern

### LINKED ISSUE #3725: [BUG] `\` aren't replaced in string accessor or nvstring, even with escacpe character
**Describe the bug**
Neither string accessor nor nvstrings can replace a `\` character, even if escaped.  Also, there is a bug where the kernel will crash if you don't escape a special character 

**Steps/Code to reproduce bug**
nvStrings Minimal
```
import nvstrings
s = nvstrings.to_device(["h\llo","go\dbye"])
print(s.replace('\\', ''))
```
outputs: 
```
['h\\llo', 'go\\dbye']
```
**cuDF with string accessor**
```
import cudf

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = cudf.read_csv(fn)
df.head()
```
output:

  | a | b | c
-- | -- | -- | --
0| test \ phase* 1 | 2 | 3
1| test \phase 2 | 4 | 5
2| test\phase* 3 | 6 | 7

And then replacement code:
```
df['a'] = df['a'].str.replace("\\","")
df['a'] = df['a'].str.replace("e","") # to show it works with alphanumerics
df['a'] = df['a'].str.replace("\*","") # to show it works with other escaped characters
df.head()
```
Outputs:

  | a | b | c
-- | -- | -- | --
0 |tst \ phas 1 | 2 | 3
1| tst \phas 2 | 4 | 5
2| tst\phas 3 | 6 | 7

**Expected behavior**
as with replace in strings, 
```
s = "h\llo"
print(s.replace('\\', ''))
```
Outputs:
```
hllo
```
i should get this output from `df['a'] = df['a'].str.replace("\\","")`:

  | a | b | c
-- | -- | -- | --
0 |tst  phas 1 | 2 | 3
1| tst phas 2 | 4 | 5
2| tstphas 3 | 6 | 7

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker using standard pull

**Additional context**
Was making a solution for https://stackoverflow.com/questions/59530094/python-coding-for-gpu/59651737#59651737 when i discovered the bug

Also, when testing, i wanted to see what would happen if i neglected the `\` and `df['a'] = df['a'].str.replace("*","")` ran for about 10-20 seconds until the kernal crashed.

### LINKED ISSUE #3732: [BUG] Special Characters cause `str.replace()` to crash if you don't use an escape character
**Describe the bug**
Running `str.replace()` on a special character without the escape character `\` causes the kernel to crash without an error

**Steps/Code to reproduce bug**
```
import cudf

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = cudf.read_csv(fn)
df['a'] = df['a'].str.replace("*","")
```
---Kernel will crash in less than 30 seconds----

**Expected behavior**
I expect an error to be thrown, and the kernel still run.  

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker

**Environment details**
RAPIDS v0.12

### LINKED ISSUE #4671: [BUG] contains_re() can return incorrect result for empty string input
**Describe the bug**
Using `contains_re` with regex pattern = `.*` on an input string which is empty or `""` returns false even though `matches_re` returns `true`

**Steps/Code to reproduce bug**
  ``` 
 TEST_F(StringsContainsTests, emptyness)
{
    std::string medium_regex = ".*";

    std::vector<const char*> h_strings{
        ""
    };
    cudf::test::strings_column_wrapper strings( h_strings.begin(), h_strings.end(),
        thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));

    auto strings_view = cudf::strings_column_view(strings);
    {
        auto results = cudf::strings::contains_re(strings_view, medium_regex);
        cudf::experimental::bool8 h_expected[] = {true};
        cudf::test::fixed_width_column_wrapper<cudf::experimental::bool8> expected( h_expected, h_expected+h_strings.size(),
            thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));
        cudf::test::expect_columns_equal(*results,expected);
    }
}
```
**Expected behavior**
`contains_re` behavior  should match `matches_re`'s behavior in this specific case.
pattern = `.*`
input = `[""]`
result = `[true]`

**Environment overview (please complete the following information)**
cudf 0.14 + Ubuntu 18.04

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #3732 
Closes #3725 
Any regex quantifier requires a previous item to repeat in the expression pattern.
For example "a*" means to match "a" zero or more times.
An invalid quantifier expression like simply "*" (no preceding char to check) was causing the regex parser to go into an infinite loop trying to resolve the previous item.
Likewise, an invalid escape sequence like "\" (single backslash) was being silently ignored.
The code logic has been fixed in this PR and errors are returned for invalid regex patterns.

Closes #4671 
The `contains()` was incorrectly returning false for empty string with regex pattern ".*"
This was due to the end-parm being set to 0 (size of empty string) on the regex find() function.
The find() allows the end-parm to be -1 to indicate to the end of the string which returns the correct result.
Adding this simple one-line fix and tests to this PR as well.

### CODE REVIEW

**Comment by rgsl888prabhu** [comment]
@davidwendt not sure whether they are relevant, there is one more issue https://github.com/rapidsai/cudf/issues/4671

**Comment by davidwendt** [comment]
After talking with @taureandyernv, we decided to throw an error for the invalid regex. This is different than Pandas which somehow silently turns regex off (?) but the results are more predictable for the caller.

**Comment by davidwendt** [comment]
Based on https://github.com/rapidsai/cudf/issues/3725#issuecomment-604471956
I added the one-line change needed in `string.py` to support single-char pattern calling `strings::replace()` instead of `strings::replace_re()`.

File: cpp/src/strings/regex/regcomp.cpp [hunk 1]
```diff
@@ -14,10 +14,11 @@
 * limitations under the License.
 */
 
+#include <cudf/utilities/error.hpp>
 #include <strings/regex/regcomp.h>
 
 #include <string.h>
-
+#include <map>
```
Comment (harrism) [inline cpp/src/strings/regex/regcomp.cpp]: From the below it looks like you meant set?

```suggestion
#include <set>
```

File: cpp/src/strings/regex/regcomp.cpp [hunk 2]
```diff
@@ -53,6 +54,13 @@ static reclass ccls_S(16); // not ccls_s
 static reclass ccls_d(4);  // digits [0-9]
 static reclass ccls_D(32); // not ccls_d plus '\n'
 
+// Tables for analyzing quantifiers
+std::set<int> valid_preceding_inst_types( {CHAR, CCLASS, NCCLASS, ANY, ANYNL} );
```
Comment (harrism) [inline cpp/src/strings/regex/regcomp.cpp]: I wouldn't use `std::set` for fixed-size arrays -- paying a lot of overhead. These are so small that you would probably be better off using `std::array` (since size is known at compile time), and then use `std::find()` to search them.  (You could also pre-sort thew contents and use `std::binary_search()`).

File: cpp/src/strings/regex/regcomp.cpp [hunk 3]
```diff
@@ -439,15 +445,70 @@ class regex_parser
                     return BOL;
                 case 'Z':
                     return EOL;
+                default:
+                {
+                    // let valid escapable chars fall through as literal CHAR
+                    if( yy && (escapable_chars.find(static_cast<char>(yy)) != escapable_chars.end()) )
+                        break;
+                    // anything else is a bad escape so throw an error
+                    std::ostringstream message;
```
Comment (harrism) [inline cpp/src/strings/regex/regcomp.cpp]: Looks like we need a CUDF_FAIL that takes a non-literal string.

Comment (jrhemstad) [reply cpp/src/strings/regex/regcomp.cpp]: I don't think the dynamic string is really necessary here. It would be perfectly fine to just say:
```
CUDF_FAIL("Invalid regex pattern: bad escape");`
```

There aren't other places in libcudf where we try and further introspect the error condition. E.g., if checking for if two columns have the same type, we just say "type mismatch". We don't try and introspect what the two different types are and print them.

Comment (davidwendt) [reply cpp/src/strings/regex/regcomp.cpp]: The error is reporting where in the regex pattern the offending character was found. I've seen some really messed up regex patterns. This is helpful in telling the user (not necessarily a coder) where the bad character was found in very long, complicate expressions.
For example, where is the bad escape sequence in the following?
```
"\"\a\b\\%\p\t\7\\\b\A\Z]\"(?:|(?:.*?(?![^\\]\\\")).?)[^\\]?\",?\s*)*)\]"
```
We have the information and I don't see why we cannot report this to the user.

Comment (jrhemstad) [reply cpp/src/strings/regex/regcomp.cpp]: You now have to maintain the extra logic of detecting the "what" and "where" of the error, which adds extra complexity (as evidenced by the fact that `CUDF_FAIL` isn't being used directly and instead manually throwing an exception). 

This may not seem like a big deal isolated to this feature, but imagine multiplying this out to every exception thrown in libcudf. 

It also sets up a dangerous precedent where the user might expect libcudf to do all of the work of trying to detect all possible bad regex patterns and report exactly what is wrong with them. 

> We have the information and I don't see why we cannot report this to the user.

The same is true for every exception thrown in libcudf. Just because you _can_ do something, doesn't mean you _should_. 

If you're not convinced and do decide to keep it, don't use `ostringstream`. It's way slower than just doing regular old string concatenation. Also, add a `CUDF_FAIL_STRING` macro that abstracts the throwing of `cudf::logic_error` with a non string literal.

**Comment by davidwendt** [comment]
rerun tests

**Comment by davidwendt** [comment]
rerun tests
