### PR TITLE
Incorrect map size in scatter_to_gather corrupts struct columns

### LINKED ISSUE #8356: [BUG] copy_if_else producing incorrect answers for structs
**Describe the bug**
When trying to implement `Case/When` and `If/Else` for Spark for Structs I ran into a test that was failing. I brought the size of the test data down a lot, but it looks like NULLs are being inserted into incorrect places for some result/

**Steps/Code to reproduce bug**
```diff
diff --git a/cpp/tests/copying/copy_if_else_nested_tests.cpp b/cpp/tests/copying/copy_if_else_nested_tests.cpp
index 9ac34a3044..7ad374ca3b 100644
--- a/cpp/tests/copying/copy_if_else_nested_tests.cpp
+++ b/cpp/tests/copying/copy_if_else_nested_tests.cpp
@@ -102,6 +102,66 @@ TYPED_TEST(TypedCopyIfElseNestedTest, StructsWithNulls)
   CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(result_column->view(), expected_result->view());
 }
 
+TYPED_TEST(TypedCopyIfElseNestedTest, LongerStructsWithNulls)
+{
+  using T = TypeParam;
+
+  using namespace cudf;
+  using namespace cudf::test;
+
+  using ints    = fixed_width_column_wrapper<T, int32_t>;
+  using structs = structs_column_wrapper;
+  using bools   = fixed_width_column_wrapper<bool, int32_t>;
+
+  auto selector_column = bools{
+      1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
+      1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
+      0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
+      1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
+      0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
+      0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
+      1, 0, 1, 1, 1, 0}.release();
+
+  std::cerr << "AT 1" << std::endl;
+  auto lhs_child_0 = ints{{
+       120,   16,   53, -121,  -15,   21,  -33,   72,   54,   90,
+       -67, -117,  -77,    0,  113,   15,  -87,   77, -128,    0,
+         0,    0,  115,   49, -107,   10,  -62,  -78,  -49,   73,
+        92,  -22,    0,  127,  -49,  101,  -82,    0,    6, -110,
+        69,  -29,  -63,  105,  -18,   84, -113,  -65,    0,   29,
+       -61,   53,   62,   87,  -84,  -49, -108,  -85,  -21,   21,
+        84,   53,   56,  -56,  -53,  -28
+      }, iterator_with_null_at(std::vector<size_type>{13, 19, 20, 21, 32, 37, 48})};
+
+  std::cerr << "AT 2" << std::endl;
+  auto lhs_child_1 = ints{{
+        27,  -80,  -24,   76,  -56,   42,    5,   13,  -69,  -77,
+        61,  -77,   72,    0,   31,  118,  -30,   86,  125,    0,
+         0,    0,   75,  -49,  125,   60,  116,  118,   64,   20,
+       -70,  -18,    0,  -25,   22,  -46,  -89,   -9,   27,  -56,
+       -77,  123,    0,  -90,   87, -113,  -37,   22,  -22,  -53,
+        73,   99,  113,   -2,  -24,  113,   75,    6,   82,  -58,
+       122, -123, -127,   19,  -62,  -24
+      }, iterator_with_null_at(std::vector<size_type>{13, 19, 20, 21, 32, 42})};
+
+  std::cerr << "AT 3" << std::endl;
+  auto lhs_structs_column = structs{{lhs_child_0, lhs_child_1}, 
+      iterator_with_null_at(std::vector<size_type>{13, 19, 20, 21, 32})}.release();
+
+  std::cerr << "AT 4" << std::endl;
+  cudf::test::print(*lhs_structs_column);
+
+  auto result_column =
+    copy_if_else(lhs_structs_column->view(), lhs_structs_column->view(), selector_column->view());
+
+  std::cerr << "AT 8" << std::endl;
+  cudf::test::print(*result_column);
+
+  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(result_column->view(), lhs_structs_column->view());
+}
+
+
+
 TYPED_TEST(TypedCopyIfElseNestedTest, Lists)
 {
   using T = TypeParam;
```

**Expected behavior**
The test should pass because the the lhs and rhs of the copy_if_else is the same thing so I don't see how we would ever get anything back except the lhs, but we get back a different answer (and some how it also crashes, which is separate)

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes the scatter map size to the target column size. 
Simplifies `copy_if_else` by skipping gather on lhs, and using lhs directly as the rhs scatter destinations for 0-rows in select col.

Closes #8356

Co-authored-by: @mythrocks

### CODE REVIEW

File: cpp/tests/copying/scatter_struct_tests.cpp [hunk 1]
```diff
@@ -241,3 +241,21 @@ TYPED_TEST(TypedStructScatterTest, SourceSmallerThanTargetScatterTest)
...
+  auto struct_col_1 = structs_col({child_1}).release();
+
+  auto scatter_map = int32s_col{2}.release();
+
+  auto expected_child  = int32s_col({0, -1, 20}, null_at(1));
+  auto expected_struct = structs_col({expected_child}).release();
+
+  auto result_ptr = scatter_structs(struct_col_1, struct_col_0, scatter_map);
+
+  CUDF_TEST_EXPECT_COLUMNS_EQUAL(*expected_struct, result_ptr, print_all);
```
Comment (ttnghia) [inline cpp/tests/copying/scatter_struct_tests.cpp:260]:
```suggestion
  auto child_tgt      = col_wrapper({0, -1, 2}, null_at(1));
  auto struct_col_tgt = structs_col({child_tgt}).release();

  auto child_src      = col_wrapper({20});
  auto struct_col_src = structs_col({child_src}).release();

  auto scatter_map = int32s_col{2}.release();

  auto expected_child  = col_wrapper({0, -1, 20}, null_at(1));
  auto expected_struct = structs_col({expected_child}).release();

  auto const result = scatter_structs(struct_col_src, struct_col_tgt, scatter_map);
  CUDF_TEST_EXPECT_COLUMNS_EQUAL(*expected_struct, result, print_all);
```

**Review by ttnghia — CHANGES_REQUESTED** [review]

File: cpp/tests/copying/scatter_struct_tests.cpp (hunk 1 above)
Comment (gerashegalov) [reply cpp/tests/copying/scatter_struct_tests.cpp:260]: This suggestion does not compile

Comment (ttnghia) [reply cpp/tests/copying/scatter_struct_tests.cpp:260]: What's the error message?

Comment (gerashegalov) [reply cpp/tests/copying/scatter_struct_tests.cpp:260]:
```
../tests/copying/scatter_struct_tests.cpp: In member function ‘virtual void TypedStructScatterTest_IntStructNullMaskRegression_Test<gtest_TypeParam_>::TestBody()’:
../tests/copying/scatter_struct_tests.cpp:247:27: error: there are no arguments to ‘col_wrapper’ that depend on a template parameter, so a declaration of ‘col_wrapper’ must be available [-fpermissive]
  247 |     auto child_tgt      = col_wrapper({0, null, 2}, null_at(1));
      |                           ^~~~~~~~~~~
../tests/copying/scatter_struct_tests.cpp:247:27: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../tests/copying/scatter_struct_tests.cpp:250:25: error: ‘col_wrapper’ was not declared in this scope
  250 |   auto child_src      = col_wrapper{20};
      |                         ^~~~~~~~~~~
../tests/copying/scatter_struct_tests.cpp: In instantiation of ‘void TypedStructScatterTest_IntStructNullMaskRegression_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = unsigned int]’:
../tests/copying/scatter_struct_tests.cpp:245:1:   required from here
../tests/copying/scatter_struct_tests.cpp:247:38: error: ‘col_wrapper’ was not declared in this scope
  247 |     auto child_tgt      = col_wrapper({0, null, 2}, null_at(1));
  ....
```

File: cpp/include/cudf/detail/scatter.cuh [hunk 2]
```diff
@@ -305,7 +305,7 @@ struct column_scatterer_impl<struct_view> {
                                             [](auto const& col) { return col.nullable(); });
     if (child_nullable) {
       auto const gather_map =
-        scatter_to_gather(scatter_map_begin, scatter_map_end, source.size(), stream);
+        scatter_to_gather(scatter_map_begin, scatter_map_end, target.size(), stream);
```
[the remark this answers is not in the document]
Comment (mythrocks) [reply cpp/include/cudf/detail/scatter.cuh:308]: Yep. :/ I remember reviewing this code, and discussing the null-mask pushdown. 

Should be fixed now.

File: cpp/tests/copying/scatter_struct_tests.cpp (hunk 1 above)
Comment (ttnghia) [reply cpp/tests/copying/scatter_struct_tests.cpp:260]: I see. Just fixed that (edited the code above). Please test again.

Comment (gerashegalov) [reply cpp/tests/copying/scatter_struct_tests.cpp]: This worked, thanks @ttnghia

**Review by ttnghia — APPROVED** [review]

**Review by harrism — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]
I don't know if my approval is strictly kosher here, but 👍.

We can add a test for `LEAD()`/`LAG()` at a later date. I'm certain that this fixes that as well.

**Comment by mythrocks** [comment]
@wbo4958, this PR should resolve #8281. :]

**Comment by harrism** [comment]
@mythrocks I discussed with @sameerz and @revans2 and they agreed this is not needed in 21.06 because Spark has disabled this functionality in that release due to the issue fixed here.

**Comment by harrism** [comment]
@gpucibot merge
