### PR TITLE
[REVIEW] Fix `cudf::split` issue returning one less than expected column vectors

### LINKED ISSUE #4027: [BUG] cudf::split function can return one less than expected number of column vectors
**Describe the bug**
In a corner case where the last two(or more) consecutive split indices are equal to the rowcount of the columnvector, the number of splits returned is one less than expected as shown below.

**Steps/Code to reproduce bug**
Java unit test.
```    try(ColumnVector cv = ColumnVector.fromBoxedInts(10, 12, 13, 14)) {
      Integer[][] expectedData = {
          {10, 12, 13, 14},
          {},
          {},
          {}};

      ColumnVector[] splits = cv.split(4, 4, 4); // or (3,4,4) with expectedData ={ {10,12,13},{14},{},{}}
      try {
        assertEquals(expectedData.length, splits.length);
        for (int splitIndex = 0; splitIndex < splits.length; splitIndex++) {
          ColumnVector subVec = splits[splitIndex];
          subVec.ensureOnHost();
          assertEquals(expectedData[splitIndex].length, subVec.getRowCount());
        }
      } finally {
        for (int i = 0 ; i < splits.length ; i++) {
          if (splits[i] != null) {
            splits[i].close();
          }
        }
      }
    }
```
The assert : `assertEquals(expectedData.length, splits.length);` fails with expected = 4 and actual size = 3. The last two entries out of the three in the splits are column vectors of rowcount = 0.
If splits is called with (3,4,4) it fails in the same way. Additionally, If the splits are such that the last one is non-empty, the test will pass.

**Expected behavior**
Actual size should be 4 , with last entry being a columnvector with rowcount = 0

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
This was due a check which removed the last possible vector. 
close #4027

### CODE REVIEW

File: cpp/include/cudf/copying.hpp [hunk 1]
```diff
@@ -367,6 +367,7 @@ std::vector<table_view> slice(table_view const& input,
  * `splits[i] != input.size()`, or `[splits[i-1], splits[i]]` otherwise.
  *
  * For all `i` it is expected `splits[i] <= splits[i+1] <= input.size()`
+ * For a `splits` size N, there will always be N+1 splits in the output
```
Comment (jrhemstad) [inline cpp/include/cudf/copying.hpp]: Can you update the above documentation that says `splits[i] != input.size()`

Comment (rgsl888prabhu) [reply cpp/include/cudf/copying.hpp]: Ahh, missed that.
