### PR TITLE
Fix `chunked_parquet_reader` behavior when input has no more rows to read

### LINKED ISSUE #15743: [BUG] chunked parquet reader is not factoring empty dataframes with `>0` columns present
**Describe the bug**
A dataframe can have `>0` columns when it has 0 rows. There are two issues at play here:

1. chunked parquet reader seems to be returning `False` when we do `has_next`, but return an empty dataframe correctly when we call `read_chunk`.
2. When a parquet file is completely exhausted `has_next` returns `False` and `read_chunk` raises a `RuntimeError` - as expected, But incase of empty dataframes, `has_next` returns `False` and `read_chunk` endlessly keeps returning the empty dataframe without any error.

**Steps/Code to reproduce bug**
```python
# Non-empty - working case

In [1]: import cudf

In [2]: df = cudf.DataFrame({'a': [1, 1, 1, 2, 2], 'b': [1,2 ,3, 4, 5]})

In [3]: df.to_parquet("a.parquet")

In [4]: from cudf._lib.parquet import ParquetReader


In [6]: reader = ParquetReader(["a.parquet"])

In [8]: reader._has_next()
Out[8]: True

In [9]: reader._read_chunk()
Out[9]: 
   a  b
0  1  1
1  1  2
2  1  3
3  2  4
4  2  5

In [10]: reader._has_next()
Out[10]: False

In [11]: reader._read_chunk()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[11], line 1
----> 1 reader._read_chunk()

File parquet.pyx:851, in cudf._lib.parquet.ParquetReader._read_chunk()

RuntimeError: Fatal CUDA error encountered at: /nvme/0/pgali/cudf/cpp/include/cudf/detail/utilities/vector_factories.hpp:277: 700 cudaErrorIllegalAddress an illegal memory access was encountered




# Empty - bug case
In [1]: import cudf

In [2]: df = cudf.DataFrame({'a': [], 'b': []})

In [3]: df
Out[3]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [4]: df.to_parquet("a.parquet")

In [5]: from cudf._lib.parquet import ParquetReader

In [6]: reader = ParquetReader(["a.parquet"])

In [7]: reader._has_next()  
Out[7]: False     # Expected: True

In [8]: reader._read_chunk()
Out[8]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [9]: reader._read_chunk()    # Expected: RuntimeError
Out[9]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [10]: reader._read_chunk()   # Expected: RuntimeError
Out[10]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [11]: reader._read_chunk()    # Expected: RuntimeError
Out[11]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [12]: reader._has_next()  
Out[12]: False
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description

Fixes #15743 

This PR solves two problems. 

First, it does not any longer throw a CUDA failure or exception when an invalid (out of bound) chunk is read via `chunked_parquet_reader::read_chunk()` and instead returns an empty chunk.

Second, for empty tables, it returns true for `has_next()` until the first call to `chunked_parquet_reader::read_chunk()`. After that `has_next()` returns false but `chunked_parquet_reader::read_chunk()` keeps returning empty chunks

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by mhaseeb123** [comment]
Committed the changes to return empty table when an out of bound chunk is read.

File: cpp/src/io/parquet/reader_impl.hpp [hunk 1]
```diff
@@ -387,6 +394,7 @@ class reader::impl {
 
   file_intermediate_data _file_itm_data;
   bool _file_preprocessed{false};
+  bool _first_pass_in_empty_table{false};
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl.hpp:397]: I think this can just be "is first pass". We do always return at least one chunk.
That said, I wonder if we can derive if we're in the first pass from the existing state.

File: cpp/src/io/parquet/reader_impl.cpp [hunk 2]
```diff
@@ -557,13 +559,17 @@ table_with_metadata reader::impl::finalize_output(
...
+  if (_file_itm_data._current_input_pass < _file_itm_data.num_passes()) {
     auto& pass    = *_pass_itm_data;
     auto& subpass = *pass.subpass;
     subpass.current_output_chunk++;
     _file_itm_data._output_chunk_count++;
   }
+  // The first pass into the empty table is completed. Disable any more passes.
+  else if (_first_pass_in_empty_table) {
+    _first_pass_in_empty_table = false;
+  }
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl.cpp:572]:
```suggestion
  if (_first_pass_in_empty_table) {
    _first_pass_in_empty_table = false;
  }
```

File: cpp/src/io/parquet/reader_impl.hpp (hunk 1 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.hpp:397]: I think we should keep it as `_first_pass_in_empty_table` as this variable only activates for empty tables to activate special handling (true until `read_chunk() called) of first pass in `has_next()` for empty tables. For non-empty tables, `has_next()` isn't affected by the pass number so this variable stays dormant.

File: cpp/src/io/parquet/reader_impl.cpp [hunk 3]
```diff
@@ -557,13 +559,17 @@ table_with_metadata reader::impl::finalize_output(
...
   }
 
-  // advance output chunk/subpass/pass info
-  if (_file_itm_data.num_passes() > 0) {
+  // advance output chunk/subpass/pass info for non-empty tables if and only if we are in bounds
+  if (_file_itm_data._current_input_pass < _file_itm_data.num_passes()) {
     auto& pass    = *_pass_itm_data;
     auto& subpass = *pass.subpass;
     subpass.current_output_chunk++;
     _file_itm_data._output_chunk_count++;
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl.cpp:567]: > That said, I wonder if we can derive if we're in the first pass from the existing state.

We can certainly determine this by taking `_file_itm_data._output_chunk_count++` out of the if clause but it might not be segfault safe if somebody uses this without verifying `_file_itm_data._output_chunk_count < _file_itm_data.num_passes()`

**Comment by mhaseeb123** [comment]
Simplified the changes!

**Review by vuule — APPROVED** [review]

File: cpp/src/io/parquet/reader_impl.hpp [hunk 4]
```diff
@@ -347,6 +354,8 @@ class reader::impl {
   }
 
  private:
+  bool is_first_output_chunk() { return _file_itm_data._output_chunk_count == 0; }
```
Comment (karthikeyann) [inline cpp/src/io/parquet/reader_impl.hpp:357]: nit: `[[nodiscard]]` and `const`.

File: cpp/tests/io/parquet_chunked_reader_test.cu [hunk 5]
```diff
@@ -1409,3 +1409,72 @@ TEST_F(ParquetChunkedReaderInputLimitTest, Mixed)
   constexpr int expected_c[] = {20, 21, 15, 14};
   input_limit_test_read(test_filenames, tbl, 128 * 1024 * 1024, 512 * 1024 * 1024, expected_c);
 }
+
+TEST_F(ParquetChunkedReaderTest, TestChunkedReadOutOfBoundChunks)
+{
+  auto const generate_input = [](int num_rows, bool nullable, bool use_delta) {
```
Comment (karthikeyann) [inline cpp/tests/io/parquet_chunked_reader_test.cu:1415]: nit: `use_delta` is unused.

Comment (karthikeyann) [reply cpp/tests/io/parquet_chunked_reader_test.cu:1415]: question: is there any reason for declaring this lambda as `const`, but next lambda is not const? (no variables are captured in both).

**Review by karthikeyann — COMMENTED** [review]
LGTM 👍
minor nitpicks and styles.

**Review by karthikeyann — APPROVED** [review]

File: cpp/tests/io/parquet_chunked_reader_test.cu (hunk 5 above)
Comment (mhaseeb123) [reply cpp/tests/io/parquet_chunked_reader_test.cu:1415]: Thanks for pointing this. Just copy pasted segments from one the tests above. Let me make both `const`.

Comment (mhaseeb123) [reply cpp/tests/io/parquet_chunked_reader_test.cu]: All done!

File: cpp/src/io/parquet/reader_impl.hpp (hunk 4 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.hpp]: All done!

**Comment by vuule** [comment]
I have another nit - the PR title is too long :D
