### PR TITLE
[Java] CollectSetAggregation: implement RollingAggregation interface [skip ci]

### LINKED ISSUE #8412: [FEA] Java: CollectSetAggregation need to implement the RollingAggregation interface
**Describe the bug**
After the introduction of the `RollingAggregation` interface, each Aggregation Operation, which can be used in rolling window, need to implement it. Otherwise, they can not corporate with the holder `AggregationOverWindow`.

**Expected behavior**
I filed #8406 to fix this issue.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fix #8412

### CODE REVIEW

File: java/src/main/java/ai/rapids/cudf/Aggregation.java [hunk 1]
```diff
@@ -300,7 +300,11 @@ public boolean equals(Object other) {
         }
     }
 
-    private static final class CollectSetAggregation extends Aggregation {
+    /**
+     * WARNING: https://github.com/rapidsai/cudf/issues/8405
+     */
+    public static final class CollectSetAggregation extends Aggregation
```
Comment (firestarman) [inline java/src/main/java/ai/rapids/cudf/Aggregation.java:306]: Isn't the class `private ` here ? Since this class should not be used directly, instead calling `collectSet` to get one.

Comment (sperlingxx) [reply java/src/main/java/ai/rapids/cudf/Aggregation.java:306]: It should be `public` because we need to use this class as a type parameter in spark-rapids, just like [here](https://github.com/NVIDIA/spark-rapids/blob/branch-21.06/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala#L670).

Comment (firestarman) [reply java/src/main/java/ai/rapids/cudf/Aggregation.java:306]: OK, if the class is required to be public, shall we need to make its constrcutors be private to avoid creating a CollectSetAggregation directly ?

Comment (sperlingxx) [reply java/src/main/java/ai/rapids/cudf/Aggregation.java:306]: Good idea, it's private now.

**Comment by firestarman** [comment]
LGTM

**Review by firestarman — APPROVED** [review]

File: java/src/main/java/ai/rapids/cudf/Aggregation.java [hunk 2]
```diff
@@ -300,12 +300,16 @@ public boolean equals(Object other) {
         }
     }
 
-    private static final class CollectSetAggregation extends Aggregation {
+    /**
+     * WARNING: https://github.com/rapidsai/cudf/issues/8405
```
Comment (ttnghia) [inline java/src/main/java/ai/rapids/cudf/Aggregation.java:304]: What?

File: java/src/main/java/ai/rapids/cudf/Aggregation.java [hunk 3]
```diff
@@ -717,6 +721,8 @@ public static CollectSetAggregation collectSet() {
 
     /**
      * Collect the values into a set.
+     * WARNING: Due to the bug in libcudf (https://github.com/rapidsai/cudf/issues/8405),
```
Comment (ttnghia) [inline java/src/main/java/ai/rapids/cudf/Aggregation.java:724]: Now we have a PR for fixing this so we can remove the comment.

**Review by ttnghia — CHANGES_REQUESTED** [review]

File: java/src/main/java/ai/rapids/cudf/Aggregation.java (hunk 2 above)
Comment (revans2) [reply java/src/main/java/ai/rapids/cudf/Aggregation.java:304]: I agree that more of an explanation of what the issue is would be good.  I would like to keep the link because it can help people with traceability to know if it has been fixed or not.

**Review by revans2 — COMMENTED** [review]
I think the change is fine. The problem is that 21.06 is already frozen, so you can re-target this to 21.08. or We are going to have to jump through a lot of hoops to show that this is a blocker and we have to re-open 21.06.

**Review by ttnghia — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Comment by sperlingxx** [comment]
@gpucibot merge
