### PR TITLE
[REVIEW] Fix strings::all_characters_of_type to allow verify-types mask

### LINKED ISSUE #4737: [BUG] Different behavior islower/isupper and all_characters_of_type
References issue #3987 and PR #4333. Specifically the comment here: https://github.com/rapidsai/cudf/issues/3987#issuecomment-595000079

It would appear that Pandas ignores non-alpha char types when using isupper/islower.
```
import pandas as pd
import cudf
ps = pd.Series(["a1","A1","a!","A!","!1","aA"])
ds = cudf.Series(["a1","A1","a!","A!","!1","aA"])
ps.str.isupper()
ds.str.isupper()
ps.str.islower()
ds.str.islower()
```
Results in a table:
```
                'a1',  'A1',  'a!',  'A!',  '!1',  'aA'
pandas isupper  False, True,  False, True,  False, False 
  cudf isupper  False, False, False, False, False, False

pandas islower  True,  False, True,  False, False, False
  cudf islower  False, False, False, False, False, False
```

Maybe introduce a mask parameter to the `cudf::strings::all_characters_of_type` to identify which character types to 'allow' when checking the types.

### PR DESCRIPTION
**Pull request by davidwendt**
Closes #4737 
The `cudf::strings::all_characters_of_type()` API accepts a `string_character_types` parameter that is used to exclusively check for specific character types within each string in a strings column. Types consist of `DECIMAL`, `SPACE`, `NUMERIC`, `ALPHA`, and others as well as `LOWER` and `UPPER`. If any of the characters in the string do not match type specified, then false is returned for that string.
This works correctly for the Python `is_()` methods except for `islower()` and `isupper()` which only check the cased characters and ignore the other characters. Therefore, `"ab!!cd".islower()` returns true even though there are two punctuation symbols included in the string.

This PR introduces a new parameter to the `all_characters_of_type()` API to specify which characters should be verified. It uses the same values from the `string_character_types` enum and can be combined to build a mask of types to check. The default value for the new parameter will be the new `ALL_TYPES` so the non-cased versions of the `is_` functions continue to work without change. Checking the characters for `islower()` and `isupper()` methods is performed by specifying the `UPPER|LOWER` combination in the new `verify_types` parameter.

Additional tests are added to specifically check for this combination behavior.
The new parameter also requires updating the Cython layer.
Finally, the warning statements from the `string.py` methods are removed here as well.

### CODE REVIEW

File: cpp/include/cudf/strings/char_types/char_types.hpp [hunk 1]
```diff
@@ -26,6 +26,9 @@ namespace strings
 /**
  * @brief Character type values.
  * These types can be or'd to check for any combination of types.
+ *
+ * This cannot be turned into an enum class because or'd entries can
+ * result in values that are not in the class.
```
Comment (cwharris) [inline cpp/include/cudf/strings/char_types/char_types.hpp:31]: I'm not sure what this means. Can you provide an example? Just that not all combinations of bits has a meaning?

File: cpp/include/cudf/strings/char_types/char_types.hpp [hunk 2]
```diff
@@ -35,9 +38,29 @@ enum string_character_types : uint32_t {
...
+    return static_cast<string_character_types>(
+        static_cast<std::underlying_type<string_character_types>::type>(lhs) |
+        static_cast<std::underlying_type<string_character_types>::type>(rhs)
+    );
+}
+
+string_character_types& operator|=(string_character_types& lhs, string_character_types rhs)
+{
+    lhs = static_cast<string_character_types>(
+        static_cast<std::underlying_type<string_character_types>::type>(lhs) |
```
Comment (cwharris) [inline cpp/include/cudf/strings/char_types/char_types.hpp:58]: `underlying_type_t` is a thing, so you wouldn't need the `::type` at the end.

File: cpp/include/cudf/strings/char_types/char_types.hpp (hunk 1 above)
Comment (davidwendt) [reply cpp/include/cudf/strings/char_types/char_types.hpp:31]: There are many combinations that have meaning. If you want to check for types NUMERIC and SPACE then you could specify NUMERIC|SPACE. If this were a class enum then this combination could not map to any existing class item. Not sure if that helps.

Comment (cwharris) [reply cpp/include/cudf/strings/char_types/char_types.hpp]: Yes it does. I have never tried to `&` or `|` class enums, but it makes sense that it would not work.

**Comment by davidwendt** [comment]
> Changes are good to go, could we also have the same test added to python?
> All we can do is just add `["a1","A1","a!","A!","!1","aA"]` to this python list: https://github.com/rapidsai/cudf/blob/branch-0.14/python/cudf/cudf/tests/test_string.py#L1085

Looks like I should be able to remove the specialized xfail'd function here and move the `isupper` and `islower` to the `type_op` array as well:
https://github.com/rapidsai/cudf/blob/627ebc51cc48188ea06c801bc1924e72060789ed/python/cudf/cudf/tests/test_string.py#L1122-L1125
