### PR TITLE
Filter Parquet row groups using row bounds

### LINKED ISSUE #19064: [BUG] Parquet filters combined with skip_rows/nrows fail in some scenarios
```python
import pylibcudf as plc
import numpy as np


# Make the table

sink = plc.io.SinkInfo(["foo.pq"])
column = plc.Column.from_array(np.arange(500_000, dtype="int32"))
table = plc.Table([column])
metadata = plc.io.types.TableInputMetadata(table)
metadata.column_metadata[0].set_name("a")

builder = plc.io.parquet.ParquetWriterOptions.builder(sink, table)
options = builder.metadata(metadata).build()
options.set_row_group_size_rows(100_000)

plc.io.parquet.write_parquet(options)

source = plc.io.SourceInfo(["foo.pq"])

def good():
    good_expr = plc.expressions.Operation(
        plc.expressions.ASTOperator.GREATER_EQUAL,
        plc.expressions.ColumnNameReference("a"),
        plc.expressions.Literal(plc.Scalar.from_numpy(np.int32(99_999))),
    )

    builder = plc.io.parquet.ParquetReaderOptions.builder(source)
    options = builder.build()
    # read table rows [50_000, 50_100) and apply filter `a >= 99_999`
    options.set_filter(good_expr)
    options.set_skip_rows(50_000)
    options.set_num_rows(100)

    tmeta = plc.io.parquet.read_parquet(options)
    
    print(plc.interop.to_arrow(tmeta.tbl))

good()


def bad():
    bad_expr = plc.expressions.Operation(
        plc.expressions.ASTOperator.GREATER_EQUAL,
        plc.expressions.ColumnNameReference("a"),
        plc.expressions.Literal(plc.Scalar.from_numpy(np.int32(100_000))),
    )

    builder = plc.io.parquet.ParquetReaderOptions.builder(source)
    options = builder.build()
    # read table rows [50_000, 50_100) and apply filter `a >= 100_000`
    options.set_filter(bad_expr)
    options.set_skip_rows(50_000)
    options.set_num_rows(100)

    tmeta = plc.io.parquet.read_parquet(options)
    
    print(plc.interop.to_arrow(tmeta.tbl))

bad()
```
The above code makes a parquet file with a single column `a` of integers from `[0, 499_999)`. With row groups of 100_000 rows.

We then read that file two ways:

1 (good): filter is `a >= 99_999`, `skip_rows = 50_000`, `num_rows = 100`
2 (bad) : filter is `a >= 100_000`, `skip_rows = 50_000`, `num_rows = 100`

In the first case, we get back the (expected) empty table. In the second case, we get back a table with 400_000 rows in it:

```
$ python bug.py
pyarrow.Table
: int32 not null
----
: [[]]
pyarrow.Table
: int32 not null
----
: [[100000,100001,100002,100003,100004,...,499995,499996,499997,499998,499999]]
```

It appears that if the filter is such that the first row group is discarded entirely, the remainder of the file is read completely (and skip_rows/num_rows) are ignored.

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description

Closes #19064

This PR enables filtering Parquet row groups using row bounds (`skip_rows` and `num_rows`) before filtering them using stats and bloom filters based on the AST filter expression.

Context: Before this PR, we used to first filter row groups using stats and bloom filters and in case of success (filters producing a smaller row group list), we ignored the row bounds completely as the row bounds across filtered list of row groups is different.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 1]
```diff
@@ -1130,151 +1217,198 @@ aggregate_reader_metadata::select_row_groups(
...
+
+  // Set the final number of rows to read to the number of selected rows
+  rows_to_read = total_selected_rows;
 
   return {rows_to_skip,
           rows_to_read,
           std::move(selection),
           std::move(num_rows_per_source),
-          total_row_groups,
+          total_row_bounds_filtered_row_groups,
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1441]: Note that this is the same `total_row_groups` as before which was the total row groups after trimming row groups with row bounds (skip_rows/num_rows).

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 2]
```diff
@@ -1130,151 +1217,198 @@ aggregate_reader_metadata::select_row_groups(
...
+    current_row_group_indices = host_span<std::vector<size_type> const>(trimmed_row_group_indices);
+  }
+
+  // Compute number of input row groups after row bounds filter
+  size_type const total_row_bounds_filtered_row_groups =
+    is_trimmed_row_groups ? compute_total_row_groups(current_row_group_indices)
+                          : total_input_row_groups;
+
+  // Struct to store the number of row groups after filtering using stats and bloom filters
   surviving_row_group_metrics num_row_groups_after_filters{};
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1322]: Future PR:

This struct may be updated such that it tracks the number of row groups filtered with row bounds as well. In that case, this function will return the total_input_row_groups instead of `total_row_bounds_filtered_row_groups` (considered as `total_row_groups` before this PR)

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 3]
```diff
@@ -41,6 +41,170 @@ namespace flatbuf = cudf::io::parquet::flatbuf;
...
+[[nodiscard]] bool are_contiguous_row_groups(
+  cudf::host_span<std::vector<size_type> const> row_group_indices,
+  cudf::host_span<metadata const> file_metadatas)
+{
+  CUDF_EXPECTS(row_group_indices.size() == file_metadatas.size(),
+               "Number of row group indices must match number of file metadatas");
+
+  // Helper function to check if a list of row group indices is contiguous
+  auto const is_contiguous = [](auto const& indices) {
+    if (indices.empty() or std::cmp_equal(indices.size(), 1)) { return true; }
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]:
```suggestion
    if (std::cmp_less_equal(indices.size(), 1)) { return true; }
```

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 4]
```diff
@@ -41,6 +41,170 @@ namespace flatbuf = cudf::io::parquet::flatbuf;
...
+    auto const& indices = row_group_indices.front();
+    return indices.empty() or is_single_source_contiguous(indices, file_metadatas.front());
+  }
+  // Multiple sources case - Find a subspan of contiguous non-empty sources and check if the span is
+  // itself contiguous
+  else {
+    // Find the index of the first (inclusive) and last (exclusive) non-empty sources
+    auto const source_span      = find_non_empty_source_span(row_group_indices);
+    auto const first_source_idx = std::get<0>(source_span);
+    auto const last_source_idx  = std::get<1>(source_span);
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: Didn't use structured bindings to defined `first/last_source_idx` as the linter fails complaining about an invalid pointer dereference at comparison between src_idx and first/last_source_idx in the body of `std::all_of`

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 5]
```diff
@@ -1131,150 +1366,211 @@ aggregate_reader_metadata::select_row_groups(
...
-    }
+  // Input row group indices must be either empty or equal to the number of data sources
+  CUDF_EXPECTS(row_group_indices.empty() or row_group_indices.size() == per_file_metadata.size(),
+               "Encountered unexpected number of input row group indices");
+
+  // Maximum number of rows in all row groups
+  auto const max_num_rows = get_num_rows();
+
+  // Compute the row bounds if no row group indices are provided, else return zeros
+  auto [rows_to_skip, rows_to_read] = [&]() {
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1237]: Simply moved this lambda from L1191

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 6]
```diff
@@ -1131,150 +1366,211 @@ aggregate_reader_metadata::select_row_groups(
...
+  // We need to recount `rows_to_read` as we select rows from row groups if:
+  // - Input row group indices are provided (no filtering with row bounds) OR
+  // - Row groups are filtered using stats or bloom filters and:
+  //     - Row groups are not filtered using row bounds OR
+  //     - Final row group indices are not contiguous
+  auto const is_rows_to_read_need_recount = [&]() {
+    return not row_group_indices.empty() or
+           (is_filtered_row_groups and
+            (not is_trimmed_row_groups or
+             not are_contiguous_row_groups(current_row_group_indices, per_file_metadata)));
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: (if the other suggestion is not adopted) maybe clearer this way?
```suggestion
            not (is_trimmed_row_groups and
                 are_contiguous_row_groups(current_row_group_indices, per_file_metadata)));
```

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 7]
```diff
@@ -1131,150 +1366,211 @@ aggregate_reader_metadata::select_row_groups(
...
+
+  // Flag to check if this is the first row group (to apply row bounds)
+  bool is_first_row_group = true;
+
+  // We need to recount `rows_to_read` as we select rows from row groups if:
+  // - Input row group indices are provided (no filtering with row bounds) OR
+  // - Row groups are filtered using stats or bloom filters and:
+  //     - Row groups are not filtered using row bounds OR
+  //     - Final row group indices are not contiguous
+  auto const is_rows_to_read_need_recount = [&]() {
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: might be good to break this into steps, where the lambda returns true if `not row_group_indices.empty()`, and then returns false if `is_filtered_row_groups` and then makes the final check for the remaining conditions. it would allow comments at each step to explain which cases are meant to be covered.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 8]
```diff
@@ -1131,150 +1366,211 @@ aggregate_reader_metadata::select_row_groups(
...
+
+  // Maximum number of rows in all row groups
+  auto const max_num_rows = get_num_rows();
+
+  // Compute the row bounds if no row group indices are provided, else return zeros
+  auto [rows_to_skip, rows_to_read] = [&]() {
+    if (not row_group_indices.empty()) { return std::pair<int64_t, size_type>{}; }
+    auto const from_opts =
+      cudf::io::detail::skip_rows_num_rows_from_options(skip_rows_opt, num_rows_opt, max_num_rows);
+    CUDF_EXPECTS(from_opts.second <= static_cast<int64_t>(std::numeric_limits<size_type>::max()),
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: I'm surprised linter does not complain about this. looks like a good place to use std::cmp

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 9]
```diff
@@ -244,6 +244,22 @@ class aggregate_reader_metadata {
...
+   * @param rows_to_skip Number of rows to skip
+   * @param rows_to_read Number of rows to read
+   *
+   * @return A tuple of surviving row group indices, and two vectors of effective (trimmed) row
+   * counts and offsets across surviving row group indices respectively
+   */
+  [[nodiscard]] std::tuple<std::vector<std::vector<size_type>>,
+                           std::vector<std::vector<size_type>>,
+                           std::vector<std::vector<size_type>>>
+  apply_row_bounds_filter(cudf::host_span<std::vector<size_type> const> input_row_group_indices,
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.hpp:261]: Why is this function declared in the header?

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 10]
```diff
@@ -244,6 +244,22 @@ class aggregate_reader_metadata {
...
     host_span<int const> column_schemas) const;
 
+  /**
+   * @brief Filters the row groups using row bounds (`skip_rows` and `num_rows`)
+   *
+   * @param rows_to_skip Number of rows to skip
+   * @param rows_to_read Number of rows to read
+   *
+   * @return A tuple of surviving row group indices, and two vectors of effective (trimmed) row
+   * counts and offsets across surviving row group indices respectively
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.hpp]: How do we have an element per row group in the whole input? Don't we only need to skip rows in the first selected row group, and limit the number of rows in the last selected row group?

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 6 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: No longer needed

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 7 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: No longer needed

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 8 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: I think it may be because we aren't using these variables anywhere like the other place where we were comparing them with the current src idx.

File: cpp/src/io/parquet/reader_impl_helpers.hpp (hunk 9 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.hpp:261]: Oh it's a member of `aggregate_reader_metadata` class

File: cpp/src/io/parquet/reader_impl_helpers.hpp (hunk 10 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.hpp]: Yes, but we might end up removing more row groups from the termini in the predicate pushdown stage so we need the whole range so that we know where the first row group starts once we are done filtering for real.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 11]
```diff
@@ -1131,150 +1227,212 @@ aggregate_reader_metadata::select_row_groups(
...
+            std::vector<size_t>(per_file_metadata.size(), 0),
+            total_row_groups,
+            {num_filtered_row_groups, num_filtered_row_groups}};
+  }
+
+  // Vector to store all row group indices across all sources
+  std::vector<std::vector<size_type>> all_row_group_indices;
+
+  // Span to track the current row group indices
+  host_span<std::vector<size_type> const> current_row_group_indices;
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1269]: Overall logic of this function's reimplementation:
1. We will track the row group indices we are currently dealing with using the span: `current_row_group_indices`
2. We initialize the said span with the input `row_group_indices` if those were specified or `all_row_group_indices`. In case the row group indices are provided, skip rows and num rows are always zero/unspecified and we read the entire file.
3. We check if we can filter (also using the word `trim`) current row group indices using row bounds (skip rows and num rows). If so, we apply the trim and update our span of current row group indices. Here, we also start tracking the `skip rows relative to the first surviving row group's row offset`.
4. Then we check if an AST filter expression was specified and if so, we apply stats/bloom filter based row group filtering (aka the predicate pushdown step) and update our span of current row group indices like before. Here, we again update the `skip rows relative to the first surviving row group's row offset` if we applied row bounds trim earlier. Note that if we didn't apply row bounds trim earlier, the skip rows was definitely zero. See definition of `is_trimmed_row_groups`.
5. At this point, we have the final span of `current_row_group_indices`.
6. We march through the final span of current row groups and put them into our `selection` vector, keeping a track of number of rows we have seen so far.
7. We return the skip rows relative to the first surviving row group and the total number of rows we saw while marching though the final list of row groups.

This way, we are adjusting our start row to be always zero (instead of absolute index in the file) + skip rows relative to the first surviving row group and total number of rows to read to the actual number of rows seen in the selected row groups.

Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp:1269]: This impl might conflict with requirements in: https://github.com/rapidsai/cudf/issues/18981. 

Edit: Actually, maybe not really as we can use (or build if `not is_trimmed_row_groups`) the `row_group_row_offsets` vector to get the absolute starting indices of each row group in the final selection as well

File: cpp/tests/io/parquet_reader_test.cpp [hunk 12]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
...
+    cudf::io::parquet_writer_options out_opts =
+      cudf::io::parquet_writer_options::builder(cudf::io::sink_info{filepath}, written_table)
+        .row_group_size_rows(rows_per_row_group)
+        .stats_level(cudf::io::statistics_freq::STATISTICS_COLUMN)
+        .build();
+    cudf::io::write_parquet(out_opts);
+  }
+
+  // int64 data for expected table
+  int64_data.resize(total_num_rows);
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp]: a separate variable would be better IMO. Then we could append `int64_data` three times.

File: cpp/tests/io/parquet_reader_test.cpp [hunk 13]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
 
   CUDF_TEST_EXPECT_TABLES_EQUAL(expected, result->view());
 }
+
+TEST_F(ParquetReaderTest, RowBoundsAndFilter)
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp:2929]: Would it make sense to include a test where all data is filtered out? just to check if we crash in that case.

File: cpp/tests/io/parquet_reader_test.cpp [hunk 14]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
...
+
+    CUDF_TEST_EXPECT_TABLES_EQUAL(expected->view(), table_with_metadata.tbl->view());
+
+    auto const& metadata = table_with_metadata.metadata;
+    EXPECT_EQ(metadata.num_input_row_groups, 3);  // RGs: {1,2,3},{},{}
+    EXPECT_TRUE(metadata.num_row_groups_after_stats_filter.has_value() and
+                metadata.num_row_groups_after_stats_filter.value() == 2);  // RGs: {2,3},{},{}
+  }
+
+  // Filtering AST - table[0] >= 70000 and table[0] < 120000
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp:3048]: ` < 120000` doesn't do anything, right?

File: cpp/tests/io/parquet_reader_test.cpp [hunk 15]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
...
+    auto const& metadata = table_with_metadata.metadata;
+    EXPECT_EQ(metadata.num_input_row_groups, 6);  // RGs: {}, {1,2,3,4},{0,1}
+    EXPECT_TRUE(metadata.num_row_groups_after_stats_filter.has_value() and
+                metadata.num_row_groups_after_stats_filter.value() == 2);  // RGs: {},{4,5},{}
+  }
+
+  // Filtering AST - table[0] < 40000 or table[0] >= 80000
+  {
+    auto constexpr rows_to_skip = 120'000;
+    auto constexpr rows_to_read = 180'000;
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp]: passing more than 180K here is valid too, right? should we test that?

File: cpp/tests/io/parquet_reader_test.cpp [hunk 16]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
...
+
+    CUDF_TEST_EXPECT_TABLES_EQUAL(expected->view(), table_with_metadata.tbl->view());
+
+    auto const& metadata = table_with_metadata.metadata;
+    EXPECT_EQ(metadata.num_input_row_groups, 9);  // RGs: {},{1,2,3,4},{0,1,2,3,4}
+    EXPECT_TRUE(metadata.num_row_groups_after_stats_filter.has_value() and
+                metadata.num_row_groups_after_stats_filter.value() == 5);  // RGs: {},{1,4},{0,1,4}
+  }
+
+  // Filtering AST - table[0] < 40000 and table[0] >= 80000
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp]:
```suggestion
  // Filtering AST - table[0] >= 40000 and table[0] < 80000
```

File: cpp/tests/io/parquet_reader_test.cpp [hunk 17]
```diff
@@ -2925,3 +2925,195 @@ TEST_F(ParquetReaderTest, DISABLED_ListsWideTable)
...
+
+    CUDF_TEST_EXPECT_TABLES_EQUAL(expected->view(), table_with_metadata.tbl->view());
+
+    auto const& metadata = table_with_metadata.metadata;
+    EXPECT_EQ(metadata.num_input_row_groups, 5);  // RGs: {},{0,1,2,3,4},{}
+    EXPECT_TRUE(metadata.num_row_groups_after_stats_filter.has_value() and
+                metadata.num_row_groups_after_stats_filter.value() == 2);  // RGs: {},{2,3},{}
+  }
+
+  // Filtering AST - table[0] < 40000 and table[0] >= 80000
```
Comment (vuule) [inline cpp/tests/io/parquet_reader_test.cpp]:
```suggestion
  // Filtering AST - table[0] < 40000 or table[0] >= 80000
```

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 18]
```diff
@@ -1115,6 +1133,84 @@ std::vector<std::string> aggregate_reader_metadata::get_pandas_index_names() con
...
+  auto row_group_row_offsets = std::vector<std::vector<size_type>>{};
+  row_group_row_offsets.reserve(num_sources);
+
+  size_type current_row_index = 0;
+
+  // Rows to skip with respect to the row offset of the first surviving row group index
+  int64_t first_row_group_relative_rows_to_skip = 0;
+
+  // For each data source
+  std::for_each(
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: What does this function do:

Marches through the input list of row group indices and starts selecting row groups in the output vector as soon as the current rows seen becomes >= skip_rows all the way until we reach >= skip_rows + num_rows. 

While doing so, we also build two vectors containing the number of rows we can read from each row group (zero if a row group is not selected) as well as the absolute row offset of each row group (regardless of whether it was selected or not). We also compute the skip rows relative to the absolute row offset of the `first selected row group` and return it.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 19]
```diff
@@ -1131,150 +1227,212 @@ aggregate_reader_metadata::select_row_groups(
...
+                                     current_row_group_indices.end(),
+                                     [](auto const& indices) { return not indices.empty(); }));
+
+        // Update the relative rows to skip with respect to the first surviving row group
+        if (std::cmp_less(first_non_empty_source_idx, current_row_group_indices.size())) {
+          // Row group index of the first element in the first non-empty source
+          auto const first_non_empty_row_group_idx =
+            current_row_group_indices[first_non_empty_source_idx].front();
+
+          first_row_group_relative_rows_to_skip = std::max<int64_t>(
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1360]: Here we are resetting the `first_row_group_relative_rows_to_skip` as the difference between the absolute `rows_to_skip` and the row group offset of the first row group in the current span of row groups (after predicate pushdown). We limit this to `zero` since it's possible the first row group starts at > `rows_to_skip` not needing any skip rows anymore.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 20]
```diff
@@ -1419,9 +1577,9 @@ aggregate_reader_metadata::select_columns(
       auto const& src_schema_elem = get_schema(src_schema_idx);
       auto const& dst_schema_elem = get_schema(dst_schema_idx, pfm_idx);
 
-      // Check the schema elements to be equal except their number of children as we only care about
-      // the specific column paths in the schema trees. Raise an invalid_argument error if the
-      // schema elements don't match.
+      // Check the schema elements to be equal except their number of children as we only care
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: over efficiency by cursor/clangd 😄

File: cpp/tests/io/parquet_reader_test.cpp (hunk 13 above)
Comment (mhaseeb123) [reply cpp/tests/io/parquet_reader_test.cpp:2929]: Makes sense. Will add one

File: cpp/tests/io/parquet_reader_test.cpp (hunk 14 above)
Comment (mhaseeb123) [reply cpp/tests/io/parquet_reader_test.cpp:3048]: By itself, no as the max value can be 100k

File: cpp/tests/io/parquet_reader_test.cpp (hunk 15 above)
Comment (mhaseeb123) [reply cpp/tests/io/parquet_reader_test.cpp]: Yep, we can def do that

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 21]
```diff
@@ -1115,6 +1133,86 @@ std::vector<std::string> aggregate_reader_metadata::get_pandas_index_names() con
...
+    thrust::counting_iterator<size_t>(0),
+    thrust::counting_iterator(num_sources),
+    [&](auto const& src_idx) {
+      auto const& file_metadata = per_file_metadata[src_idx];
+      auto const num_row_groups = input_row_group_indices[src_idx].size();
+      row_group_num_rows.emplace_back(num_row_groups, size_type{0});
+      row_group_row_offsets.emplace_back(num_row_groups, size_type{0});
+
+      // Return early if we have reached the maximum number of rows
+      if (current_row_index >= rows_to_skip + rows_to_read) { return; }
```
Comment (davidwendt) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: So this return will only stop this iteration and not the `std::for_each()` which will continue until `num_sources`.
Just making sure my understanding and the intention here.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 22]
```diff
@@ -1115,6 +1133,86 @@ std::vector<std::string> aggregate_reader_metadata::get_pandas_index_names() con
...
+      std::for_each(
+        input_row_group_indices[src_idx].begin(),
+        input_row_group_indices[src_idx].end(),
+        [&](auto const& rg_idx) {
+          // Return early if we have reached the maximum number of rows to read
+          if (current_row_index >= rows_to_skip + rows_to_read) { return; }
+
+          // Validate the row group index
+          CUDF_EXPECTS(rg_idx >= 0 and std::cmp_less(rg_idx, file_metadata.row_groups.size()),
+                       "Invalid rowgroup index");
```
Comment (davidwendt) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]:
```suggestion
                       "Invalid rowgroup index", std::invalid_argument);
```
The `rg_idx` values here are provided by the caller so this seems like an invalid argument case?

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 23]
```diff
@@ -1131,150 +1229,218 @@ aggregate_reader_metadata::select_row_groups(
...
-      // Check if we have less than 2B total row groups.
-      CUDF_EXPECTS(total_row_groups <= std::numeric_limits<cudf::size_type>::max(),
-                   "Total number of row groups exceed the size_type's limit");
-      return static_cast<size_type>(total_row_groups);
-    } else {
-      return num_row_groups;
-    }
+  // Input row group indices must be either empty or equal to the number of data sources
+  CUDF_EXPECTS(row_group_indices.empty() or row_group_indices.size() == per_file_metadata.size(),
+               "Encountered unexpected number of input row group indices");
```
Comment (davidwendt) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: Could this be an `std::invalid_argument` case as well?

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 21 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: Yep, basically once the condition satisfies, we will just be filling up row_group_row_counts and row_group_row_offsets with zeroed vectors and returning in the outer loop

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 24]
```diff
@@ -1115,6 +1133,81 @@ std::vector<std::string> aggregate_reader_metadata::get_pandas_index_names() con
...
+  auto const num_sources = input_row_group_indices.size();
+
+  auto filtered_row_group_indices = std::vector<std::vector<size_type>>(num_sources);
+  auto row_group_row_counts       = std::vector<std::vector<size_type>>{};
+  row_group_row_counts.reserve(num_sources);
+  auto row_group_row_offsets = std::vector<std::vector<size_type>>{};
+  row_group_row_offsets.reserve(num_sources);
+
+  size_type current_row_index = 0;
+
```
Comment (mhaseeb123) [inline cpp/src/io/parquet/reader_impl_helpers.cpp:1155]: Removed `CUDF_EXPECTS` checks in this function as we always call it with a sane `all_row_group_indices` list. The outer function (`select_row_groups`) still has the sanitization checks and now throws an `std::invalid_argument`

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 22 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: Removed CUDF_EXPECTS checks in this function as we always call it with a sane `all_row_group_indices` list. The caller function (`select_row_groups`) still has the same sanitization checks and now throws an `std::invalid_argument`

File: cpp/src/io/parquet/reader_impl_helpers.cpp (hunk 20 above)
Comment (vuule) [reply cpp/src/io/parquet/reader_impl_helpers.cpp]: I think this is clang-format's work when indentation increases for a moment. These should be reverted IMO.

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 25]
```diff
@@ -1131,150 +1224,220 @@ aggregate_reader_metadata::select_row_groups(
...
+                  // For each row group in this data source
+                  std::for_each(
+                    current_row_group_indices[src_idx].begin(),
+                    current_row_group_indices[src_idx].end(),
+                    [&](auto const& rg_idx) {
+                      // Validate the row group index
+                      CUDF_EXPECTS(
+                        rg_idx >= 0 and std::cmp_less(rg_idx, file_metadata.row_groups.size()),
+                        "Invalid rowgroup index",
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]: either this is wrong or half of the variable names are wrong :)
```suggestion
                        "Invalid row group index",
```

**Review by vuule — APPROVED** [review]
Looks great, got nothing substantial to add

File: cpp/src/io/parquet/reader_impl_helpers.cpp [hunk 26]
```diff
@@ -41,6 +41,24 @@ namespace flatbuf = cudf::io::parquet::flatbuf;
...
+{
+  auto const total_row_groups =
+    std::accumulate(row_group_indices.begin(),
+                    row_group_indices.end(),
+                    size_t{0},
+                    [](auto sum, auto const& row_groups) { return sum + row_groups.size(); });
+
+  // Check if we have less than 2B total row groups.
+  CUDF_EXPECTS(total_row_groups <= std::numeric_limits<size_type>::max(),
+               "Total number of row groups exceed the cudf::size_type's limit");
```
Comment (davidwendt) [inline cpp/src/io/parquet/reader_impl_helpers.cpp]:
```suggestion
               "Total number of row groups exceed the column size limit",
               std::overflow_error);
```
This is the standard error message we have been using for this.

**Review by davidwendt — APPROVED** [review]
