### PR TITLE
[REVIEW] Fix ORC timestamp to UTC conversion

### LINKED ISSUE #1669: [BUG] Investigate whether ORC reader handles timestamps correctly

### PR DESCRIPTION
**Pull request by OlivierNV**
Fix ORC timestamp conversion to UTC
Fixes #1669

### CODE REVIEW

File: cpp/src/io/orc/timezone.h [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2019, NVIDIA CORPORATION.
+ * Copyright (c) 2018, NVIDIA CORPORATION.
```
Comment (j-ieong) [inline cpp/src/io/orc/timezone.h]: Remain at 2019?

Comment (mjsamoht) [reply cpp/src/io/orc/timezone.h]: That is odd.  We should keep it at 2019.
