### PR TITLE
[REVIEW] Do not break consumption loop on local client timeout

### LINKED ISSUE #5886: [BUG] read_gdf() in the custreamz.Kafka module is dropping data
I'm using this to produce random data to a 4-partition Kafka topic.

```
import confluent_kafka
from confluent_kafka import KafkaError, KafkaException
from confluent_kafka import TopicPartition
import sys
from time import sleep
import numpy as np
from random import randrange,seed
import json
import math
import time
import random

num_columns = 40

def column_names(size):
    base_cols = ["AppId{}", "LoggedTime{}", "timestamp{}"]
    cols = []
    mult = math.ceil(size/len(base_cols))
    for i in range(mult):
        for c in base_cols:
            cols.append(c.format(i))
            if(len(cols) == size): break
    return cols

def generate_json(num_columns):
    dict_out = {}
    cols = column_names(num_columns)
    for col in cols:
        if col.startswith("AppId"): dict_out[col] = randrange(1,50000)
        elif col.startswith("LoggedTime"): dict_out[col] = randrange(1,50000)
        else: dict_out[col] = randrange(1,50000)
    return json.dumps(dict_out)

bootstrap_servers = 'localhost:9092'
producer_conf = {'bootstrap.servers': bootstrap_servers, 'compression.type':'snappy'}

producer = confluent_kafka.Producer(producer_conf)
topic = "gfn-telemetry"

def delivery_callback(err, msg):
        if err:
            sys.stderr.write('%% Message failed delivery: %s\n' % err)

count = 0    
while True:
    producer.produce(topic, generate_json(num_columns), callback=delivery_callback)
    count = count + 1
    if count%100000 == 0:
        producer.flush()
```

And I'm using this script to consume messages:

```
import cudf
import random

topic = "gfn-telemetry" # Topic with 4 partitions
j = random.randint(0, 100000)
bootstrap_servers = 'localhost:9092'
consumer_conf = {
    "bootstrap.servers": bootstrap_servers,
    "enable.partition.eof": "true",
    "group.id": "custreamz-grp-test-%i" % j,
    "session.timeout.ms": "60000",
    "auto.offset.reset": "earliest"
}

from custreamz import kafka
consumer = kafka.Consumer(consumer_conf)
print(len(consumer.read_gdf(topic="gfn-telemetry", partition=0, lines=True, start=0, end=100000)))
print(len(consumer.read_gdf(topic="gfn-telemetry", partition=1, lines=True, start=0, end=100000)))
print(len(consumer.read_gdf(topic="gfn-telemetry", partition=2, lines=True, start=0, end=100000)))
print(len(consumer.read_gdf(topic="gfn-telemetry", partition=3, lines=True, start=0, end=100000)))
```

Given that the topic has enough data, the length of the dataframes created by `read_gdf` is different for each partition, as opposed to a fixed size of `100000`, which is incorrect. 

cc: @jdye64

### PR DESCRIPTION
**Pull request by jdye64**
Clients who choose to use a single KafkaConsumer object may experience local client socket timeouts which given the previous implementation would break the consumption loop. This changes so that the consumption loop is not broken on that event.

This closes #5886

### CODE REVIEW

**Comment by chinmaychandak** [comment]
@devavret, @trevorsm7 Can we please get a quick review on this?

File: cpp/libcudf_kafka/src/kafka_consumer.cpp [hunk 1]
```diff
@@ -124,8 +124,7 @@ void kafka_consumer::consume_to_buffer()
       buffer.append(static_cast<char *>(msg->payload()));
       buffer.append(delimiter);
       messages_read++;
-    } else if (msg->err() == RdKafka::ErrorCode::ERR__TIMED_OUT ||
-               msg->err() == RdKafka::ErrorCode::ERR__PARTITION_EOF) {
+    } else if (msg->err() == RdKafka::ErrorCode::ERR__PARTITION_EOF) {
       // If there are no more messages or a timeout reading a message occurs then return
```
Comment (vuule) [inline cpp/libcudf_kafka/src/kafka_consumer.cpp:128]: This comment needs to be updated.
