### PR TITLE
Include row group level stats when writing ORC files

### LINKED ISSUE #9964: [FEA] orc file written by cudf doesn't include Column Statistics in RowIndex
Spark 3.2 has changed the orc dependency to 1.6.11 which has different behaviors with orc 1.5.10 (spark-plugins shaded) when picking row group with filter pushed down.

In a word, Spark 3.2 will **return empty** when reading the orc file written by cudf with filter pushed down which is because of missing Column Statistic in RowIndex.

From the orc spec, Column Statistic of RowIndex seems not to be a required field. But if the orc file didn't include Column Statistic in RowIndex, the spark will get incorrect result.

### PR DESCRIPTION
**Pull request by vuule**
Closes #9964 
Encodes row group level stats with the rest and writes the encoded blobs into the protobuf, at the start of each stripe (other stats are in the file footer).
Adds `put_bytes` to `ProtobufWriter` to optimize writing of buffers.
Adds new struct to represent the encoded ORC statistics so they are separated by granularity level (instead of using a single vector).

### CODE REVIEW

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
Measured a small performance regression due to additional stats encode. Difference is within a few percent (hard to measure exactly due to variance between runs).

**Comment by vuule** [comment]
Will look into adding a test, unsure if this is possible with the available readers.

File: cpp/src/io/orc/orc.cpp [hunk 1]
```diff
@@ -209,43 +209,55 @@ void ProtobufWriter::put_row_index_entry(int32_t present_blk,
...
+      // RLE run pos always zero (assumes RLE aligned with row index boundaries)
+      put_byte(0);
     }
   }
-  m_buf->data()[lpos]     = (uint8_t)(sz + 2);
+  // size of the field 1
   m_buf->data()[lpos + 2] = (uint8_t)(sz);
+
+  if (stats != nullptr) {
+    sz += put_uint(2 * 8 + PB_TYPE_FIXEDLEN);
```
Comment (hyperbolic2346) [inline cpp/src/io/orc/orc.cpp:254]: 2 and 8 seem magical here. Should they be named with a constexpr to add some clarity to this calculation?

Maybe this section needs a comment like
```
// data stream is a 4 byte type followed by a 4 byte size followed by the actual stat data block
```

File: cpp/src/io/orc/orc.h [hunk 2]
```diff
@@ -470,16 +470,22 @@ class ProtobufWriter {
  public:
   ProtobufWriter() { m_buf = nullptr; }
   ProtobufWriter(std::vector<uint8_t>* output) { m_buf = output; }
-  void putb(uint8_t v) { m_buf->push_back(v); }
+  void put_byte(uint8_t v) { m_buf->push_back(v); }
+  template <typename T>
+  void put_bytes(T const& values)
```
Comment (hyperbolic2346) [inline cpp/src/io/orc/orc.h:475]: `put_uint` returns the number of bytes added. Would it make sense to have that in `put_bytes` and `put_byte` as well? This could remove some of the magic addition to the size and keep things looking consistent.

File: cpp/src/io/orc/writer_impl.cu [hunk 3]
```diff
@@ -1980,37 +2017,34 @@ void writer::impl::write(table_view const& table)
...
-          std::make_move_iterator(column_stats.begin()) + stripes.size() * orc_table.num_columns(),
-          std::make_move_iterator(column_stats.end()));
-      }
-      // Stripe-level statistics
+    // File-level statistics
+    // NOTE: Excluded from chunked write mode to avoid the need for merging stats across calls
+    if (single_write_mode and not statistics.file_level.empty()) {
+      // First entry contains total number of rows
+      buffer_.resize(0);
+      pbw_.put_byte(1 * 8 + PB_TYPE_VARINT);
```
Comment (hyperbolic2346) [inline cpp/src/io/orc/writer_impl.cu:2025]: more magic numbers here. What does the `1 * 8` represent? Is this a bitmask?

**Review by hyperbolic2346 — CHANGES_REQUESTED** [review]
Copyrights need to be updated on some files here. I like these changes, I think they are going in the right direction for readability.

**Comment by wbo4958** [comment]
> nd writes the encoded blobs into the protobuf, at the start of each stripe (other stats are in the file footer).
> Adds `put_bytes` to `ProtobufWriter` to optimize writing of buffers.
> Adds new struct to represent the encoded ORC

Maybe we can add a configure to enable or disable this FEA after SPARK has bumped to the ORC repo which has the fix.

**Comment by vuule** [comment]
> > nd writes the encoded blobs into the protobuf, at the start of each stripe (other stats are in the file footer).
> > Adds `put_bytes` to `ProtobufWriter` to optimize writing of buffers.
> > Adds new struct to represent the encoded ORC
> 
> Maybe we can add a configure to enable or disable this FEA after SPARK has bumped to the ORC repo which has the fix.

👍 
@mythrocks is working on API changes that will allow callers to disable rowgroup level statistics, so they can effectively revert the behavioral changes in this PR.

**Comment by jlowe** [comment]
> Maybe we can add a configure to enable or disable this FEA after SPARK has bumped to the ORC repo which has the fix.

That only works when everyone stops using the older Spark version(s) (and any other Java-based data processing frameworks) that still using the old ORC version with the reading bug.  While those frameworks on the older ORC version are still in use, cudf applications could still end up creating ORC files that those frameworks will silently drop data when reading with predicate pushdown.  Even though the spec says these things are technically optional, it is very sketchy to be the only ORC writer on the planet that is not generating these stats.

I think it's fine making it possible in libcudf to avoid writing these stats, but IMO cudf applications should always ask for the stats to be generated unless they know there's no chance the files they're creating could be read by data processing frameworks that could be affected by the ORC reading bug.

**Comment by vuule** [comment]
> I think it's fine making it possible in libcudf to avoid writing these stats, but IMO cudf applications should always ask for the stats to be generated unless they know there's no chance the files they're creating could be read by data processing frameworks that could be affected by the ORC reading bug.

That's right. Writing all statistics will be the default.

File: cpp/src/io/orc/writer_impl.cu (hunk 3 above)
Comment (vuule) [reply cpp/src/io/orc/writer_impl.cu]: That's how the field numbers in protobuf are encoded, with last three bits reserved the field type. 
Centralized the magic into a single function (improvement over the pre-PR code:)), let me know what you think.

File: cpp/src/io/orc/orc.h (hunk 2 above)
Comment (vuule) [reply cpp/src/io/orc/orc.h]: Good suggestion; done.

File: cpp/src/io/orc/orc.cpp (hunk 1 above)
Comment (vuule) [reply cpp/src/io/orc/orc.cpp]: 2 is a field number, from the ORC protobuf spec. I think the meaning is a lot clearer now, with the use of `encode_field_number`.

Comment (hyperbolic2346) [reply cpp/src/io/orc/orc.cpp]: This is much nicer, thanks!

File: cpp/src/io/orc/writer_impl.cu (hunk 3 above)
Comment (hyperbolic2346) [reply cpp/src/io/orc/writer_impl.cu]: Yes, I was reluctant to suggest since it was old code, but it seemed a small enough change and enough of a win. I like how this turned out. Thank you for doing this extra work.

**Review by hyperbolic2346 — APPROVED** [review]

**Comment by vuule** [comment]
rerun tests

File: cpp/src/io/orc/orc.cpp [hunk 4]
```diff
@@ -209,43 +209,54 @@ void ProtobufWriter::put_row_index_entry(int32_t present_blk,
...
+      // RLE run pos always zero (assumes RLE aligned with row index boundaries)
+      sz += put_byte(0);
     }
   }
-  m_buf->data()[lpos]     = (uint8_t)(sz + 2);
+  // size of the field 1
   m_buf->data()[lpos + 2] = (uint8_t)(sz);
+
+  if (stats != nullptr) {
+    sz += put_uint(encode_field_number<decltype(*stats)>(2));  // 2: statistics
```
Comment (nvdbaranec) [inline cpp/src/io/orc/orc.cpp:252]: Nit:  maybe field number (2 in this case) should be an enum.   I see that it's used in a lot of places though, so maybe a followup.

File: cpp/src/io/orc/orc.h [hunk 5]
```diff
@@ -131,6 +131,67 @@ struct Metadata {
   std::vector<StripeStatistics> stripeStats;
 };
 
+int static constexpr encode_field_number(int field_number, uint8_t field_type) noexcept
```
Comment (nvdbaranec) [inline cpp/src/io/orc/orc.h:134]: Yeah I feel like field number should be an enum.  Looks like field_type already is an enum, but an anonymous one.

File: cpp/src/io/orc/orc.h [hunk 6]
```diff
@@ -470,16 +477,27 @@ class ProtobufWriter {
...
   ProtobufWriter() { m_buf = nullptr; }
   ProtobufWriter(std::vector<uint8_t>* output) { m_buf = output; }
-  void putb(uint8_t v) { m_buf->push_back(v); }
+  uint32_t put_byte(uint8_t v)
+  {
+    m_buf->push_back(v);
+    return 1;
+  }
+  template <typename T>
+  uint32_t put_bytes(T const& values)
```
Comment (nvdbaranec) [inline cpp/src/io/orc/orc.h:486]: Maybe a span here?

**Review by nvdbaranec — APPROVED** [review]
Looks good.  Might not hurt to cook up some kind of tests for this.

File: cpp/src/io/orc/orc.h (hunk 5 above)
Comment (vuule) [reply cpp/src/io/orc/orc.h:134]: Yeah, field type can be passed as enum, I'll look into that.

**Comment by vuule** [comment]
rerun tests

**Comment by vuule** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge
