### PR TITLE
Change calls to cudaMemcpyToSymbol to cudaMemcpyToSymbolAsync

### LINKED ISSUE #20373: [BUG]: Unexpected Default CUDA stream usage in `contains_re`
**Describe the bug**

I'm debugging a CUDA `Memcpy HtoD` that's occurring on the default stream during a `contains_re` call, despite me passing in a `stream`.

**Steps/Code to reproduce bug**

Here's my test programing using pylibcudf:

```python
import pylibcudf as plc
import pyarrow as pa
import nvtx
from rmm.pylibrmm.stream import Stream

stream = Stream()
col = plc.Column.from_arrow(pa.array(["a", "b", "c"], pa.string()), stream=stream)

program = plc.strings.regex_program.RegexProgram.create("a", flags=plc.strings.regex_flags.RegexFlags.DEFAULT)
with nvtx.annotate("contains_re"):
    result = plc.strings.contains.contains_re(col, program, stream=stream)

stream.synchronize()
```

And https://gist.github.com/TomAugspurger/74eebbfc73a71f604e6e95a1b1e9b185 has a completely unreviewed translation to C++ that was generated by an AI tool. Both programs demonstrate the issue when run under nsys, so I'll focus on the simpler python one.

I run the program with

```
nsys profile -o debug -f true python debug.py
```

Image

I can provide the nsys profile if necessary.

**Expected behavior**

All CUDA operations would happen on the provided stream.

**Additional context**

I'm far from a C++ expert, but I had an AI tool try to track things down, which I've tried to validate. It seems the problem is in this call chain in `contains_impl`:

- `regex_device_builder::create_prog_device`: https://github.com/rapidsai/cudf/blob/029d8d36fe7f1f06a380b7c1cf77c7c217efe0f2/cpp/src/strings/contains.cu#L63
- `reprog_device::create`: https://github.com/rapidsai/cudf/blob/029d8d36fe7f1f06a380b7c1cf77c7c217efe0f2/cpp/src/strings/regex/regex_program_impl.h#L35
- `reprog_device`: https://github.com/rapidsai/cudf/blob/029d8d36fe7f1f06a380b7c1cf77c7c217efe0f2/cpp/src/strings/regex/regexec.cpp#L67
- `get_character_flags_table`: https://github.com/rapidsai/cudf/blob/029d8d36fe7f1f06a380b7c1cf77c7c217efe0f2/cpp/src/strings/regex/regexec.cpp#L33
- `cudaMemcpyToSymbol`: https://github.com/rapidsai/cudf/blob/029d8d36fe7f1f06a380b7c1cf77c7c217efe0f2/cpp/src/strings/utilities.cu#L105C19-L105C37

My understanding is that `cudaMemcpyToSymbol` doesn't accept a stream, but `cudaMemcpyToSymbolAsync` does (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gc3551568f691baad5fb776b7656ecc05).

Apologies if I've mistaken anything here.

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Changes calls to `cudaMemcpyToSymbol` to `cudaMemcpyToSymbolAsync` in libcudf.

Closes #20373 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/include/cudf/strings/detail/char_tables.hpp [hunk 1]
```diff
@@ -21,9 +24,11 @@ using character_flags_table_type = std::uint8_t;
  * This table is used to check the type of character like
  * alphanumeric, decimal, etc.
  *
+ * @param stream CUDA stream used for device memory operations and kernel launches
  * @return Device memory pointer to character flags table.
  */
-character_flags_table_type const* get_character_flags_table();
+character_flags_table_type const* get_character_flags_table(
+  rmm::cuda_stream_view stream = cudf::get_default_stream());
```
Comment (PointKernel) [inline cpp/include/cudf/strings/detail/char_tables.hpp:31]:
```suggestion
character_flags_table_type const* get_character_flags_table(
  rmm::cuda_stream_view stream);
```
Question: do we want to remove the default stream as it's a detail API? https://github.com/rapidsai/cudf/issues/9854

Comment (davidwendt) [reply cpp/include/cudf/strings/detail/char_tables.hpp:31]: This function is used in some python-udf classes, so I believe it will be difficult to remove the default without some overhauling of that code. Once that code supports streams properly, we can remove the default.

**Comment by vyasr** [comment]
This makes me wonder whether we should update the [stream testing utility](https://github.com/rapidsai/cudf/blob/main/cpp/tests/utilities/identify_stream_usage.cpp) to completely disallow calling certain non-stream-ordered functions if they have corresponding stream testing variants. Would we ever want to use cudaMemcpy instead of cudaMemcpyAsync in our code base anymore, for instance? We can always pass the default stream as a parameter to get back to the legacy behavior.

**Comment by bdice** [comment]
@vyasr I'd be okay with that proposal!

File: cpp/include/cudf/strings/detail/char_tables.hpp [hunk 2]
```diff
@@ -76,9 +83,11 @@ struct special_case_mapping {
  * This table is used to handle special case character mappings that
  * don't trivially work with the normal character cases table.
  *
+ * @param stream CUDA stream used for device memory operations and kernel launches
  * @return Device memory pointer to the special case mapping table
  */
-const struct special_case_mapping* get_special_case_mapping_table();
+const struct special_case_mapping* get_special_case_mapping_table(
```
Comment (PointKernel) [inline cpp/include/cudf/strings/detail/char_tables.hpp]:
```suggestion
special_case_mapping const* get_special_case_mapping_table(
```
nit: get rid of the c-style return type and use west const
