### PR TITLE
[REVIEW] Fix casting values to cudf::bool8

### LINKED ISSUE #2575: [BUG] casting a non-zero value to bool8 can return false
**Describe the bug**
Casting an integral value larger than 8-bits to a bool8 can return a false result if the lower 8 bits of the value are zero.

**Steps/Code to reproduce bug**
Apply this patch and run the unary tests:
```patch
diff --git a/cpp/tests/unary/unary_ops_test.cu b/cpp/tests/unary/unary_ops_test.cu
index 4784f0bba..387540f83 100644
--- a/cpp/tests/unary/unary_ops_test.cu
+++ b/cpp/tests/unary/unary_ops_test.cu
@@ -189,6 +189,20 @@ TEST_F(col_cast_test, usage_example) {
                EXPECT_TRUE( results == outputInt32Col );
        }
 
+        // example for cudf::cast int64 to bool8
+        {
+          std::vector<int64_t> inputData = { 0x12345678, 0x12345600 };
+          auto inputCol = cudf::test::column_wrapper<int64_t>(inputData);
+          gdf_column output;
+          EXPECT_NO_THROW( output = cudf::cast(inputCol, GDF_BOOL8) );
+          auto outputCol = cudf::test::column_wrapper<cudf::bool8>(output);
+          auto out_h = outputCol.to_host();
+          auto out_data = std::get<0>(out_h);
+          ASSERT_TRUE(out_data.size() == 2);
+          ASSERT_TRUE(out_data[0]);
+          ASSERT_TRUE(out_data[1]);
+        }
+
        // example for cudf::cast generic to date32
        {
                auto results = cudf::test::column_wrapper<cudf::date32>(std::vector<cudf::date32>{
```

**Expected behavior**
Any non-zero value cast to a bool8 yields a true result.

### PR DESCRIPTION
**Pull request by tranquiltempeh**
Description:
Fixes #2575 by casting values to a bool first before casting them to cudf::bool8. Internally, bool8 is implemented as a char, so casting to a bool8 can incorrectly return a value of false if the downcasted value is non-zero but its low-order byte is zero, because the downcasting operation to char simply takes the low-order byte. To fix this, this change cast to a bool first, before casting that to a bool8.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
Instead of modifying the unary ops, the root issue needs to be addressed in the `wrapper` class.

We need to modify the constructor that is specialized for `bool8` to be expanded such that a `cudf::bool8` can be constructible from anything that a `bool` can be constructed from.

https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/include/cudf/utilities/legacy/wrapper_types.hpp#L87

I don't believe this will work as-is, but it's in the general direction of the right answer:
```
  template <typename U, gdf_dtype dtype = type_id,
            std::enable_if_t<(dtype == GDF_BOOL8)> * = nullptr>
  CUDA_HOST_DEVICE_CALLABLE constexpr explicit wrapper(U v)
      : value{static_cast<bool>(v)} {}
```

This may need an additional SFINAE with `std::is_constructible<bool, U>`.

File: cpp/include/cudf/utilities/legacy/wrapper_types.hpp [hunk 1]
```diff
@@ -77,15 +77,15 @@ struct wrapper
   using value_type = T;                                          ///< The underlying fundamental type of the wrapper
   value_type value;                                              ///< The wrapped value
 
-  template <gdf_dtype dtype = type_id,
+  template <typename from_type, gdf_dtype dtype = type_id,
```
Comment (jrhemstad) [inline cpp/include/cudf/utilities/legacy/wrapper_types.hpp]: This will make _all_ wrappers constructible from any type, not just `value_type`, which is not what we want.

File: cpp/tests/unary/unary_ops_test.cu [hunk 2]
```diff
@@ -189,6 +189,21 @@ TEST_F(col_cast_test, usage_example) {
 		EXPECT_TRUE( results == outputInt32Col );
 	}
 
+
+    // example for cudf::cast int64 to bool8
```
Comment (j-ieong) [inline cpp/tests/unary/unary_ops_test.cu]:
```suggestion
	// example for cudf::cast int64 to bool8
```
For consistency with rest of the file.

File: cpp/include/cudf/utilities/legacy/wrapper_types.hpp [hunk 3]
```diff
@@ -80,12 +80,12 @@ struct wrapper
...
   CUDA_HOST_DEVICE_CALLABLE
-  constexpr explicit wrapper(T v) : value{v} {}
+  constexpr explicit wrapper(value_type v) : value{v} {}
 
-  template <gdf_dtype dtype = type_id,
+  template <typename from_type, gdf_dtype dtype = type_id,
             std::enable_if_t<(dtype == GDF_BOOL8)> * = nullptr>
-  CUDA_HOST_DEVICE_CALLABLE constexpr explicit wrapper(T v)
-      : value{static_cast<bool>(v)} {}
+  CUDA_HOST_DEVICE_CALLABLE constexpr explicit wrapper(from_type v)
```
Comment (jrhemstad) [inline cpp/include/cudf/utilities/legacy/wrapper_types.hpp]: New constructor needs tests in `types_test`.

File: cpp/include/cudf/utilities/legacy/wrapper_types.hpp [hunk 4]
```diff
@@ -80,12 +80,12 @@ struct wrapper
...
+      : value{static_cast<value_type>(static_cast<bool>(v))} {}
```
Comment (jrhemstad) [inline cpp/include/cudf/utilities/legacy/wrapper_types.hpp]: Is the cast to `value_type` necessary?

File: cpp/tests/types/types_test.cpp [hunk 5]
```diff
@@ -209,8 +213,8 @@ TYPED_TEST(WrappersNoBoolTest, BooleanOperators)
 }
 
 // Ensure bool8 constructor is correctly casting the input type to a bool
-TEST_F(WrappersTestBool8, BooleanConstructor) {
-  using UnderlyingType = cudf::bool8::value_type;
+TYPED_TEST(WrappersBoolTest, BooleanConstructor) {
```
Comment (jrhemstad) [inline cpp/tests/types/types_test.cpp]: Existing tests shouldn't need to be modified. Furthermore, this isn't really testing what we want.

We want a new `TYPED_TEST_CASE` that is tested across all the types `int8_t, int16_t, ... float, double` to ensure that constructing a `bool8` from those types will properly convert to a `bool` and not suffer from overflow.

File: cpp/tests/types/types_test.cpp [hunk 6]
```diff
@@ -292,6 +318,16 @@ TEST_F(WrappersTestBool8, CastArithmeticTest)
               static_cast<bool>(static_cast<int>(t1) + static_cast<int>(t2)));
 }
 
+// Ensure bool8 constructor is correctly casting the input type to a bool
+TYPED_TEST(Bool8CtorTest, Bool8CastTest) {
+using SourceType = TypeParam;
+  for (int i = 0; i < NUM_TRIALS; ++i) {
+    SourceType t{this->rand()};
+    cudf::bool8 const w{t};
+    EXPECT_EQ(unwrap(w), static_cast<bool>(t));
```
Comment (jrhemstad) [inline cpp/tests/types/types_test.cpp]: I'm not sure this is testing what we want. This will just verify that `unwrap(w)` and  `static_cast<bool>(t)` are greater than zero.

I _think_ what we want to test is this:
```
    EXPECT_EQ(unwrap(w), static_cast<bool8::value_type>(static_cast<bool>(t))));
```

This will ensure that the underlying value of `w` is identical to the value of `t`.

**Comment by j-ieong** [comment]
rerun tests

**Comment by harrism** [comment]
@jrhemstad OK to approve?
