### PR TITLE
cudf::detail::pinned_allocator doesn't throw from `deallocate`

### LINKED ISSUE #14165: [BUG] pinned_host_vector can cause abrupt program termination
**Describe the bug**
pinned_host_vector can throw from within it's destructor, causing the application process to terminate abruptly.  For example, this is causing abnormal termination of Spark executors when a GPU illegal access occurs during a Parquet read.  Since the executor process is abruptly terminated via low-level `abort()`, there's no chance to convey a useful message from the driver to the executor otherwise try to handle at the application level the `cudf::fatal_cuda_error` exception that is being thrown.

**Steps/Code to reproduce bug**
Compile and run the following program:
```c++
#include <stdexcept>
#include <cudf/detail/utilities/pinned_host_vector.hpp>

__global__ void crash(int *x) {
  int *y = NULL;
  *x = y[12345678];
}

int main() {
  int *x;
  try {
    auto p = cudf::detail::pinned_host_vector<uint8_t>(4096);
    cudaMalloc(&x, sizeof(*x));
    crash<<<1,1>>>(x);
    cudaDeviceSynchronize();
  } catch (std::exception const& e) {
  }
  return 0;
}
```
which will produce the following output:
```
terminate called after throwing an instance of 'cudf::fatal_cuda_error'
  what():  Fatal CUDA error encountered at: /home/jlowe/src/spark-rapids-jni/target/libcudf-install/include/cudf/detail/utilities/pinned_host_vector.hpp:172: 700 cudaErrorIllegalAddress an illegal memory access was encountered
Aborted (core dumped)
```

**Expected behavior**
Exceptions should not be thrown from destructors and cause an application to be terminated abruptly with no chance for the application to shutdown gracefully.

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Fixes #14165

The deallocate function is called by the `pinned_host_vector`. Throwing from destructors is bad since they can't be caught, and generally get converted into runtime sig aborts.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

File: cpp/include/cudf/detail/utilities/pinned_host_vector.hpp [hunk 1]
```diff
@@ -169,7 +169,12 @@ class pinned_allocator {
    *        It is the responsibility of the caller to destroy
    *        the objects stored at \p p.
    */
-  __host__ inline void deallocate(pointer p, size_type /*cnt*/) { CUDF_CUDA_TRY(cudaFreeHost(p)); }
+  __host__ inline void deallocate(pointer p, size_type /*cnt*/)
+  {
+    auto dealloc_worked = cudaFreeHost(p);
+    (void)dealloc_worked;
```
Comment (divyegala) [inline cpp/include/cudf/detail/utilities/pinned_host_vector.hpp:175]: I have never seen a type cast without assignment. What does this line do?

Comment (davidwendt) [reply cpp/include/cudf/detail/utilities/pinned_host_vector.hpp:175]: Generally, in Release mode, I believe this will suppress a variable-is-set-but-never-used warning from the compiler since the assert is compiled out.

Comment (robertmaynard) [reply cpp/include/cudf/detail/utilities/pinned_host_vector.hpp:175]: Correct on all accounts

Comment (divyegala) [reply cpp/include/cudf/detail/utilities/pinned_host_vector.hpp:175]: And where does the `status__` variable come from, seeing that it's never declared?

Comment (robertmaynard) [reply cpp/include/cudf/detail/utilities/pinned_host_vector.hpp:175]: Thanks @divyegala, that is a typo. I pushed a correction

**Review by divyegala — APPROVED** [review]

**Review by hyperbolic2346 — APPROVED** [review]
