### PR TITLE
Fix exclusive scan when including nulls and improve testing

### LINKED ISSUE #8462: [BUG] scan null_policy is either documented wrong or is producing incorrect results
**Describe the bug**
`cudf::scan` contains the following documentation

```
 * The null values are skipped for the operation, and if an input element
 * at `i` is null, then the output element at `i` will also be null.
```

But it also documents the `null_handling` parameter as

```
 * @param[in] null_handling Exclude null values when computing the result if
 * null_policy::EXCLUDE. Include nulls if null_policy::INCLUDE.
 * Any operation with a null results in a null.
```

The two appear to be inconsistent with each other. If I exclude nulls and there are nulls in my data would that row show up as a null or would it be excluded? If I include nulls does that mean that all values after the null are null? because `Any operation with a null results in a null.` or does it mean that a null input row results in a null output row and `The null values are skipped`. But if they are skipped then how in `INCLUDE` different from `EXCLUDE`? So I ran some tests to find out, and things get even worse.

For example:

Aggregation: SUM
Input: INT32 `[1, 2, null, 3, 5, 8, 10]`

Results 

|                                               |`null_policy::INCLUDE`|`null_policy::EXCLUDE`|
|---------------------------------------|-------------------------------|--------------------------------|
|**`scan_type::INCLUSIVE`** |`[1, 3, null, null, null, null, null]` | `[1, 3, null, 6, 11, 19, 29]`|
|**`scan_type::EXCLUSIVE`**|`[0, 1, 3, 3, 6, 11, 19]` |`[0, 1, null, 3, 6, 11, 19]` |

For some reason when null are included on an inclusive scan then everything after the first null results in a null, but on an exclusive scan nulls are treated as if they were the default value.

When you exclude nulls at least the two implementations are consistent, and I guess follows the documentation, but I am not really sure what excluding a null means if nulls still show up in the output. 

This pattern applies for all of the other scan aggregations that are supported

### PR DESCRIPTION
**Pull request by harrism**
Fixes #8462 by generalizing the existing `mask_inclusive_scan` used in `inclusive_scan` so it can be applied the same way in `exclusive_scan`. #8462 demonstrated holes in test coverage, so this PR also reorganizes `scan_tests` test infrastructure to enable a single set of tests to be applied to all supported data types and parameters, correctly expecting exceptions in unsupported cases (e.g. no product scans on fixed-point, only min/max inclusive scans on strings).

### CODE REVIEW

**Review by devavret — APPROVED** [review]
LGTM

File: cpp/tests/reductions/scan_tests.cpp [hunk 1]
```diff
@@ -14,584 +14,390 @@
...
-  // skipna=false
-  CUDF_EXPECT_NO_THROW(
-    col_out = cudf::scan(
-      input_view, cudf::make_sum_aggregation(), scan_type::INCLUSIVE, null_policy::INCLUDE));
-  cudf::test::fixed_width_column_wrapper<TypeParam> expected_col_out2(
-    out_v.begin(), out_v.end(), out_b.begin());
-  if (do_print) {
-    print_view(expected_col_out2, "expect = ");
-    print_view(col_out->view(), "result = ");
+  std::function<HostType(HostType, HostType)> make_agg(std::unique_ptr<aggregation> const& agg)
```
Comment (mythrocks) [inline cpp/tests/reductions/scan_tests.cpp:185]: Reading this test has been thoroughly informative.

File: cpp/tests/reductions/scan_tests.cpp [hunk 2]
```diff
@@ -14,584 +14,390 @@
...
-  cudf::test::fixed_width_column_wrapper<TypeParam> expected_col_out2(
-    out_v.begin(), out_v.end(), out_b.begin());
-  if (do_print) {
-    print_view(expected_col_out2, "expect = ");
-    print_view(col_out->view(), "result = ");
+  template <typename Ti>
+  void print(thrust::host_vector<Ti> const& v, const char* msg = nullptr)
+  {
+    std::cout << msg << " {";
+    std::for_each(v.begin(), v.end(), [](Ti i) { std::cout << ", " << i; });
```
Comment (mythrocks) [inline cpp/tests/reductions/scan_tests.cpp:295]: There's no way around that leading `,`, is there?

**Review by mythrocks — APPROVED** [review]

File: cpp/include/cudf_test/type_lists.hpp [hunk 3]
```diff
@@ -85,15 +86,21 @@ typename std::enable_if<cudf::is_fixed_width<TypeParam>() &&
 make_type_param_vector(std::initializer_list<T> const& init_list)
 {
   thrust::host_vector<TypeParam> vec(init_list.size());
-  std::transform(std::cbegin(init_list), std::cend(init_list), std::begin(vec), [](auto const& e) {
-    if (std::is_unsigned<TypeParam>::value)
+  std::transform(std::cbegin(init_list), std::cend(init_list), std::begin(vec), [](T const& e) {
```
[the remark this answers is not in the document]
Comment (harrism) [reply cpp/include/cudf_test/type_lists.hpp]: We don't. Fixed, thanks.  Also changed from `if constexpr {return} else {return}` to `if constexpr {return} return` to workaround known CUDA compiler issue (spurious warning I just noticed).

File: cpp/tests/reductions/scan_tests.cpp (hunk 2 above)
Comment (harrism) [reply cpp/tests/reductions/scan_tests.cpp]: This has all been eliminated and simplified. Thanks for catching.

**Comment by harrism** [comment]
@gpucibot merge
