### PR TITLE
[REVIEW] Fix read_csv `int32` overflow

### LINKED ISSUE #6284: [BUG] Int32 overflow in read_csv with large byte_range offset
**Describe the bug**
After #6138  was merged (the previous commit works fine for me), the offset used for a `byte_range` argument to `read_csv` is now limited to `2_147_483_647` (to avoid int32 overflow).  This is problematic for csv files larger than 2GB, where the user (or `dask_cudf`) will typically need to read in byte-ranges with larger offsets.

**Steps/Code to reproduce bug**
```python
import cudf
cudf.datasets.timeseries(
    start='2000-01-01',
    end='2002-12-31',
    dtypes={'name': str, 'id': int, 'x': float, 'y': float},
).to_csv("big_file.csv", chunksize=100000) # Makes 2.9 GB file

# SUCCEEDS
byte_range = (2_147_483_647, 100_000_000)
cudf.read_csv("big_file.csv", byte_range=byte_range, header=None)

# FAILS
byte_range = (2_147_483_648, 100_000_000)
cudf.read_csv("big_file.csv", byte_range=byte_range, header=None)
```
**Traceback**
```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-14-c5000bf13a04> in <module>
      1 # FAILS
      2 byte_range = (2_147_483_648, 100_000_000)
----> 3 cudf.read_csv("big_file.csv", byte_range=byte_range, header=None)

/datasets/rzamora/miniconda3/envs/cudf_16/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/datasets/rzamora/miniconda3/envs/cudf_16/lib/python3.7/site-packages/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, parse_dates, comment, na_values, keep_default_na, na_filter, prefix, index_col, **kwargs)
     84         na_filter=na_filter,
     85         prefix=prefix,
---> 86         index_col=index_col,
     87     )
     88 

~/workspace/cudf-0.16/cudf/python/cudf/cudf/_lib/csv.pyx in cudf._lib.csv.read_csv()

~/workspace/cudf-0.16/cudf/python/cudf/cudf/_lib/csv.pyx in cudf._lib.csv.make_csv_reader_options()

OverflowError: value too large to convert to int32_t
```

**Expected behavior**
I expect `cudf.read_csv( ..., byte_range=(2_147_483_648, ...))` to work fine.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 60d25ea04bf018905836310a18133806f780cb22 (HEAD)
     Author: Ram (Ramakrishna Prabhu) <42624703+rgsl888prabhu@users.noreply.github.com>
     Date:   Fri Sep 18 17:00:29 2020 -0500
     
     [REVIEW] Add builder API for cuIO `csv_writer_options` and `csv_reader_options` (#6122)
     
     * read_csv lib_cudf
     
     * cython plumbing to new csv
     
     * write csv support
     
     * doc
     
     * changes
     
     * CHANGELOG.md
     
     * adding rmm header
     
     * docs
     
     * review changes with na rep and benchmark
     
     * review changes
     
     * review changes
     
     * review changes
     
     * changes
     
     * test cases for exceptions and na values
     
     * doc header removed and header file complete path added
     
     * rmm change
     **git submodules***
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2020-03-04"
     DGX_SWBUILD_VERSION="4.4.0"
     DGX_COMMIT_ID="ee09ebc"
     DGX_PLATFORM="DGX Server for DGX-1"
     DGX_SERIAL_NUMBER="QTFCOU8220024"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx14 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Sep 21 11:04:30 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   31C    P0    55W / 300W |   3186MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   32C    P0    40W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   30C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   29C    P0    41W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   30C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   30C    P0    41W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   32C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   28C    P0    42W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      7535      C   ...mora/miniconda3/envs/cudf_16/bin/python  1257MiB |
     |    0      7773      C   ...mora/miniconda3/envs/cudf_16/bin/python  1917MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             1840.494
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.04
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /datasets/rzamora/miniconda3/envs/cudf_16/bin/cmake
     cmake version 3.18.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89
     
     ***Python***
     /datasets/rzamora/miniconda3/envs/cudf_16/bin/python
     Python 3.7.8
     
     ***Environment Variables***
     PATH                            : /home/nfs/rzamora/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/bin:/home/nfs/rzamora/bin:/home/nfs/rzamora/.local/bin:/datasets/rzamora/miniconda3/envs/cudf_16/bin:/datasets/rzamora/miniconda3/condabin:/usr/local/cuda/bin:/opt/bin:/home/nfs/rzamora/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/bin:/home/nfs/rzamora/bin:/home/nfs/rzamora/.local/bin:/usr/local/cuda/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /datasets/rzamora/miniconda3/envs/cudf_16
     PYTHON_PATH                     :
     
     ***conda packages***
     /datasets/rzamora/miniconda3/condabin/conda
     # packages in environment at /datasets/rzamora/miniconda3/envs/cudf_16:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     argon2-cffi               20.1.0           py37h8f50634_1    conda-forge
     arrow-cpp                 1.0.1           py37h1234567_1_cuda    conda-forge
     arrow-cpp-proc            1.0.1                      cuda    conda-forge
     attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
     aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
     babel                     2.8.0                      py_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.1            py37hc8dfbb8_0    conda-forge
     boost-cpp                 1.72.0               h7b93d67_2    conda-forge
     brotli                    1.0.9                he1b5a44_0    conda-forge
     brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
     bzip2                     1.0.8                h516909a_3    conda-forge
     c-ares                    1.16.1               h516909a_3    conda-forge
     ca-certificates           2020.6.20            hecda079_0    conda-forge
     certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
     cffi                      1.14.1           py37h2b28604_0    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.2               h5c55442_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.1              py37hb09aad4_0    conda-forge
     cudatoolkit               10.2.89              h6bb024c_0    nvidia
     cudf                      0.16.0a0+1865.g798267bd5d          pypi_0    pypi
     cudnn                     7.6.5                cuda10.2_0
     cupy                      7.8.0            py37h940342b_0    conda-forge
     curl                      7.71.1               he644dc0_5    conda-forge
     cython                    0.29.21          py37h3340039_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.25.0+14.g18964944           dev_0    <develop>
     dask-cuda                 0.16.0a0+90.g2fa52fe           dev_0    <develop>
     dask-cudf                 0.16.0a0+1866.g60d25ea04b.dirty           dev_0    <develop>
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2.25.0+7.ga8032534          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37hc8dfbb8_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37h3340039_1    conda-forge
     entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  1.0.0.post1      py37h8f50634_0    conda-forge
     fastparquet               0.4.1            py37h03ebfcd_0    conda-forge
     fastrlock                 0.5              py37h3340039_0    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               he1b5a44_0    conda-forge
     freetype                  2.10.2               he06d7ca_0    conda-forge
     fsspec                    0.8.1                      py_0    conda-forge
     future                    0.18.2           py37hc8dfbb8_1    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.0                he1b5a44_2    conda-forge
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                5.28.0                     py_0    conda-forge
     icu                       67.1                 he1b5a44_0    conda-forge
     identify                  1.5.0              pyh9f0ad1d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
     importlib_metadata        1.7.0                         0    conda-forge
     iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.3.4            py37h43977f1_0    conda-forge
     ipython                   7.18.1           py37hc6149b9_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2           py37hc8dfbb8_0    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     json5                     0.9.4              pyh9f0ad1d_0    conda-forge
     jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
     jupyterlab                2.2.7                      py_0    conda-forge
     jupyterlab_server         1.2.0                      py_0    conda-forge
     krb5                      1.17.1               hfafb76e_3    conda-forge
     lcms2                     2.11                 hbd6801e_0    conda-forge
     ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
     libblas                   3.8.0               17_openblas    conda-forge
     libcblas                  3.8.0               17_openblas    conda-forge
     libcurl                   7.71.1               hcdd3856_5    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_2    conda-forge
     libffi                    3.2.1             he1b5a44_1007    conda-forge
     libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
     libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
     libgomp                   9.3.0               h24d8f2e_16    conda-forge
     liblapack                 3.8.0               17_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libprotobuf               3.12.4               h8b12597_0    conda-forge
     librmm                    0.16.0a200909   cuda10.2_g9d02c5b_365    rapidsai-nightly
     libsodium                 1.0.18               h516909a_0    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
     libtiff                   4.1.0                hc7e4089_6    conda-forge
     libutf8proc               2.5.0                h516909a_2    conda-forge
     libuv                     1.39.0               h516909a_0    conda-forge
     libwebp-base              1.1.0                h516909a_3    conda-forge
     llvmlite                  0.34.0           py37h5202443_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.2.2                      py_0    conda-forge
     markupsafe                1.1.1            py37h8f50634_1    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h8f50634_1001    conda-forge
     more-itertools            8.5.0                      py_0    conda-forge
     msgpack-python            1.0.0            py37h99015e2_1    conda-forge
     nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
     nbformat                  5.0.7                      py_0    conda-forge
     nbsphinx                  0.7.1              pyh9f0ad1d_0    conda-forge
     nccl                      2.7.8.1              hc6a2c23_0    conda-forge
     ncurses                   6.2                  he1b5a44_1    conda-forge
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.1.3            py37hc8dfbb8_0    conda-forge
     numba                     0.51.2           py37h9fdb41a_0    conda-forge
     numpy                     1.19.1           py37h7ea13bd_2    conda-forge
     numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1g               h516909a_1    conda-forge
     packaging                 20.4               pyh9f0ad1d_0    conda-forge
     pandas                    1.1.2            py37h3340039_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
     pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
     pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
     pillow                    7.2.0            py37h718be6c_1    conda-forge
     pip                       20.2.3                     py_0    conda-forge
     pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
     pre-commit                2.7.1            py37hc8dfbb8_0    conda-forge
     pre_commit                2.7.1                         0    conda-forge
     prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
     prompt-toolkit            3.0.7                      py_0    conda-forge
     psutil                    5.7.2            py37h8f50634_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.9.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37h1234567_1_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.6.1                      py_0    conda-forge
     pynvml                    8.0.4                    pypi_0    pypi
     pyopenssl                 19.1.0                     py_1    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.0           py37h8f50634_0    conda-forge
     pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
     pytest                    6.0.1            py37hc8dfbb8_0    conda-forge
     python                    3.7.8           h6f2ec95_1_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py37h8f50634_0    conda-forge
     pyzmq                     19.0.2           py37hac76be4_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.08.01           he1b5a44_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2020.7.14        py37h8f50634_0    conda-forge
     requests                  2.24.0             pyh9f0ad1d_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.16.0a200909   cuda_10.2_py37_g9d02c5b_365    rapidsai-nightly
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37hc8dfbb8_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.2.1                      py_0    conda-forge
     sphinx-copybutton         0.3.0              pyh9f0ad1d_0    conda-forge
     sphinx-markdown-tables    0.0.14             pyh9f0ad1d_1    conda-forge
     sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.33.0               h4cf870e_0    conda-forge
     streamz                   0.5.5                    pypi_0    pypi
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift                    0.11.0          py37he1b5a44_1001    conda-forge
     thrift-cpp                0.13.0               h62aa4f2_3    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.1             pyh9f0ad1d_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.4            py37h8f50634_1    conda-forge
     traitlets                 5.0.4                      py_0    conda-forge
     typed-ast                 1.4.1            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.2                    py_0    conda-forge
     urllib3                   1.25.10                    py_0    conda-forge
     virtualenv                20.0.20          py37hc8dfbb8_1    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.2                he1b5a44_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.1.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1009    conda-forge
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Additional context**
This bug prevents the OLCF benchmarks from working on the latest `branch-0.16` cc @pentschev

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
closes #6284

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

File: cpp/include/cudf/io/csv.hpp [hunk 1]
```diff
@@ -351,7 +351,7 @@ class csv_reader_options {
    *
    * @param offset Number of bytes of offset.
    */
-  void set_byte_range_offset(size_type offset)
+  void set_byte_range_offset(size_t offset)
```
Comment (jrhemstad) [inline cpp/include/cudf/io/csv.hpp:354]: `size_t` should always be qualified with `std`. 
```suggestion
  void set_byte_range_offset(std::size_t offset)
```

**Review by jrhemstad — CHANGES_REQUESTED** [review]

**Comment by davidwendt** [comment]
Just curious why there are 23 commits in this PR dating back to August.

**Comment by rgsl888prabhu** [comment]
> Just curious why there are 23 commits in this PR dating back to August.

Not sure why.

**Comment by rgsl888prabhu** [comment]
> Just curious why there are 23 commits in this PR dating back to August.

May be because currently we do squash and merge, so old commits are not seen while  comparing.

**Review by galipremsagar — APPROVED** [review]
Approving from cython/python side. I'll add the python test under fuzz tests as part of this issue: https://github.com/rapidsai/cudf/issues/6260

**Review by jrhemstad — APPROVED** [review]

**Review by cwharris — APPROVED** [review]

**Review by cwharris — CHANGES_REQUESTED** [review]
Any chance we can add a test case?

**Comment by rgsl888prabhu** [comment]
> Any chance we can add a test case?

Prem is planning to add test case in his fuzz-test, so I left.

**Comment by cwharris** [comment]
@rgsl888prabhu fuzz test is for random testing, but this is a specific edge case. seems more appropriate to make it a unit test.

**Comment by cwharris** [comment]
sorry. wrong button. :)

**Review by davidwendt — APPROVED** [review]

File: python/cudf/cudf/tests/test_csv.py [hunk 2]
```diff
@@ -1023,6 +1023,19 @@ def test_csv_reader_byte_range(tmpdir, segment_bytes):
...
+    fname = tmpdir.mkdir("gdf_csv").join("tmp_csvreader_file17.csv")
+
+    cudf.datasets.timeseries(
+        start="2000-01-01",
+        end="2002-12-31",
+        dtypes={"name": str, "id": int, "x": float, "y": float},
+    ).to_csv(fname, chunksize=100000)
+
+    byte_range = (2_147_483_648, 100_000_000)
+    cudf.read_csv(fname, byte_range=byte_range, header=None)
```
Comment (kkraus14) [inline python/cudf/cudf/tests/test_csv.py:1036]: This test looks quite expensive. Anything we could do to mock it instead or something similar?

Comment (rgsl888prabhu) [reply python/cudf/cudf/tests/test_csv.py:1036]: This test doesn't take much time, but to just check type limitation, we can observe which error message we are getting and depending on that we can Assert or Pass the test.

Comment (kkraus14) [reply python/cudf/cudf/tests/test_csv.py:1036]: Writing out a 2+ GB file to disk could be painful / slow on some machines / environments. The error messaging makes sense to me to change the test for.

File: python/cudf/cudf/tests/test_csv.py [hunk 3]
```diff
@@ -1028,12 +1028,16 @@ def test_csv_reader_byte_range_type_corner_case(tmpdir):
...
     ).to_csv(fname, chunksize=100000)
 
-    byte_range = (2_147_483_648, 100_000_000)
-    cudf.read_csv(fname, byte_range=byte_range, header=None)
+    byte_range = (2_147_483_648, 0)
+    try:
+        cudf.read_csv(fname, byte_range=byte_range, header=None)
+    except RuntimeError as e:
+        if "Offset is past end of file" not in str(e):
+            raise e
```
Comment (kkraus14) [inline python/cudf/cudf/tests/test_csv.py:1040]: Instead of doing this we should be able to do:
```
with pytest.raises(RuntimeError, match="Offset is past end of file"):
    cudf.read_csv(fname, byte_range=byte_range, header=None)
```

May need to tweak the match regex to get it right, but that's the idea

File: python/cudf/cudf/tests/test_csv.py [hunk 4]
```diff
@@ -1023,6 +1023,20 @@ def test_csv_reader_byte_range(tmpdir, segment_bytes):
...
 
 
+def test_csv_reader_byte_range_type_corner_case(tmpdir):
+    fname = tmpdir.mkdir("gdf_csv").join("tmp_csvreader_file17.csv")
+
+    cudf.datasets.timeseries(
+        start="2000-01-01",
+        end="2000-01-02",
+        dtypes={"name": str, "id": int, "x": float, "y": float},
+    ).to_csv(fname, chunksize=100000)
```
Comment (kkraus14) [inline python/cudf/cudf/tests/test_csv.py:1033]: Instead of writing to a file or going through cudf at all here can we just contruct a basic StringIO buffer here instead?

```
from io import StringIO

buf = StringIO('a,b,c\n0,1,2\n')
byte_range = (2_147_483_648, 0)
with pytest.raises(RuntimeError, match="Offset is past end of file"):
    cudf.read_csv(buf, byte_range=byte_range, header=None)

Comment (rgsl888prabhu) [reply python/cudf/cudf/tests/test_csv.py:1033]: With StringIO, it first goes to arrow to read sample data and it fails with different error, so can't use it.

Comment (kkraus14) [reply python/cudf/cudf/tests/test_csv.py:1033]: Maybe use `BytesIO` instead? `buf = BytesIO(b'a,b,c\n0,1,2\n')`

I know we plumbed support for IO buffers in the Python layer.

Comment (rgsl888prabhu) [reply python/cudf/cudf/tests/test_csv.py:1033]: It is issue in lubcudf, not in python

Comment (rgsl888prabhu) [reply python/cudf/cudf/tests/test_csv.py:1033]: cudf/cpp/include/cudf/io/datasource.hpp:250: Cannot read file data

Comment (kkraus14) [reply python/cudf/cudf/tests/test_csv.py:1033]: This should be handled... https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/_lib/io/utils.pyx#L39-L43

Comment (kkraus14) [reply python/cudf/cudf/tests/test_csv.py:1033]: Either way we can handle this in a follow up.

**Review by kkraus14 — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by rgsl888prabhu** [comment]
rerun tests
