### PR TITLE
Mark column chunks in a PQ reader `pass` as large strings when the cumulative `offsets` exceeds the large strings threshold.

### LINKED ISSUE #17158: [BUG] Chunked parquet reader incorrect results for large string columns
**Describe the bug**
When reading parquet with the chunked parquet reader, I get a different result than with the non-chunked reader for certain datasets with large string columns.

**Steps/Code to reproduce bug**
```python

import pylibcudf as plc
import pyarrow as pa
import cudf

PATH = xyz # snip
columns = abc # snip

reader = plc.io.parquet.ChunkedParquetReader(
        plc.io.SourceInfo([PATH]),
        columns=columns,
        nrows=-1,
        skip_rows=0,
        chunk_read_limit=0,
        pass_read_limit=17179869184 # 16 GiB
)
chk = reader.read_chunk()
tbl = chk.tbl
names = chk.column_names()
concatenated_columns = tbl.columns()

while reader.has_next():
    tbl = reader.read_chunk().tbl
    for i in range(tbl.num_columns()):
        concatenated_columns[i] = plc.concatenate.concatenate(
                [concatenated_columns[i], tbl._columns[i]]
        )
        tbl._columns[i] = None

chunked_col = plc.interop.to_arrow(concatenated_columns[2])

non_chunked = plc.io.parquet.read_parquet(
        plc.io.SourceInfo([PATH]),
        columns=columns,
        nrows=-1,
        skip_rows=0
        )

non_chunked_col = plc.interop.to_arrow(non_chunked.columns[2])

assert chunked_col.equals(non_chunked_col) # False

```

**Expected behavior**
I expect the same data.

**Environment overview (please complete the following information)**
 - Environment location: Bare metal
 - Method of cuDF install: Source

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
24.12 head. `PATH` and `columns` are internal values I can provide, contact me for details.  
cc @galipremsagar @GregoryKimball

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description

This PR implements a method to correctly set the large-string property for column chunks in a in the Chunked Parquet Reader subpass if the cumulative string offsets have exceeded the large strings threshold.

Fixes #17158

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/io/parquet/reader_impl.cpp [hunk 1]
```diff
@@ -192,10 +206,15 @@ void reader::impl::decode_page_data(read_mode mode, size_t skip_rows, size_t num
...
+        auto const col_string_size = col_string_sizes[pass.chunks[c].src_col_index];
         // only do string buffer for leaf
-        if (idx == max_depth - 1 and out_buf.string_size() == 0 and
-            col_string_sizes[pass.chunks[c].src_col_index] > 0) {
-          out_buf.create_string_data(col_string_sizes[pass.chunks[c].src_col_index], _stream);
+        if (idx == max_depth - 1 and out_buf.string_size() == 0 and col_string_size > 0) {
+          out_buf.create_string_data(
+            col_string_size,
+            pass.cumulative_col_string_sizes[pass.chunks[c].src_col_index] >
+              static_cast<size_t>(strings::detail::get_offset64_threshold()),
```
Comment (ttnghia) [inline cpp/src/io/parquet/reader_impl.cpp:216]: Does this mean, we may create some small-string columns for the first several chunks, then suddenly we see large string thus we will create all large string columns from that chunk until the end of the reading?

Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.cpp:216]: Yes, that's because we use [str_offset](https://github.com/rapidsai/cudf/blob/0b9277b3abe014b9ab1cf7f849c36b21c2422bbe/cpp/src/io/parquet/parquet_gpu.hpp#L338) for pages within the same pass to compute string offsets in the output buffer, which along with `offptr` is typecasted to `cudf::size_type` here https://github.com/rapidsai/cudf/blob/0b9277b3abe014b9ab1cf7f849c36b21c2422bbe/cpp/src/io/parquet/page_string_decode.cu#L1137

That being said, with default chunking mechanism, we will encounter big n-1 chunks and only the last chunk to be smaller (remnant) depending on the `pass_read_limit` set.

Comment (ttnghia) [reply cpp/src/io/parquet/reader_impl.cpp:216]: Is is possible to have the first `n` chunk having small-string columns while the following chunks have large-string columns? In addition, if having mixed small/large string columns in different chunks, will there be anything to be concerned?

Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.cpp:216]: > Is it possible to have the first n chunk having small-string columns while the following chunks have large-string columns?
Very unlikely imo as it would mean having front-loaded non-string columns and back-loaded string cols. Regardless, we should be able to handle it with the changes in this PR keeping a track of the `offset_ptr` of all string cols.

> if having mixed small/large string columns in different chunks, will there be anything to be concerned?
No we compute string offsets (from a column's pages) per column so for any non-string cols, that will be zero

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 2]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+
+TEST_F(ParquetStringsTest, ChunkedReadLargeStrings)
+{
+  // Construct a table with one large strings column > 2GB
+  auto const wide = this->wide_column();
+  auto input      = cudf::concatenate(std::vector<cudf::column_view>(120000, wide));  ///< 230MB
+
+  int constexpr multiplier = 12;
+  std::vector<cudf::column_view> input_cols(multiplier, input->view());
+  auto col0 = cudf::concatenate(input_cols);  ///< 2.70GB
```
Comment (mhaseeb123) [inline cpp/tests/large_strings/parquet_tests.cpp:82]: Column from GTest: `CaseTest.ToLower`

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 3]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+  cudf::io::parquet_writer_options out_opts =
+    cudf::io::parquet_writer_options::builder(cudf::io::sink_info{filepath}, expected)
+      .compression(cudf::io::compression_type::ZSTD)
+      .stats_level(cudf::io::STATISTICS_NONE)
+      .metadata(expected_metadata);
+  cudf::io::write_parquet(out_opts);
+
+  // Read with chunked_parquet_reader
+  size_t constexpr pass_read_limit =
+    size_t{8} * 1024 * 1024 *
```
Comment (mhaseeb123) [inline cpp/tests/large_strings/parquet_tests.cpp:101]: Chosen by trial and error so the chunking would result in two subpasses. First subpass reading ~2.24GB strings and second one reading the rest of 338MB.

**Review by ttnghia — APPROVED** [review]

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 3 above)
Comment (davidwendt) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: This appears to be a very large file?
How long does this test take to run? Also, how long under compute-sanitizer?

Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: It’s the same column from another large string gtest (`CaseTest.Lower`). Takes roughly 2s to run and 5.5s with `compute-sanitizer —rmm_mode=cuda`

Comment (davidwendt) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: Ok. Thanks for checking!

Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: Without compute sanitizer, the peak GPU mem usage seen in nvidia-smi is roughly 3.4GB and with compute sanitizer, it’s roughly 14.3GB

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 4]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+  auto reader = cudf::io::chunked_parquet_reader(0, pass_read_limit, default_in_opts);
+
+  auto tables = std::vector<std::unique_ptr<cudf::table>>{};
+  while (reader.has_next()) {
+    tables.emplace_back(reader.read_chunk().tbl);
+  }
+  auto table_views = std::vector<cudf::table_view>{};
+  for (auto const& tbl : tables) {
+    table_views.emplace_back(tbl->view());
+  }
```
Comment (davidwendt) [inline cpp/tests/large_strings/parquet_tests.cpp:115]:
```suggestion
  std::transform( tables.begin(), tables.end(), std::back_inserter(table_views), [] (auto& t) { return t->view(); });
```

File: cpp/src/io/parquet/reader_impl.cpp [hunk 5]
```diff
@@ -97,22 +97,36 @@ void reader::impl::decode_page_data(read_mode mode, size_t skip_rows, size_t num
...
+    // ensure cumulative column string sizes have been initialized
+    if (pass.cumulative_col_string_sizes.empty()) {
+      pass.cumulative_col_string_sizes.resize(_input_columns.size(), 0);
+    }
+
+    // add to cumulative column string sizes from this subpass
+    std::transform(pass.cumulative_col_string_sizes.begin(),
+                   pass.cumulative_col_string_sizes.end(),
+                   col_string_sizes.begin(),
+                   pass.cumulative_col_string_sizes.begin(),
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl.cpp:112]: Could we avoid the resize above by using a back_inserter here?

Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.cpp:112]: Technically yes, based on conditional; back_insert if empty else add vectors. Though, `resize` happens only once per reader `pass` based on the same predicate.

Comment (vuule) [reply cpp/src/io/parquet/reader_impl.cpp:112]: > back_insert if empty else add vectors

That's definitely not better than the current code. Resolving :)

File: cpp/src/io/parquet/reader_impl.cpp [hunk 6]
```diff
@@ -97,22 +97,36 @@ void reader::impl::decode_page_data(read_mode mode, size_t skip_rows, size_t num
...
+                   std::plus<>{});
+
     // check for overflow
     auto const threshold         = static_cast<size_t>(strings::detail::get_offset64_threshold());
-    auto const has_large_strings = std::any_of(col_string_sizes.cbegin(),
-                                               col_string_sizes.cend(),
+    auto const has_large_strings = std::any_of(pass.cumulative_col_string_sizes.cbegin(),
```
Comment (vuule) [inline cpp/src/io/parquet/reader_impl.cpp:117]: I think we need a comment either here or at the `transform` call to explain why we're using the cumulative sizes here.

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 7]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+  auto table_views = std::vector<cudf::table_view>{};
+  std::transform(tables.begin(), tables.end(), std::back_inserter(table_views), [](auto& tbl) {
+    return tbl->view();
+  });
+  auto result            = cudf::concatenate(table_views);
+  auto const result_view = result->view();
+
+  // Verify
+  for (auto cv : result_view) {
```
Comment (vuule) [inline cpp/tests/large_strings/parquet_tests.cpp:120]:
```suggestion
  for (auto const& cv : result_view) {
```

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 8]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+  auto const expected    = cudf::table_view{{col0->view()}};
+  auto expected_metadata = cudf::io::table_input_metadata{expected};
+  expected_metadata.column_metadata[0].set_encoding(
+    cudf::io::column_encoding::DELTA_LENGTH_BYTE_ARRAY);
+
+  // Write to Parquet
+  auto const filepath = g_temp_env->get_temp_filepath("ChunkedReadLargeStrings.parquet");
+  cudf::io::parquet_writer_options out_opts =
+    cudf::io::parquet_writer_options::builder(cudf::io::sink_info{filepath}, expected)
+      .compression(cudf::io::compression_type::ZSTD)
```
Comment (vuule) [inline cpp/tests/large_strings/parquet_tests.cpp:94]: why ZSTD?
also, is it any faster to write to a `std::vector` instead of a file?

File: cpp/tests/large_strings/parquet_tests.cpp [hunk 9]
```diff
@@ -69,3 +70,57 @@ TEST_F(ParquetStringsTest, ReadLargeStrings)
...
+
+  int constexpr multiplier = 12;
+  std::vector<cudf::column_view> input_cols(multiplier, input->view());
+  auto col0 = cudf::concatenate(input_cols);  ///< 2.70GB
+
+  // Expected table
+  auto const expected    = cudf::table_view{{col0->view()}};
+  auto expected_metadata = cudf::io::table_input_metadata{expected};
+  expected_metadata.column_metadata[0].set_encoding(
+    cudf::io::column_encoding::DELTA_LENGTH_BYTE_ARRAY);
```
Comment (vuule) [inline cpp/tests/large_strings/parquet_tests.cpp:88]: Why is the encoding specified for this test?
Apologies if I missed a conversation :)

**Review by vuule — COMMENTED** [review]
small comments; the core of the change looks good.

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 9 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:88]: Came from copy-pasting the test body from the above GTest which does the same thing as this one except using `read_parquet`.

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 8 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:94]: ^ Same as above. Probably, the test takes 2s to run anyway, 5s with `compute-sanitizer`

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 3 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: @vuule for vis

File: cpp/src/io/parquet/reader_impl.cpp (hunk 6 above)
Comment (mhaseeb123) [reply cpp/src/io/parquet/reader_impl.cpp:118]: Added a couple comments to provide more context.

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 3 above)
Comment (vuule) [reply cpp/tests/large_strings/parquet_tests.cpp:101]: I'm okay with two seconds. I get triggered closer to 10s mark :D

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 8 above)
Comment (vuule) [reply cpp/tests/large_strings/parquet_tests.cpp:94]: I think we should prefer the defaults if there's no reason to do otherwise.

Well... 2s is still hefty for a single test. I do suspect removing IO does not help, so not pushing for it here.

Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:92]: All done. removed!

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 9 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:86]: Update: Removing this encoding changes the chunking behavior and requires empirically choosing another smaller `pass_read_limit` so leaving this as is.

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 8 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp]: Discussed offline: We have disabled this test by default as it is too brittle and depends on empirical pass_read_limit, ZSTD scratch space, and DLBA encoding which may change in the future leading to false failures.

File: cpp/tests/large_strings/parquet_tests.cpp (hunk 9 above)
Comment (mhaseeb123) [reply cpp/tests/large_strings/parquet_tests.cpp:93]: Same comment as above. Disabled by default with comments added.

**Review by vuule — APPROVED** [review]
Thank you for iterating on this!

**Review by davidwendt — APPROVED** [review]

**Comment by binmahone** [comment]
hi @mhaseeb123 , I have a silly question (because I'm not very familiar with CUDF code): why are cumulative string offsets counted per pass instead of per subpass? We have a parquet file whose string column in one RG alone is more than 2G, after https://github.com/rapidsai/cudf/pull/17207 such column will be treated as large string column and thus become unacceptable in Spark-Rapids (Spark-Rapids does not allow large columns, as described in https://github.com/rapidsai/cudf/issues/16215) 

If cumulative string offsets are counted per subpass, then we can keep using normal string columns in many cases. Is there any particular reason stopping us from going with subpass?

**Comment by nvdbaranec** [comment]
@binmahone @mhaseeb123 
I'm not familiar with how we're doing this new handling of large string columns, but it does seem like the subpass level is where it would make the most sense to do it.  Subpasses are what correspond to an actual blob of output, so that's where you'd ideally want to trap it.  Passes are just IO operations of 1 or more row groups, which as you stated, can be arbitrarily big.

**Comment by mhaseeb123** [comment]
@nvdbaranec 
> I'm not familiar with how we're doing this new handling of large string columns, but it does seem like the subpass level is where it would make the most sense to do it.

Yes, you are correct. I updated the behavior accordingly in #17693 and it solves both @binmahone's comment and the original issue this PR aimed to solve.
