### PR TITLE
Use default value for decimal precision in parquet writer when not specified

### LINKED ISSUE #9962: [BUG] Parquet Reader Bench throwing cudf::logic_error
**Describe the bug**
Running the libcudf Parquet Reader benchmark (no args other than `--benchmark_format=json`) results in a cudf::logic_error:
```
terminate called after throwing an instance of 'cudf::logic_error'                                                                                                    
  what():  cuDF failure at: /rapids/cudf/cpp/src/io/parquet/writer_impl.cu:464: Precision must be specified for decimal columns
```

**Steps/Code to reproduce bug**
Run the libcudf Parquet Reader benchmark

**Expected behavior**
The benchmark completes w/ no errors

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
Docker: FROM rapidsai/rapidsai-dev-nightly:22.02-cuda11.5-devel-ubuntu20.04-py3.7

 - Method of cuDF install: [conda, Docker, or from source]
After pulling the above nightly Docker image, I build & run the benchmark

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
https://gist.github.com/randerzander/8e3a8876850848672ea9f889b827ba5e

### PR DESCRIPTION
**Pull request by devavret**
Fixes #9962

### CODE REVIEW

File: cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp [hunk 1]
```diff
@@ -50,8 +50,16 @@ void BM_parq_read_varying_input(benchmark::State& state)
   auto const view = tbl->view();
 
   cuio_source_sink_pair source_sink(source_type);
+  auto table_meta = cudf::io::table_input_metadata(view);
+  if (state.range(0) == int32_t(type_group_id::FIXED_POINT)) {
```
Comment (ttnghia) [inline cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp:54]:
```suggestion
  if (state.range(0) == static_cast<int32_t>(type_group_id::FIXED_POINT)) {
```

File: cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp [hunk 2]
```diff
@@ -160,12 +168,12 @@ void BM_parq_read_varying_options(benchmark::State& state)
     ->Unit(benchmark::kMillisecond)                                                          \
     ->UseManualTime();
 
-RD_BENCHMARK_DEFINE_ALL_SOURCES(PARQ_RD_BM_INPUTS_DEFINE, integral, type_group_id::INTEGRAL);
-RD_BENCHMARK_DEFINE_ALL_SOURCES(PARQ_RD_BM_INPUTS_DEFINE, floats, type_group_id::FLOATING_POINT);
+// RD_BENCHMARK_DEFINE_ALL_SOURCES(PARQ_RD_BM_INPUTS_DEFINE, integral, type_group_id::INTEGRAL);
+// RD_BENCHMARK_DEFINE_ALL_SOURCES(PARQ_RD_BM_INPUTS_DEFINE, floats, type_group_id::FLOATING_POINT);
```
Comment (ttnghia) [inline cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp:172]: Not sure if these commented lines are still needed.

**Comment by devavret** [comment]
After fixing the missing decimal precision, this still fails with `Benchmark did not read the entire table`. I think the logic to determine row_groups is improper. https://github.com/rapidsai/cudf/blob/ce02856c099694ad463dbf7970dfc69276842557/cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp#L123
because
1. It uses 128 MB hardcoded
2. Row group is no longer fixed to being 128 MB with #9615 
3. Even if it was fixed, there is no guarantee the row groups will be data size/128 MB because 128 MB is still just an upper limit. There can be more row groups.

I'm thinking the fix could be that we add a libcudf API to read metadata. But this could take longer.

Apart from this failure, I see some more in the benchmarks for `row_selection::NROWS`. I think we should just disable `ParquetRead/row_selection` benchmarks for now.

File: cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp [hunk 3]
```diff
@@ -101,8 +109,17 @@ void BM_parq_read_varying_options(benchmark::State& state)
   auto const view = tbl->view();
 
   std::vector<char> parquet_data;
+  auto table_meta = cudf::io::table_input_metadata(view);
+  // Precision is required for decimal columns but the value doesn't affect the performance
+  for (cudf::size_type c = 0; c < view.num_columns(); ++c) {
```
Comment (hyperbolic2346) [inline cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp:114]:
```suggestion
  for (auto c = 0; c < view.num_columns(); ++c) {
```

This might read easier.

**Review by hyperbolic2346 — APPROVED** [review]
Overall this change seems fine, but it sounds like there is more work to be done here as always.

**Comment by devavret** [comment]
> Can we default to the max precision for the input decimal type?

I think this was avoided because there were some spark rules that limited precision based on decimal type width. And I figured all other libcudf users might not agree with those rules. The precursor to the precision setting in table_input_metadata was a writer option and that also threw when precision wasn't specified. @hyperbolic2346 would know why.

Although it wouldn't hurt because precision is merely a schema thing. It doesn't affect the data written into the pages, which are still the underlying rep.

**Review by ttnghia — APPROVED** [review]

**Comment by devavret** [comment]
rerun tests

**Comment by devavret** [comment]
@gpucibot merge
