### PR TITLE
Deduplicate parquet physical type enums

### LINKED ISSUE #18525: [FEA] Deduplicate `TypeKind` and `Type` enums in `parquet_metadata.hpp` and `parquet_schema.hpp`
**Describe the bug**
We currently have two enums - called `TypeKind` and `Type` defined in `parquet_metadata.hpp` and `parquet_schema.hpp` respectively - to represent Parquet physical types. The former is mainly being used in `struct parquet_column_schema` also defined in `parquet_metadata.hpp`. We should deduplicate the enum and only use the `enum Type` from `parquet_schema.hpp`

**Steps/Code to reproduce bug**
No bug seen currently but can lead to inconsistencies and extra maintenance effort in the future as Parquet physical types evolve.

**Expected behavior**
`struct parquet_column_schema` must use the `enum Type` from `parquet_schema.hpp` instead of a duplicate version.

**Environment overview (please complete the following information)**
N/A

**Environment details**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description

Closes #18525.

This PR removes the duplicated `TypeKind` enum representing Parquet physical types and updates its use with the `Type` enum defined in `parquet_schema.hpp`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/include/cudf/io/parquet_metadata.hpp [hunk 1]
```diff
@@ -21,14 +21,16 @@
...
 #include <cudf/io/types.hpp>
 #include <cudf/utilities/export.hpp>
 
-#include <optional>
 #include <string_view>
-#include <variant>
 #include <vector>
 
+//! Parquet physical `Type`
+using Type = cudf::io::parquet::Type;
```
Comment (mhaseeb123) [inline cpp/include/cudf/io/parquet_metadata.hpp:32]:
```suggestion
using cudf::io::parquet::Type;
```

File: cpp/include/cudf/io/parquet_metadata.hpp [hunk 2]
```diff
@@ -21,14 +21,16 @@
...
+#include <cudf/io/parquet_schema.hpp>
 #include <cudf/io/types.hpp>
 #include <cudf/utilities/export.hpp>
 
-#include <optional>
 #include <string_view>
-#include <variant>
 #include <vector>
 
+//! Parquet physical `Type`
```
Comment (mhaseeb123) [inline cpp/include/cudf/io/parquet_metadata.hpp:31]: To pass doxygen style-check

File: cpp/include/cudf/io/parquet_metadata.hpp [hunk 3]
```diff
@@ -21,14 +21,16 @@
...
+using cudf::io::parquet::Type;
```
Comment (vuule) [inline cpp/include/cudf/io/parquet_metadata.hpp:32]: should this be in the cudf::io namespace?

Comment (vuule) [reply cpp/include/cudf/io/parquet_metadata.hpp:32]: I mean should the `using` here be in the namespace?

Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet_metadata.hpp:32]: I see. yeah of course

Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet_metadata.hpp]: All done!

File: cpp/include/cudf/io/parquet_metadata.hpp [hunk 4]
```diff
@@ -89,11 +73,18 @@ struct parquet_column_schema {
...
+  [[nodiscard]] auto type() const { return _type; }
+
+  /**
+   * @brief Returns parquet physical type of the column.
    *
-   * @return Column parquet type
+   * @deprecated in branch-25.06 and to be removed in a future release; Use `type()` instead.
    */
-  [[nodiscard]] auto type_kind() const { return _type_kind; }
+  [[deprecated]] [[nodiscard]] auto type_kind() const { return _type; }
```
Comment (mhaseeb123) [inline cpp/include/cudf/io/parquet_metadata.hpp:87]: Deprecating instead of renaming to avoid breaking change.

File: cpp/include/cudf/io/parquet_metadata.hpp [hunk 5]
```diff
@@ -37,23 +36,8 @@ namespace io {
...
-  INT64                = 2,
-  INT96                = 3,  // Deprecated
-  FLOAT                = 4,
-  DOUBLE               = 5,
-  BYTE_ARRAY           = 6,
-  FIXED_LEN_BYTE_ARRAY = 7,
-};
-}  // namespace parquet
+//! Parquet physical `Type`
+using cudf::io::parquet::Type;
```
Comment (PointKernel) [inline cpp/include/cudf/io/parquet_metadata.hpp:40]: probably clearer not to use an alias

**Review by PointKernel — APPROVED** [review]
Nice cleanups. I have one question but no need to review it again.

File: cpp/include/cudf/io/parquet_metadata.hpp (hunk 4 above)
Comment (vuule) [reply cpp/include/cudf/io/parquet_metadata.hpp:87]: isn't it returning a different type now?

File: cpp/include/cudf/io/parquet_metadata.hpp (hunk 5 above)
Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet_metadata.hpp:40]: Using `cudf::io::parquet::Type` directly in `parquet_column_schema` unfortunately fails docs build for some reason. Hence this alias.

File: cpp/include/cudf/io/parquet_metadata.hpp (hunk 4 above)
Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet_metadata.hpp:87]: The same thing.

**Review by vuule — APPROVED** [review]
