### PR TITLE
Fix parquet predicate filtering with column projection

### LINKED ISSUE #15051: [BUG] Parquet reader cannot use filters in tandem with column projection
**Describe the bug**

Reading a column-projected parquet file (that has $N$ on disk columns) and simultaneously applying a filter expression to the read columns is not possible, unless the columns we request to read are the first $[0, \dots, K), K \le N$.

The problem appears to be that the filter expression must (eventually) refer to columns by their index, however one part of the code (that uses row-group filters) expects these indices to match the indices of the columns in the un-projected metadata, whereas another part needs the indices to match the requested projected column indices. It is not possible to arrange this to be the case for either a reordering or a non-dense subset of columns.

**Steps/Code to reproduce bug**

```patch
diff --git a/cpp/tests/io/parquet_reader_test.cpp b/cpp/tests/io/parquet_reader_test.cpp
index abbd0c97f0..1113d6c578 100644
--- a/cpp/tests/io/parquet_reader_test.cpp
+++ b/cpp/tests/io/parquet_reader_test.cpp
@@ -1406,6 +1406,28 @@ TEST_F(ParquetReaderTest, FilterIdentity)
   CUDF_TEST_EXPECT_TABLES_EQUAL(*result.tbl, *result2.tbl);
 }
 
+TEST_F(ParquetReaderTest, FilterWithColumnProjection)
+{
+  auto [src, filepath] = create_parquet_with_stats("FilterWithColumnProjection.parquet");
+  auto val = cudf::numeric_scalar<uint32_t>{10};
+  auto lit = cudf::ast::literal{val};
+  auto col_ref = cudf::ast::column_name_reference{"col_uint32"};
+  auto col_index = cudf::ast::column_reference{0};
+  auto read_expr = cudf::ast::operation(cudf::ast::ast_operator::LESS, col_ref, lit);
+  auto filter_expr = cudf::ast::operation(cudf::ast::ast_operator::LESS, col_index, lit);
+
+  auto predicate = cudf::compute_column(src, filter_expr);
+  auto projected_table = cudf::table_view{{src.get_column(2), src.get_column(0)}};
+  auto expected = cudf::apply_boolean_mask(projected_table, *predicate);
+
+  auto read_opts =
+    cudf::io::parquet_reader_options::builder(cudf::io::source_info{filepath})
+     .columns({"col_double", "col_uint32"})
+     .filter(read_expr);
+  auto result = cudf::io::read_parquet(read_opts);
+  CUDF_TEST_EXPECT_TABLES_EQUAL(*result.tbl, *expected);
+}
+
 TEST_F(ParquetReaderTest, FilterReferenceExpression)
 {
   auto [src, filepath] = create_parquet_with_stats("FilterReferenceExpression.parquet");
```

Build the cudf tests and then run:
```
$ ./PARQUET_TEST --gtest_filter=ParquetReaderTest.FilterWithColumnProjection
Note: Google Test filter = ParquetReaderTest.FilterWithColumnProjection
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ParquetReaderTest
[ RUN      ] ParquetReaderTest.FilterWithColumnProjection
unknown file: Failure
C++ exception with description "CUDF failure at:/home/coder/cudf/cpp/src/io/parquet/predicate_pushdown.cpp:111: Invalid type and stats combination" thrown in the test body.

[  FAILED  ] ParquetReaderTest.FilterWithColumnProjection (13 ms)
[----------] 1 test from ParquetReaderTest (13 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (13 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ParquetReaderTest.FilterWithColumnProjection

 1 FAILED TEST
```

**Expected behavior**

This should work.

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
Fixes #15051

The predicate filtering in parquet did not work while column projection is used. This PR fixes that limitation.

With this PR change, the user will be able to use both column name reference and column index reference in the filter.
- column name reference: the filters may specify any columns by name even if they are not present in column projection.
- column reference (index): The indices used should be the indices of output columns in the requested order.

This is achieved by extracting column names from filter and add to output buffers, after predicate filtering is done, these filter-only columns are removed and only requested columns are returned.
The change includes reading only output columns' statistics data instead of all root columns.

Summary of changes:
- `get_column_names_in_expression` extracts column names in filter.
- The extra columns in filter are added to output buffers during reader initialization
  - `cpp/src/io/parquet/reader_impl_helpers.cpp`, `cpp/src/io/parquet/reader_impl.cpp`
- instead of extracting statistics data of all root columns, it extracts for only output columns (including columns in filter)
  - `cpp/src/io/parquet/predicate_pushdown.cpp`
  - To do this, output column schemas and its dtypes should be cached.
  - statistics data extraction code is updated to check for `schema_idx` in row group metadata.
  - No need to convert filter again for all root columns, reuse the passed output columns reference filter. 
  - Rest of the code is same.
- After the output filter predicate is calculated, these filter-only columns are removed
- moved `named_to_reference_converter` constructor to cpp, and remove used constructor.
- small include<> cleanup

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by GregoryKimball** [comment]
This is great! Nice work @karthikeyann. Let's please add a step to drop any filter columns that weren't part of the requested column set before returning the table.

File: cpp/src/io/parquet/predicate_pushdown.cpp [hunk 1]
```diff
@@ -374,9 +374,46 @@ class stats_expression_converter : public ast::detail::expression_transformer {
...
+    return dtype;
+  };
+
+  auto const& root = get_schema(0);
+  for (auto const& schema_idx : root.children_idx) {
+    if (schema_idx < 0) { continue; }
+    _root_level_types.push_back(get_dtype(schema_idx));
+    _root_level_names.push_back(get_schema(schema_idx).name);
+  }
+  return {_root_level_types, _root_level_names};
```
Comment (wence-) [inline cpp/src/io/parquet/predicate_pushdown.cpp:411]: *question*: These are fields of the `aggregate_reader_metadata` struct, so should they _also_ be returned here? Or, conversely, if we're returning them here, should they then not be members of the struct?

**Comment by wence-** [comment]
Thanks, like @GregoryKimball it would be nice if the column selection were disjoint from the filtering selection logic in terms of determining what columns are finally returned. So that I can filter on (say) `"A"` and `"B"`, but return `"C"` and `"D"`.

**Review by wence- — COMMENTED** [review]
A few questions

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 2]
```diff
@@ -251,6 +251,21 @@ class named_to_reference_converter : public ast::detail::expression_transformer
...
   }
 
+  named_to_reference_converter(std::reference_wrapper<ast::expression const> expr,
+                               host_span<std::string const> root_column_names)
+  {
+    // create map for column name.
+    std::transform(
+      thrust::make_zip_iterator(root_column_names.begin(), thrust::counting_iterator<size_t>(0)),
+      thrust::make_zip_iterator(root_column_names.end(),
+                                thrust::counting_iterator(root_column_names.size())),
```
[the remark this answers is not in the document]
Comment (karthikeyann) [reply cpp/src/io/parquet/reader_impl_helpers.hpp:264]: updated.

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 3]
```diff
@@ -251,6 +251,21 @@ class named_to_reference_converter : public ast::detail::expression_transformer
...
+      std::inserter(column_name_to_index, column_name_to_index.end()),
+      [](auto const& name_index) {
+        return std::make_pair(thrust::get<0>(name_index), thrust::get<1>(name_index));
+      });
+
+    expr.get().accept(*this);
```
[the remark this answers is not in the document]
Comment (karthikeyann) [reply cpp/src/io/parquet/reader_impl_helpers.hpp:270]: `expr` is not modified. A new expression is created and stored and finally it can be accessed after visitor is done.

File: cpp/include/cudf/io/parquet.hpp [hunk 4]
```diff
@@ -195,6 +195,10 @@ class parquet_reader_options {
   /**
    * @brief Sets AST based filter for predicate pushdown.
    *
+   * The filter can utilize cudf::ast::column_name_reference to reference a column by its name,
+   * even if it's not necessarily present in the requested projected columns.
+   * To refer to output column indices, you can use cudf::ast::column_reference.
```
Comment (wence-) [inline cpp/include/cudf/io/parquet.hpp:200]: *suggestion*: I think this is not fully clear. To my understanding there are two possible column mappings available:

1. The on disk parquet data, this has columns `["A", ..., "X"]` (say), in an order defined by the parquet file
2. The requested projected columns, `["X", "A", "Y"]` (say), in an order defined by caller

If I refer to column indices `[0, 2]` in my filter expression, will these apply to `"X"` and `"Y"` both when being applied to the projected column data (as a post-filter) and the row-group pre-filtering?

File: cpp/include/cudf/io/parquet.hpp [hunk 5]
```diff
@@ -195,6 +195,31 @@ class parquet_reader_options {
...
+   * Here, `1` will refer to column "B" because output will contain all columns in
+   * order ["A", ..., "Z"].
+   * Example 3: with column projection
+   * @code
+   * use_columns({"A", "Z", "X"})
+   * .filter(operation(ast_operator::LESS, column_reference{1}, literal{100}));
+   * @endcode
+   * Here, `1` will refer to column "Z" because output will contain 3 columns in
+   * order ["A", "Z", "X"].
+   *
```
Comment (wence-) [inline cpp/include/cudf/io/parquet.hpp:222]: Thanks, this clarifies things. So we can only refer to the projected columns with `column_reference{}`, and do so in projected order. Whereas `column_name_reference` can refer to any column in the parquet file, and obviously order doesn't matter.

Comment (karthikeyann) [reply cpp/include/cudf/io/parquet.hpp:222]: If there is no projection, projected columns is all columns in the parquet file. So, `column_reference{}` can reference them.

File: cpp/src/io/parquet/predicate_pushdown.cpp [hunk 6]
```diff
@@ -374,9 +374,44 @@ class stats_expression_converter : public ast::detail::expression_transformer {
...
+{
+  // TODO, get types and names for only names present in filter.? and their col_idx.
+  // create root column types and names as vector
+  if (!_root_level_types.empty()) return;
+  std::function<cudf::data_type(int)> get_dtype = [strings_to_categorical,
+                                                   timestamp_type_id,
+                                                   &get_dtype,
+                                                   this](int schema_idx) -> cudf::data_type {
+    // returns type of root level columns only.
+    // if (schema_idx < 0) { return false; }
```
Comment (vuule) [inline cpp/src/io/parquet/predicate_pushdown.cpp:388]: old code?

File: cpp/src/io/parquet/predicate_pushdown.cpp [hunk 7]
```diff
@@ -374,9 +374,44 @@ class stats_expression_converter : public ast::detail::expression_transformer {
...
+      return get_dtype(schema_elem.children_idx[0]);
+    }
+
+    auto const one_level_list = schema_elem.is_one_level_list(get_schema(schema_elem.parent_idx));
+    // if we're at the root, this is a new output column
+    auto const col_type = one_level_list
+                            ? type_id::LIST
+                            : to_type_id(schema_elem, strings_to_categorical, timestamp_type_id);
+    auto const dtype    = to_data_type(col_type, schema_elem);
+    // path_is_valid is skipped for nested columns here. TODO: more test cases where no leaf.
```
Comment (vuule) [inline cpp/src/io/parquet/predicate_pushdown.cpp:401]: TODO

**Review by vuule — CHANGES_REQUESTED** [review]
first pass - small suggestions

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 8]
```diff
@@ -284,12 +307,60 @@ class named_to_reference_converter : public ast::detail::expression_transformer
...
+   * @copydoc ast::detail::expression_transformer::visit(ast::operation const& )
+   */
+  std::reference_wrapper<ast::expression const> visit(ast::operation const& expr) override;
+
+  /**
+   * @brief Returns the column names in AST.
+   *
+   * @return AST operation expression
+   */
+  [[nodiscard]] std::vector<std::string> get_column_names() const
```
[the remark this answers is not in the document]
Comment (karthikeyann) [reply cpp/src/io/parquet/reader_impl_helpers.hpp]: That's a great suggestion. After I moved the class to cpp, I used `names_from_expression(args).to_vector();`

File: cpp/src/io/parquet/reader_impl.cpp [hunk 9]
```diff
@@ -355,13 +357,25 @@ reader::impl::impl(std::size_t chunk_read_limit,
...
   _reader_column_schema = options.get_column_schema();
 
-  // Select only columns required by the options
+  // Select only columns required by the options and filter
+  std::optional<std::vector<std::string>> filter_columns_names;
+  if (options.get_filter().has_value() and options.get_columns().has_value()) {
+    // list, struct, dictionary are not supported by AST filter yet.
+    // extract columns not present in get_columns() & keep count to remove at end.
+    auto extractor       = names_from_expression(options.get_filter(), *(options.get_columns()));
+    filter_columns_names = extractor.get_column_names();
```
[the remark this answers is not in the document]
Comment (karthikeyann) [reply cpp/src/io/parquet/reader_impl.cpp]: moved it.

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 10]
```diff
@@ -234,23 +243,37 @@ class named_to_reference_converter : public ast::detail::expression_transformer
...
   named_to_reference_converter(std::optional<std::reference_wrapper<ast::expression const>> expr,
                                table_metadata const& metadata)
-    : metadata(metadata)
   {
     if (!expr.has_value()) return;
+    // create map for column name.
+    auto it_name_id = thrust::make_zip_iterator(metadata.schema_info.cbegin(),
+                                                thrust::counting_iterator<size_t>(0));
+    std::transform(it_name_id,
+                   it_name_id + metadata.schema_info.size(),
```
[the remark this answers is not in the document]
Comment (karthikeyann) [reply cpp/src/io/parquet/reader_impl_helpers.hpp]: removed usage of zip iterator and used 2 iterator transform version.

**Comment by GregoryKimball** [comment]
@etseidl Does this change look like it will work for your application?

**Comment by etseidl** [comment]
> @etseidl Does this change look like it will work for your application?

Yes, I believe so.

File: cpp/include/cudf/io/parquet.hpp (hunk 5 above)
Comment (wence-) [reply cpp/include/cudf/io/parquet.hpp:223]: Thanks, this updated docstring looks good to me.

File: cpp/src/io/parquet/predicate_pushdown.cpp [hunk 11]
```diff
@@ -206,22 +208,31 @@ struct stats_caster {
...
+            auto const& max_value = colchunk.meta_data.statistics.max_value.has_value()
+                                      ? colchunk.meta_data.statistics.max_value
+                                      : colchunk.meta_data.statistics.max;
+            // translate binary data to Type then to <T>
+            min.set_index(stats_idx, min_value, colchunk.meta_data.type);
+            max.set_index(stats_idx, max_value, colchunk.meta_data.type);
+          } else {
+            // Marking it null, if column present in row group
+            min.set_index(stats_idx, thrust::nullopt, {});
+            max.set_index(stats_idx, thrust::nullopt, {});
```
Comment (wence-) [inline cpp/src/io/parquet/predicate_pushdown.cpp:234]: *nit (non-blocking)*: Possibly worthwhile migrating `set_index` to `std::optional`.

File: cpp/src/io/parquet/reader_impl_helpers.hpp [hunk 12]
```diff
@@ -167,18 +169,19 @@ class aggregate_reader_metadata {
...
 
+  std::tuple<host_span<data_type const>, host_span<std::string const>> get_schema_dtypes(
+    bool strings_to_categorical, type_id timestamp_type_id);
+
   /**
    * @brief Filters the row groups based on predicate filter
    *
    * @param row_group_indices Lists of row groups to read, one per source
-   * @param output_dtypes List of output column datatypes
    * @param filter AST expression to filter row groups based on Column chunk statistics
```
[the remark this answers is not in the document]
Comment (wence-) [reply cpp/src/io/parquet/reader_impl_helpers.hpp:244]: Thanks.

File: cpp/tests/io/parquet_reader_test.cpp [hunk 13]
```diff
@@ -1406,6 +1406,56 @@ TEST_F(ParquetReaderTest, FilterIdentity)
...
+
+  // Error cases
+  {  // column_reference is not same type as literal, column_reference index is out of bounds
+    for (auto const index : {0, 2}) {
+      auto col_index2    = cudf::ast::column_reference{index};
+      auto read_ref_expr = cudf::ast::operation(cudf::ast::ast_operator::LESS, col_index2, lit);
+      auto read_opts = cudf::io::parquet_reader_options::builder(cudf::io::source_info{filepath})
+                         .columns({"col_double", "col_uint32"})
+                         .filter(read_ref_expr);
+      EXPECT_THROW(cudf::io::read_parquet(read_opts), cudf::logic_error);
```
Comment (wence-) [inline cpp/tests/io/parquet_reader_test.cpp:1454]: *nit (non-blocking)*: should these throw (per https://github.com/rapidsai/cudf/issues/12885) respectively `cudf::data_type_error` and `std::out_of_range`?

**Review by wence- — APPROVED** [review]
Thanks! LGTM

File: cpp/src/io/parquet/predicate_pushdown.cpp (hunk 11 above)
Comment (karthikeyann) [reply cpp/src/io/parquet/predicate_pushdown.cpp:234]: `min_value` and `min` from `Statistics` struct uses `thrust::optional`, which is passed here.
https://github.com/rapidsai/cudf/blob/064dd7b02166cc67e882b708d66621bc3fafd70b/cpp/src/io/parquet/parquet.hpp uses `thrust::optional` everywhere  (except at 2 places). Not sure why. 
@vuule

File: cpp/tests/io/parquet_reader_test.cpp (hunk 13 above)
Comment (karthikeyann) [reply cpp/tests/io/parquet_reader_test.cpp:1454]: Nice suggestion. These exceptions are thrown from AST. I will create another PR to fix it in AST code.

Comment (vuule) [reply cpp/tests/io/parquet_reader_test.cpp:1454]: if there are two reasons to throw, we need two separate tests

**Review by vuule — APPROVED** [review]

**Review by mhaseeb123 — APPROVED** [review]
Not a blocker but please confirm if we need to cache `output_dtypes` at this time or if just constructing it on the fly would be better.

**Comment by karthikeyann** [comment]
> Thanks for the effort. The changes look good. Not a blocker but please confirm if we need to cache `output_dtypes` at this time or if just constructing it on the fly would be better.

Updated to construct on the fly. will work with `read_chunk()` as well.
