### PR TITLE
Fix JIT cache multi-process test flakiness in slow drives

### LINKED ISSUE #6716: [BUG] JIT_CACHE_MULTIPROC is flaky on slow hard drives
**Describe the bug**
The `JIT_CACHE_MULTIPROC` test is sometimes failing when run on a system that has a rather slow disk speed.  The failure rate is approx 50%.  The output of the failing test is one of these:

```
Child output end
/gpfs/fs1/esoha/cudf/cpp/tests/jit/jit-cache-multiprocess-test.cpp:107: Failure
      Expected: (((status) & 0xff00) >> 8)
      Which is: 1
To be equal to: 0
```

or 

    ￼C++ exception with description "boost::filesystem::remove: Directory not empty: "/home/xxxx/.cudf/0.17.0"" thrown in the test body.

**Steps/Code to reproduce bug**

```
cd /gpfs/fs1/$USER
module load cuda/11.0.1
CUDF_HOME=$(pwd)/cudf
git clone https://github.com/rapidsai/cudf.git $CUDF_HOME
cd $CUDF_HOME
git submodule update --init --remote --recursive
conda env create --name cudf_dev1 --file conda/environments/cudf_dev_cuda11.0.yml
conda activate cudf_dev1
cd $CUDF_HOME/cpp
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 50
make test
```

**Expected behavior**
Expected all tests to pass.  All but on passed

**Environment overview (please complete the following information)**
 - Environment location: In a DGX cluster
 - Method of cuDF install: conda

**Environment details**
```
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_OTA_VERSION="4.0.7"
     DGX_OTA_DATE="Wed Sep 18 18:35:31 UTC 2019"
     DGX_PLATFORM="DGX Server for DGX-1"
     DGX_SERIAL_NUMBER="QTFCOU7460092"
     
     DGX_OTA_VERSION="4.0.7"
     DGX_OTA_DATE="Tue Sep 24 20:33:55 PDT 2019"
     
     DGX_OTA_VERSION="4.0.7"
     DGX_OTA_DATE="Wed Sep 25 19:27:46 PDT 2019"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux prm-dgx-26 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Nov  9 13:51:11 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   27C    P0    42W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   30C    P0    42W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   30C    P0    43W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   27C    P0    42W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   29C    P0    42W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   31C    P0    43W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   29C    P0    43W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   28C    P0    41W / 300W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             2827.634
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.10
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /usr/bin/cmake
cmake: /gpfs/fs1/esoha/miniconda2/envs/join/lib/libcurl.so.4: no version information available (required by cmake)
     cmake version 3.10.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /gpfs/fs1/esoha/miniconda2/bin/python
     Python 2.7.18
     
     ***Environment Variables***
     PATH                            : ~/.local/bin:/gpfs/fs1/esoha/miniconda2/bin:/gpfs/fs1/esoha/miniconda2/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : :/gpfs/fs1/esoha/miniconda2/envs/join/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /gpfs/fs1/esoha/miniconda2
     PYTHON_PATH                     :
     
     ***conda packages***
     /gpfs/fs1/esoha/miniconda2/bin/conda
     # packages in environment at /gpfs/fs1/esoha/miniconda2:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     anaconda-client           1.7.2                    py27_0
     asn1crypto                1.4.0                      py_0
     attrs                     20.2.0                     py_0
     ca-certificates           2020.10.14                    0
     certifi                   2019.11.28               py27_0
     cffi                      1.14.0           py27he30daa8_1
     chardet                   3.0.4                 py27_1003
     clyent                    1.2.2                    py27_1
     conda                     4.8.4                    py27_0
     conda-package-handling    1.6.0            py27h7b6447c_0
     cryptography              2.8              py27h1ba5d50_0
     decorator                 4.4.2                      py_0
     enum34                    1.1.6                    py27_1
     functools32               3.2.3.2                  py27_1
     futures                   3.3.0                    py27_0
     idna                      2.10                       py_0
     ipaddress                 1.0.23                     py_0
     ipython_genutils          0.2.0                    py27_0
     jsonschema                3.0.2                    py27_0
     jupyter_core              4.6.1                    py27_0
     libedit                   3.1.20191231         h14c3975_1
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.1.0                hdf63c60_0
     libstdcxx-ng              9.1.0                hdf63c60_0
     nbformat                  4.4.0                    py27_0
     ncurses                   6.2                  he6710b0_1
     openssl                   1.1.1h               h7b6447c_0
     pexpect                   4.8.0                    pypi_0    pypi
     pip                       19.3.1                   py27_0
     ptyprocess                0.6.0                    pypi_0    pypi
     pycosat                   0.6.3            py27h7b6447c_0
     pycparser                 2.20                       py_2
     pyopenssl                 19.1.0                     py_1
     pyrsistent                0.15.6           py27h7b6447c_0
     pysocks                   1.7.1                    py27_0
     python                    2.7.18               h15b4118_1
     python-dateutil           2.8.1                      py_0
     pytz                      2020.1                     py_0
     pyyaml                    5.2              py27h7b6447c_0
     readline                  8.0                  h7b6447c_0
     requests                  2.24.0                     py_0
     ruamel_yaml               0.15.87          py27h7b6447c_0
     scandir                   1.10.0           py27h7b6447c_0
     setuptools                44.0.0                   py27_0
     six                       1.15.0                     py_0
     sqlite                    3.33.0               h62c20be_0
     tk                        8.6.10               hbc83047_0
     tqdm                      4.49.0                     py_0
     traitlets                 4.3.3                    py27_0
     urllib3                   1.25.7                   py27_0
     wheel                     0.35.1                     py_0
     xbb-tools                 0.2                      pypi_0    pypi
     yaml                      0.1.7                had09818_2
     zlib                      1.2.11               h7b6447c_3
     
</pre></details>
```

### PR DESCRIPTION
**Pull request by devavret**
Fixes #6716

### CODE REVIEW

File: cpp/tests/jit/jit-cache-test.hpp [hunk 1]
```diff
@@ -45,7 +45,11 @@ struct JitCacheTest : public ::testing::Test, public cudf::jit::cudfJitCache {
   void purgeFileCache()
   {
 #if defined(JITIFY_USE_CACHE)
-    boost::filesystem::remove_all(cudf::jit::getCacheDir());
+    std::vector<boost::filesystem::path> file_paths;
```
Comment (nvdbaranec) [inline cpp/tests/jit/jit-cache-test.hpp:48]: A quick comment on why it's done this way would be good, so no one accidentally recreates this issue in the future.

**Review by nvdbaranec — CHANGES_REQUESTED** [review]
One small comment request.

File: cpp/tests/jit/jit-cache-test.hpp (hunk 1 above)
Comment (devavret) [reply cpp/tests/jit/jit-cache-test.hpp:48]: Makes sense. It's not immediately apparent from the code why the directory isn't deleted.

**Review by nvdbaranec — APPROVED** [review]

**Review by davidwendt — APPROVED** [review]
