### PR TITLE
Intentionally leak thread_local CUDA resources to avoid crash (part 1)

### LINKED ISSUE #13229: [BUG] Crash running parquet reader benchmarks.
The PARQUET_READER_NVBENCH crashes (segfault) at exit on some machines.   It doesn't seem to happen consistently for everyone, but it tends to be reproducible once it starts happening.

To reproduce, run PARQUET_READER_NVBENCH and you should get a segfault right at the end after it has printed out all of it's results.

I've narrowed it down to something specific to the `parquet_read_io_compression` suite.  In addition, `compute-sanitizer` does not turn anything up so this seems to be something purely cpu-side.

### PR DESCRIPTION
**Pull request by kingcrimsontianyu**
## Description

The NVbench application `PARQUET_READER_NVBENCH` in libcudf currently crashes with the segmentation fault. To reproduce:

```
./PARQUET_READER_NVBENCH -d 0 -b 1 --run-once -a io_type=FILEPATH -a compression_type=SNAPPY -a cardinality=0 -a run_length=1
```
 
The root cause is that some (1) `thread_local`  objects on the main thread in `libcudf` and (2) `static` objects in `kvikio` are destroyed after `cudaDeviceReset()` in NVbench and upon program termination. These objects should simply be leaked, since their destructors making CUDA calls upon program termination constitutes UB in CUDA.

This simple PR is the cuDF side of the fix. The other part is done here https://github.com/rapidsai/kvikio/pull/462.

closes #13229

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/src/utilities/stream_pool.cpp [hunk 1]
```diff
@@ -130,7 +130,6 @@ rmm::cuda_device_id get_current_cuda_device()
  */
 struct cuda_event {
   cuda_event() { CUDF_CUDA_TRY(cudaEventCreateWithFlags(&e_, cudaEventDisableTiming)); }
-  virtual ~cuda_event() { CUDF_ASSERT_CUDA_SUCCESS(cudaEventDestroy(e_)); }
```
Comment (wence-) [inline cpp/src/utilities/stream_pool.cpp:133]: *issue (maybe)*: This means that _every_ usage of `cuda_event` in the code base will leak the underlying event. Is this really what we want? Perhaps we only want to leak the `thread_local` ones below.

That is, should we change `event_for_thread` to do (approximately):

```
thread_local std::vector<cuda_event *> thread_events(get_num_cuda_devices());
...
thread_events[device_id.value()] = new cuda_event();
```
?

Alternately, if the _only_ usage of `cuda_event` is in `event_for_thread`, we could just delete this class completely and implement `event_for_thread` as:

```
thread_local std::vector<cudaEvent_t> thread_events(...);
if (!thread_events[device_id.value()]) {
    CUDF_CUDA_TRY(cudaEventCreateWithFlags(&thread_events[device_id.value()], ...);
}
return thread_events[device_id.value()];
```

WDYT?

Comment (kingcrimsontianyu) [reply cpp/src/utilities/stream_pool.cpp:133]: `cuda_event` is only used as the RAII wrapper by `event_for_thread`, so deleting the user-defined destructor and allocating `cuda_event` on the heap happen to be equivalent. I agree that the leak makes the `cuda_event` wrapper entirely superfluous, so I will use the alternative approach you suggested to make the code cleaner. Thank you @wence- !

Comment (kingcrimsontianyu) [reply cpp/src/utilities/stream_pool.cpp:133]: Completed

File: cpp/src/utilities/stream_pool.cpp [hunk 2]
```diff
@@ -147,12 +136,13 @@ struct cuda_event {
  */
 cudaEvent_t event_for_thread()
 {
-  thread_local std::vector<std::unique_ptr<cuda_event>> thread_events(get_num_cuda_devices());
+  thread_local std::vector<cudaEvent_t> thread_events(get_num_cuda_devices());
```
[the remark this answers is not in the document]
Comment (kingcrimsontianyu) [reply cpp/src/utilities/stream_pool.cpp:139]: I see. Should `cuda_event` be moved to the header file `include/cudf/detail/utilities/stream_pool.hpp`? It's currently defined in `.cpp`.

[the remark this answers is not in the document]
Comment (vuule) [reply cpp/src/utilities/stream_pool.cpp:139]: Yeah, we should move it at some point.

[the remark this answers is not in the document]
Comment (kingcrimsontianyu) [reply cpp/src/utilities/stream_pool.cpp]: On a second thought, this event RAII wrapper should be moved to a separate header file if found useful. I have some doubt on its necessity after a brief search in the cudf repo. Anway, for this PR, I'm keeping its location unchanged, and have applied the change you suggested. @vuule

**Review by vuule — APPROVED** [review]

File: cpp/src/utilities/stream_pool.cpp [hunk 3]
```diff
@@ -147,11 +147,12 @@ struct cuda_event {
...
-  thread_local std::vector<std::unique_ptr<cuda_event>> thread_events(get_num_cuda_devices());
+  // The program may crash if this function is called from the main thread and user application
+  // subsequently calls cudaDeviceReset().
+  // As a workaround, here we intentionally disable RAII and leak cudaEvent_t.
+  thread_local std::vector<cuda_event*> thread_events(get_num_cuda_devices());
   auto const device_id = get_current_cuda_device();
-  if (not thread_events[device_id.value()]) {
-    thread_events[device_id.value()] = std::make_unique<cuda_event>();
-  }
+  if (not thread_events[device_id.value()]) { thread_events[device_id.value()] = new cuda_event(); }
```
Comment (lamarrr) [inline cpp/src/utilities/stream_pool.cpp:155]: explicitly delete the copy constructor and define the move constructor for cuda_event, otherwise there'll be a dangling handle and double-free in the future.

Comment (vuule) [reply cpp/src/utilities/stream_pool.cpp:155]: Good catch!
Technically not related to the segfault fix, but it would be good to fix the potential source of bugs sooner rather than later :)

**Review by ttnghia — APPROVED** [review]
