### PR TITLE
Fix CI workflows for pandas-tests and add test summary.

### LINKED ISSUE #14846: [CI] Add the results of running the pandas tests suites with cudf.pandas in the job summary page
Currently, to see the results of running the pandas test suite with cudf.pandas, one must inspect the logs of the `pandas-tests` CI job. It would be nicer if a summary was available in the Job Summary page.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR fixes issues with the `pandas-tests` job that were introduced during the pandas 2 migration.

It also closes #14846 by adding GitHub Actions summaries for all wheel test jobs, including `cudf.pandas`. Depends on https://github.com/rapidsai/shared-workflows/pull/173.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: python/cudf/cudf/pandas/scripts/run-pandas-tests.sh [hunk 1]
```diff
@@ -183,11 +184,10 @@ and not test_numpy_ufuncs_basic[nullable_float-rad2deg]"
 
 PANDAS_CI="1" python -m pytest -p cudf.pandas \
     -m "not single_cpu and not db" \
-    -k "not test_overwrite_warns and not test_complex_series_frame_alignment and not $TEST_NUMPY_UFUNCS_BASIC_FLAKY" \
-    --durations=50 \
-    --import-mode=importlib \
```
Comment (shwina) [inline python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:188]: Can we put this back?

Comment (shwina) [reply python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:188]: IIRC without this, tests in directories like `io/` or `csv/` wouldn't be imported (pytest would confuse those for the `io` and `csv` standard modules for example)

Comment (vyasr) [reply python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:188]: Yes let's try putting back both of these arguments and see if that breaks anything. If it works we should keep it.

Comment (bdice) [reply python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:188]: Oh, my mistake. I didn't realize I had deleted those lines!

File: ci/cudf_pandas_scripts/pandas-tests/run.sh [hunk 2]
```diff
@@ -1,12 +1,16 @@
...
 # All rights reserved.
 # SPDX-License-Identifier: Apache-2.0
 
+set -euo pipefail
+
 PANDAS_TESTS_BRANCH=${1}
 
 rapids-logger "Running Pandas tests using $PANDAS_TESTS_BRANCH branch"
-rapids-logger "PR number: $RAPIDS_REF_NAME"
+if [ -n "${RAPIDS_REF_NAME:-""}" ]; then
```
Comment (bdice) [inline ci/cudf_pandas_scripts/pandas-tests/run.sh:11]: Making this conditional makes it easier to repro CI locally. Otherwise you get an unbound variable error.

File: ci/cudf_pandas_scripts/pandas-tests/run.sh [hunk 3]
```diff
@@ -1,12 +1,14 @@
...
 # All rights reserved.
 # SPDX-License-Identifier: Apache-2.0
 
+set -euo pipefail
+
 PANDAS_TESTS_BRANCH=${1}
 
 rapids-logger "Running Pandas tests using $PANDAS_TESTS_BRANCH branch"
-rapids-logger "PR number: $RAPIDS_REF_NAME"
+rapids-logger "PR number: ${RAPIDS_REF_NAME:-"unknown"}"
```
Comment (bdice) [inline ci/cudf_pandas_scripts/pandas-tests/run.sh:11]: Making this conditional makes it easier to repro CI locally. Otherwise you get an unbound variable error.

**Review by shwina — APPROVED** [review]

File: ci/test_wheel_cudf.sh [hunk 4]
```diff
@@ -22,9 +22,22 @@ RAPIDS_PY_WHEEL_NAME="cudf_${manylinux}_${RAPIDS_PY_CUDA_SUFFIX}" rapids-downloa
...
+    rapids-logger "Run smoke tests for cudf"
     python ./ci/wheel_smoke_test_cudf.py
 else
-    python -m pytest -n 8 ./python/cudf/cudf/tests
+    rapids-logger "pytest cudf"
+    pushd python/cudf/cudf/tests
+    python -m pytest \
+      --cache-clear \
+      --junitxml="${RAPIDS_TESTS_DIR}/junit-cudf.xml" \
+      --numprocesses=8 \
```
Comment (vyasr) [inline ci/test_wheel_cudf.sh:39]: Did you choose to use `--numprocesses` instead of `-n` to match the conda tests? I'm fine with either option but I think (without having done any real investigation) that `-n` is more common. That may also be a dichotomy between wheels/conda (since we implemented GHA for each in parallel at roughly the same time there was less coordination/enforcement of uniformity) that we could try to unify over time.

File: python/cudf/cudf/pandas/scripts/run-pandas-tests.sh [hunk 5]
```diff
@@ -16,12 +16,13 @@
...
 # This script creates a `pandas-testing` directory if it doesn't exist
 
+set -euo pipefail
 
 # Grab the Pandas source corresponding to the version
 # of Pandas installed.
 PANDAS_VERSION=$(python -c "import pandas; print(pandas.__version__)")
 
-PYTEST_IGNORES="--ignore=tests/io/test_user_agent.py"
+PYTEST_IGNORES="--ignore=tests/io/test_user_agent.py --ignore=tests/interchange/test_impl.py"
```
Comment (vyasr) [inline python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:25]: Can we just inline this variable? It's only used once, it's defined far from that location (the pytest call), and it's incongruous with how we provide basically every other argument inline.

**Review by vyasr — APPROVED** [review]
One thing I'd like to see changed, but this PR generally looks good and I don't think it's worth blocking merge if you don't want to make the change, so resolve as you see fit.

File: ci/test_wheel_cudf.sh (hunk 4 above)
Comment (bdice) [reply ci/test_wheel_cudf.sh:39]: We've generally chosen to write the full names of flags wherever possible in our CI scripts. You're correct, this was an artifact of us doing isolated work on conda and wheels at the same time. I took this opportunity to make them match.

File: python/cudf/cudf/pandas/scripts/run-pandas-tests.sh (hunk 5 above)
Comment (bdice) [reply python/cudf/cudf/pandas/scripts/run-pandas-tests.sh:25]: It's "far" but not really that far. It's just that there's another very large variable definition in between. I think I'm going to leave this as-is because I don't think it is worth another CI run to change.

**Review by AyodeAwe — APPROVED** [review]
