### PR TITLE
Change the default dictionary policy in Parquet writer from `ALWAYS` to `ADAPTIVE`

### LINKED ISSUE #15501: [BUG] Prevent silent fallback to uncompressed when writing parquet files with ZSTD compression
**Describe the bug**
We've identified some cases with long strings columns where the parquet writer generates >16 MB pages and falls back to an uncompressed write. Due to a hard limit of 16 MB in nvcomp ZSTD compression API, if an encoded page size exceeds 16 MB, we can no longer call use nvcomp's ZSTD codec. Commonly, the large page is the dictionary page in a dict-encoded column.

**Steps/Code to reproduce bug**
I will post a repro file once we have something that can be publicly shared. @pmixer we would love your help here.

**Expected behavior**
We expected ZSTD compression to be used when it is requested.

**Desired change**
These options are still under discussion. We may opt for one, or both, or something else.

* Drop the 16 MB limit in the nvcomp ZSTD compression API. We may choose to throw a warning that the requested page is large. 
* Set the libcudf dictionary policy to "Adaptive" when ZSTD is in use. and maybe always (see #12211)

### PR DESCRIPTION
**Pull request by mhaseeb123**
## Description
This PR changes the default dictionary policy in parquet from `ALWAYS` to `ADAPTIVE` and adds an argument `max_dictionary_size` to control the `ADAPTIVE`-ness of the dictionary policy. This change prevents a silent fallback to `UNCOMPRESSED` when writing parquet files with `ZSTD` compression leading to better performance for several use cases.

Partially closes #15501. 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by mhaseeb123** [comment]
CC: @GregoryKimball

**Comment by vuule** [comment]
There's also the Python side to be changed.
Python writer has a bool `use_dictionary` which translates to either ALWAYS or NEVER. We probably need to change this part of the API. Not sure how it should be done (and maybe avoid a breaking change?).
If we just need a branch for testing, just a simple `cudf_io_types.dictionary_policy.ALWAYS` -> `cudf_io_types.dictionary_policy.ADAPTIVE` should do.

File: cpp/include/cudf/io/parquet.hpp [hunk 1]
```diff
@@ -555,7 +555,7 @@ class parquet_writer_options {
   // Maximum size of min or max values in column index
   int32_t _column_index_truncate_length = default_column_index_truncate_length;
   // When to use dictionary encoding for data
-  dictionary_policy _dictionary_policy = dictionary_policy::ALWAYS;
```
Comment (abellina) [inline cpp/include/cudf/io/parquet.hpp:558]: would this change the default for all  codecs or just ZSTD?

Comment (abellina) [reply cpp/include/cudf/io/parquet.hpp:558]: oh I think this just opens it so the codec check is actually performed.

Comment (vuule) [reply cpp/include/cudf/io/parquet.hpp:558]: this would apply to all compression codecs

Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet.hpp:558]: All codecs for now. This is just an experimental branch to test `dict_policy` out.

**Comment by mhaseeb123** [comment]
> There's also the Python side to be changed. Python writer has a bool `use_dictionary` which translates to either ALWAYS or NEVER. We probably need to change this part of the API. Not sure how it should be done (and maybe avoid a breaking change?). If we just need a branch for testing, just a simple `cudf_io_types.dictionary_policy.ALWAYS` -> `cudf_io_types.dictionary_policy.ADAPTIVE` should do.

Thanks, I have pushed the ^suggested change. This is only a testing branch

**Comment by GregoryKimball** [comment]
Do you think this is would be a "breaking" change? @mhaseeb123 @vuule

**Comment by mhaseeb123** [comment]
> Do you think this is would be a "breaking" change? @mhaseeb123 @vuule

Probably not, functionality wise at least. 🤔

File: python/cudf/cudf/_lib/parquet.pyx [hunk 2]
```diff
@@ -478,7 +478,7 @@ def write_parquet(
         )
 
     dict_policy = (
-        cudf_io_types.dictionary_policy.ALWAYS
+        cudf_io_types.dictionary_policy.ADAPTIVE
         if use_dictionary
```
Comment (vuule) [inline python/cudf/cudf/_lib/parquet.pyx:482]: Thoughts on expanding this parameter to allow selecting ALWAYS?
It could be a string or a bool, where the bool keeps the behavior implemented here (true->adaptive, false->never). A string would map 1:1 to libcudf options.
CC @galipremsagar

Comment (mhaseeb123) [reply python/cudf/cudf/_lib/parquet.pyx:482]: I agree with this but perhaps with an enum instead of strings?

Comment (etseidl) [reply python/cudf/cudf/_lib/parquet.pyx:482]: Would you want me to fold this into #15613? It's going to hit the same parts of the python code.

Comment (vuule) [reply python/cudf/cudf/_lib/parquet.pyx:482]: I'd like to keep the policy change isolated in a separate PR, because it's a bit on the risky side.

Comment (vuule) [reply python/cudf/cudf/_lib/parquet.pyx:482]: I'm not sure about enums. Looking at the current Python APIs, e.g.
```
def write_parquet(
    table,
    object filepaths_or_buffers,
    object index=None,
    object compression="snappy",
    object statistics="ROWGROUP",
    object metadata_file_path=None,
    object int96_timestamps=False,
    object row_group_size_bytes=_ROW_GROUP_SIZE_BYTES_DEFAULT,
    object row_group_size_rows=None,
    object max_page_size_bytes=None,
    object max_page_size_rows=None,
    object partitions_info=None,
    object force_nullable_schema=False,
    header_version="1.0",
    use_dictionary=True,
):
```
There's a lot of use of strings for parameters that could be enums. Would like to hear from a Python expert.

Comment (mhaseeb123) [reply python/cudf/cudf/_lib/parquet.pyx:482]: Strings are fine as well but +1 on would like to hear from a Python expert on which would be a better choice.

Comment (etseidl) [reply python/cudf/cudf/_lib/parquet.pyx:482]: FWIW pyarrow uses strings for similar parameters.

Comment (galipremsagar) [reply python/cudf/cudf/_lib/parquet.pyx:482]: I think it's okay to leave as is. This is the docstring from pyarrow:


Screenshot 2024-05-07 at 2 41 21 PM


This means we just have to update our docstring of `use_dictionary` to say we will try to encode as dict until a certain size, and beyond that we leave it as plain...something like that.

File: python/cudf/cudf/io/parquet.py [hunk 3]
```diff
@@ -962,6 +962,22 @@ def to_parquet(
             if partition_offsets is not None
             else None
         )
+
+        # Set up the dictionary policy
+        dict_policy=None
```
[the remark this answers is not in the document]
Comment (galipremsagar) [reply python/cudf/cudf/io/parquet.py:967]: Do other engines have these keywords?

[the remark this answers is not in the document]
Comment (mhaseeb123) [reply python/cudf/cudf/io/parquet.py:967]: TLDR; Extra keywords would be cudf specific but wouldn't break any interop as boolean is supported. Here's what others have:

* pyarrow: boolean or list of columns (partially boolean) with [adaptive](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) being default (via threshold:  `dictionary_pagesize_limit`).
* fastparquet: [no argument](https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write) related to use_dictionary or dictionary policy
* parquet-mr: boolean `enableDictionary` along with a [threshold](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java#L207) `dictionaryPageSize` so I would say similar to pyarrow

[the remark this answers is not in the document]
Comment (vuule) [reply python/cudf/cudf/io/parquet.py:967]: @GregoryKimball suggested to match pyarrow here - bool + threshold.
I'm fine with that. We don't need to expose any strings then.

[the remark this answers is not in the document]
Comment (galipremsagar) [reply python/cudf/cudf/io/parquet.py:967]: Yup, we should use bool +  `dictionary_pagesize_limit`

[the remark this answers is not in the document]
Comment (mhaseeb123) [reply python/cudf/cudf/io/parquet.py]: Pushed the new changes!

File: cpp/include/cudf/io/parquet.hpp [hunk 4]
```diff
@@ -564,7 +564,7 @@ class parquet_writer_options {
...
+  dictionary_policy _dictionary_policy = dictionary_policy::ADAPTIVE;
```
Comment (etseidl) [inline cpp/include/cudf/io/parquet.hpp:567]: Should we also change the default for the chunked writer to be consistent?

File: python/cudf/cudf/utils/ioutils.py [hunk 5]
```diff
@@ -277,6 +277,10 @@
 max_page_size_rows: integer or None, default None
     Maximum number of rows of each page of the output.
     If None, 20000 will be used.
+max_dictionary_size: integer or None. default None
+    Maximum size of dictionary page for each output column chunks. Dictionary
```
Comment (etseidl) [inline python/cudf/cudf/utils/ioutils.py:281]:
```suggestion
    Maximum size of the dictionary page for each output column chunk. Dictionary
```

File: python/cudf/cudf/utils/ioutils.py [hunk 6]
```diff
@@ -291,8 +295,8 @@
     ``return_metadata=True`` instead of specifying ``metadata_file_path``
 use_dictionary : bool, default True
     When ``False``, prevents the use of dictionary encoding for Parquet page
-    data. When ``True``, dictionary encoding is preferred when not disabled due
-    to dictionary size constraints.
+    data. When ``True``, dictionary encoding is preferred subjected to
```
Comment (etseidl) [inline python/cudf/cudf/utils/ioutils.py:298]:
```suggestion
    data. When ``True``, dictionary encoding is preferred subject to
```

**Review by etseidl — COMMENTED** [review]
Looks good! Just a few nits and a question.

File: cpp/include/cudf/io/parquet.hpp (hunk 4 above)
Comment (mhaseeb123) [reply cpp/include/cudf/io/parquet.hpp:567]: Yes!

File: python/cudf/cudf/_lib/parquet.pyx [hunk 7]
```diff
@@ -609,6 +623,11 @@ cdef class ParquetWriter:
         self.row_group_size_rows = row_group_size_rows
         self.max_page_size_bytes = max_page_size_bytes
         self.max_page_size_rows = max_page_size_rows
+        self.max_dictionary_size = (
```
Comment (vuule) [inline python/cudf/cudf/_lib/parquet.pyx:626]: shouldn't this assign to `dict_policy`?

File: python/cudf/cudf/_lib/parquet.pyx
Comment (vuule) [inline python/cudf/cudf/_lib/parquet.pyx:1]: I think we would benefit from testing this. Writing repetitive data and checking the encoding should work. Something like

```
    pf = pq.ParquetFile(fname)
    fmd = pf.metadata
    assert "DELTA_BINARY_PACKED" in fmd.row_group(0).column(0).encodings
```

can be used to check if dictionary encoding is being used.

File: python/cudf/cudf/_lib/parquet.pyx (hunk 7 above)
Comment (mhaseeb123) [reply python/cudf/cudf/_lib/parquet.pyx:626]: Yes, my bad. I am amazed that it compiled fine.

Comment (vuule) [reply python/cudf/cudf/_lib/parquet.pyx:626]: I was surprised as well. That's what prompted me to suggest tests :D

Comment (mhaseeb123) [reply python/cudf/cudf/_lib/parquet.pyx]: 😆 makes sense.

File: python/cudf/cudf/_lib/parquet.pyx
Comment (mhaseeb123) [reply python/cudf/cudf/_lib/parquet.pyx:1]: Just pushed the test!

**Review by vuule — APPROVED** [review]
Thank you for iterating on this.
Looks great!

**Review by galipremsagar — APPROVED** [review]

File: python/cudf/cudf/utils/ioutils.py [hunk 8]
```diff
@@ -277,6 +277,10 @@
 max_page_size_rows: integer or None, default None
     Maximum number of rows of each page of the output.
     If None, 20000 will be used.
+max_dictionary_size: integer or None. default None
```
Comment (bdice) [inline python/cudf/cudf/utils/ioutils.py:280]:
```suggestion
max_dictionary_size: integer or None, default None
```

**Review by bdice — APPROVED** [review]
