### PR TITLE
Fix JIT transform kernel crash on non-default CUDA streams

### LINKED ISSUE #21920: [BUG] JIT transform kernel reads freed host memory on non-default CUDA streams
## Describe the bug

`compute_column_jit` (and any JIT transform path using `column_views_to_device` in `jit/helpers.hpp`) crashes with `cudaErrorMisalignedAddress` or `cudaErrorIllegalAddress` when called on a non-default CUDA stream.

## Root cause

`column_views_to_device` builds a `std::vector<DeviceView>` on the stack and copies it to device memory via `cuda_memcpy_async`. On CUDA 13.0+ with non-default streams, `cuda_memcpy_async` routes through `cudaMemcpyBatchAsync` with `cudaMemcpySrcAccessOrderStream`, which **defers reading the host source buffer** until the stream reaches the copy. The host `std::vector` is destroyed when the function returns—before the stream executes the copy—so the kernel receives garbage device-view metadata (corrupted `_data` pointers, `_size`, etc.).

On the default stream, `cudaMemcpyBatchAsync` is not used (the code falls back to `cudaMemcpyAsync`, which reads the source immediately), so the bug does not manifest.

## Minimum reproducer

```cpp
rmm::cuda_stream stream;  // non-default

auto iter = thrust::make_constant_iterator(1.0);
auto col  = cudf::test::fixed_width_column_wrapper<double>(iter, iter + 100);
cudf::column_view cv = col;
auto table = cudf::table_view(std::vector<cudf::column_view>{cv});

auto expr = cudf::ast::column_reference(0);

// Triggers cudaErrorMisalignedAddress under compute-sanitizer
auto result = cudf::compute_column_jit(table, expr, stream);
stream.synchronize();
```

The same call on the default stream succeeds. The AST evaluator (`compute_column`) is not affected because it does not use `column_views_to_device`.

## Environment

- CUDA 13.1 (requires 13.0+ for `cudaMemcpyBatchAsync`)
- Any non-default CUDA stream
- Any memory resource (not specific to async MR)

## Impact

Any caller of `compute_column_jit`, `transform_extended`, or the JIT filter-join path that uses a non-default stream is affected. Discovered via TPC-H Q1 in the Velox CudfFilterProject operator.

### PR DESCRIPTION
**Pull request by bdice**
## Description

`column_views_to_device()` in `jit/helpers.hpp` copies a stack-local `std::vector` of device-view structs to the GPU via `cuda_memcpy_async`. On CUDA 13.0+ with non-default streams, this routes through `cudaMemcpyBatchAsync` with `cudaMemcpySrcAccessOrderStream`, which defers reading the host source until the stream reaches the copy. The host `std::vector`'s destructor frees memory immediately (not stream-ordered), so the source data is destroyed before the stream executes the copy. The kernel then receives garbage device-view metadata.

Fix: allocate the host staging array from the pinned memory pool via a new `make_empty_pinned_vector()` factory. The pinned vector's destructor is stream-ordered, so the source memory remains valid until after the deferred copy completes.

`make_empty_pinned_vector()` is added for parity with `make_empty_host_vector()`. The "empty with capacity" variant is needed here because `column_device_view` is not default-constructible—we can only `reserve` capacity up front and `push_back` each element.

Closes #21920

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cpp/tests/ast/transform_tests.cpp [hunk 1]
```diff
@@ -1047,4 +1049,25 @@ TYPED_TEST(DecimalComparisonTest, DecimalComparison)
...
+  auto col_ref_0  = cudf::ast::column_reference(0);
+  auto col_ref_1  = cudf::ast::column_reference(1);
+  auto expression = cudf::ast::operation(cudf::ast::ast_operator::ADD, col_ref_0, col_ref_1);
+
+  auto expected = column_wrapper<int32_t>{13, 27, 21, 50};
+  auto result   = Executor::compute_column(table, expression, stream);
+  stream.synchronize();
+
+  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected, result->view(), verbosity);
+}
```
Comment (davidwendt) [inline cpp/tests/ast/transform_tests.cpp:1074]: Perhaps this is missing from https://github.com/rapidsai/cudf/blob/main/cpp/tests/streams/transform_test.cpp and should be moved there?

Comment (bdice) [reply cpp/tests/ast/transform_tests.cpp:1074]: I considered that. Those stream tests are meant to enforce that we don't use the _default_ stream when a custom stream is passed. This test is about _correctness_ (stream safety) when a nondefault custom stream is passed.

Comment (bdice) [reply cpp/tests/ast/transform_tests.cpp:1074]: @vyasr if we work on #21922, is there a future in which we don't need the separate stream tests anymore because they're covered by the main test suite?

Comment (bdice) [reply cpp/tests/ast/transform_tests.cpp:1074]: @davidwendt If you're unconvinced by that explanation, I am happy to move it to the other file. Let me know your thoughts.

Comment (davidwendt) [reply cpp/tests/ast/transform_tests.cpp:1074]: I'm good with the explanation. Sometimes the stream tests are forgotten so I'm glad you considered this for there. Perhaps a comment here for future developers who think this should be moved. Mind you, those future developers could be me and you 6 months from now.

**Review by mhaseeb123 — APPROVED** [review]
