### PR TITLE
Handle hyphen as literal for regex cclass when incomplete range

### LINKED ISSUE #11537: cuDF not interpreting "-" within a regex set consistent with documentation and pandas.
cuDF regex interpretation of “-“ within a regex set does not conform to the documentation ([]https://docs.python.org/3/library/re.html), resulting in (at least) two unexpected and undesirable results:

1. cuDF throws an error:  cuDF failure at: /workspace/.conda-bld/work/cpp/src/strings/regex/regcomp.cpp:437: invalid regex pattern: nothing to repeat at position 17
2. cuDF results do not match those from pandas.

This issue is visible when using regex to identify email addresses.  The observed deviation from the documentation is that the “-“ needs to be either escaped (“\\-“) or not located at the beginning or end of the set (“[-“ and “-]”).

The below notebook includes multiple regex permutations (escaped “-“ in the set, etc.) to reproduce both of the above issues and to show regex where cuDF and pandas do match:  

[]https://github.com/brianklobucher/issue_analysis/blob/master/RAPIDS_regex/RAPIDS-regex-email-addresses.ipynb

Expected behavior:  cuDF and pandas regex produce identical results without needing to change the regex.

Environment:
* These issues were present for both RAPIDS 22.04 and 22.06.
* This was run on WSL Ubuntu 20.04.4 LTS.
* RAPIDS was installed via conda.

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Handles an incomplete range in a regex cclass pattern `[a-], [-z], [-]` by interpretting the hyphen `-` as a literal.
Added gtest to test this new behavior.

Closes #11537 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]

File: cpp/tests/strings/contains_tests.cpp [hunk 1]
```diff
@@ -460,6 +460,30 @@ TEST_F(StringsContainsTests, OverlappedClasses)
...
+  auto sv    = cudf::strings_column_view(input);
+
+  {
+    auto results = cudf::strings::contains_re(sv, "[a-z]");
+    cudf::test::fixed_width_column_wrapper<bool> expected({1, 0, 0, 1, 1});
+    CUDF_TEST_EXPECT_COLUMNS_EQUAL(*results, expected);
+  }
+  {
+    cudf::test::fixed_width_column_wrapper<bool> expected({1, 1, 0, 1, 1});
+    auto results = cudf::strings::contains_re(sv, "[g-]");
```
Comment (upsj) [inline cpp/tests/strings/contains_tests.cpp:475]: I could imagine two other interesting test cases: hyphens being both a literal and a special character like `+--`, and multiple ranges `a-b-` or `-a-b`.

Also, it might make sense to test error cases like `a-b-c` explicitly? I guess we don't expect the second hyphen to be parsed as a literal in that case.

**Review by upsj — APPROVED** [review]

File: cpp/tests/strings/contains_tests.cpp (hunk 1 above)
Comment (davidwendt) [reply cpp/tests/strings/contains_tests.cpp:475]: Thanks Tobias. I added some more tests. 
Interestingly `[a-b-c]` is treated as `[a-c]` which I think makes sense and I like alot.
Looks like any multi-range [c<sub>1</sub>-c<sub>2</sub>-...-c<sub>n</sub>] is simply processed as [c<sub>1</sub>-c<sub>n</sub>] by the libcudf implementation.
However, this appears to be not consistent with other regex implementations.

**Comment by davidwendt** [comment]
@gpucibot merge
