### PR TITLE
Fix chunked_pack::next() returning overflowed int for >2GB data

### LINKED ISSUE #20876: [BUG] `cudf::chunked_pack` returns overflowed int from `next` as the number of bytes written
**Describe the bug**

When I pass a table with 4000MB (4194304000B) of data (in 1 column), and pass the same size as the `user_buffer_size`, `chunked_pack::next` returns overflowed int result as the number of bytes written. 

`chunked_pack::get_total_contiguous_size` still returns the correct size (4194304000)  IINM. 

I believe this is an int32/ cudf::size_type overflow in the implementation somewhere. But `chunked_pack` accepts and returns `std::size_t`, so the callers are unaware of this limitation. 

**Steps/Code to reproduce bug**

```c++
    // Create the chunked_pack instance to get total output size
    size_t total_size;
    {
        cudf::chunked_pack packer(table.view(), bounce_buffer_size, stream, table_mr);
        total_size = packer.get_total_contiguous_size();
    }

    // Allocate bounce buffer and destination buffer using the pack_mr
    rmm::device_buffer bounce_buffer(bounce_buffer_size, stream, pack_mr);
    rmm::device_buffer destination(total_size, stream, pack_mr);

    auto run_packer = [&] {
        cudf::chunked_pack packer(table.view(), bounce_buffer_size, stream, pack_mr);

        std::cout << "bounce_buffer_size: " << bounce_buffer_size  << " " << bounce_buffer.size() << std::endl;
        std::cout << "total size " << total_size << std::endl;
        std::size_t offset = 0;
        while (packer.has_next()) {
            auto const bytes_copied = packer.next(
                cudf::device_span<std::uint8_t>(
                    static_cast<std::uint8_t*>(bounce_buffer.data()), bounce_buffer_size
                )
            );
            std::cout << "bytes_copied: " << bytes_copied << std::endl;
            RAPIDSMPF_CUDA_TRY(cudaMemcpyAsync(
                static_cast<std::uint8_t*>(destination.data()) + offset,
                bounce_buffer.data(),
                bytes_copied,
                cudaMemcpyDefault,
                stream.value()
            ));
            offset += bytes_copied;
        }
    };
```
 output: 

```bash
bounce_buffer_size: 4194304000 4194304000
total size 4194304000
bytes_copied: 18446744073608888320
terminate called after throwing an instance of 'rmm::cuda_error'
  what():  CUDA error at: /tmp/conda-bld-output/bld/rattler-build_librmm/work/cpp/src/cuda_stream_view.cpp:45: cudaErrorIllegalAddress an illegal memory access was encountered
Aborted
```

**Expected behavior**

return proper size_t output OR change `chunked_pack` arguments to `cudf::size_type`. 

**Environment overview (please complete the following information)**
 - Environment location: bare-metal
 - Method of cuDF install: conda

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

```bash
(rapidsmpf-dev) nperera@e40448e-lcedt:~/git/rapidsmpf/cpp/build$ conda list cudf 
# packages in environment at /home/nperera/miniforge3/envs/rapidsmpf-dev:
#
# Name                     Version          Build                         Channel
cudf                       26.02.00a177     cuda13_py313_251215_c3e18024  rapidsai-nightly
dask-cudf                  26.02.00a177     cuda13_251215_c3e18024        rapidsai-nightly
libcudf                    26.02.00a177     cuda13_251215_c3e18024        rapidsai-nightly
pylibcudf                  26.02.00a177     cuda13_py313_251215_c3e18024  rapidsai-nightly
```

**Additional context**

### PR DESCRIPTION
**Pull request by ttnghia**
Fixes an integer overflow in `chunked_pack::next()` when a single call copies more than 2 GB.

The internal `contiguous_split_chunk()` method returned `cudf::size_type` (`int32_t`), which truncated and then sign-extended the byte count back to `std::size_t`, producing an incorrect value. This changes the return type to `std::size_t`. The method is private (defined only in the `.cu` file), so there is no ABI or public API impact.

A regression test is added, disabled by default since it requires much of GPU memory.

Closes #20876

### CODE REVIEW

File: cpp/tests/copying/split_tests.cpp [hunk 1]
```diff
@@ -1719,6 +1720,42 @@ TEST_F(ContiguousSplitUntypedTest, DISABLED_VeryLargeColumnTestChunked)
...
+{
+  auto const mr = cudf::get_current_device_resource_ref();
+
+  // 270M INT64 elements = 270 * 1024 * 1024 * 8 = 2,264,924,160 bytes > INT32_MAX
+  constexpr cudf::size_type num_rows = 270 * 1024 * 1024;
+  auto const col                     = cudf::make_fixed_width_column(
+    cudf::data_type{cudf::type_id::INT64}, num_rows, cudf::mask_state::UNALLOCATED);
+
+  auto const expected_total_size = static_cast<std::size_t>(num_rows) * sizeof(int64_t);
+  ASSERT_GT(expected_total_size, static_cast<std::size_t>(std::numeric_limits<int32_t>::max()));
```
Comment (mhaseeb123) [inline cpp/tests/copying/split_tests.cpp]:
```suggestion
  EXPECT_GT(expected_total_size, static_cast<std::size_t>(std::numeric_limits<int32_t>::max()));
```

File: cpp/tests/copying/split_tests.cpp [hunk 2]
```diff
@@ -1719,6 +1720,42 @@ TEST_F(ContiguousSplitUntypedTest, DISABLED_VeryLargeColumnTestChunked)
   CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*col, result[0].table.column(0));
 }
 
+// This test requires about 7GB of device memory.
+// It verifies that chunked_pack::next() returns the correct byte count
+// when a single call copies more than 2GB (INT32_MAX bytes).
+// See https://github.com/rapidsai/cudf/issues/20876
```
Comment (mhaseeb123) [inline cpp/tests/copying/split_tests.cpp]:
```suggestion
// Disabled as this test requires about 7GB of device memory.
// See https://github.com/rapidsai/cudf/issues/20876 for more info
```

File: cpp/tests/copying/split_tests.cpp (hunk 1 above)
Comment (mhaseeb123) [reply cpp/tests/copying/split_tests.cpp]: Is `ASSERT` really needed here?

**Comment by ttnghia** [comment]
Applied all suggestions from review — simplified the test comment, changed `ASSERT_GT` to `EXPECT_GT`, and updated the PR description. Thanks @mhaseeb123 and @bdice!

**Review by wence- — APPROVED** [review]
